<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Type";
$strModified = "Ændret";
$strSize = "Størrelse";
$fbRefresh = "Opdater";
$fbProperties = "Egenskaber";
$fbNewFolder = "Ny mappe";
$fbDelete = "Slet";
$fbCut = "Klip";
$fbPaste = "Indsæt";
$fbCopy = "Kopier";
$fbFiletypes = "Filtyper";
$fbPath = "Sti";
$fbFolders = "Mapper";
$fbNoSelect = "Du har ikke valgt en post. Klik på et ikon ved siden af et navn for at vælge en post.";
$fbConfirmDelete = "Bekræft sletning";
$fbGeneral = "Generelt";
$fbConfirmOverwrite = "Bekræft overskrivelse";
$strOverwritePrefix = "Er du sikker på du ønsker at overskrive ";
$strOverwriteSuffix = "?";
$fbDescription = "Beskrivelse";
$fbLocation = "Sted";
$fbUpload = "Overfør";
$fbUpload_text = "Vælg en fil at overføre";
$fbUpload_nofile = "Modtagelsen mislykkedes.";
$fbFolderExists = "Mappen eksisterer allerede.";
$fbFolder = "Mappe";
$fbSelect = "Vælg fil...";
$fbNoFile = "Filen du prøvede at overføre er for stor.<br /> Den maksimale filstørrelse er sat til: ";
$fbPleaseWait = "Vent venligst. Sender data...";
$fbFilename = "Filnavn";
$fbUpLevel = "Et niveau op";
$fbItems = "Post(er)";
$fbFolderSize = "Mappe størrelse";
$fbMaxUploadSize = "Maksimal størrelse";
$ml_file_too_big = "Filen du prøvede at vedhæfte er for stor, den maksimale filstørrelse for vedhæftede filer er sat til: ";
$cmdSearch = "Søg";
$fbNameExists = "Navnet eksisterer allerede.";
$fbThis = 'denne';
$fbFiles = 'Filer';
$fs_no_multi_select = 'Du kan ikke vælge mere end én post af gangen med dette valg';
$cms_untitled = 'Ikke navngivet';
$cms_insert_file = 'Indsæt fil';
$cms_preview = 'Forhåndsvisning';
$cms_keywords = 'Nøgleord';
$cms_priority = 'Prioritet';
$cms_hide_folder = 'Skjul denne mappe på sitet';
$cms_theme = 'Tema';
$cms_use_go_auth = 'Brug Group-Office autorisering på dette site';
$cms_search_files_prefix = 'HTML filerne kan indeholde ordet';
$cms_search_files_suffix = 'bliver automatisk valgt. Klik på \'Ok\' for at gemme dette valg.';
$cms_new_site = 'Nyt site';
$cms_search_files = 'Find i filer';
$cms_subscribe = 'Tilmeld';
$cms_sites = 'Sted(er)';
$cms_style = 'Stil';
$cms_insert_file_url = 'Indsæt URL';
$cms_templates = 'Skabeloner';
$cms_files = 'Filer';
$cms_items = 'Post(er)';
$cms_header = 'Header';
$cms_footer = 'Footer';
$cms_new_theme = 'Nyt tema';
$cms_themes = 'tema(er)';
$cms_themes_menu = 'Temaer';
$cms_all_sites = 'Alle sites';
$cms_your_sites = 'Dit site';
$cms_cmd_new_site = 'Nyt site';
$cms_template_items = 'Skabelon(er)';
$cms_new_template_item = 'Ny skabelon';
$cms_found_one = '1 fil fundet';
$cms_found = 'filer fundet';
$cms_empty = 'Dette afsnit er tomt og formodentlig ved at blive vedligeholdt.';
$cms_new_page = 'Ny side';
$cms_search_words = 'Søgeord';
$cms_no_themes = 'Du har ikke valgt nogen temaer endnu. Opret først et tema.';
$cms_edit_search_words = 'rediger søgeord';
$cms_id = 'Site ID';

$cms_cleanup = 'Ryd&nbsp;op&nbsp;i&nbsp;HTML';
$cms_settings = 'Indstillinger';
$cms_site_exists = 'Et site ved det navn eksisterer allerede';
$cms_main_template = 'Primær';
$cms_confirm_close = 'Ændringer vil gå tabt. Er du sikker?';

$cms_restrict_editor = 'Begræns editor til forud definerede stiler';
$cms_enable_publish = 'Lokal hjemmeside publicering';

$cms_path_not_writable = 'Stien du indtastede er ugyldig og Group-Office har ikke skriverettigheder til den.';
$cms_publish = 'Publicering';
$cms_path_already_used = 'Stien du indtastede er allerede i brug af en anden hjemmeside.';
$cms_site_offline = 'Dette site er i øjeblikket nede';

$cms_disable_publish = 'Gør site utilgængelig';
$cms_publish_dynamic = 'Publicer dynamisk';
$cms_publish_static = 'Publicer statisk';

//2.05
$cms_sendmail_error = 'Din besked kunne ikke sendes. Prøv venligst igen.';
$cms_sendmail_success = 'Tak. Din besked blev sendt.';
$cms_message = 'Besked';
$cms_subject = 'Emne';
$cms_domain = 'Domæne';
$cms_replace_filenames = 'Erstat filnavne';

//2.06
$cms_multipage_display = 'Opsummer alle mappens sider og de første sider af undermapper';
$cms_hot_item = 'Vis denne side i listen over smarte ting';
$cms_normal_display = 'Vis den første side af mappen';

$cms_display_type = 'Når en besøgende åbner en mappe på denne hjemmeside:';
$cms_read_more = 'Læs mere';
$cms_additional_style = 'Stil der bruges i editoren';
