<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Typpi";
$strModified = "Muokattu";
$strSize = "Koko";
$fbRefresh = "Päivititä";
$fbProperties = "Ominaisuudet";
$fbNewFolder = "Uusi kansio";
$fbDelete = "Poista";
$fbCut = "Leikkaa";
$fbPaste = "Liitä";
$fbCopy = "Kopoi";
$fbFiletypes = "Tiedostotyypit";
$fbPath = "Polku";
$fbFolders = "Kansiot";
$fbNoSelect = "Et valinnut mitään. Valitse painamalla nimen vieressä oleva ikonia.";
$fbConfirmDelete = "Varimista poisto";
$fbGeneral = "Yleinen";
$fbConfirmOverwrite = "Varmista korvaaminen";
$strOverwritePrefix = "Oletko oletko varma että haluat korvata ";
$strOverwriteSuffix = "?";
$fbDescription = "Kuvaus";
$fbLocation = "Paikka";
$fbUpload = "Lataa järjestelmään";
$fbUpload_text = "Valitse tiedosto jonka haluat ladata järjestelmään";
$fbUpload_nofile = "Mitään tiedostoa ei vastaanotettu.";
$fbFolderExists = "Kansio on jo olemassa.";
$fbFolder = "Kansio";
$fbSelect = "Valitse tiedosto...";
$fbNoFile = "Tiedosto jonko yritit ladat järjestelmään on liian suuri.<br /> Suurin ladattavan tiedoston koko on: ";
$fbPleaseWait = "Ole hyvä ja odota. Tietoja siirretään...";
$fbFilename = "Tiedostonimi";
$fbUpLevel = "Taso ylöspäin";
$fbItems = "tiedosto(t)";
$fbFolderSize = "Kansion koko";
$fbMaxUploadSize = "Maksimi koko";
$ml_file_too_big = "Tiedosto jonka yritit liittää on liian suuri, liitetiedoston suurin koko on: ";
$cmdSearch = "Etsi";
$fbNameExists = "Nimi on jo olemassa.";
$fbThis = 'tämä';
$fbFiles = 'Tiedostot';
$fs_no_multi_select = 'Ei voi valita kuin yhden tällä valinnalla';
$cms_untitled = 'Ilman otsikkoa';
$cms_insert_file = 'Lisää tiedosto';
$cms_preview = 'Esikatselu';
$cms_keywords = 'Avainsanat';
$cms_priority = 'Prioritetti';
$cms_hide_folder = 'Piilota tämä kansio';
$cms_theme = 'Tema';
$cms_use_go_auth = 'Käytä Group-Office autentikointia tällä sivustolla';
$cms_search_files_prefix = 'HTML tiedosto joka sisältää sanan';
$cms_search_files_suffix = 'on automaattisesti valittu. Paina \'Ok\' valinnan tallentamiseksi.';
$cms_new_site = 'Uuso sivusto';
$cms_search_files = 'Etsi tiedostot';
$cms_subscribe = 'Tilaa';
$cms_sites = 'sivusto(t)';
$cms_style = 'Tyylit';
$cms_insert_file_url = 'Lisää URL';
$cms_templates = 'Mallit';
$cms_files = 'Tiedostot';
$cms_items = 'tavara(t)';
$cms_header = 'Yläotsikko';
$cms_footer = 'Alaotsikko';
$cms_new_theme = 'Uusi teema';
$cms_themes = 'teema(t)';
$cms_themes_menu = 'Teemat';

$cms_your_sites = 'Sinun sivustot';
$cms_cmd_new_site = 'Uusi sivusto';
$cms_template_items = 'malli(t)';
$cms_new_template_item = 'Uusi malli';
$cms_found_one = '1 tiedosto löytyi';
$cms_found = 'tiedostoa löytyi';
$cms_empty = 'Tämä osasto on tyhjä ja todennäköisesti työn alla.';
$cms_new_page = 'Uusi sivu';
$cms_search_words = 'Hae sanat';
$cms_edit_search_words = 'muokka haku sanoja';
$cms_id = 'Sivusto ID';

$cms_cleanup = 'Siivoa&nbsp;HTML';
$cms_settings = 'Asetukset';
$cms_site_exists = 'Tällä nimellä sivusto löytyy jo';

$cms_confirm_close = 'Muutoksia ei talleteta, oletko varma?';

$cms_restrict_editor = 'Rajoita muokkaus ennalta määriteltyihin tyyleihin';
$cms_enable_publish = 'Salli näyttäminen paikallisilla sivustoilla';

$cms_path_not_writable = 'Polku jonka annnoit on väärä tai Group-Officella ei ole kirjoitusoikeutta siihen.';
$cms_publish = 'Näyttäminen';
$cms_path_already_used = 'Polku jonka annoit on jo toisen sivuston käytössä.';
$cms_site_offline = 'Tämä sivusto tällähetkellä offline tilassa';

$cms_disable_publish = 'Aseta sivusto offline tilaan';
$cms_publish_dynamic = 'Näytä dynaamisesti';
$cms_publish_static = 'Näytä staattisesti';

//2.05
$cms_sendmail_error = 'Viestiäsi ei voitu lähetttää, yritä uudestaan.';
$cms_sendmail_success = 'Kiitos. Viestisi on lähetetty.';
$cms_message = 'Viesti';
$cms_subject = 'Aihe';
$cms_domain = 'Domain';
$cms_replace_filenames = 'Korvaa tiedosto nimet';

//2.06
$cms_multipage_display = 'Tee kooste kansioiden kaikista sivuista ja alakansion ensimmäisestä sivusta';
$cms_hot_item = 'Näytä tämä sivu kuumissa aiheissa';
$cms_normal_display = 'Näytä tämän kansion ensimmäinen sivu';

$cms_display_type = 'Kun vierailija avaa kansion tällä sivustolla:';
$cms_read_more = 'Jatka lukemista';
$cms_additional_style = 'Editorin käyttämä tyyli';

//2.11
$cms_activate_frontpage = 'Aktivoi tämän tyylin etusivu';
$cms_main_template = 'Pää malli'; //Changed string
$cms_frontpage_template = 'Etusivun malli';
$cms_websites = 'Sivustot'; 
$cms_insert_component = 'Lisää komponentti';

$cms_languages = 'Kielet';
$cms_new_language = 'Uusi kieli';
$cms_default = 'Oletus';
$cms_title = 'Otsikko';
$cms_language = 'Kieli';
$cms_image = 'Kuva';
$cms_no_image_selected = 'Kuvaa ei ole valittu';
$cms_selected_image = 'Valittu kuva';
$cms_no_image = 'Ei kuvaa';

$cms_multipage = 'Tee kooste tämän kansion kohteista';

$cms_no_themes = 'Sinulla ei vielä ole teemoja. Lue teema ensin. Sinulla pitää olla järjestelmänvalvojan oikeudet teman luomiseksi.'; //changed string

$cms_select_local = 'Valite paikallinen tiedosto';
$cms_webmaster = 'Webmaster&nbsp;sähköposti';

$cms_allow_properties = 'Anna muiden muokata tämän sivuston ominaisuuksia.';
$cms_multilingual = 'Käytä useampaa kieltä tälllä sivustolla';

//2.12
$cms_search_words_overview = 'Hakusanojen kooste';
$cms_no_occurences = 'Avain sanoja ei ole tällä sivustolla.';
$cms_there_are_results_for_multiple = 'On %s tulosta \'%s\':lle';
$cms_there_are_results_for_single = 'On 1 tulos \'%s\':lle';

$cms_print_style = 'Tulostus tyylit';

$cms_search = 'Haku';
$cms_login = 'Kirjoittaudu';

//2.14
$cms_searchengine_info = 'Hakukonetiedot';
$cms_autogenerate_searchengine_info = 'Luo automaattisesti hakukonetiedot (Suositus)';
