<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = '種類';
$strModified = '編集';
$strSize = 'サイズ';
$fbRefresh = '更新';
$fbProperties = 'プロパティ';
$fbNewFolder = '新規フォルダ';
$fbDelete = '削除';
$fbCut = '切り取り';
$fbPaste = '貼り付け';
$fbCopy = 'コピー';
$fbFiletypes = 'ファイルの種類';
$fbPath = 'パス';
$fbFolders = 'フォルダ';
$fbNoSelect = 'アイテムが選択されていません。名前横のアイコンをクリックしてアイテムを選択してください。';
$fbConfirmDelete = '削除を確認';
$fbGeneral = '一般';
$fbConfirmOverwrite = '上書きを確認';
$strOverwritePrefix = '上書きしてもよろしいですか';
$strOverwriteSuffix = '？';
$fbDescription = '説明';
$fbLocation = 'ロケーション';
$fbUpload = 'アップロード';
$fbUpload_text = 'アップロードするファイルを選択';
$fbUpload_nofile = 'ファイルが受信できませんでした。';
$fbFolderExists = 'フォルダは既に存在しています。';
$fbFolder = 'フォルダ';
$fbSelect = 'ファイルを選択...';
$fbNoFile = 'アップロードするファイルが大きすぎます。<br /> 転送可能なファイルサイズ: ';
$fbPleaseWait = 'しばらくお待ちください。データを送信しています...';
$fbFilename = 'ファイル名';
$fbUpLevel = '上の階層';
$fbItems = 'アイテム';
$fbFolderSize = 'フォルダサイズ';
$fbMaxUploadSize = '最大サイズ';
$ml_file_too_big = '添付するファイルサイズが大きすぎます。添付可能なファイルサイズ: ';
$cmdSearch = '検索';
$fbNameExists = 'ファイルはすでに存在しています。';
$fbThis = 'this';
$fbFiles = 'ファイル';
$fs_no_multi_select = 'このオプションでは１つ以上のェイテムは選択できません。';
$cms_untitled = '無題';
$cms_insert_file = 'ファイルを挿入';
$cms_preview = 'プレビュー';
$cms_keywords = 'キーワード';
$cms_priority = 'プロパティ';
$cms_hide_folder = 'サイトからこのフォルダを隠す。';
$cms_theme = 'テーマ';
$cms_use_go_auth = 'このサイトに認証を使用する。';
$cms_search_files_prefix = 'HTMLファイルは単語が含まれています';
$cms_search_files_suffix = 'は自動的に選択されました。「OK」をクリックして選択を保存してください。';
$cms_new_site = '新規サイト';
$cms_search_files = 'ファイル検索';
$cms_subscribe = '署名';
$cms_sites = 'サイト';
$cms_style = 'スタイル';
$cms_insert_file_url = 'URLを挿入';
$cms_templates = 'テンプレート';
$cms_files = 'ファイル';
$cms_items = 'アイテム';
$cms_header = 'ヘッダー';
$cms_footer = 'フッター';
$cms_new_theme = '新規テーマ';
$cms_themes = 'テーマ';
$cms_themes_menu = 'テーマ';

$cms_your_sites = 'あなたのサイト';
$cms_cmd_new_site = '新規サイト';
$cms_template_items = 'テンプレート';
$cms_new_template_item = '新規テンプレート';
$cms_found_one = '1ファイル見つかりました。';
$cms_found = 'ファイル見つかりました。';
$cms_empty = 'このセクションは空です。メンテナンス中です。';
$cms_new_page = '新規ページ';
$cms_search_words = '語句検索';
$cms_edit_search_words = '検索語句を編集';
$cms_id = 'サイトID';

$cms_cleanup = 'クリーンアップHTML';
$cms_settings = '設定';
$cms_site_exists = '同じ名前のサイトが存在します。';

$cms_confirm_close = '変更は破棄されます。よろしいですか？';

$cms_restrict_editor = '定義済みのスタイルで編集者を制限してください。';
$cms_enable_publish = 'ローカルウェブサイトを公開';

$cms_path_not_writable = '入力したパスは無効であるか：Group-Officeでは書き込み不可能です。';
$cms_publish = '公開';
$cms_path_already_used = '入力したパスはほかのウェブサイトで既に使用されています。';
$cms_site_offline = 'このサイトは現在オフラインです';

$cms_disable_publish = 'サイトをオフライン';
$cms_publish_dynamic = '動的にパブリッシュ';
$cms_publish_static = '静的にパブリッシュ';

//2.05
$cms_sendmail_error = 'メッセージは送信されませんでした。再送信してください';
$cms_sendmail_success = 'メッセージは送信されました';
$cms_message = 'メッセージ';
$cms_subject = '件名';
$cms_domain = 'ドメイン';
$cms_replace_filenames = 'ファイル名置換';

//2.06
$cms_multipage_display = 'サブフォルダの初期ページも含めてすべてのページを表示する';
$cms_hot_item = 'このページをホットアイテムとして表示する';
$cms_normal_display = 'このフォルダの初期ページとして表示する';

$cms_display_type = '訪問者がこのウェブページのフォルダを開いたら:';
$cms_read_more = '続きを読む';
$cms_additional_style = 'エディターで使うスタイル';

//2.11
$cms_activate_frontpage = 'このテーマのフロントページをアクティブにする';
$cms_main_template = 'メインテーマ'; //Changed string
$cms_frontpage_template = 'フロントページテンプレート';
$cms_websites = 'ウェブサイト'; 
$cms_insert_component = 'コンポーネント挿入';

$cms_languages = '言語';
$cms_new_language = '新規言語';
$cms_default = 'デフォルト';
$cms_title = 'タイトル';
$cms_language = '言語';
$cms_image = 'イメージ';
$cms_no_image_selected = 'イメージが選択されていません。';
$cms_selected_image = '選択イメージ';
$cms_no_image = 'イメージなし';

$cms_multipage = 'このフォルダの全ページとサブフォルダの最初のページを要約してください';

$cms_no_themes = 'テーマがありません。はじめにテーマを作成してください。 テーマを作成するには管理者権限が必要です。'; //changed string

$cms_select_local = 'ローカルファイルを選択';
$cms_webmaster = 'ウェブマスターE-mail';

$cms_allow_properties = 'サイトプロパティの変更を許可する';
$cms_multilingual = 'サイトで複数言語を使用する';

//2.12
$cms_search_words_overview = '検索語句の概要';
$cms_no_occurences = 'このウェブページにはキーワードが見つかりませんでした。';
$cms_there_are_results_for_multiple = '%s 件の検索結果： \'%s\'';
$cms_there_are_results_for_single = '1件の検索結果： \'%s\'';

$cms_print_style = '印刷スタイル';

$cms_search = '検索';
$cms_login = 'ログイン';

//2.14
$cms_searchengine_info = 'サーチエンジン情報';
$cms_autogenerate_searchengine_info = '自動的にサーチエンジン情報が生成する (推奨)';
