<?php
require_once($GO_LANGUAGE->get_fallback_language_file('cms'));

$fbMultipleFiles='Múltiplos ficheiros';
$strType = "Tipe";
$strModified = "Modificado";
$strSize = "Tamanho";
$fbRefresh = "Refrecar";
$fbProperties = "Propriedades";
$fbNewFolder = "Nova Pasta";
$fbDelete = "Apagar";
$fbCut = "Cortar";
$fbPaste = "Colar";
$fbCopy = "Copiar";
$fbFiletypes = "Tipos de Ficheiros";
$fbPath = "Caminho";
$fbFolders = "Pastas";
$fbNoSelect = "Não seleccionou um item. Clique num ícone junto ao nome para seleccionar o item.";
$fbConfirmDelete = "Confirmar apagar";
$fbGeneral = "Geral";
$fbConfirmOverwrite = "Confirmar substituir";
$strOverwritePrefix = "Tem a certeza que deseja substituir ";
$strOverwriteSuffix = "?";
$fbDescription = "Descrição";
$fbLocation = "Localização";
$fbUpload = "Enviar Ficheiro";
$fbUpload_text = "Seleccione ficheiro a enviar";
$fbUpload_nofile = "Nenhum ficheiro recebido.";
$fbFolderExists = "A pasta já existe.";
$fbFolder = "Pasta";
$fbSelect = "Seleccionar Ficheiro...";
$fbNoFile = "Nenhum ficheiro recebido. Talvez o ficheiro seja demasiado grande.<br /> O tamanho máximo é: ";
$fbPleaseWait = "Por favor, aguarde. A enviar dados...";
$fbFilename = "Nome do Ficheiro";
$fbUpLevel = "Um nível acima";
$fbItems = "item(s)";
$fbFolderSize = "Tamanho da pasta";
$fbMaxUploadSize = "Tamanho máximo";
$ml_file_too_big = "O ficheiro a anexar é demasiado grande. O tamanho máximo dos anexos é: ";
$cmdSearch = "Pesquisar";
$fbNameExists = "O nome já existe.";
$fbThis = 'este';
$fbFiles = 'Ficheiros';
$fs_no_multi_select = 'Não pode seleccionar mais de um item com esta opção';
$cms_untitled = 'Sem nome';
$cms_insert_file = 'Inserir ficheiro';
$cms_preview = 'Pré-visualizar';
$cms_keywords = 'Palavras a pesquisar';
$cms_priority = 'Prioridade';
$cms_hide_folder = 'Esconder esta pasta';
$cms_theme = 'Tema';
$cms_use_go_auth = 'Usar autenticação Group-Office neste site';
$cms_search_files_prefix = 'Ficheiros HTML onde exista a palavra';
$cms_search_files_suffix = 'são seleccionados automaticamente. Clique em \'Ok\' para guardar esta selecção.';
$cms_new_site = 'Novo Site';
$cms_search_files = 'Pesquisar ficheiros';
$cms_subscribe = 'Subscrever';
$cms_sites = 'site(s)';
$cms_style = 'Estilo';
$cms_insert_file_url = 'Inserir endereço';
$cms_templates = 'Modelos';
$cms_files = 'Ficheiros';
$cms_items = 'item(s)';
$cms_header = 'Cabeçalho';
$cms_footer = 'Rodapé';
$cms_new_theme = 'Novo tema';
$cms_themes = 'tema(s)';
$cms_themes_menu = 'Temas';

$cms_your_sites = 'Os seus sites';
$cms_cmd_new_site = 'Novo Site';
$cms_template_items = 'modelo(s)';
$cms_new_template_item = 'Novo modelo';
$cms_found_one = '1 ficheiro encontrado';
$cms_found = 'ficheiros encontrados';
$cms_empty = 'Esta secção está vazia ou provavelmente em manutenção.';
$cms_new_page = 'Nova Página';
$cms_search_words = 'Pesquisar palavras';
$cms_edit_search_words = 'editar pesquisa de palavras';
$cms_id = 'Site ID';

$cms_cleanup = 'Limpar HTML';
$cms_settings = 'Configurações';
$cms_site_exists = 'Já existe um site com este nome';

$cms_confirm_close = 'As laterações serão perdidas. Tem a certeza?';

$cms_restrict_editor = 'Restringir o editor aos estilos pré-definidos';
$cms_enable_publish = 'Permitir publicação local do site';

$cms_path_not_writable = 'O caminho indicado não é válido ou não pode ser escrito por Group-Office.';
$cms_publish = 'Publicação';
$cms_path_already_used = 'O caminho indicado já está a ser utilizado por outro site.';
$cms_site_offline = 'Este site está actualmente inacessível';

$cms_disable_publish = 'Tornar site inacessível';
$cms_publish_dynamic = 'Publicação dinâmica';
$cms_publish_static = 'Publicação estática';

//2.05
$cms_sendmail_error = 'A mensagem não pode ser enviada. Por favor, tente de novo.';
$cms_sendmail_success = 'Obrigado. A mensagem foi enviada.';
$cms_message = 'Mensagem';
$cms_subject = 'Assunto';
$cms_domain = 'Domínio';
$cms_replace_filenames = 'Substituir ficheiros';

//2.06
$cms_multipage_display = 'Somar todas as páginas das pastas e as primeiras páginas das sub-pastas';
$cms_hot_item = 'Mostrar esta página nos itens em destaque';
$cms_normal_display = 'Mostrar a primeira página desta página';

$cms_display_type = 'Quando alguém abrir uma pasta nesta página da web:';
$cms_read_more = 'Ler mais';
$cms_additional_style = 'Estilo do editor';

//2.11
$cms_activate_frontpage = 'Activar a página inicial para este tema';
$cms_main_template = 'Modelo principal'; //Changed string
$cms_frontpage_template = 'Modelo da página inicial';
$cms_websites = 'Sies da Web'; 
$cms_insert_component = 'Inserir componente';

$cms_languages = 'Línguas';
$cms_new_language = 'Nova língua';
$cms_default = 'Por defeito';
$cms_title = 'Título';
$cms_language = 'Língua';
$cms_image = 'Imagem';
$cms_no_image_selected = 'Imagem não seleccionada';
$cms_selected_image = 'Imagem seleccionada';
$cms_no_image = 'Sem imagem';

$cms_multipage = 'Sumário dos itens nesta página';

$cms_no_themes = 'Ainda não tem temas. Crie primeiro um tema. Necessita de privilégios administrativos.'; //changed string

$cms_select_local = 'Seleccione um ficheiro local';
$cms_webmaster = 'Email do Webmaster';

$cms_allow_properties = 'Permitir que outros modifiquem as propriedades do site.';
$cms_multilingual = 'Usar múltiplas línguas com este site';

//2.12
$cms_search_words_overview = 'Vista de palavras pesquisadas';
$cms_no_occurences = 'A pesquisa não encontrou resultados nestas páginas.';
$cms_there_are_results_for_multiple = 'Há %s resultados para \'%s\'';
$cms_there_are_results_for_single = 'Há 1 resultado para \'%s\'';

$cms_print_style = 'Imprimir estilos';

$cms_search = 'Pesquisar';
$cms_login = 'Entrar';

//2.14
$cms_searchengine_info = 'Informação sobre o motor de pesquisa';
$cms_autogenerate_searchengine_info = 'Gerar automaticamente informação sobre o motor de pesquisa (Recomendado)';

//2.15 
$cms_template_item = 'Modelo';
$cms_page_template = 'Este modelo pode ser utilizado para páginas';

$cms_go_auth = 'Usar autenticação Group-Office';

$cms_start_page = 'Página inicial';


$cms_hot_item_text='Item de texto em destaque';

//2.16
$cms_unregistered_comments = 'Permitir comentários de qualquer visitante';

$cms_comments = 'Comentários';
$cms_comments_text = 'Pode deixar comentários ao fundo desta página.';
$cms_comments_login = 'Precisa de entrar para deixar comentários.';
$cms_add_comment = 'Adicionar comentário';
$cms_comments_missing_field = 'Deve indicar um nome e o comentário.';

$cms_logout = 'Sair';
$cms_subject = 'Assunto';
$cms_message = 'Mensagem';
$cms_send_message = 'Enviar';

$cms_contact_form = 'Formulário de contacto';
$cms_user_search = 'Pesquisa de utilizador';

$cms_insert_plugin = 'Inserir Plugin';
$cms_logged_out =  'Acabou de sair';

$cms_insert_contactform = 'Inserir formulário de contacto';
$cms_message_height = 'Altura do campo da mensagem';
$cms_insert_comments = 'Inserir formulário de comentários';
$cms_commentsform='Formulário de comentários';


$cms_login_template_item = 'Modelo - Entrada';
$cms_default_go_login='Caixa de entrada Group-Office por defeito';

$cms_userfield = 'Campo de dados do utilizador';
$cms_fckeditor_styles='estilos seleccionáveis';
$cms_fckeditor_help='Clique aqui para documentação';

$cms_add_contact_success_title='Obrigado!';
$cms_add_contact_success_text='Já é subscritor da newsletter!';
$cms_add_contact_email_subject='Novo contacto a adicionar à lista de email';
$cms_new_comment_subject = 'Novo comentário deixado em %s';
$cms_insert_video='Inserir vídeo';
$cms_antispam_text='Por favor, responda a esta simples pergunta para evitar o SPAM';
$cms_antispam_fail='A resosta à pergunta anti-spam está incorrecta. Por favor, tente de novo.';
$cms_insert_video='Inserir vídeo';

$cms_batch_upload = 'Enviar Múltiplos Ficheiros';
$cms_batch_upload_text = 'Com esta função pode inserir múltiplas ligações para ficheiros de uma só vez.';