<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "Typ";
$strModified = "Modifierad";
$strSize = "Storlek";
$fbRefresh = "uppdatera";
$fbProperties = "egenskaper";
$fbNewFolder = "ny katalog";
$fbDelete = "radera";
$fbCut = "klipp";
$fbPaste = "klistra";
$fbCopy = "kopiera";
$fbFiletypes = "filtyper";
$fbPath = "Sökväg";
$fbFolders = "Kataloger";
$fbNoSelect = "Du valde ingenting. Tryck på en ikon bredvid namnet för att välja.";
$fbConfirmDelete = "Bekräfta radering";
$fbGeneral = "Generellt";
$fbConfirmOverwrite = "Bekräfta överskrivning";
$strOverwritePrefix = "Är du säker på att du vill skriva över ";
$strOverwriteSuffix = "?";
$fbDescription = "Beskrivning";
$fbLocation = "Plats";
$fbUpload = "ladda upp";
$fbUpload_text = "Välj en fil att ladda upp";
$fbUpload_nofile = "Ingen fil mottogs.";
$fbFolderExists = "Katalogen existerar redan.";
$fbFolder = "Katalog";
$fbSelect = "Välj fil...";
$fbNoFile = "Filen du har försökt att ladda upp är för stor.<br /> Den maximala flstorleken är satt till: ";
$fbPleaseWait = "Vad god vänta. Sänder data... ";
$fbFilename = "Filnamn";
$fbUpLevel = "stega upp";
$fbItems = "sak(er)";
$fbFolderSize = "Katalogens storlek";
$fbMaxUploadSize = "Max storlek";
$ml_file_too_big = "Filen du försökte bifoga är för stor, den maximala filstorleken är satt till: ";
$cmdSearch = "Sök";
$fbNameExists = "Namnet existerar redan.";
$fbThis = 'denna';
$fbFiles = 'Filer';
$fs_no_multi_select = 'Du kan ej välja mer än ett item med detta val';
$cms_untitled = 'Untitled';
$cms_insert_file = 'Lägg in fil';
$cms_preview = 'Förhandsgrandska';
$cms_keywords = 'Nyckelord';
$cms_priority = 'Prioritet';
$cms_hide_folder = 'Göm denna katalog.';
$cms_theme = 'Tema';
$cms_use_go_auth = 'Använd Group-Office autensiering på denna site';
$cms_search_files_prefix = 'HTML-flen som innehåller ordet';
$cms_search_files_suffix = 'är vald automatiskt. Klicka på \''.$cmdOk.'\' för att spara detta val.';
$cms_new_site = 'Ny site';
$cms_search_files = 'sök filer';
$cms_subscribe = 'prenumenera';
$cms_sites = 'site(r)';
$cms_style = 'Stil';
$cms_insert_file_url = 'Lägg in URL';
$cms_templates = 'mallar';
$cms_files = 'filer';
$cms_items = 'sak(er)';
$cms_header = 'Header';
$cms_footer = 'Footer';
$cms_new_theme = 'nytt tema';
$cms_themes = 'tema';
$cms_themes_menu = 'teman';
$cms_all_sites = 'alla siter';
$cms_your_sites = 'dina siter';
$cms_cmd_new_site = 'ny site';
$cms_template_items = 'mall(ar)';
$cms_new_template_item = 'ny mall';
$cms_found_one = '1 fil funnen';
$cms_found = 'filer funna';
$cms_empty = 'Denna sektion är tom och förmodligen under uppbyggnad.';
$cms_new_page = 'ny sida';
$cms_search_words = 'Sökord';
$cms_edit_search_words = 'editera sökord';
$cms_id = 'Site ID';

$cms_cleanup = 'Rensa upp&nbsp;HTML';
$cms_settings = 'Inställningar';
$cms_site_exists = 'En site med detta namn existerar redan';

$cms_confirm_close = 'Ändringarna kommer gå förlorade, är du säker?';

$cms_restrict_editor = 'Begränsa editeraren till fördefinierade stilar';
$cms_enable_publish = 'Tillåt publisering av lokala websiter';

$cms_path_not_writable = 'Sökvägen du angav är felaktig eller inte skrivbar av Group-Office.';
$cms_publish = 'Publisering';
$cms_path_already_used = 'Sökvägen du angav används redan av en annan website.';
$cms_site_offline = 'Denna site är för närvarande offline';

$cms_disable_publish = 'Gör site offline';
$cms_publish_dynamic = 'Publisera dynamiskt';
$cms_publish_static = 'Publisera statiskt';

//2.05
$cms_sendmail_error = 'Ditt meddelande kunde inte skickas. Var vänlig försök igen.';
$cms_sendmail_success = 'Tack. Ditt meddelande har skickats.';
$cms_message = 'Meddelande';
$cms_subject = 'Ämne';
$cms_domain = 'Domän';
$cms_replace_filenames = 'Ersätt filnamn';

//2.06
$cms_multipage_display = 'Summera alla sidor i katalogerna och den första sidan i underkatalogerna';
$cms_hot_item = 'Visa denna sida i hot items';
$cms_normal_display = 'Visa den första sidan i denna katalog';

$cms_display_type = 'När en besökare öppnar en katalog i denna webbsida:';
$cms_read_more = 'Läs mer';
$cms_additional_style = 'Stil som används i editorn';

//2.11
$cms_activate_frontpage = 'Aktivera framsida för detta tema';
$cms_main_template = 'Huvud mall'; //Changed string
$cms_frontpage_template = 'Framsides mall';
$cms_websites = 'Websiter'; 
$cms_insert_component = 'Infoga komponent';

$cms_languages = 'Språk';
$cms_new_language = 'Nytt språk';
$cms_default = 'Default';
$cms_title = 'Titel';
$cms_language = 'Språk';
$cms_image = 'Bild';
$cms_no_image_selected = 'Ingen bild vald';
$cms_selected_image = 'Välj bild';
$cms_no_image = 'Ingen bild';

$cms_multipage = 'Summera alla sidor i dessa mappar och första sidan av undermapparna';

$cms_no_themes = 'Du har inget tema än. Skapa ett tema först. Du behöver administratörsrättigheter för att skapa teman.'; //changed string

$cms_select_local = 'Välj lokal fil';
$cms_webmaster = 'Webmaster&nbsp;e-post';

$cms_allow_properties = 'Tillåt att andra ändrar i sitens egenskaper.';
$cms_multilingual = 'Använd flera språk för denna site';

//2.12
$cms_search_words_overview = 'Sökords överblick';
$cms_no_occurences = 'Nyckelorder förekommer inte i denna websites sidor.';
$cms_there_are_results_for_multiple = 'Det finns %s resultat för \'%s\'';
$cms_there_are_results_for_single = 'Det finns 1 resultat för \'%s\'';

$cms_print_style = 'Skriv ut stilar';

$cms_search = 'Sök';
$cms_login = 'Logga in';
