<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('cms'));

$strType = "ชนิด";
$strModified = "ปรับปรุง";
$strSize = "ขนาด";
$fbRefresh = "รีเฟรช";
$fbProperties = "คุณสมบัติ";
$fbNewFolder = "สร้างกล่องใหม่";
$fbDelete = "ลบ";
$fbCut = "ตัด";
$fbPaste = "วาง";
$fbCopy = "คัดลอก";
$fbFiletypes = "ชนิดของไฟล์";
$fbPath = "ทางเดิน";
$fbFolders = "กล่อง";
$fbNoSelect = "คุณไม่ได้ทำการเลือกรายการ. คลิกที่ไอค่อนถัดจากชื่อเพื่อเลือกรายการ";
$fbConfirmDelete = "ยืนยันการลบ";
$fbGeneral = "ทั่วไป";
$fbConfirmOverwrite = "ยืนยันการเขียนทับ";
$strOverwritePrefix = "คุณต้องการที่จะเขียนทับ";
$strOverwriteSuffix = "?";
$fbDescription = "รายละเอียด";
$fbLocation = "ตำแหน่ง";
$fbUpload = "อัพโหลด";
$fbUpload_text = "เลือกไฟล์ที่ต้องการจะอัพโหลด";
$fbUpload_nofile = "ไม่มีไฟล์ใดที่ไม่ได้รับ";
$fbFolderExists = "กล่องนี้มีอยู่แล้ว";
$fbFolder = "กล่อง";
$fbSelect = "เลือกไฟล์";
$fbNoFile = "ไฟล์ที่คุณอัพโหลดมีขนาดใหญ่เกินไป.<br /> ขนาดไฟล์สูงสุดที่อัพโหลดได้คือ: ";
$fbPleaseWait = "โปรดรอสักครู่กำลังส่งข้อมูล...";
$fbFilename = "ชื่อไฟล์";
$fbUpLevel = "เพิ่มระดับ";
$fbItems = "รายการ";
$fbFolderSize = "ขนาดของกล่อง";
$fbMaxUploadSize = "ขนาดสูงสุด";
$ml_file_too_big = "ไฟล์ที่คุณแนบมาใหญ่มาก, ขนาดไฟล์สูงสุดที่ตั้งไว้คือ: ";
$cmdSearch = "ค้นหา";
$fbNameExists = "ชื่อนี้ซ้ำ.";
$fbThis = 'นี้';
$fbFiles = 'ไฟล์';
$fs_no_multi_select = 'คุณไม่สามารถเลือกรายการได้มากกว่าหนึ่งอย่างด้วยตัวเลือกนี้';
$cms_untitled = 'ไม่มีชื่อ';
$cms_insert_file = 'แทรกไฟล์';
$cms_preview = 'ดูก่อน';
$cms_keywords = 'คำค้นหา';
$cms_priority = 'ความสำคัญ';
$cms_hide_folder = 'ซ่อนกล่องนี้ในไซท์';
$cms_theme = 'ทีม';
$cms_use_go_auth = 'ใช้ Group-Office เป็นการรับรองเว็บนี้';
$cms_search_files_prefix = 'ไฟล์ HTML ที่บรรจุคำว่า';
$cms_search_files_suffix = 'ได้ทำการเลือกอัตโนมัตแล้ว. คลิกปุ่ม \'ตกลง\'เพื่อบันทึก.';
$cms_new_site = 'สร้างไซท์ใหม่';
$cms_search_files = 'ค้นหาไฟล์';
$cms_subscribe = 'ซับสคริป';
$cms_sites = 'ไซท์';
$cms_style = 'สไตล์';
$cms_insert_file_url = 'แทรก URL';
$cms_templates = 'เทมเพลท';
$cms_files = 'ไฟล์';
$cms_items = 'รายการ';
$cms_header = 'เฮดเดอร์';
$cms_footer = 'ฟุตเตอร์';
$cms_new_theme = 'สร้างทีมใหม่';
$cms_themes = 'ทีม';
$cms_themes_menu = 'รูปแบบ';
$cms_all_sites = 'ไซท์ทั้งหมด';
$cms_your_sites = 'ไซท์ของคุณ';
$cms_cmd_new_site = 'ไซท์ใหม่';
$cms_template_items = 'เทมเพลท';
$cms_new_template_item = 'สร้างเทมเพลทใหม่';
$cms_found_one = 'ค้นพบ 1 ไฟล์';
$cms_found = 'ค้นพบไฟล์แล้ว';
$cms_empty = 'เซกชันนี้ว่างเป็นไปได้ว่าอาจเก็บไปแล้ว';
$cms_new_page = 'สร้างหน้าใหม่';
$cms_search_words = 'ค้นหาคำ';
$cms_no_themes = 'คุณยังไม่มีรูปแบบ. สร้างรูปแบบก่อน';
$cms_edit_search_words = 'แก้ไขคำค้นหา';
$cms_id = 'ไซท์ไอดี';

$cms_cleanup = 'ลบ&nbsp;HTML';
$cms_settings = '';
$cms_site_exists = 'ชื่อไซท์นี้มีอยู่แล้ว';
$cms_main_template = 'หน้าหลัก';
$cms_confirm_close = 'การเปลี่ยนครั้งนี้จะสูญหาย?';

$cms_restrict_editor = 'Restrict editor to predefined styles';
$cms_enable_publish = 'เปิดเว็บโลคอลให้ทุกคนเห็น';

$cms_path_not_writable = 'พาธที่คุณเข้ามาไม่สามารถแก้ไข Group-Officeได้ .';
$cms_publish = 'การพิมพ์';
$cms_path_already_used = 'ทางเดินที่คุณเข้ามาถูกใช้โดยเว็บไซท์อื่น.';
$cms_site_offline = 'ไซท์นี้ขณะนี้เป็นออฟไลน์';

$cms_disable_publish = 'กำหนดให้ไซท์นี้เป็นออฟไลน์';
$cms_publish_dynamic = 'พิมพ์แบบได้นามิก';
$cms_publish_static = 'พิมพ์แบบสแตติก';

//2.05
$cms_sendmail_error = 'ข้อความของคุณยังไม่ได้ส่ง. กรุณาลองใหม่';
$cms_sendmail_success = 'ขอบคุณ.ข้อความของคุณถูกส่งไปแล้ว.';
$cms_message = 'ข้อความ';
$cms_subject = 'หัวข้อ';
$cms_domain = 'โดเมน';
$cms_replace_filenames = 'วางชื่อไฟล์';

//2.06
$cms_multipage_display = 'รวมหน้าทั้งหมดของกล่องและหน้าแรกในกล่องซ้อน';
$cms_hot_item = 'แสดงหน้านี้ในหน้าพิเศษ';
$cms_normal_display = 'แสดงหน้าแรกของกล่องนี้';

$cms_display_type = 'เมื่อมีการเข้าไปในกล่อง:';
$cms_read_more = 'อ่านเพิ่มเติม';
$cms_additional_style = 'สไตล์ที่ใช้ในการแก้ไข';
//2.08
$sc_recur_section = 'Recurrence';
$sc_options_section = 'Options';
$sc_close = 'ปิด';

$cal_count_single = 'เหตุการณ์';
$cal_count_multiple = 'เหตุการณ์';

$cal_until = 'จนถึง';
$cal_forever = 'ตลอดไป';

//2.09
$cal_merged_overview = 'Merged overview';
$cal_own_availability = 'Own availability';
