<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Въвели сте невалиден период за време';
$pm_add_hours_success = 'Датата която е въведена отдолу е запазена успешно';
$pm_already_booked = 'Вие вече сте ангажиран в този период';
$pm_new_entry = 'Ново въвеждане в';
$pm_fees = 'Тарифи';
$pm_new_fee = 'Нова тарифа';
$pm_users = 'Потребители';
$pm_materials = 'Материали';
$pm_new_material = 'Нов материал';
$pm_project_data = 'Projectdata от';
$pm_load= 'Зареждане';
$pm_enter_data = 'Въведете дата';
$pm_value = 'Стойност';
$pm_too_old = 'Не е позволено да въвеждате дата по стара от една седмица';

$pm_employee = 'Чиновник';
$pm_project = 'Проект';
$pm_starttime = 'Стартиране на време';
$pm_endtime = 'Край на времето';
$pm_breaktime = 'Почивка';
$pm_this_week = 'Въведено тази седмица';
$pm_no_projects = 'Нямате никакви проекти';
$pm_hours = 'Часове';
$pm_total_hours = 'Общо часове';
$pm_client = 'Клиент';
$pm_created_at = 'Създадено на';

$pm_show_all = 'Покажи всичко';
$pm_show_period = 'Покажи от';
$pm_to = 'до';
$pm_show_month = 'Покажи месец';

$pm_total_hours_days = 'Общо часове/дни';
$pm_projects_count = 'проект(и)';
$pm_show_data = 'Покажи дата';
$pm_new_project = 'Нов проект';
$pm_other_contacts = 'Други контакти';
$pm_no_contacts = 'Вие нямате контакт който може да функционира като клиент за този проект. Моля създайте първо един';

$pm_unit_value = 'Единица стойност';
$pm_units = 'Единици';
$pm_mins = 'Минути';
$pm_no_fees = 'Няма тарифи които са създадени. Само потребители с администраторски привилегии могат да създават тарифи.';
$pm_fee = 'Fee';
$pm_no_contact = 'Нищо';
$pm_load_period= 'Период';
$pm_load_type= 'Зареди дата за';
$pm_total_fee = 'Обща тарифа';
$pm_total_days = 'Общо дни';
$pm_total_units = 'Общо единици';
$pm_summary = 'Бележки';
