<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Zadal jste špatný časový interval';
$pm_add_hours_success = 'Zadaná data byla v pořádku uložena';

$pm_new_entry = 'Nové zadání v';
$pm_fees = 'Sazby';
$pm_new_fee = 'Nová sazba';
$pm_users = 'Uživatelé';
$pm_materials = 'Materiál';
$pm_new_material = 'Nový meteriál';
$pm_project_data = 'Project data from';

$pm_value = 'Hodnota';
$pm_too_old = 'Nemůžete zadávat údaje starší než 1 týden';

$pm_employee = 'Zaměstnanci';
$pm_project = 'Projekt';
$pm_starttime = 'Začátek';
$pm_endtime = 'Konec';
$pm_breaktime = 'Přerušení';
$pm_this_week = 'Zadáno tento týden';
$pm_no_projects = 'Nemáte žádný projekt';
$pm_hours = 'Hodin';
$pm_total_hours = 'Celkem hodin';
$pm_client = 'Klient';
$pm_created_at = 'Založeno';

$pm_show_all = 'Zobrazit vše';
$pm_show_period = 'Zobrazit od';
$pm_to = 'do';
$pm_show_month = 'Zobrazit měsíc';

$pm_total_hours_days = 'Celkový počet hodin/dnů';
$pm_projects_count = 'projekt(y)';
$pm_show_data = 'Zobrazit data';
$pm_new_project = 'Nový projekt';
$pm_other_contacts = 'Ostatní kontakty';
$pm_no_contacts = 'Nemáte zadaného žádněho klienta, prosím napřed jej vytvořte';

$pm_unit_value = 'Hodnota jednotky';
$pm_units = 'Jednotek';
$pm_mins = 'minut';
$pm_no_fees = 'Nejsou zatím žádné sazby. Pouze administrátor může zadávat sazby.';
$pm_fee = 'Výdaj';
$pm_no_contact = 'žádný';
$pm_load_period= 'Perioda';
$pm_load_type= 'Nahrát data pouze pro';
$pm_total_fee = 'Celkové výdaje';
$pm_total_days = 'Celkem dní';
$pm_total_units = 'Celkem jednotek';
$pm_summary = 'Souhrn';
$pm_this_entry = 'tato položka';
$pm_entry = 'položka';
//translation required
$pm_timer_started_at = 'Stopky začaly v';
$pm_start_timer = 'Pustit stopky';
$pm_stop_timer = 'Zastavit stopky';

$pm_start_date = 'Začátek';
$pm_end_date = 'Konec';
$pm_responsible = 'Zodpovídá';
$pm_status = 'Stav';

$pm_status_values[1] = 'Nabídka';
$pm_status_values[2] = 'Probíhá';
$pm_status_values[3] = 'Čeká';
$pm_status_values[4] = 'Hotovo';
$pm_status_values[5] = 'Uhrazeno';

$pm_filter = 'Filtr';
$pm_project_exists = 'Projekt s tímto jménem už existuje';

$pm_clocked_in = 'Je vám počítán čas. Klikněte zde pro ukončení měření času';

$pm_alert = 'Projekt je po termínu';
$pm_budget = 'Rozpočet';
$pm_probability = 'Šance';
$pm_yours_only = 'Vy sami';
$pm_description = 'Popis';

$pm_no_projects = 'Žádný projekt nebyl nenalezen.';


//2.08
$pm_projects = 'Projekty';
//2.12
$pm_select_project = 'Prosím zvolte projekt';
$pm_already_booked = 'Máte už záznam pro toto období. Klikněte na %s pro editaci tohoto záznamu'; //changed value. Search above
$pm_here = 'zde';
$pm_load= 'Zobrazit hodiny'; //chnaged. Search above

$pm_edit_data = 'Editace odpracovaných hodin';
$pm_enter_data = 'Zadání odpracovaných hodin';//changed, search above

//2.14
$pm_templates = 'Šablony';
$pm_template = 'Šablona';
$pm_new_template = 'Nová šablona';
$pm_no_templates = 'Žádné šablony nenalezeny';

$pm_template_offset = 'Úkol začíná';
$pm_template_after = 'když nový projekt startuje v';


$pm_new_template_event = 'Nový úkol';
$pm_duration = 'Doba';

$pm_no_template_events = 'Žádné úkoly nenalezeny';
$pm_no_template = 'Nepoužívej šablonu';

$pm_put_events_in = 'dej úkoly do';

//2.15
$pm_shift_events = 'Posuň související schůzky  ůkoly když změním startovací datum projektu';

$pm_relate_to_self = 'Projekt nemůže být související sám se sebou';

$pm_print_options = 'Tiskni nastaveni';
$pm_print_options_text = 'You can select a time period to only print the projects which have started later then the start date and ended before the end date. Leave these fields empty to print all projects.';

$pm_internal_fee= 'Internal fee';
$pm_external_fee= 'External fee';

$pm_total_external_fee = 'Total external fee';
$pm_total_internal_fee = 'Total internal fee';

$pm_billed='Billed';

$pm_fee_time = 'Value per';

$pm_book_units='Only enter a number of time units';
$pm_show_project_users = 'Specify working hours of all project users';

$pm_to_bill = 'To be billed';

$pm_total_recieved = 'Total recieved';
$pm_result = 'Result';

$pm_customer='Customer';

$pm_book_rights = 'Book access';

$pm_template_exists = 'A template with this name already exists';

$pm_link_calendar= 'Put working hours in a calendar';

$pm_project='Project';

$pm_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=221';
