<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Du har indtastet en forkert tidsperiode';
$pm_add_hours_success = 'De indtastede data er gemt';
$pm_already_booked = 'Du har allerede en aftale i den periode';
$pm_new_entry = 'Ny aftale ved';
$pm_fees = 'Beløb';
$pm_new_fee = 'Nyt beløb';
$pm_users = 'Brugere';
$pm_materials = 'Materialer';
$pm_new_material = 'Nyt materiale';
$pm_project_data = 'Projekt data fra';
$pm_load= 'Hent';
$pm_enter_data = 'Indtast data';
$pm_value = 'Værdi';
$pm_too_old = 'Du kan ikke indtaste data der er mere end en uge gamle';

$pm_employee = 'Ansatte';
$pm_project = 'Projekt';
$pm_starttime = 'Start tidspunkt';
$pm_endtime = 'Slut tidspunkt';
$pm_breaktime = 'Afbrydelsestidspunkt';
$pm_this_week = 'Indtastet denne uge';
$pm_no_projects = 'Du har ingen projekter';
$pm_hours = 'Timer';
$pm_total_hours = 'Total antal timer';
$pm_client = 'Klient';
$pm_created_at = 'Oprettet';

$pm_show_all = 'Vis alle';
$pm_show_period = 'Vis fra';
$pm_to = 'til';
$pm_show_month = 'Vis måned';

$pm_total_hours_days = 'Ialt timer/dage';
$pm_projects_count = 'projekt(er)';
$pm_show_data = 'Vis data';
$pm_new_project = 'Nyt projekt';
$pm_other_contacts = 'Andre kontakter';
$pm_no_contacts = 'Du har ingen kontakt der kan bruges som klient til dette projekt. Du skal først oprette en kontakt';

$pm_unit_value = 'Enhedsværdi';
$pm_units = 'Enheder';
$pm_mins = 'min.';
$pm_no_fees = 'Der er ikke oprettet nogen beløb. Kun en bruger med administrator rettigheder kan oprette beløb.';
$pm_fee = 'Beløb';
$pm_no_contact = 'Ingen';
$pm_load_period= 'Periode';
$pm_load_type= 'Hent kun data for';
$pm_total_fee = 'Totalt beløb';
$pm_total_days = 'Antal dage';
$pm_total_units = 'Antal enheder';
$pm_summary = 'Oversigt';
$pm_this_entry = 'denne tidsbestilling';
$pm_entry = 'tidsbestilling';
//translation required
$pm_timer_started_at = 'Timer startet';
$pm_start_timer = 'Klok ind';
$pm_stop_timer = 'Klok ud';

$pm_start_date = 'Start dato';
$pm_end_date = 'Afslutningsdato';
$pm_responsible = 'Ansvarlig';
$pm_status = 'Status';

$pm_status_values[1] = 'Tilbud';
$pm_status_values[2] = 'I gang';
$pm_status_values[3] = 'Venter';
$pm_status_values[4] = 'Udført';
$pm_status_values[5] = 'Faktureret';

$pm_filter = 'Filter';
$pm_project_exists = 'Et projekt ved det navn eksisterer allerede';

$pm_clocked_in = 'Du er allerede klokket ind. Klik her for at klokke ud';

$pm_alert = 'Dette projekt forventes færdigt';
$pm_budget = 'Budget';
$pm_probability = 'Sandsynlighed';
$pm_yours_only = 'Dig selv';
$pm_description = 'Beskrivelse';

$pm_no_projects = 'Ingen projekter fundet.';
