<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'You entered an invalid time period';
$pm_add_hours_success = 'Data as entered below was saved successfully';

$pm_new_entry = 'New entry at';
$pm_fees = 'Fees';
$pm_new_fee = 'New fee';
$pm_users = 'Users';
$pm_materials = 'Materials';
$pm_new_material = 'New material';
$pm_project_data = 'Projectdata from';

$pm_value = 'Value';
$pm_too_old = 'You are not allow to enter data older then one week';

$pm_employee = 'Employee';
$pm_project = 'Project';
$pm_starttime = 'Starting time';
$pm_endtime = 'Ending time';
$pm_breaktime = 'Break time';
$pm_this_week = 'Entered this week';
$pm_no_projects = 'You don\'t have any projects';
$pm_hours = 'Hours';
$pm_total_hours = 'Total number of hours';
$pm_client = 'Client';
$pm_created_at = 'Created at';

$pm_show_all = 'Show all';
$pm_show_period = 'Show from';
$pm_to = 'to';
$pm_show_month = 'Show month';

$pm_total_hours_days = 'Total number of hours/days';
$pm_projects_count = 'project(s)';
$pm_show_data = 'Show data';
$pm_new_project = 'New project';
$pm_other_contacts = 'Other contacts';
$pm_no_contacts = 'You don\'t have a contact that can function as a client for this project. Please create one first';

$pm_unit_value = 'Unit value';
$pm_units = 'Units';
$pm_mins = 'mins';
$pm_no_fees = 'There are no fees created yet. Only a user with administrator privileges can create fees.';
$pm_fee = 'Fee';
$pm_no_contact = 'None';
$pm_load_period= 'Period';
$pm_load_type= 'Only load data for';
$pm_total_fee = 'Total fee';
$pm_total_days = 'Total days';
$pm_total_units = 'Total units';
$pm_summary = 'Summary';
$pm_this_entry = 'this booking';
$pm_entry = 'booking';
//translation required
$pm_timer_started_at = 'Timer started at';
$pm_start_timer = 'Clock in';
$pm_stop_timer = 'Clock out';

$pm_start_date = 'Start date';
$pm_end_date = 'End date';
$pm_responsible = 'Responsible';
$pm_status = 'Status';

$pm_status_values[1] = 'Offer';
$pm_status_values[2] = 'Ongoing';
$pm_status_values[3] = 'Waiting';
$pm_status_values[4] = 'Done';
$pm_status_values[5] = 'Billed';

$pm_filter = 'Filter';
$pm_project_exists = 'A project with this name already exists';

$pm_clocked_in = 'You are clocked in. Click here if you want to clock out';

$pm_alert = 'This project is over due';
$pm_budget = 'Budget';
$pm_probability = 'Probability';
$pm_yours_only = 'Yourself';
$pm_description = 'Description';

$pm_no_projects = 'No projects found.';


//2.08
$pm_projects = 'Projects';
//2.12
$pm_select_project = 'Please select a project';
$pm_already_booked = 'You have already booked in this period. Click %s to edit this booking'; //changed value. Search above
$pm_here = 'here';
$pm_load= 'View hours'; //chnaged. Search above

$pm_edit_data = 'Edit working hours';
$pm_enter_data = 'Enter working hours';//changed, search above

//2.14
$pm_templates = 'Templates';
$pm_template = 'Template';
$pm_new_template = 'New template';
$pm_no_templates = 'No templates found';

$pm_template_offset = 'Todo starts';
$pm_template_after = 'after the new project starts at';


$pm_new_template_event = 'New todo';
$pm_duration = 'Duration';

$pm_no_template_events = 'No todos found';
$pm_no_template = 'Don\'t use a template';

$pm_put_events_in = 'put todos in';

//2.15
$pm_shift_events = 'Shift related appointments and tasks when I change the project start date';

$pm_relate_to_self = 'Project can\'t be related to itself';

$pm_print_options = 'Print options';
$pm_print_options_text = 'You can select a time period to only print the projects which have started later then the start date and ended before the end date. Leave these fields empty to print all projects.';

$pm_internal_fee= 'Internal fee';
$pm_external_fee= 'External fee';

$pm_total_external_fee = 'Total external fee';
$pm_total_internal_fee = 'Total internal fee';

$pm_billed='Billed';

$pm_fee_time = 'Value per';

$pm_book_units='Only enter a number of time units';
$pm_show_project_users = 'Specify working hours of all project users';

$pm_to_bill = 'To be billed';

$pm_total_recieved = 'Total recieved';
$pm_result = 'Result';

$pm_customer='Customer';

$pm_book_rights = 'Book access';

$pm_template_exists = 'A template with this name already exists';

$pm_link_calendar= 'Put working hours in a calendar';

$pm_project='Project';

$pm_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=221';

$pm_add_project_hours = 'Select a project if you want to add this event as project hours too';
$pm_dont_add_to_project = 'Don\'t add to a project';