<?php
//Uncomment this line in new translations! LI 09.02.2006
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Syötit kelvottoman aika välin';
$pm_add_hours_success = 'Tallennus onnistui';

$pm_new_entry = 'Uusi tieto';
$pm_fees = 'Kustannukset';
$pm_new_fee = 'Uusi kustannus';
$pm_users = 'Käyttäjät';
$pm_materials = 'Materiaalit';
$pm_new_material = 'Uusi materiaali';
$pm_project_data = 'Projektitiedot alkaen';

$pm_value = 'Arvo';
$pm_too_old = 'Et saa syöttää viikkoa vanhempia tietoja';

$pm_employee = 'Työntekijä';
$pm_project = 'Projekti';
$pm_starttime = 'Aloitus aika';
$pm_endtime = 'Lopetus aika';
$pm_breaktime = 'Tauko aika';
$pm_this_week = 'Syötetty tällä viikolla';
$pm_no_projects = 'Sinulla ei ole projekteja';
$pm_hours = 'Tunnit';
$pm_total_hours = 'Kokonaistuntimäärä';
$pm_client = 'Asiakas';
$pm_created_at = 'Luotu';

$pm_show_all = 'Näytä kaikki';
$pm_show_period = 'Näytä alkaen';
$pm_to = '-';
$pm_show_month = 'Näytä kuukausi';

$pm_total_hours_days = 'Tuntien/päivien kokonaismäärä';
$pm_projects_count = 'projekti(t)';
$pm_show_data = 'Näytä tiedot';
$pm_new_project = 'Uusi projekti';
$pm_other_contacts = 'Muut yhteydet';
$pm_no_contacts = 'Sinulla ei ole yhteyttä joka voisi toimia asiakkaan tässä projetkissa. Luo sellainen ensin';

$pm_unit_value = 'Yksikkö hinta';
$pm_units = 'Yksiköitä';
$pm_mins = 'minutit';
$pm_no_fees = 'Mitään kustannuksia ei ole luotu. Vain järjestelmävalvojan oikeudet omaava käyttäjä voi luoda kustannuksia.';
$pm_fee = 'Kustannus';
$pm_no_contact = 'Tyhjä';
$pm_load_period= 'Aikajakso';
$pm_load_type= 'Lataa ainostaan tiedot';
$pm_total_fee = 'Kustannus yhteensä';
$pm_total_days = 'Päiviä yhteensä';
$pm_total_units = 'Yksiköitä yhteensä';
$pm_summary = 'Yhteensä';
$pm_this_entry = 'tämä kirjaus';
$pm_entry = 'kirjaus';
//translation required
$pm_timer_started_at = 'Ajastin käynnistetty';
$pm_start_timer = 'Kello sisään';
$pm_stop_timer = 'Kello ulos';

$pm_start_date = 'Aloitus päivämäärä';
$pm_end_date = 'Loppu päivämäärä';
$pm_responsible = 'vastuullinen';
$pm_status = 'Tila';

$pm_status_values[1] = 'Tarjous';
$pm_status_values[2] = 'Työn alla';
$pm_status_values[3] = 'Odottamassa';
$pm_status_values[4] = 'Tehyt';
$pm_status_values[5] = 'Laskutettu';

$pm_filter = 'Suodatin';
$pm_project_exists = 'Tämän niminen projekti on jo olemassa';

$pm_clocked_in = 'Olet merkitty sisään. Paina tästä jos haluat poistua';

$pm_alert = 'Tämä projekti on myöhässä';
$pm_budget = 'Budjetti';
$pm_probability = 'Todennäköisyys';
$pm_yours_only = 'Itsellesi';
$pm_description = 'Kuvaus';

$pm_no_projects = 'Projekteja ei löytnyt.';


//2.08
$pm_projects = 'Projektit';
//2.12
$pm_select_project = 'Valitse projekti';
$pm_already_booked = 'Olet jo varattuna tänän aikana. Paina %s muokataksesi tätä varausta'; //changed value. Search above
$pm_here = 'tässä';
$pm_load= 'Näytä tunnit'; //chnaged. Search above

$pm_edit_data = 'Muokkaa työtunnit';
$pm_enter_data = 'Syötä työtunnit';//changed, search above

//2.14
$pm_templates = 'Mallipohjat';
$pm_template = 'Mallipohja';
$pm_new_template = 'Uusi mallipohja';
$pm_no_templates = 'Malipohja ei löytynyt';

$pm_template_offset = 'Tehtävä alkaa';
$pm_template_after = 'uuden projektin jälkeen alkaa kello';


$pm_new_template_event = 'Uusi tehtävä';
$pm_duration = 'Kesto';

$pm_no_template_events = 'Mitään tehtäviä ei löytynyt';
$pm_no_template = 'Älä käytä mallipohjaa';

$pm_put_events_in = 'laita tehtävät';

//2.15
$pm_shift_events = 'Siirrä liittyvät tapaamiset ja tehtävät kun projektin aloitus päivä siirtyy';

$pm_project_agenda = 'Projektiaikataulu';
$pm_relate_to_self = 'Projekti ei voi viitata itseensä';
