<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Vous avez entré une période horaire invalide';
$pm_add_hours_success = 'Les données entrées ci-dessous ont été enregistrées avec succès';
$pm_new_entry = 'Nouvelle entrée';
$pm_fees = 'honoraires';
$pm_new_fee = 'Nouvel honoraire';
$pm_users = 'Utilisateurs';
$pm_materials = 'Matériels';
$pm_new_material = 'Nouveau matériel';
$pm_project_data = 'Données du projet de';
$pm_value = 'Valeur';
$pm_too_old = 'Vous n\'êtes pas autorisé à entrez des données de plus d\'une semaine';
$pm_employee = 'Employé';
$pm_project = 'Projet';
$pm_starttime = 'Heure de début';
$pm_endtime = 'Heure de fin';
$pm_breaktime = 'Heure de pause';
$pm_this_week = 'Entrées cette semaine';
$pm_no_projects = 'Vous n\'avez pas de projet';
$pm_hours = 'Heures';
$pm_total_hours = 'Nombre total d\'heures';
$pm_client = 'Client';
$pm_created_at = 'Créé à';
$pm_show_all = 'Montrer tout';
$pm_show_period = 'Montrer de';
$pm_to = 'à';
$pm_show_month = 'Montrer le mois';
$pm_total_hours_days = 'Nombre total d\'heures/jours';
$pm_projects_count = 'projet(s)';
$pm_show_data = 'Montrer les données';
$pm_new_project = 'Nouveau projet';
$pm_other_contacts = 'Autres contacts';
$pm_no_contacts = 'Vous n\'avez pas de contact qui puisse fonctionner comme client pour ce projet. Veuillez d\abord en créer un.';
$pm_unit_value = 'Unité de valeur';
$pm_units = 'Unités';
$pm_mins = 'mins';
$pm_no_fees = 'Il n\'y a pas encore d\'honoraire de créé. Seul un utilisateur avec des privilèges d\'administrateur peut créer des honoraires.';
$pm_fee = 'Honoraire';
$pm_no_contact = 'Aucun';
$pm_load_period= 'Période';
$pm_load_type= 'Charger uniquement les données pour';
$pm_total_fee = 'Total honoraire';
$pm_total_days = 'Total jours';
$pm_total_units = 'Total unités';
$pm_summary = 'Résumé';
$pm_this_entry = 'cette réservation';
$pm_entry = 'réservation';

//translation required
$pm_timer_started_at = 'Minuteur démarré à';
$pm_start_timer = 'Synchronisation';
$pm_stop_timer = 'Désynchronisation';
$pm_start_date = 'Date de début';
$pm_end_date = 'Date de fin';
$pm_responsible = 'Responsable';
$pm_status = 'Statut';
$pm_status_values[1] = 'Proposition';
$pm_status_values[2] = 'En cours';
$pm_status_values[3] = 'En attente';
$pm_status_values[4] = 'Fait';
$pm_status_values[5] = 'Facturé';
$pm_filter = 'Filtre';
$pm_project_exists = 'Un projet avec le même nom existe déjà';
$pm_clocked_in = 'Vous êtes en cours de synchronisation. Cliquez ici pour vous désynchroniser';
$pm_alert = 'Ce projet a une date dépassée !';
$pm_budget = 'Budget';
$pm_probability = 'Probabilité';
$pm_yours_only = 'Vous-même';
$pm_description = 'Description';
$pm_no_projects = 'Aucun projet trouvé.';

//2.08
$pm_projects = 'Projets';

//2.12
$pm_select_project = 'Veuillez sélectionner un projet';
$pm_already_booked = 'Vous avez déjà réservé cette période. Cliquez %s pour éditer cette réservation'; //changed value. Search above
$pm_here = 'ici';
$pm_load= 'Voir les heures'; //chnaged. Search above
$pm_edit_data = 'Editer les heures de travail';
$pm_enter_data = 'saisir des heures de travail'; //changed, search above

//2.14
$pm_templates = 'Modèles';
$pm_template = 'Modèle';
$pm_new_template = 'Nouveau modèle';
$pm_no_templates = 'Aucun modèle trouvé';
$pm_template_offset = 'La tâche débute à';
$pm_template_after = 'après le nouveau projet démarre à';
$pm_new_template_event = 'Nouvelle tâche';
$pm_duration = 'Durée';
$pm_no_template_events = 'Aucune tâche trouvée';
$pm_no_template = 'Ne pas utiliser un modèle';
$pm_put_events_in = 'Mettre les tâches dans';

//2.15
$pm_shift_events = 'Lier les rendez-vous et les tâches lorsque je change la date de début d\'un projet';
$pm_relate_to_self = 'Un projet ne peut pas être en relation avec lui même';
$pm_print_options = 'Option d\'impression';
$pm_print_options_text = 'Vous pouvez sélectionner une période de temps pour imprimer uniquement les projets qui ont démarré après la date de début et qui ont été terminés avant la date de fin. Laissez ces champs vides pour imprimer tous les projets.';
$pm_internal_fee= 'Honoraire interne';
$pm_external_fee= 'Honoraire externe';
$pm_total_external_fee = 'Total honoraire externe';
$pm_total_internal_fee = 'Total honoraire interne';
$pm_billed='Facturé';
$pm_fee_time = 'Valeur par';
$pm_book_units='Entrez uniquement un nombre d\'unité de temps';
$pm_show_project_users = 'Specifiez les heures de travail de tous les utilisateurs de projet';
$pm_to_bill = 'A être facturé';
$pm_total_recieved = 'Total reçu';
$pm_result = 'Resultat';
$pm_customer='Client';
$pm_book_rights = 'Droits de réservation';
$pm_template_exists = 'Un modèle avec le même nom existe déjà';
$pm_link_calendar= 'Mettre les heures travaillées dans le calendrier';
?>