<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'הכנסת תאריך לא תקף';
$pm_add_hours_success = 'הנתונים אשר הוכנסו נשמרו בהצלחה';
$pm_already_booked = 'כבר ישנו רישום בתאריך זה';
$pm_new_entry = 'כניסה חדשה בתאריך';
$pm_fees = 'חיוב';
$pm_new_fee = 'חיוב חדש';
$pm_users = 'משתמשים';
$pm_materials = 'חומרים';
$pm_new_material = 'חומר חדש';
$pm_project_data = 'נתוני פרוייקט מאת';
$pm_load= 'טען';
$pm_enter_data = 'הכנס נתונים';
$pm_value = 'ערך';
$pm_too_old = 'אין באפשרותך להכניס נתונים שיותר ישנים משבוע';

$pm_employee = 'עובד';
$pm_project = 'פרוייקט';
$pm_starttime = 'זמן התחלה';
$pm_endtime = 'זמן סיום';
$pm_breaktime = 'זמן הפסקה';
$pm_this_week = 'הוכנס השבוע';
$pm_no_projects = 'אין לך פרוייקטים';
$pm_hours = 'שעות';
$pm_total_hours = 'סך כל השעות';
$pm_client = 'לקוח';
$pm_created_at = 'נוצר בתאריך';

$pm_show_all = 'הצג הכל';
$pm_show_period = 'הצג מאת';
$pm_to = 'אל';
$pm_show_month = 'הצג חודש';

$pm_total_hours_days = 'סך שעות ליום';
$pm_projects_count = 'פרויקט(ים)';
$pm_show_data = 'הצג נתונים';
$pm_new_project = 'פרוייקט חדש';
$pm_other_contacts = 'אנשי קשר אחרים';
$pm_no_contacts = 'אין לך איש קשר שיכול להיות כלקוח עבור פרוייקט זה , נא ליצור תחילה אחד חדש';

$pm_unit_value = 'ערך יחידה';
$pm_units = 'יחידות';
$pm_mins = 'mins';
$pm_no_fees = 'אין כרגע חיובים שנוצרו , רק משתמש עם הרשאות מנהל יכול ליצור חיובים';
$pm_fee = 'חיוב';
$pm_no_contact = 'אף אחד';
$pm_load_period= 'תקופה';
$pm_load_type= 'טען רק נתונים עבור';
$pm_total_fee = 'סך חיוב';
$pm_total_days = 'סך ימים';
$pm_total_units = 'סך יחידות';
$pm_summary = 'סיכום';
$pm_this_entry = 'הזמנה זו';
$pm_entry = 'הזמנה';
//translation required
$pm_timer_started_at = 'קוצב הזמן החל ב ';
$pm_start_timer = 'התחלת שעון עבודה';
$pm_stop_timer = 'סיום שעון עבודה';

$pm_start_date = 'תאריך התחלה';
$pm_end_date = 'תאריך סיום';
$pm_responsible = 'אחראי';
$pm_status = 'סטטוס';

$pm_status_values[1] = 'הצעה';
$pm_status_values[2] = 'מתמשך';
$pm_status_values[3] = 'ממתין';
$pm_status_values[4] = 'בוצע';
$pm_status_values[5] = 'חויב';

$pm_filter = 'פילטר';
$pm_project_exists = 'פרוייקט בשם זה כבר קיים';

$pm_clocked_in = 'זמנך החל להמדד , לחץ כאן אם הנך מעוניין לעוצרו';

$pm_alert = 'פרויקט זה נמשך מעבר לתאריך היעד';
$pm_budget = 'תקציב';
$pm_probability = 'הסתברות';
$pm_yours_only = 'בעצמך';
$pm_description = 'תיאור';

$pm_no_projects = 'לא נמצא אף פרוייקט';
