<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = '無効な期間設定です。';
$pm_add_hours_success = '入力されたデータの保存が完了しました';

$pm_new_entry = '新規エントリー';
$pm_fees = '料金';
$pm_new_fee = '新規料金';
$pm_users = 'ユーザ';
$pm_materials = '素材';
$pm_new_material = '新規素材';
$pm_project_data = 'プロジェクトデータ';

$pm_value = '単価';
$pm_too_old = '一週間以上古いデータは入力できません。';

$pm_employee = '従業員';
$pm_project = 'プロジェクト';
$pm_starttime = '開始時';
$pm_endtime = '終了時';
$pm_breaktime = '中断時';
$pm_this_week = '今週の参加';
$pm_no_projects = 'プロジェクトはありません';
$pm_hours = '時間';
$pm_total_hours = '総時間';
$pm_client = 'クライアント';
$pm_created_at = '作成';

$pm_show_all = '全て表示';
$pm_show_period = 'ここから';
$pm_to = 'ここまで表示';
$pm_show_month = '月を表示';

$pm_total_hours_days = '総 時間/日';
$pm_projects_count = 'プロジェクト';
$pm_show_data = 'データを表示';
$pm_new_project = '新規プロジェクト';
$pm_other_contacts = '他の連絡先';
$pm_no_contacts = 'このプロジェクトのクライアントとして機能できる連絡先がありません。 まずはじめに作成してください。';

$pm_unit_value = 'ユニット対価';
$pm_units = 'ユニット';
$pm_mins = '最低単価';
$pm_no_fees = 'まだ料金が作成されていません。管理者ユーザだけが料金を作成できます。';
$pm_fee = '料金';
$pm_no_contact = 'なし';
$pm_load_period= '期間';
$pm_load_type= '担当データのみ';
$pm_total_fee = '合計料金';
$pm_total_days = '合計日数';
$pm_total_units = '合計ユニット';
$pm_summary = '概要';
$pm_this_entry = 'この予約 ';
$pm_entry = '予約 ';
//translation required
$pm_timer_started_at = 'タイマー開始';
$pm_start_timer = 'タイマー記録開始';
$pm_stop_timer = 'タイマー記録終了';

$pm_start_date = '開始日時';
$pm_end_date = '終了日時';
$pm_responsible = '責任';
$pm_status = 'ステータス';

$pm_status_values[1] = '提議';
$pm_status_values[2] = '進行中';
$pm_status_values[3] = '停滞中';
$pm_status_values[4] = '完了';
$pm_status_values[5] = '請求済み';

$pm_filter = 'フィルタ';
$pm_project_exists = 'このプロジェクト名はすでに存在しています';

$pm_clocked_in = 'タイマーを記録し始めました。終了するにはクリックしてください';

$pm_alert = 'このプロジェクトは納期を終えました。';
$pm_budget = '予算';
$pm_probability = '見込み';
$pm_yours_only = '自身';
$pm_description = '説明';

$pm_no_projects = 'プロジェクトはありません。';


//2.08
$pm_projects = 'プロジェクト';
//2.12
$pm_select_project = 'プロジェクトを選択してください。';
$pm_already_booked = 'この期間内に予定がすでに存在しています %s をクリックしてブッキングを調整してください'; //changed value. Search above
$pm_here = 'here';
$pm_load= '時間を表示'; //chnaged. Search above

$pm_edit_data = '作業時間を編集';
$pm_enter_data = '作業時間を入力';//changed, search above

//2.14
$pm_templates = 'テンプレート';
$pm_template = 'テンプレート';
$pm_new_template = '新規テンプレート';
$pm_no_templates = 'テンプレートがありません';

$pm_template_offset = 'Todo 開始';
$pm_template_after = '新規プロジェクト開始後';


$pm_new_template_event = '新規 todo';
$pm_duration = '持続期間';

$pm_no_template_events = 'todoがありません';
$pm_no_template = 'テンプレートを使わない';

$pm_put_events_in = 'todoを設定';

//2.15
$pm_shift_events = 'プロジェクト開始日を変更したら関係するアポイントとタスクを移動する';

$pm_relate_to_self = 'プロジェクトは関係していません';
