<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Du har satt inn en feil tidsperiode';
$pm_add_hours_success = 'De innsatte data er gjemt';
$pm_already_booked = 'Du har allerede en avtale i den perioden';
$pm_new_entry = 'Ny avtale';
$pm_fees = 'Beløå';
$pm_new_fee = 'Nytt beløp';
$pm_users = 'Brukere';
$pm_materials = 'Materiale';
$pm_new_material = 'Nytt materiale';
$pm_project_data = 'Prosjekt data fra';
$pm_load= 'Hent';
$pm_enter_data = 'Legg inn data';
$pm_value = 'Verdi';
$pm_too_old = 'Du kan ikke legge til data som er mer enn en uke gammel';
$pm_employee = 'Ansatte';
$pm_project = 'Prosjekt';
$pm_starttime = 'Start tidspunkt';
$pm_endtime = 'Slutt tidspunk';
$pm_breaktime = 'Break time';
$pm_this_week = 'Satt inn denne uke';
$pm_no_projects = 'Du har ingen prosjekter';
$pm_hours = 'Timer';
$pm_total_hours = 'Total antall timer';
$pm_client = 'Klient';
$pm_created_at = 'Opprettet';

$pm_show_all = 'Vis alle';
$pm_show_period = 'Vis alle fra';
$pm_to = 'til';
$pm_show_month = 'Vis måned';

$pm_total_hours_days = 'Ialt timer/dager';
$pm_projects_count = 'projekt(er)';
$pm_show_data = 'Vis data';
$pm_new_project = 'Nytt projekt';
$pm_other_contacts = 'Andre kontakter';
$pm_no_contacts = 'Du har ingen kontakter Som kan brukes som klient til dette projektet. Du må først opprette kontakter';

$pm_unit_value = 'Enhet valør';
$pm_units = 'Enheter';
$pm_mins = 'minutter';
$pm_no_fees = 'Det er ingen betaling laget ennå. Kun en bruker med administrator rettigheter sette inn betaling.';
$pm_fee = 'Betaling';
$pm_no_contact = 'Ingen';
$pm_load_period= 'Periode';
$pm_load_type= 'Last data for';
$pm_total_fee = 'Totalt beløp';
$pm_total_days = 'Totalt antall dager';
$pm_total_units = 'Totalt antall enheter';
$pm_summary = 'Summering';
