<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Você introduziu um período de tempo inválido';
$pm_add_hours_success = 'Os dados inseridos abaixo foram salvos com sucesso';
$pm_already_booked = 'Você já reservou este período';
$pm_new_entry = 'Nova entrada em';
$pm_fees = 'Taxas';
$pm_new_fee = 'Nova taxa';
$pm_users = 'Usuários';
$pm_materials = 'Materiais';
$pm_new_material = 'Novo material';
$pm_project_data = 'Data do projeto de';
$pm_load= 'Carregar';
$pm_enter_data = 'Introduzir dados';
$pm_value = 'Valor';
$pm_too_old = 'Você não pode introduzir dados mais velhos que uma semana';
$pm_employee = 'Empregado';
$pm_project = 'Projeto';
$pm_starttime = 'Iniciado em';
$pm_endtime = 'Concluido em';
$pm_breaktime = 'Pausa';
$pm_this_week = 'Introduzido nesta semana';
$pm_no_projects = 'Você não tem nenhum projeto';
$pm_hours = 'Horas';
$pm_total_hours = 'Número total de horas';
$pm_client = 'Cliente';
$pm_created_at = 'Criado em';
$pm_show_all = 'Mostrar tudo';
$pm_show_period = 'Mostrar de';
$pm_to = 'a';
$pm_show_month = 'Mostrar meses';
$pm_total_hours_days = 'Número total de horas/dias';
$pm_projects_count = 'Projeto(s)';
$pm_show_data = 'Mostrar dados';
$pm_new_project = 'Novo Projeto';
$pm_other_contacts = 'Outros contatos';
$pm_no_contacts = 'Você não tem um contato que pode funcionar como cliente para este projeto. Por favor crie um contato antes e tente novamente.';
$pm_unit_value = 'Valor de unidade';
$pm_units = 'Unidades';
$pm_mins = 'Minutos';
$pm_no_fees = 'As taxas ainda não existem ou não foram criadas. Somente um usuário com privilégios administrativos pode criar taxas.';
$pm_fee = 'Taxa';
$pm_no_contact = 'Nenhum';
$pm_load_period= 'período';
$pm_load_type= 'Carregar dados por';
$pm_total_fee = 'Valor Total';
$pm_total_days = 'Total de Dias';
$pm_total_units = 'Total de Unidades';
$pm_summary = 'Sumário';

$pm_this_entry = 'este registro';
$pm_entry = 'registro';
//translation required
$pm_timer_started_at = 'Marcador de Tempo inicia em';
$pm_start_timer = 'Iniciar Marcador de Tempo';
$pm_stop_timer = 'Para Marcador de Tempo';

$pm_start_date = 'Data de início';
$pm_end_date = 'Data de término';
$pm_responsible = 'Responsável';
$pm_status = 'Situação';

$pm_status_values[1] = 'Projeto';
$pm_status_values[2] = 'Em andamento';
$pm_status_values[3] = 'Aguardando';
$pm_status_values[4] = 'Pronto';
$pm_status_values[5] = 'Finalizado';

$pm_filter = 'Filtro';
$pm_project_exists = 'Um projeto com este nome já existe';

$pm_clocked_in = 'Você está marcando o tempo. Clique aqui para parar';

$pm_alert = 'Este projeto está acima do estipulado';
$pm_budget = 'Orçamento';
$pm_probability = 'Probabilidade';
$pm_yours_only = 'Meus dados';
$pm_description = 'Descrição';

$pm_no_projects = 'Nenhum projeto encontrado.';

//2.08
$pm_projects = 'Projetos';
//2.12
$pm_select_project = 'Favor selecionar um projeto';
$pm_already_booked = 'Você já reservou este período. Clique %s para editar esta reserva'; //changed value. Search above
$pm_here = 'aqui';
$pm_load= 'Ver horas'; //changed. Search above

$pm_edit_data = 'Editar horário de trabalho';
$pm_enter_data = 'Entrar horário de trabalho';//changed, search above

//2.14
$pm_templates = 'Modelos';
$pm_template = 'Modelo';
$pm_new_template = 'Novo modelo';
$pm_no_templates = 'Nenhum modelo encontrado';

$pm_template_offset = 'Inicio de Pendência';
$pm_template_after = 'deposi do novo projeto inicia em';


$pm_new_template_event = 'Nova pendência';
$pm_duration = 'Duração';

$pm_no_template_events = 'Nenhum pendência encontrada';
$pm_no_template = 'Não usar modelo';

$pm_put_events_in = 'colocar pendências em';

//2.15
$pm_shift_events = 'Deslocar compromissos e tarefas relacionadas quando eu mudo a data do começo do projeto';

$pm_relate_to_self = 'Projeto não pode se relacionar com ele mesmo';

$pm_print_options = 'Imprimir opções';
$pm_print_options_text = 'Você pode selecionar um período de tempo para imprimir somente os projetos que começaram depois que a data do começo e terminaram antes da data final. Deixar estes campos vazios para imprimir todos os projetos.';

$pm_internal_fee= 'Taxa interna';
$pm_external_fee= 'Taxa externa';

$pm_total_external_fee = 'Taxa externa total';
$pm_total_internal_fee = 'taxa interna total';

$pm_billed='Faturado';

$pm_fee_time = 'Valor por';

$pm_book_units='Entrar somente o numero de unidades de tempo quando reservar horários';
$pm_show_project_users = 'Especificar horas de trabalho para todos usuários do projeto';

$pm_to_bill = 'A ser faturado';

$pm_total_recieved = 'Total recebido';
$pm_result = 'Resultado';

$pm_customer='Cliente';

$pm_book_rights = 'Acesso ao livro';
