<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Período de tempo inválido';
$pm_add_hours_success = 'Os dados foram guardados com sucesso';
$pm_already_booked = 'Já reservou este período';
$pm_new_entry = 'Nova entrada em';
$pm_fees = 'Valores';
$pm_new_fee = 'Definir Valor';
$pm_users = 'utilizadores';
$pm_materials = 'materiais';
$pm_new_material = 'material novo';
$pm_project_data = 'Data do projecto de';
$pm_load= 'carga';
$pm_enter_data = 'introduzir dados';
$pm_value = 'Valor';
$pm_too_old = 'Não pode introduzir dados mais antigos que uma semana';

$pm_employee = 'Responsável';
$pm_project = 'Projecto';
$pm_starttime = 'Início';
$pm_endtime = 'Fim';
$pm_breaktime = 'Suspenso';
$pm_this_week = 'Introduzido nesta semana';
$pm_no_projects = 'Não tem projectos';
$pm_hours = 'Horas';
$pm_total_hours = 'Total de horas';
$pm_client = 'Cliente';
$pm_created_at = 'Criado em';

$pm_show_all = 'Mostrar tudo';
$pm_show_period = 'Mostrar de';
$pm_to = 'a';
$pm_show_month = 'Mostrar mês';

$pm_total_hours_days = 'Total de horas/dias';
$pm_projects_count = 'projecto(s)';
$pm_show_data = 'mostrar dados';
$pm_new_project = 'Novo Projecto';
$pm_other_contacts = 'Outros contactos';
$pm_no_contacts = 'Não tem um contacto que pode funcionar como cliente para este projecto. Por favor crie um contacto primeiro e tente outra vez.';

$pm_unit_value = 'Valor Unidade';
$pm_units = 'Unidades';
$pm_mins = 'minutos';
$pm_no_fees = 'Ainda não existem taxas. Somente um utilizador com privilégios administrativos pode criar taxas.';
$pm_fee = 'Taxa';
$pm_no_contact = 'Nenhum';
$pm_load_period= 'Período';
$pm_load_type= 'Mostrar dados apenas de';
$pm_total_fee = 'Taxa total';
$pm_total_days = 'Dias totais';
$pm_total_units = 'Unidades totais';
$pm_summary = 'Sumário';

$pm_this_entry = 'esta reserva';
$pm_entry = 'reserva';
//translation required
$pm_timer_started_at = 'Temporizador iniciado às';
$pm_start_timer = 'Iniciar contagem de tempo';
$pm_stop_timer = 'Parar contagem de tempo';

$pm_start_date = 'Início';
$pm_end_date = 'Fim';
$pm_responsible = 'Responsável';
$pm_status = 'Estado';

$pm_status_values[1] = 'Pro bono';
$pm_status_values[2] = 'Em curso';
$pm_status_values[3] = 'Pendente';
$pm_status_values[4] = 'Concluído';
$pm_status_values[5] = 'Facturado';

$pm_filter = 'Filtro';
$pm_project_exists = 'Já existe um projecto com este nome';

$pm_clocked_in = 'Iniciou uma contagem de tempo. Clique aqui se desejar parar a contagem.';

$pm_alert = 'Este projecto está fora do prazo';
$pm_budget = 'Objectivo';
$pm_probability = 'Probabilidade';
$pm_yours_only = 'Pessoal';
$pm_description = 'Descrição';

$pm_no_projects = 'Não há projectos.';


//2.08
$pm_projects = 'Projectos';
//2.12
$pm_select_project = 'Seleccione um projecto';
$pm_already_booked = 'Já reservou este período. Clique %s para editar esta reserva'; //changed value. Search above
$pm_here = 'aqui';
$pm_load= 'Ver Horas'; //changed. Search above

$pm_edit_data = 'Editar Horas';
$pm_enter_data = 'Lançar Horas';//changed, search above

//2.14
$pm_templates = 'Modelos';
$pm_template = 'Modelo';
$pm_new_template = 'Novo modelo';
$pm_no_templates = 'Não há modelos';

$pm_template_offset = 'Compromisso com início em';
$pm_template_after = 'depois do novo projecto iniciar em';


$pm_new_template_event = 'Novo Compromisso';
$pm_duration = 'Duração';

$pm_no_template_events = 'Compromissos - sem registos';
$pm_no_template = 'Não utilizar um modelo';

$pm_put_events_in = 'colocar Compromisso em';

//2.15
$pm_shift_events = 'Alterar tarefas e apontamentos relacionados quando alterar a data de início do projecto';

$pm_relate_to_self = 'O projecto não pode referir-se a si próprio';

$pm_print_options = 'Imprimir - Opções';
$pm_print_options_text = 'Pode seleccionar um período de tempo. Se deixar os campos em branco, imprime todos os projectos.';

$pm_internal_fee= 'Custos internos';
$pm_external_fee= 'Custos externos';

$pm_total_external_fee = 'Total custos internos';
$pm_total_internal_fee = 'Total custos externos';

$pm_billed='Facturado';

$pm_fee_time = 'Valor por';

$pm_book_units='Indique apenas um número de unidades de tempo';
$pm_show_project_users = 'Indique as horas de todos os projectos';

$pm_to_bill = 'A facturar';

$pm_total_recieved = 'Total recebido';
$pm_result = 'Resultado';

$pm_customer='Cliente';

$pm_book_rights = 'Reservas - Acesso';

$pm_template_exists = 'Já existe um modelo com este nome';

$pm_link_calendar= 'Inserir horas no calendário';

$pm_project='Projecto';

$pm_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=221';