<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Вы ввели неправильный период';
$pm_add_hours_success = 'Data as entered below was saved successfully';
$pm_already_booked = 'You have already booked in this period';
$pm_new_entry = 'New entry at';
$pm_fees = 'Оплата';
$pm_new_fee = 'Новая оплата';
$pm_users = 'Пользователи';
$pm_materials = 'Материалы';
$pm_new_material = 'Новый материал';
$pm_project_data = 'Projectdata from';
$pm_load= 'Загрузка';
$pm_enter_data = 'Введите данные';
$pm_value = 'Значение';
$pm_too_old = 'You are not allow to enter data older then one week';

$pm_employee = 'Employee';
$pm_project = 'Проект';
$pm_starttime = 'Дата начала';
$pm_endtime = 'Дата завершения';
$pm_breaktime = 'Время остановки';
$pm_this_week = 'Entered this week';
$pm_no_projects = 'You don\'t have any projects';
$pm_hours = 'Часов';
$pm_total_hours = 'Total number of hours';
$pm_client = 'Клиент';
$pm_created_at = 'Created at';

$pm_show_all = 'Показать все';
$pm_show_period = 'Показать с';
$pm_to = 'по';
$pm_show_month = 'Показать месяц';

$pm_total_hours_days = 'Всего количество часов/дней';
$pm_projects_count = 'проект(ов)';
$pm_show_data = 'Показать данные';
$pm_new_project = 'Новый проект';
$pm_other_contacts = 'Другие контакты';
$pm_no_contacts = 'You don\'t have a contact that can function as a client for this project. Please create one first';

$pm_unit_value = 'Значение единиц';
$pm_units = 'Единиц';
$pm_mins = 'минут';
$pm_no_fees = 'There are no fees created yet. Only a user with administrator privileges can create fees.';
$pm_fee = 'Fee';
$pm_no_contact = 'None';
$pm_load_period= 'Период';
$pm_load_type= 'Only load data for';
$pm_total_fee = 'Total fee';
$pm_total_days = 'Всего дней';
$pm_total_units = 'Всего единиц';
$pm_summary = 'Итого';
$pm_this_entry = 'this booking';
$pm_entry = 'booking';
//translation required
$pm_timer_started_at = 'Timer started at';
$pm_start_timer = 'Clock in';
$pm_stop_timer = 'Clock out';

$pm_start_date = 'Начальная дата';
$pm_end_date = 'Конечная дата';
$pm_responsible = 'Responsible';
$pm_status = 'Статус';

$pm_status_values[1] = 'Offer';
$pm_status_values[2] = 'Ongoing';
$pm_status_values[3] = 'Ожидание';
$pm_status_values[4] = 'Завершен';
$pm_status_values[5] = 'Billed';

$pm_filter = 'Фильтр';
$pm_project_exists = 'Проект с таким именем уже существует';

$pm_clocked_in = 'You are clocked in. Click here if you want to clock out';

$pm_alert = 'This project is over due';
$pm_budget = 'Бюджет';
$pm_probability = 'Probability';
$pm_yours_only = 'Yourself';
$pm_description = 'Описание';

$pm_no_projects = 'Проекты не найдены.';


//2.08
$pm_projects = 'Проекты';
//2.12
$pm_select_project = 'Пожалуйста, выберете проект';
$pm_already_booked = 'You have already booked in this period. Click %s to edit this booking'; //changed value. Search above
$pm_here = 'здесь';
$pm_load= 'Просмотр часов'; //chnaged. Search above

$pm_edit_data = 'Редактирование рабочих часов';
$pm_enter_data = 'Введите рабочие часы';//changed, search above
