<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Vnesli ste napaèno èasovno obdobje';
$pm_add_hours_success = 'Podatek vnesen spodaj je bil uspe¹no shranjen';
$pm_already_booked = 'V tem èasovnem obdobju ¾e imate rezervacijo';
$pm_new_entry = 'Nov vnos v';
$pm_fees = 'Honorarji';
$pm_new_fee = 'Nov honorar';
$pm_users = 'Uporabniki';
$pm_materials = 'Gradivo';
$pm_new_material = 'Novo gradivo';
$pm_project_data = 'Projektni podatki iz';
$pm_load= 'Load';
$pm_enter_data = 'Vnesi podatke';
$pm_value = 'Vrednost';
$pm_too_old = 'Ne smete vna¹ati podatkov starej¹ih od enega tedna';

$pm_employee = 'Zaposleni';
$pm_project = 'Projekt';
$pm_starttime = 'Zaèetni èas';
$pm_endtime = 'Konèni èas';
$pm_breaktime = 'Odmor';
$pm_this_week = 'Vneseno ta teden';
$pm_no_projects = 'Nimate nobenih projektov';
$pm_no_projects = 'Ni najdenih projektov.';
$pm_hours = 'Ure';
$pm_total_hours = 'Skupno ¹tevilo ur';
$pm_client = 'Odjemalec';
$pm_created_at = 'Ustvarjen ob';

$pm_show_all = 'Prika¾i vse';
$pm_show_period = 'Poka¾i iz';
$pm_to = 'do';
$pm_show_month = 'Poka¾i mesec';

$pm_total_hours_days = 'Skupno ¹tevilo ur/dnevov';
$pm_projects_count = 'projekt(i)';
$pm_show_data = 'Poka¾i podatke';
$pm_new_project = 'Nov projekt';
$pm_other_contacts = 'Drugi stiki';
$pm_no_contacts = 'Nimate stika, ki bi ga lahko oznaèilo kot uporabnika v tem projektu. Najprej ustvarite nov stik';

$pm_unit_value = 'Vrednost enote';
$pm_units = 'Enote';
$pm_mins = 'minut';
$pm_no_fees = 'Pristojbine ¹e niso bile narejene. Samo uporabnik z  skrbni¹kimi privilegiji lahko ustvari pristojbine.';
$pm_fee = 'Pristojbina';
$pm_no_contact = 'Noben';
$pm_load_period= 'Period';
$pm_load_type= 'Only load data for';
$pm_total_fee = 'Celotna pristojbina';
$pm_total_days = 'Skupaj dni';
$pm_total_units = 'Skupaj enot';
$pm_summary = 'Povzetek';
$pm_this_entry = 'ta rezervacija';
$pm_entry = 'rezervacija';
//translation required
$pm_timer_started_at = '©tevec zagnan ob';
$pm_start_timer = 'Zaèetek dela';
$pm_stop_timer = 'Konec dela';

$pm_start_date = 'Zaèetni datum';
$pm_end_date = 'Konèni datum';
$pm_responsible = 'Odgovoren';
$pm_status = 'Stanje';

$pm_status_values[1] = 'Ponudba';
$pm_status_values[2] = 'V teku';
$pm_status_values[3] = 'Èakanje';
$pm_status_values[4] = 'Konèano';
$pm_status_values[5] = 'Raèunano';

$pm_filter = 'Filter';
$pm_project_exists = 'Projekt s tem imenom ¾e obstaja';

$pm_clocked_in = 'Sedaj ste zaèeli z delom. Kliknite sem, èe ¾elite konèati z delom';

$pm_alert = 'Ta projekt je prekoraèen';
$pm_budget = 'Proraèun';
$pm_probability = 'Verjetnost';
$pm_yours_only = 'Sam';
$pm_description = 'Opis';

$pm_no_projects = 'Nimate nobenih projektov';
$pm_no_projects = 'Ni najdenih projektov.';
