<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'Du angav en felaktig tidsperiod';
$pm_add_hours_success = 'Data som angavs nedanför sparades';

$pm_new_entry = 'Nytt inlägg på';
$pm_fees = 'Avgift';
$pm_new_fee = 'Ny avgift';
$pm_users = 'Användare';
$pm_materials = 'Material';
$pm_new_material = 'Nytt material';
$pm_project_data = 'Projektdata från';

$pm_value = 'Värde';
$pm_too_old = 'Det är inte möjligt att lägga in data som är äldre en en vecka';

$pm_employee = 'Anställd';
$pm_project = 'Projekt';
$pm_starttime = 'Starttid';
$pm_endtime = 'Slutttid';
$pm_breaktime = 'Rasttid';
$pm_this_week = 'Inskrivet denna vecka';
$pm_no_projects = 'Du har inga projekt';
$pm_hours = 'Timmar';
$pm_total_hours = 'Totalt antal timmar';
$pm_client = 'Klient';
$pm_created_at = 'Skapad';

$pm_show_all = 'Visa alla';
$pm_show_period = 'Visa från';
$pm_to = 'till';
$pm_show_month = 'Visa månad';

$pm_total_hours_days = 'Totalt antal av timmar/dagar';
$pm_projects_count = 'Projekt';
$pm_show_data = 'Visa data';
$pm_new_project = 'Nytt projekt';
$pm_other_contacts = 'Andra kontakter';
$pm_no_contacts = 'Du har ingen kontakt som kan fungera som en klient för detta projekt. Var god skapa en först';

$pm_unit_value = 'Enhetspris';
$pm_units = 'Enheter';
$pm_mins = 'minuter';
$pm_no_fees = 'Inga avgifter är skapade ännu. Endast en användare med administratörsrättigheter kan skapa detta.';
$pm_fee = 'Avgift';
$pm_no_contact = 'Ingen';
$pm_load_period= 'Period';
$pm_load_type= 'Ladda data för';
$pm_total_fee = 'Total avgift';
$pm_total_days = 'Total dagar';
$pm_total_units = 'Total enheter';
$pm_summary = 'Summa';
$pm_this_entry = 'denna bokning';
$pm_entry = 'bokning';
//translation required
$pm_timer_started_at = 'Timer startade';
$pm_start_timer = 'Klocka in';
$pm_stop_timer = 'Klocka ut';

$pm_start_date = 'Start datum';
$pm_end_date = 'Slut datum';
$pm_responsible = 'Ansvarig';
$pm_status = 'Status';

$pm_status_values[1] = 'Offert';
$pm_status_values[2] = 'Pågående';
$pm_status_values[3] = 'Väntande';
$pm_status_values[4] = 'Färdigt';
$pm_status_values[5] = 'Fakturerat';

$pm_filter = 'Filter';
$pm_project_exists = 'Ett project med detta namn existerar redan';

$pm_clocked_in = 'Du har klockat in. Klicka här för att klocka ut.';

$pm_alert = 'Detta projekt är försenat';
$pm_budget = 'Budget';
$pm_probability = 'Sannolikhet';
$pm_yours_only = 'Dig själv';
$pm_description = 'Beskrivning';

$pm_no_projects = 'Inga projekt hittade.';


//2.08
$pm_projects = 'Projekt';
//2.12
$pm_select_project = 'Välj ett projekt';
$pm_already_booked = 'Du har redan angett data under denna period. Klicka på %s för att ändra denna data'; //changed value. Search above
$pm_here = 'här';
$pm_load= 'Visa timmar'; //chnaged. Search above

$pm_edit_data = 'Ändra arbetstimmar';
$pm_enter_data = 'Lägg till arbetstimmar';//changed, search above
