<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = 'คุณใส่เวลาไม่ถูกต้อง';
$pm_add_hours_success = 'ข้อมูลจากด้านล่างได้บันทึกเรียบร้อยแล้ว';
$pm_already_booked = 'คุณมีข้อมูลซ้ำกันในคาบเวลานี้';
$pm_new_entry = 'New entry at';
$pm_fees = 'ค่าใช้จ่าย';
$pm_new_fee = 'ค่าใช้จ่ายใหม่';
$pm_users = 'ผู้ใช้';
$pm_materials = 'เครื่องมือ';
$pm_new_material = 'เครื่องมือใหม่';
$pm_project_data = 'ข้อมูลโปรเจค';
$pm_load= 'โหลด';
$pm_enter_data = 'กรอกข้อมูล';
$pm_value = 'ค่า';
$pm_too_old = 'คุณไม่สารมารถเข้าดูข้อมูลที่มีอายุต่ำกว่าหนึ่งอาทิตย์';

$pm_employee = 'พนักงาน';
$pm_project = 'โปรเจ็ค';
$pm_starttime = 'เวลาเริ่ม';
$pm_endtime = 'เวลาสิ้นสุด';
$pm_breaktime = 'เวลาพัก';
$pm_this_week = 'เข้าสู่สัปดาห์นี้';
$pm_no_projects = 'คุณยังไม่มีโปรเจ็ค';
$pm_hours = 'ชั่วโมง';
$pm_total_hours = 'ชั่วโมงรวมทั้งหมด';
$pm_client = 'ลูกค้า';
$pm_created_at = 'สร้างโดย';

$pm_show_all = 'แสดงทั้งหมด';
$pm_show_period = 'แสดงจาก';
$pm_to = 'ถึง';
$pm_show_month = 'แสดงแบบเดือน';

$pm_total_hours_days = 'วัน/ชัวโมงรวมทั้งหมด';
$pm_projects_count = 'โปรเจ็ค';
$pm_show_data = 'แสดงข้อมูล';
$pm_new_project ='โปรเจ็คใหม่';
$pm_other_contacts = 'ผู้ติดต่อคนอื่นๆ';
$pm_no_contacts = 'คุณยังไม่มีผู้ติดต่อ กรุณาคลิกสร้างผู้ติดต่อใหม่';

$pm_unit_value = 'ค่าต่อหน่วย';
$pm_units = 'ยูนิต';
$pm_mins = 'นาที';
$pm_no_fees = 'ในขณะนี้ยังไม่มีค่าใช้จ่ายหากต้องการเพิ่มกรุณาล็อกอินด้วยผู้ใช้ที่มีสิทธิ์ระดับผู้ดูแลโปรเจ็ค';
$pm_fee = 'ค่าใช้จ่าย';
$pm_no_contact = 'ไม่มี';
$pm_load_period= 'คาบ';
$pm_load_type= 'โหลดข้อมูลเพียงอย่างเดียวเพื่อ';
$pm_total_fee = 'ค่าใช้จ่ายีเพื่อง';
$pm_total_days = 'วันรวมทั้งหมด';
$pm_total_units = 'ยูนิตทั้งหมด';
$pm_summary = 'รวม';
$pm_this_entry = 'this booking';
$pm_entry = 'booking';
//translation required
$pm_timer_started_at = 'เวลาเริ่มที่';
$pm_start_timer = 'คล็อกอิน';
$pm_stop_timer = 'คล็อกเอ้าท์';

$pm_start_date = 'วันเริ่ม';
$pm_end_date = 'วันสิ้นสุด';
$pm_responsible = 'ผลตอบรับ';
$pm_status = 'สถานะ';

$pm_status_values[1] = 'เสนอ';
$pm_status_values[2] = 'ระหว่างการเสนอ';
$pm_status_values[3] = 'คอย';
$pm_status_values[4] = 'ระหว่างการทำงาน';
$pm_status_values[5] = 'วางบิล';

$pm_filter = 'Filter';
$pm_project_exists = 'ชื่อโปรเจ็คนี้ซ้ำ';

$pm_clocked_in = 'คุณได้เข้าระบบมาแล้วหากต้องการออกให้คลิกที่นี่';

$pm_alert = 'โปรเจ็คนี้เกินเวลา';
$pm_budget = 'Budget';
$pm_probability = 'ความน่าจะเป็นไปได้';
$pm_yours_only = 'ด้วยตัวคุณเอง';
$pm_description = 'บรรยาย';

$pm_no_projects = 'ไม่พบโปรเจ็ค';

//2.08
$pm_projects = 'โปรเจ็ค';
