<?php
require_once($GO_LANGUAGE->get_fallback_language_file('projects'));

$pm_invalid_period = '你/妳所輸入的時間期間錯誤';
$pm_add_hours_success = '以下輸入的資料已成功儲存';
$pm_already_booked = '你/妳已有預約在這期間';
$pm_new_entry = '新增輸入在';
$pm_fees = '費用';
$pm_new_fee = '新增費用';
$pm_users = '使用者';
$pm_materials = '物料';
$pm_new_material = '新增物料';
$pm_project_data = '專案資料由';
$pm_load= '載入';
$pm_enter_data = '輸入資料';
$pm_value = '價格';
$pm_too_old = '不允你/妳許輸入早於一星期前的資料';

$pm_employee = '雇員';
$pm_project = '專案';
$pm_starttime = '開始時間';
$pm_endtime = '結束時間';
$pm_breaktime = '休息時間';
$pm_this_week = '這星期已輸入';
$pm_no_projects = '你/妳沒有任何專案';
$pm_hours = '小時';
$pm_total_hours = '總共小時';
$pm_client = '客戶';
$pm_created_at = '建立在';

$pm_show_all = '顯示所有';
$pm_show_period = '顯示由';
$pm_to = '至';
$pm_show_month = '顯示月份';

$pm_total_hours_days = '總共小時/日數';
$pm_projects_count = '專案';
$pm_show_data = '顯示資料';
$pm_new_project = '新增專案';
$pm_other_contacts = '其他聯絡人';
$pm_no_contacts = '在這專案，你/妳沒有聯絡人可作為客戶，請先建立。';

$pm_unit_value = '單位值';
$pm_units = '單位';
$pm_mins = '分鐘';
$pm_no_fees = '這裡還沒有建立費用，只有擁有管理員權限的使用者才能建立費用。';
$pm_fee = '費用';
$pm_no_contact = '沒有';
$pm_load_period= '週期';
$pm_load_type= '載入資料到';
$pm_total_fee = '總共費用';
$pm_total_days = '總共日數';
$pm_total_units = '總共單位';
$pm_summary = '摘要';

$pm_this_entry = '這個預約';

$pm_entry = '預約';

//translation required
$pm_timer_started_at = '計時器開始在';
$pm_start_timer = '開始計時器';
$pm_stop_timer = '停止計時器';

$pm_start_date = '開始日期';
$pm_end_date = '結束日期';
$pm_responsible = '負責人';
$pm_status = '狀態';

$pm_status_values[1] = '提議';
$pm_status_values[2] = '正在進行中';
$pm_status_values[3] = '等待';
$pm_status_values[4] = '完成';
$pm_status_values[5] = '已開帳單';

$pm_filter = '篩選';
$pm_project_exists = '這個名稱的專案已存在';
$pm_clocked_in = "你/妳已紀錄上班時間，如果你/妳想紀錄下班時間可按這裡";
$pm_alert = '這個專案已延誤了';
$pm_budget = '預算';
$pm_probability = '可能性';
$pm_yours_only = '你/妳自己';
$pm_description = '描述';
$pm_no_projects = '找不到任何專案';
