<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('search'));
$search_title='البحث حسب الكلمه الرئيسية';
$search_web='أبحث في المواقع الالكترونية مع ومواقع الأخبار!';
$search_text='ادخل الكلمات الرئيسية او عبارة البحث :';
$search_files='البحث عن الملفات والمجلدات في الفريق الحالي.';
$cmdSearch='بحث';
$search_global='البحث الفريق الحالي';
$search_results='نتيجة';
?>