<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('search'));

$search_title = "Hledat klíčová slova";
$search_web = "Prohledat web pomocí Google!";
$search_text = "Zadejte klíčové slovo(a) nebo fráze pro hledání:";
$search_files = "Hledat soubor nebo složku v Group-Office.";
$cmdSearch = "Hledat";
$search_global='Hledat v Group-Office';
$search_results='výsledek(y)';
