<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('search'));
$search_title='Schluesselwortsuche';
$search_web='Web-Suche mit Google';
$search_text='Einen Suchbegriff eingeben und auf \'Suchen\' klicken.';
$search_files='Suche nach Dateien und Ordnern in Group-Office.';
$cmdSearch='Suchen';
$search_global='In Group-Office suchen';
$search_results='Ergebnis(se)';
?>