<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('search'));

$search_title = "Search by keyword";
$search_web = "Search the Web with Google!";
$search_text = "Enter keyword(s) or search phrase:";
$search_files = "Search for files and folders in Group-Office.";
$cmdSearch = "Search";
$search_global='Search Group-Office';
$search_results='result(s)';
