<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('search'));

$search_title = "Rechercher sur un mot clé";
$search_web = "Rechercher sur le web avec Google";
$search_text = "Entrez votre recherche et cliquez sur 'Chercher'.";
$search_files = "Rechercher des fichiers et des dossiers dans Group-Office.";
$cmdSearch = "Chercher";
?>
