<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('search'));
$search_title='Keresés kulcsszó alapján';
$search_web='Keresés az Interneten a Google segítségével';
$search_text='Írja be a kulcsszót/kulcsszavakat, vagy a keresendő kifejezést:';
$search_files='Fájlok és mappák keresése a Group-Office rendszerén belül.';
$cmdSearch='Keresés';
?>