<?php
require_once($GO_LANGUAGE->get_fallback_language_file('search'));

$search_title = "Pesquisar palavras chave";
$search_web = "Pesquisar a Web com o Google!";
$search_text = "Inserir palavra chave ou frase:";
$search_files = "Pesquisar ficheiros e pastas do Group-Office.";
$cmdSearch = "Pesquisar";
$cmdSearch = "Pesquisar";
$search_global='Pesquisa no Group-Office';
$search_results='resultado(s)';

