<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('search'));
$search_title='Išči po ključni besedi';
$search_web='Preišči Internet z Googlom!';
$search_text='Vstavi ključne besede ali iskalno frazo:';
$search_files='Išči datoteke ali mape v Group-Office.';
$cmdSearch='Išči';
$search_global='Išči po Group-Office';
$search_results='rezultat(i)';
?>