<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('search'));

$search_title = "Najdi datoteke in imenike";
$search_title = "I¹èi po kljuèni besedi";
$search_web = "I¹èi po spletu z Google-om!";
$search_text = "Vnesi kljuène besede ali iskalno frazo:";
$search_files = "Najdi datoteke in imenike v Group-Officu.";
$cmdSearch = "Iskanje";
$cmdSearch = "Iskanje";
$cmdSearch = "Iskanje";
$cmdSearch = "Iskanje";
$cmdSearch = "Iskanje";
