<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Podívat se na';
$strType = "Typ";
$strModified = "Měněno";
$strCreated = "Vytvořeno";
$strAccessed = "Použito";
$strSize = "Velikost";
$fbRefresh = "Obnovit";
$fbProperties = "Vlastnosti";
$fbNewFolder = "Nová složka";
$fbDelete = "Smazat";
$fbCut = "Vyjmout";
$fbPaste = "Vložit";
$fbCopy = "Kopírovat";
$fbFiletypes = "Typy souborů";
$fbSharing = "Sdíleni";
$fbShares = "Sdílené složky";
$fbShare = "Sdílená složka";
$fbPath = "Cesta";
$fbFolders = "Složky";
$fbNoSelect = "Nic jste nevybrali, vyberte soubor(y) ze seznamu.";
$fbConfirmDelete = "Potvrďte smazání";
$fbWritePermissions = "Práva k zápisu";
$fbReadPermissions = "Práva ke čtení";
$fbGeneral = "Obecné";
$fbConfirmOverwrite = "Potvrďte přepsání";
$strOverwritePrefix = "Jste si jistí že chcete přepsat ";
$strOverwriteSuffix = "?";
$fbDescription = "Popis";
$fbLocation = "Umístění";
$fbUpload = "Nahrát";
$fbUpload_text = "Zvolte soubor pro nahrání";
$fbUpload_nofile = "Nebyl nahrán žádný soubor.";
$fbVersions = "Verze";
$fbDelete_version = "Určitě chcete smazat tuto verzi?";
$fbFolderExists = "Složka už existuje.";
$fbEmailFile = "Soubor s E-mailem";
$fbFolder = "Složka";

$fbNoFile = "Pokoušíte se nahrát příliš velký soubor.<br />Maximální velikost pro nahrávané soubory je: ";
$fbPleaseWait = "Prosím vyčkejte. Posílám data...";
$fbFilename = "Název souboru";
$fbUpLevel = "O úroveň výš";
$fbItems = "položka(y)";
$fbFolderSize = "Velikost složky";
$fbMaxUploadSize = "Maximální velikost";
$ml_file_too_big = "Pokoušíte se připojit příliš velký soubor. Maximální velikost pro nahrávané soubory je: ";
$cmdSearch = "Hledej";
$fbNoRightToOverwrite = "Soubor už existuje a nemáte oprávnění ho přepsat.";
$fbSaveFile = "Uložit soubor jako...";
$fbNameExists = "Takové jméno už ve složce existuje.";
$fbThis = 'tento';
$fbFiles = 'Soubory';
$fs_activate_sharing = 'Nastavit sdílení';
$fs_calculate_folder_size = 'Spočítat velikost složky';
$fs_no_multi_select = 'Pro tuto akci můžete zvolit jen jeden soubor';
$fs_search = 'Hledat';
$search_title = "Hledat soubory a složky";
$fs_keyword = 'Klíčové slovo';
$fs_enter_keyword = 'Prosím zadejte klíčové slovo';
$fs_modified_before = 'Změněno před';
$fs_modified_after = 'Změněno po';

//translation required
$fb_compress='Sbalit';
$fb_decompress='Rozbalit';
$fb_failed_to_create = 'Nelze vytvořit archív.';
$fb_failed_to_extract = 'Chyba při rozbalování';
$fb_compression_type = 'Typ archivu';
$fbFreeQuotaSpace = 'Volné místo ve vaší složce';

//2.11
$fb_unkown_compression = 'Neznámý typ archívu';
$fs_new_doc = 'Nový dokument';
$fs_cleanup = 'Vyčistit HTML';
$fbMultipleFiles = 'Více souborů';
$fbSelect = "Zvolte soubor"; //changed

//2.14
$fs_confirm_unshare = 'Jste si jisti, že chcete zrušit všechna oprávnění na tomto adresáři?';
$fs_users = 'Uživatelé';
$fs_personal = 'Osobní';

$fs_inssufficient_diskspace = 'Nedostatek diskového prostoru!';

//2.15
$fs_open_containing_folder = 'Otevři obsahující adresář';
$fs_file_put_in='Soubor "%s" je nahrán na "%s"';
$fs_new_file_uploaded = 'Nový soubor nahrán: %s';

$fs_download = 'Stáhnout';
$fs_view = 'Prohlížet';

$fs_notify = 'Pošli mi email. když někdo uploaduje soubor';

$fs_status='Status';
$fs_author='Author';
$fs_no_status_history='Žádná historie statusu';
$fs_no_status='Žádný';
$fs_file_updated='Soubor %s modifikován';
$fs_open_properties='Otevři okno s vlastnostmi souboru při dvojím kliknutí';

$fs_file='Soubor';

$fs_enable_gota = 'Povol Group-Office Transfer Agent. Group-Office Transfer Agent je malý Java program, který ukládá soubory do Group-Office když je editujete lokálně. Group-Office Professional and Java 1.6 nebo vyšší je potřeba na vašem počítači.';
$fs_show_files_on_summary = 'Ukaž posledních 10 modifikovaných souborů na souhrné stránce';

$fs_recursion='Nemůžete přesouvat nebo kopírovat adresáře do sebe sama';
$fs_select_destination = 'Vyberte cílový adresář'; 
$fs_move = 'Přesunout';

$fs_java_not_installed="Java není nainstalována. Java je požadována Group-Office Transfer Agentem. Chcete ji nainstalovat? Jestli ji nechcete nainstalovat, nebo nemůžete, je možné vypnout Group-Office Transfer Agenta v Konfiguraci -> Soubory.";
$fs_java_install = 'Instalovat Java Webstart';
$fs_java_install_text = 'Prosím začněte s Java instalací nyní kliknutím na horní lištu této stránky. Jestli toto nefunguje, můžete zkusit kliknout <a class="normal" href="http://www.java.com">sem a nainstalovat Javu manuálně.</a>';


$fs_notify_folder='Upozorni mě na změnu v souborech v tomto adresáři';

$fs_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=220';
