<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Kig i';
$strType = "Type";
$strModified = "Ændret";
$strCreated = "Oprettet";
$strAccessed = "Læst";
$strSize = "Størrelse";
$fbRefresh = "Opdater";
$fbProperties = "Egenskaber";
$fbNewFolder = "Ny mappe";
$fbDelete = "Slet";
$fbCut = "Klip";
$fbPaste = "Indsæt";
$fbCopy = "Kopier";
$fbFiletypes = "Filtyper";
$fbSharing = "Deling";
$fbShares = "Delte mapper";
$fbShare = "Delt mappe";
$fbPath = "Sti";
$fbFolders = "Mapper";
$fbNoSelect = "Du har ikke valgt en fil. Klik på ikonet ved filnavne for at vælge filer.";
$fbConfirmDelete = "Bekræft sletning";
$fbWritePermissions = "Skriverettigheder";
$fbReadPermissions = "Læserettigheder";
$fbGeneral = "Generelt";
$fbConfirmOverwrite = "Bekræft overskrivning";

$strOverwritePrefix = "Er du sikker på du vil overskrive ";
$strOverwriteSuffix = "?";
$fbDescription = "Beskrivelse";
$fbLocation = "Placering";
$fbUpload = "Overfør";
$fbUpload_text = "Vælg fil der skal overføres";
$fbUpload_nofile = "Filen blev ikke modtaget.";
$fbVersions = "Versioner";
$fbDelete_version = "Er du sikker på du vil slette denne version?";
$fbFolderExists = "Mappen eksisterer allerede.";
$fbEmailFile = "Send fil";
$fbFolder = "Mappe";
$fbSelect = "Vælg fil...";
$fbNoFile = "Filen du forsøgte at overføre er for stor.<br /> Den maksimale overførbare filstørrelse er sat til: ";
$fbPleaseWait = "Vent venligst mens data overføres...";
$fbFilename = "Filnavn";
$fbUpLevel = "Et niveau op";
$fbItems = "Element(er)";
$fbFolderSize = "Størrelse af mappe";
$fbMaxUploadSize = "Maksimal størrelse";

$ml_file_too_big = "Filen du forsøgte at vedhæfte er for stor, den maksimale størrelse for vedhæftede filer er sat til: ";
$cmdSearch = "Søg";
$fbNoRightToOverwrite = "Filen eksisterer allerede og du har ikke tilladelse til at overskrive den.";
$fbSaveFile = "Gem som...";
$fbNameExists = "Navnet findes allerede i denne mappe.";
$fbThis = 'denne';
$fbFiles = 'Filer';
$fs_activate_sharing = 'Aktiver deling';
$fs_calculate_folder_size = 'Beregn mappe størrelse';
$fs_no_multi_select = 'Du kan kun vælge ét element med denne funktion';
$fs_search = 'Søg';
$search_title = "Søg efter filer og mapper";
$fs_keyword = 'Nøgleord';
$fs_enter_keyword = 'Indtast nøgleord';
$fs_modified_before = 'Ændret før';
$fs_modified_after = 'Ændret efter';

//translation required
$fb_compress='Komprimer';
$fb_decompress='Udpak';
$fb_failed_to_create = 'Kunne ikke oprette arkiv.';
$fb_failed_to_extract = 'Kunne ikke pakke ud';
$fb_compression_type = 'Komprimering';
$fbFreeQuotaSpace = 'Ledig plads i din mappe';
