<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Hae kansiosta';
$strType = "Tyyppi";
$strModified = "Muokattu";
$strCreated = "Luotu";
$strAccessed = "Käytetty";
$strSize = "Koko";
$fbRefresh = "Päivitä";
$fbProperties = "Ominaisuudet";
$fbNewFolder = "Uusi kansio";
$fbDelete = "Poista";
$fbCut = "Leikkaa";
$fbPaste = "Liitä";
$fbCopy = "Kopioi";
$fbFiletypes = "Tiedostotyyppi";
$fbSharing = "Jako";
$fbShares = "Jaetut kansiot";
$fbShare = "Jaettu kansio";
$fbPath = "Haku polku";
$fbFolders = "Kansiot";
$fbNoSelect = "Et valinnut mitään. Valitse painamalla nimen vieressä oleva ikonia.";
$fbConfirmDelete = "varmista poisto";
$fbWritePermissions = "Kirjoitus oikeudet";
$fbReadPermissions = "Luku oikeudet";
$fbGeneral = "Yleiset";
$fbConfirmOverwrite = "Varmista ylikirjoitus";
$strOverwritePrefix = "Oletko varma että haluat kirjoittaa yli ";
$strOverwriteSuffix = "?";
$fbDescription = "Kuvaus";
$fbLocation = "Paikka";
$fbUpload = "Lataa";
$fbUpload_text = "Valitse ladattava tiedosto";
$fbUpload_nofile = "Mitään tiedosto ei otettu vastaan.";
$fbVersions = "Versions";
$fbDelete_version = "Oletko varma että haluat tuhota tämän version?";
$fbFolderExists = "Kansio on jo olemassa.";
$fbEmailFile = "Sähköposti tiedosto";
$fbFolder = "Kansio";

$fbNoFile = "Tiedosto jonka yritit ladata on liian suuri.<br /> Suurin ladattavan tiedoston koko on: ";
$fbPleaseWait = "Odota. Tietoja siirretään...";
$fbFilename = "Tiedosto nimi";
$fbUpLevel = "Taso ylöspäin";
$fbItems = "tiedosto(t)";
$fbFolderSize = "Kansion koko";
$fbMaxUploadSize = "Maksimi koko";
$ml_file_too_big = "Tiedosto jonka yritit liittää on liian suuri, liitetiedoston suurin koko on: ";
$cmdSearch = "Haku";
$fbNoRightToOverwrite = "Tiedoto on jo olemassa eikö sinulla ole ylikirjoitus oikeutta.";
$fbSaveFile = "Talleta tiedosto nimellä...";
$fbNameExists = "Nimi on jo olemassa tässä kansiossa.";
$fbThis = 'tämä';
$fbFiles = 'Tiedostot';
$fs_activate_sharing = 'Aktivoi jako';
$fs_calculate_folder_size = 'Laske kansio koko';
$fs_no_multi_select = 'Et voi valita kuin yhden tällä valinnalla';
$fs_search = 'Haku';
$search_title = "Hake tiedostoja ja kansioita";
$fs_keyword = 'Hakusana';
$fs_enter_keyword = 'Syötä hakusana';
$fs_modified_before = 'Muokattu ennen';
$fs_modified_after = 'Muokattu jälkeen';

//translation required
$fb_compress='Tiivistä';
$fb_decompress='Pura';
$fb_failed_to_create = 'Arkiston luonti epäonnistui.';
$fb_failed_to_extract = 'Purku epäonnistui';
$fb_compression_type = 'Tiivistys';
$fbFreeQuotaSpace = 'Vapaata tilaa hakemistossa';

//2.11
$fb_unkown_compression = 'Tuntematon tiivistys muoto';
$fs_new_doc = 'Uusi dokumentti';
$fs_cleanup = 'Puhdista HTML';
$fbMultipleFiles = 'Moni tiedosto';
$fbSelect = "valitse tiedosto"; //changed

//2.14
$fs_confirm_unshare = 'Oletko varma että haluat poistaa kaikki oikeudet tähnä kansioon?';
$fs_users = 'Käyttäjät';
$fs_personal = 'Henkilökohtainen';

$fs_inssufficient_diskspace = 'Talletus tilaa ei ole tarpeeksi';

//2.15
$fs_open_containing_folder = 'Avaa sisältävä kansio';
$fs_file_put_in='Tiedosto "%s" noudettu "%s"';
$fs_new_file_uploaded = 'Uusi tiedosto noudettu: %s';
