<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Regarder dans';
$strType = "Type";
$strModified = "Modifié";
$strCreated = "Crée";
$strAccessed = "Accédé";
$strSize = "Taille";
$fbRefresh = "Rafraîchir";
$fbProperties = "Propriétés";
$fbNewFolder = "Nouveau dossier";
$fbDelete = "Supprimer";
$fbCut = "Couper";
$fbPaste = "Coller";
$fbCopy = "Copier";
$fbFiletypes = "Type de fichier";
$fbSharing = "Partagé";
$fbShares = "Dossiers partagés";
$fbShare = "Dossier partagé";
$fbPath = "Chemin";
$fbFolders = "Dossiers";
$fbNoSelect = "Vous n'avez pas sélectionné d'élément. Cliquez sur un icône près du nom pour choisir l'élément.";
$fbConfirmDelete = "Confirmer la suppression";
$fbWritePermissions = "Permissions d'écriture";
$fbReadPermissions = "Permissions de lecture";
$fbGeneral = "Général";
$fbConfirmOverwrite = "Confirmer l'écrasement";
$strOverwritePrefix = "Etes vous certain(e) de vouloir écraser le fichier ?";
$strOverwriteSuffix = "?";
$fbDescription = "Description";
$fbLocation = "Emplacement";
$fbUpload = "télécharger vers le serveur";
$fbUpload_text = "Choisissez le fichier à télécharger";
$fbUpload_nofile = "Aucun fichier reçu.";
$fbVersions = "Versions";
$fbDelete_version = "Etes vous certain(e) de vouloir supprimer cette version ?";
$fbFolderExists = "Le dossier existe déjà.";
$fbEmailFile = "envoyer le fichier par mail";
$fbFolder = "Dossier";
$fbSelect = "Choisissez le fichier...";
$fbNoFile = "Le fichier que vous avez essayé de télécharger est trop gros.<br /> La taille maximale d'un fichier est de : ";
$fbPleaseWait = "Veuillez patienter. Envoi des données...";
$fbFilename = "Nom de fichier";
$fbUpLevel = "Dossier parent";
$fbItems = "élément(s)";
$fbFolderSize = "Taille du dossier";
$fbMaxUploadSize = "Taille maximale";
$ml_file_too_big = "Le fichier que vous voulez joindre est trop gros, la taille maximale pour les fichiers attachés est de : ";
$cmdSearch = "Recherche";
$fbNoRightToOverwrite = "Le fichier existe déjà et vous n'avez pas le droit de l'écraser.";
$fbSaveFile = "Enregistrer le fichier sous...";
$fbNameExists = "Le nom existe déjà dans ce dossier.";
$fbThis = 'ce';
$fbFiles = 'Fichiers';
$fs_activate_sharing = 'Activation du partage';
$fs_calculate_folder_size = 'Calcul de la taille du dossier';
$fs_no_multi_select = 'Vous ne pouvez pas sélectionner plus d\'un élément avec cette option';
$fs_search = 'Recherche';
$search_title = "Rechercher des fichiers et des dossiers";
$fs_keyword = 'Mot-clé';
$fs_enter_keyword = 'Entrez un mot clé';
$fs_modified_before = 'Modifiés avant';
$fs_modified_after = 'Modifiés après';
$fb_compress='Compresser';
$fb_decompress='Décompresser';
$fb_failed_to_create = 'Impossible de créer l\'archive.';
$fb_failed_to_extract = 'Erreur pendant l\'extraction';
$fb_compression_type = 'Compression';
$fbFreeQuotaSpace = 'Espace libre dans votre dossier';

//2.11
$fb_unkown_compression = 'Type de compression inconnu';
$fs_new_doc = 'Nouveau document';
$fs_cleanup = 'Nettoyer le HTML';
$fbMultipleFiles = 'Fichiers multiples';
$fbSelect = "Sélectionner un fichier"; //changed

//2.14
$fs_confirm_unshare = 'Etes-vous certain de vouloir supprimer toutes les permissions sur ce répertoire ?';
$fs_users = 'Utilisateurs';
$fs_personal = 'Personnel';
$fs_inssufficient_diskspace = 'Espace disque insuffisant';

//2.15
$fs_open_containing_folder = 'Répertoire ouvert';
$fs_file_put_in = 'Le fichier "%s" est transféré sur "%s"';
$fs_new_file_uploaded = 'Nouveau fichier transféré : %s';
$fs_download = 'Téléchargement';
$fs_view = 'Vue';
$fs_notify = 'Envoyer un e-mail si quelqu\'un expédie un nouveau fichier';
$fs_status = 'Statut';
$fs_author = 'Auteur';
$fs_no_status_history = 'Aucune historique de statut';
$fs_no_status = 'Aucun';
$fs_file_updated = 'Fichier "%s" modifié';
$fs_open_properties = 'Ouvrir la fenêtre de propriété quand un fichier est double-cliqué';
?>
