<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Look in';
$strType = "種類";
$strModified = "編集日";
$strCreated = "作成";
$strAccessed = "アクセス";
$strSize = "サイズ";
$fbRefresh = "更新";
$fbProperties = "プロパティ";
$fbNewFolder = "新規フォルダ";
$fbDelete = "削除";
$fbCut = "切り取り";
$fbPaste = "貼り付け";
$fbCopy = "コピー";
$fbFiletypes = "ファイルの種類";
$fbSharing = "共有";
$fbShares = "共有フォルダ";
$fbShare = "共有フォルダ";
$fbPath = "パス";
$fbFolders = "フォルダ";
$fbNoSelect = "アイテムが選択されていません。 アイテムを選択するために名前横のアイコンをクリックしてください。";
$fbConfirmDelete = "削除を確認";
$fbWritePermissions = "書き込み権限";
$fbReadPermissions = "読込権限";
$fbGeneral = "一般";
$fbConfirmOverwrite = "上書きを確認";
$strOverwritePrefix = "上書きしてよろしいですか ";
$strOverwriteSuffix = "?";
$fbDescription = "説明";
$fbLocation = "ロケーション";
$fbUpload = "アップロード";
$fbUpload_text = "アップロードするファイルを選択";
$fbUpload_nofile = "ファイルが受け取れません。";
$fbVersions = "バージョン";
$fbDelete_version = "このバージョンを削除してよろしいですか？";
$fbFolderExists = "フォルダは存在しています。";
$fbEmailFile = "E-mailファイル";
$fbFolder = "フォルダ";

$fbNoFile = "アップロードするファイルサイズが大きすぎます。<br /> 転送可能なファイルサイズ: ";
$fbPleaseWait = "しばらくお待ちください。データを送信しています...";
$fbFilename = "ファイル名";
$fbUpLevel = "上の階層";
$fbItems = "アイテム";
$fbFolderSize = "フォルダサイズ";
$fbMaxUploadSize = "最大サイズ";
$ml_file_too_big = "添付するファイルサイズが大きすぎます。添付可能なファイルサイズ: ";
$cmdSearch = "検索";
$fbNoRightToOverwrite = "ファイルはすでに存在しています。上書き可能な権限がありません。";
$fbSaveFile = "名前を付けて保存...";
$fbNameExists = "このフォルダ名はすでに存在しています。";
$fbThis = 'this';
$fbFiles = 'ファイル';
$fs_activate_sharing = 'アクティブな共有';
$fs_calculate_folder_size = 'フォルダサイズを計算';
$fs_no_multi_select = 'このオプションでは、一つ以上のアイテムは選択できません。';
$fs_search = '検索';
$search_title = "ファイルやフォルダを検索";
$fs_keyword = 'キーワード';
$fs_enter_keyword = 'キーワードを入力';
$fs_modified_before = '編集前';
$fs_modified_after = '編集後';

//translation required
$fb_compress='圧縮';
$fb_decompress='解凍';
$fb_failed_to_create = 'アーカイブの作成に失敗しました。';
$fb_failed_to_extract = '解凍に失敗しました。';
$fb_compression_type = '圧縮の種類';
$fbFreeQuotaSpace = 'ディレクトリのフリースペース';

//2.11
$fb_unkown_compression = '不明な圧縮タイプ';
$fs_new_doc = '新規ドキュメント';
$fs_cleanup = 'クリーンアップHTML';
$fbMultipleFiles = '複数ファイル';
$fbSelect = "ファイル選択"; //changed
	
//2.14
$fs_confirm_unshare = '本当にこのフォルダのすべての権限をはずしますか?';
$fs_users = 'ユーザ';
$fs_personal = '個人';

$fs_inssufficient_diskspace = 'ディスク容量不足';

//2.15
$fs_open_containing_folder = '含まれるフォルダを開く';
$fs_file_put_in=' "%s" のファイルは "%s" としてアップロードされました';
$fs_new_file_uploaded = '新規ファイルアップロード: %s';
