<?php
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Abrir';
$strType = "Tipo";
$strModified = "Modificado";
$strCreated = "Criado";
$strAccessed = "Acessado";
$strSize = "Tamanho";
$fbRefresh = "Atualizar";
$fbProperties = "Propriedades";
$fbNewFolder = "Pasta Nova";
$fbDelete = "Excluir";
$fbCut = "Recortar";
$fbPaste = "Colar";
$fbCopy = "Copiar";
$fbFiletypes = "Tipos de Arquivos";
$fbSharing = "Compartilhar";
$fbShares = "Pastas compartilhadas";
$fbShare = "Pastas compartilhada";
$fbPath = "Caminho";
$fbFolders = "Pastas";
$fbNoSelect = "Você não selecionou nenhum item. Clique no ícone próximo ao nome para selecionar um item.";
$fbConfirmDelete = "Confirmar a exclusão";
$fbWritePermissions = "Permissão para escrever";
$fbReadPermissions = "Permissão para ler";
$fbGeneral = "Geral";
$fbConfirmOverwrite = "Confirmar a escrita";
$strOverwritePrefix = "Tem certeza que quer reescrever ";
$strOverwriteSuffix = "?";
$fbDescription = "Descrição";
$fbLocation = "Localização";
$fbUpload = "Enviar";
$fbUpload_text = "Enviar texto";
$fbUpload_nofile = "Nenhum arquivo foi recebido.";
$fbVersions = "Versões";
$fbDelete_version = "Tem certeza que deseja deletar esta versão?";
$fbFolderExists = "Essa Pasta já existe.";
$fbEmailFile = "enviar um arquivo";
$fbFolder = "Pasta";
$fbSelect = "Selecione o ficheiro...";
$fbNoFile = "O arquivo que você tentou enviar é muito grande.<br /> O tamanho máximo para tranferência de arquivos está ajustado para: ";
$fbPleaseWait = "Por favor aguarde. Enviando dados...";
$fbFilename = "Nome do arquivo";
$fbUpLevel = "Nível acima";
$fbItems = "Item(s)";
$fbFolderSize = "Tamanho da pasta";
$fbMaxUploadSize = "Tamanho máximo";
$ml_file_too_big = "O arquivo que você tentou anexar é muito grande, o tamanho máximo para transferência de arquivos está ajustado para: ";
$cmdSearch = "Pesquisar";
$fbNoRightToOverwrite = "O arquivo já existe e você não tem permissão para o reescrever.";
$fbSaveFile = "Guardar Arquivo Como...";
$fbNameExists = "Esse nome já existe nesta pasta.";
$fbThis = 'Isto';
$fbFiles = 'Arquivos';
$fs_activate_sharing = 'Ativar compartilhamento';
$fs_calculate_folder_size = 'Calcular o tamanho da pasta';
$fs_no_multi_select = 'Você não pode selecionar mais de um item com esta opção ';
$fs_search = 'Pesquisar';
$search_title = "Pesquisar Arquivos e Pastas";
$fs_keyword = 'Palavra-chave';
$fs_enter_keyword = 'Por favor insira uma palavra-chave ou frase';
$fs_modified_before = 'Modificado antes de';
$fs_modified_after = 'Modificado depois de';

//translation required
$fb_compress='Comprimir';
$fb_decompress='Decomprimir';
$fb_failed_to_create = 'Falha ao criar arquivo.';
$fb_failed_to_extract = 'Falha ao extrair';
$fb_compression_type = 'Compressão';
$fbFreeQuotaSpace = 'Espaço livre em sua pasta';

//2.11
$fb_unkown_compression = 'Tipo de compressão desconhecida';
$fs_new_doc = 'Novo documento';
$fs_cleanup = 'Limpar HTML';
$fbMultipleFiles = 'Multiplos arquivos';
$fbSelect = "Selecionar arquivo"; //changed

//2.14
$fs_confirm_unshare = 'Você tem certeza que quer remover todas permissões nesta pasta?';
$fs_users = 'Usuários';
$fs_personal = 'Pessoal';

$fs_inssufficient_diskspace = 'Espaço em disco insuficiente';

//2.15
$fs_open_containing_folder = 'Abrir pasta contendo';
$fs_file_put_in='O arquivo "%s" foi carregado para "%s"';
$fs_new_file_uploaded = 'Novo arquivo carregado: %s';

$fs_download = 'Baixar';
$fs_view = 'Vista';

$fs_notify = 'Enviar um e-mail se alguém carregar um novo arquivo';
