<?php
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Procurar';
$strType = "Tipo";
$strModified = "Modificado";
$strCreated = "Criado";
$strAccessed = "Acedido";
$strSize = "Tamanho";
$fbRefresh = "Refrescar";
$fbProperties = "Propriedades";
$fbNewFolder = "Nova Pasta";
$fbDelete = "Apagar";
$fbCut = "Cortar";
$fbPaste = "Colar";
$fbCopy = "Copiar";
$fbFiletypes = "Tipos de ficheiros";
$fbSharing = "Partilhar";
$fbShares = "Pastas partilhadas";
$fbShare = "Pasta partilhada";
$fbPath = "Caminho";
$fbFolders = "Pastas";
$fbNoSelect = "Não seleccionou um item. Clique no ícone junto do nome para seleccionar o item.";
$fbConfirmDelete = "Confirmar apagar";
$fbWritePermissions = "Permissão de escrita";
$fbReadPermissions = "Permissão de leitura";
$fbGeneral = "Geral";
$fbConfirmOverwrite = "Confirmar substitui&ccedil;ão";
$strOverwritePrefix = "Confirma substitui&ccedil;ão de ";
$strOverwriteSuffix = "?";
$fbDescription = "Descri&ccedil;ão";
$fbLocation = "Posi&ccedil;&atilde;o";
$fbUpload = "Enviar";
$fbUpload_text = "Seleccione o ficheiro a enviar";
$fbUpload_nofile = "Nenhum ficheiro foi recebido.";
$fbVersions = "Vers&otilde;es";
$fbDelete_version = "Confirma apagar esta versão?";
$fbFolderExists = "Essa pasta não existe";
$fbEmailFile = "Enviar ficheiro por email";
$fbFolder = "Pasta";
$fbSelect = "Seleccione o ficheiro...";
$fbNoFile = "O ficheiro é demasiado grande.<br /> O tamanho m&aacute;ximo é: ";
$fbPleaseWait = "Por favor aguarde. A enviar dados...";
$fbFilename = "Nome de ficheiro";
$fbUpLevel = "Um n&iacute;vel acima";
$fbItems = "ficheiro(s)";
$fbFolderSize = "Tamanho da Pasta";
$fbMaxUploadSize = "Tamanho máximo";
$ml_file_too_big = "O ficheiro é demasiado grande, o tamanho máximo é: ";
$cmdSearch = "Pesquisar";
$fbNoRightToOverwrite = "O ficheiro já existe e tem permissão para o substituir.";
$fbSaveFile = "Guardar Ficheiro como...";
$fbNameExists = "O nome j&aacute; existe nesta pasta.";
$fbThis = 'isto';
$fbFiles = 'Ficheiros';
$fs_activate_sharing = 'Activar partilha';
$fs_calculate_folder_size = 'Calcular o tamanho da pasta';
$fs_no_multi_select = 'Não pode seleccionar mais de um item com esta op&ccedil;ão ';
$fs_search = 'Pesquisar';
$search_title = "Pesquisar Ficheiros e Pastas";
$fs_keyword = 'Escreva o que procura';
$fs_enter_keyword = 'Escreva, por favor, o que procura';
$fs_modified_before = 'Modificado antes de';
$fs_modified_after = 'Modificado depois de';

$fb_compress='Comprimir';
$fb_decompress='Descomprimir';
$fb_failed_to_create = 'Falha ao criar o arquivo.';
$fb_failed_to_extract = 'Falha ao extrair';
$fb_compression_type = 'Comprimir';
$fbFreeQuotaSpace = 'Espa&ccedil;o livre na Directoria';

//2.11
$fb_unkown_compression = 'Tipo desconhecido de compressão';
$fs_new_doc = 'Novo Documento';
$fs_cleanup = 'Limpar  HTML';
$fbMultipleFiles = 'Múltiplos ficheiros';
$fbSelect = "Seleccione ficheiro"; //changed

//2.14
$fs_confirm_unshare = 'Tem a certeza que pretende remover todas as permiss&otilde;es nesta pasta?';
$fs_users = 'Utilizadores';
$fs_personal = 'Pessoal';

$fs_inssufficient_diskspace = 'Espa&ccedil;o em disco insuficiente';

//2.15
$fs_open_containing_folder = 'Abrir pasta';
$fs_file_put_in='O ficheiro  "%s" foi enviado para "%s"';
$fs_new_file_uploaded = 'Ficheiro enviado: %s';

$fs_download = 'Descarregar';
$fs_view = 'Ver';

$fs_notify = 'Enviar um email se alguém enviar um novo ficheiro';


$fs_status='Estado';
$fs_author='Autor';
$fs_no_status_history='Sem histórico';
$fs_no_status='Nenhum';
$fs_file_updated='O ficheiro %s foi actualizado';
$fs_open_properties='Abrir a janela de propriedades quando se der um duplo clique sobre um ficheiro';


$fs_file='Ficheiro';

$fs_enable_gota = 'Activar o Agente de Transferências Group-Office. Este Agente é um pequeno programa Java que guarda os ficheiros em Group-Office quando os edita localmente. Necessita da versão Profissional e Java 1.6 ou superior no computador.';
$fs_show_files_on_summary = 'Mostrar os 10 últimos ficheiros modificados na página do Sumário';

$fs_recursion='Não pode mover/copiar pastas para elas próprias';
$fs_select_destination = 'Seleccione a pasta destino'; 
$fs_move = 'Mover';

$fs_java_not_installed="Java não está instalado. Java é necessário para poder utilizar o Agente de Transferências Group-Office. Deseja instalar agora? Se não desejar ou não puder instalar o Java, pode desactivar o Agente de Transferências Group-Office em Configura&ccedil;ão -> Ficheiros.";
$fs_java_install = 'Instalar Java';
$fs_java_install_text = 'Para iniciar a instala&ccedil;ão do Java clique na barra de informa&ccedil;ão ao cimo desta página. Se não funcionar, tente dar um clique <a class="normal" href="http://www.java.com">aqui para instalar manualmente.</a>';


$fs_notify_folder='Notificar sobre altera&ccedil;&otilde;es feitas a ficheiros nesta pasta';

$fs_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=220';