<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Look in';
$strType = "Тип";
$strModified = "Изменен";
$strCreated = "Создан";
$strAccessed = "Accessed";
$strSize = "Размер";
$fbRefresh = "Обновить";
$fbProperties = "Настройки";
$fbNewFolder = "Новая папка";
$fbDelete = "Удалить";
$fbCut = "Вырезать";
$fbPaste = "Вставить";
$fbCopy = "Копировать";
$fbFiletypes = "Filetypes";
$fbSharing = "Sharing";
$fbShares = "Shared папки";
$fbShare = "Shared папки";
$fbPath = "Путь";
$fbFolders = "Папка";
$fbNoSelect = "You didn't select an item. Click on an icon next to the name to select an item.";
$fbConfirmDelete = "Confirm delete";
$fbWritePermissions = "Права на запись";
$fbReadPermissions = "Права на чтение";
$fbGeneral = "General";
$fbConfirmOverwrite = "Подтверждение перезаписи";
$strOverwritePrefix = "Вы действительно хотите перезаписать файл";
$strOverwriteSuffix = "?";
$fbDescription = "Описание";
$fbLocation = "Расположение";
$fbUpload = "Загрузка (от Вас)";
$fbUpload_text = "Выберете файл для загрузки";
$fbUpload_nofile = "No file was not recieved.";
$fbVersions = "Версии";
$fbDelete_version = "Are you sure you want to delete this version?";
$fbFolderExists = "The folder already exists.";
$fbEmailFile = "E-mail файл";
$fbFolder = "Папка";
$fbSelect = "Выбор файла...";
$fbNoFile = "The file you tried to upload is too big.<br /> The maximum transferable filesize is set to: ";
$fbPleaseWait = "Пожалуйста ждите. Отсылаются данные...";
$fbFilename = "Имя файла";
$fbUpLevel = "Уровень вверх";
$fbItems = "item(s)";
$fbFolderSize = "Размер папки";
$fbMaxUploadSize = "Максимальный размер";
$ml_file_too_big = "The file you tried to attach is too big, the maximum filesize for attachments is set to: ";
$cmdSearch = "Поиск";
$fbNoRightToOverwrite = "The file already exist and you do not have the right to overwrite it.";
$fbSaveFile = "Сохранить файл как...";
$fbNameExists = "Такое имя файла уже существует в этой папке.";
$fbThis = 'эти';
$fbFiles = 'Файлы';
$fs_activate_sharing = 'Activate sharing';
$fs_calculate_folder_size = 'подсчитать размер папки';
$fs_no_multi_select = 'U can\'t select more then one item with this option';
$fs_search = 'Поиск';
$search_title = "Поиск папок и файлов";
$fs_keyword = 'Ключевые слова';
$fs_enter_keyword = 'Пожалуйста введите ключевые слова';
$fs_modified_before = 'Измененные после';
$fs_modified_after = 'Измененные до';

//translation required
$fb_compress='Заархивировать';
$fb_decompress='Разархивировать';
$fb_failed_to_create = 'Архив не создан.';
$fb_failed_to_extract = 'Ошибка при распаковке архива';
$fb_compression_type = 'Сжатие';
$fbFreeQuotaSpace = 'Свободное место в папке';


//2.11
$fb_unkown_compression = 'Неизвестный метод сжатия';
$fs_new_doc = 'Новый документ';
$fs_cleanup = 'Очистить HTML';
$fbMultipleFiles = 'Multiple files';
$fbSelect = "Выбранный файл"; //changed
