<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = 'Kolla i';
$strType = "Typ";
$strModified = "Modifierad";
$strCreated = "Skapad";
$strAccessed = "Åtkommen";
$strSize = "Storlek";
$fbRefresh = "Ladda om";
$fbProperties = "Egenskaper";
$fbNewFolder = "Ny mapp";
$fbDelete = "Radera";
$fbCut = "Klipp ut";
$fbPaste = "Klistra in";
$fbCopy = "Kopiera";
$fbFiletypes = "Filtyper";
$fbSharing = "Utdelning";
$fbShares = "Delade mappar";
$fbShare = "Delad mapp";
$fbPath = "Sögväg";
$fbFolders = "Mappar";
$fbNoSelect = "Du valde ingenting. Tryck på en ikon bredvid namnet för att välja något.";
$fbConfirmDelete = "Bekräfta radering";
$fbWritePermissions = "Skrivrättigheter";
$fbReadPermissions = "Läsrättigheter";
$fbGeneral = "Generellt";
$fbConfirmOverwrite = "Bekräfta överskrivning";
$strOverwritePrefix = "Är du säker på att du vill skriva över ";
$strOverwriteSuffix = "?";
$fbDescription = "Beskrivning";
$fbLocation = "Plats";
$fbUpload = "Ladda upp";
$fbUpload_text = "Välj fil att ladda upp";
$fbUpload_nofile = "Ingen fil mottogs.";
$fbVersions = "Versioner";
$fbDelete_version = "*Är du säker på att du vill radera denna version?";
$fbFolderExists = "Mappen existerar redan.";
$fbEmailFile = "E-posta fil";
$fbFolder = "Mapp";

$fbNoFile = "Filen du försökte ladda upp är för stor.<br />Den maximala storleken är satt till: ";
$fbPleaseWait = "Var god vänta. Skickar data...";
$fbFilename = "Filnamn";
$fbUpLevel = "Nivå upp";
$fbItems = "Föremål";
$fbFolderSize = "Storlek på mapp";
$fbMaxUploadSize = "Maximal storlek";
$ml_file_too_big = "Filen du försökte bifoga är för stor, den maximala storleken för bifogningar är: ";
$cmdSearch = "Sök";
$fbNoRightToOverwrite = "Filen existerar redan och du har inte rättigheter till att skriva över den.";
$fbSaveFile = "Spara fil som...";
$fbNameExists = "Namnet existerar redan i denna mapp.";
$fbThis = 'denna';
$fbFiles = 'Filer';
$fs_activate_sharing = 'Aktivera delning';
$fs_calculate_folder_size = 'Beräkna mappstorlek';
$fs_no_multi_select = 'Du kan inte välja mer än en sak med detta val';
$fs_search = 'Sök';
$search_title = "Sök efter filer och mappar";
$fs_keyword = 'Sökord';
$fs_enter_keyword = 'Var god ange ett sökord';
$fs_modified_before = 'Modifierad innan';
$fs_modified_after = 'Modifierad efter';

//translation required
$fb_compress='Packa';
$fb_decompress='Packa upp';
$fb_failed_to_create = 'Misslyckades med att skapa arkiv.';
$fb_failed_to_extract = 'Uppackningen misslyckades';
$fb_compression_type = 'Kompression';
$fbFreeQuotaSpace = 'Tillgängligt utrymme i din mapp';

//2.11
$fb_unkown_compression = 'Okänd kompressions typ';
$fs_new_doc = 'Nytt dokument';
$fs_cleanup = 'Rensa upp HTML';
$fbMultipleFiles = 'Multipla filer';
$fbSelect = "Välj fil"; //changed
