<?php
require_once($GO_LANGUAGE->get_fallback_language_file('filesystem'));

$strLookIn = '瀏覽';
$strType = "類型";
$strModified = "修改日期";
$strCreated = "建立日期";
$strAccessed = "存取日期";
$strSize = "大小";
$fbRefresh = "重新整理";
$fbProperties = "內容";
$fbNewFolder = "新增資料夾";
$fbDelete = "移除";
$fbCut = "剪下";
$fbPaste = "貼上";
$fbCopy = "複製";
$fbFiletypes = "檔案類型";
$fbSharing = "分享";
$fbShares = "已分享資料夾";
$fbShare = "已分享資料夾";
$fbPath = "路徑";
$fbFolders = "資料夾";
$fbNoSelect = "你/妳沒有選擇任何物件，請先選取檔案圖形側的正方型";
$fbConfirmDelete = "確定移除";
$fbWritePermissions = "寫入權限";
$fbReadPermissions = "讀取權限";
$fbGeneral = "一般";
$fbConfirmOverwrite = "確定覆蓋\";
$strOverwritePrefix = "你/妳是否確定要覆蓋\";
$strOverwriteSuffix = "?";
$fbDescription = "描述";
$fbLocation = "位置";
$fbUpload = "上載";
$fbUpload_text = "選擇檔案上載";
$fbUpload_nofile = "沒有已接收檔案";
$fbVersions = "版本";
$fbDelete_version = "你/妳是否確定消除這個版本";
$fbFolderExists = "資料夾已存在";
$fbEmailFile = "電郵檔案";
$fbFolder = "資料夾";
$fbSelect = "選擇檔案...";
$fbNoFile = "你所上載的檔案太大<br/>最大的可傳送檔案限制已設定為:";	
$fbPleaseWait = "請等待，正在傳送資料...";
$fbFilename = "檔案名稱";
$fbUpLevel = "上一層";
$fbItems = "項目";
$fbFolderSize = "資料夾大小";
$fbMaxUploadSize = "上載限制大小";
$ml_file_too_big = "你所上載的附件太大，最大的附件限制已設定為";
$cmdSearch = "搜尋";
$fbNoRightToOverwrite = "檔案已存在，你/妳沒有權限覆蓋它";
$fbSaveFile = "另存新檔....";
$fbNameExists = "名稱已存在這資料夾";
$fbThis = '這個';
$fbFiles = '檔案';
$fs_activate_sharing = '啟動分享';
$fs_calculate_folder_size = '計算資料夾大小';
$fs_no_multi_select = "在這個選項，你/妳不可以選擇多於一個項目";
$fs_search = '搜尋';
$search_title = "搜尋所有資料夾及檔案";
$fs_keyword = '關鍵字';
$fs_enter_keyword = '請輸入關鍵字';
$fs_modified_before = '在這日期之前修改';
$fs_modified_after = '在這日期之後修改';

//translation required

$fb_compress='壓縮';

$fb_decompress='解壓縮';

$fb_failed_to_create = '建立壓縮檔失敗';

$fb_failed_to_extract = '解壓失敗';

$fb_compression_type = '壓縮';
