<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='تبادل ملفات مع';
$sync_calendar='التقويم';
$sync_addressbook='العناوين';
$sync_server_is_master='Data from Group-Office is more important then the data from the guest device';
$sync_sync_private='Synchronize private appointments too';
$sync_devices='الاجهزة';
$sync_last_calendar_sync='التقزيم الاخير';
$sync_last_addressbook_sync='Last addressbook sync';
$sync_never='Never';
$sync_last_todos_sync='اليوم الاخير';
$sync_log='Sync log';
$sync_max_days_old='Sync events not older then';
$sync_days='الايام';
$sync_delete_old_events='Delete events from the client that are older then the time above';
$sync_click_to_verify='اضغط هنا';
$sync_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=185';
?>