<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Sincronitza amb:';
$sync_calendar='Calendari';
$sync_addressbook='Llibreta d\'adreces';
$sync_server_is_master='Les dades de Group-Office són més importants que les dades del dispositiu convidat';
$sync_sync_private='Sincronitza les cites privades també';
$sync_devices='Dispositius';
$sync_last_calendar_sync='Darrera sincronització de calendari';
$sync_last_addressbook_sync='Darrera sincronització de llibreta d\'adreces';
$sync_never='Mai';
$sync_last_todos_sync='Sincronització de darreres tasques';
$sync_log='Registre de sincronització';
$sync_max_days_old='Sincronitza events no més antics de';
$sync_days='dies';
$sync_delete_old_events='Suprimeix events del client que siguin més vells que la data indicada aquí al damunt';
?>