<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Synchronizuj s:';
$sync_calendar = 'Kalendář';
$sync_addressbook = 'Adresář';
$sync_server_is_master = 'Data z Group-Office jsou důležtější než data na zařízení hosta';
$sync_sync_private = 'Synchronizuj také privátní schůzky';
$sync_devices = 'Zažízení';

$sync_last_calendar_sync = 'Poslední synchro kalendáře';
$sync_last_addressbook_sync = 'Poslední synchro adresáře';

$sync_never = 'Nikdy';

//2.15
$sync_last_todos_sync = 'Posladní synchro úkolů';
$sync_log='Synchro log';

//2.16
$sync_max_days_old = 'Synchronizuj události né starší než';
$sync_days = 'dnů';
$sync_delete_old_events='Smaž události z klienta,které jsou starší než čas nahoře';
$sync_click_to_verify='Klikni pro kontrolu';

$sync_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=185';
