<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Synchronisiere mit:';
$sync_calendar='Kalender';
$sync_addressbook='Adressbuch';
$sync_server_is_master='Die Daten von Group-Office haben die höchste Priorität';
$sync_sync_private='Die privaten Termine ebenfalls synchronisieren';
$sync_devices='Geräte';
$sync_last_calendar_sync='Kalender zuletzt synchronisiert';
$sync_last_addressbook_sync='Adressbuch zuletzt synchronisiert';
$sync_never='Niemals';
$sync_last_todos_sync='Aufgaben zuletzt synchronisiert';
$sync_log='Sync Log';
$sync_max_days_old='Sync Ereignisse nicht älter als';
$sync_days='Tage';
$sync_delete_old_events='Ereignisse des Benutzers löschen, die älter als der angegebene Zeitpunkt sind';
$sync_click_to_verify='Klicken zum bestätigen';
?>