<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Synchronize with:';
$sync_calendar = 'Calendar';
$sync_addressbook = 'Addressbook';
$sync_server_is_master = 'Data from Group-Office is more important then the data from the guest device';
$sync_sync_private = 'Synchronize private appointments too';
$sync_devices = 'Devices';

$sync_last_calendar_sync = 'Last calendar sync';
$sync_last_addressbook_sync = 'Last addressbook sync';

$sync_never = 'Never';

//2.15
$sync_last_todos_sync = 'Last todos sync';
$sync_log='Sync log';

//2.16
$sync_max_days_old = 'Sync events not older then';
$sync_days = 'days';
$sync_delete_old_events='Delete events from the client that are older then the time above';
$sync_click_to_verify='Click to verify';

$sync_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=185';
