<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Synkronoi käyttäen:';
$sync_calendar = 'Kalenteri';
$sync_addressbook = 'Osoitekirja';
$sync_server_is_master = 'Group-Officen tiedot ovat tärkeämpiä kuin vieraan laitteen';
$sync_sync_private = 'Synkronoi myös yksityiset tiedot';
$sync_devices = 'Laitteet';

$sync_last_calendar_sync = 'Edellinen kalenteri synkronointi';
$sync_last_addressbook_sync = 'Edellinen osoitekirja synkronointi';

$sync_never = 'Ei koskaan';
