<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$charset = 'UTF-8';

$sync_with = 'Synchroniser avec:';
$sync_calendar = 'Calendrier';
$sync_addressbook = 'Carnet d\'adresse';
$sync_server_is_master = 'Les données de Group-Office sont plus importantes que celle du PDA';
$sync_sync_private = 'Synchroniser les rendez-vous privés';
$sync_devices = 'Appareil';
$sync_last_calendar_sync = 'Dernière synchronisation du calendrier';
$sync_last_addressbook_sync = 'Dernière synchronisation du carnet d\'adresse';
$sync_never = 'Jamais';

//2.15
$sync_last_todos_sync = 'Dernière synchronisation des tâches';
$sync_log='Log de synchronisation';

//2.16
$sync_max_days_old = 'Ne pas synchroniser les rendez-vous antérieurs à';
$sync_days = 'jours';
$sync_delete_old_events='Sur le PDA, supprimer les rendez-vous antérieurs à la période ci-dessus';
?>
