<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Szinkronizálás ezzel:';
$sync_calendar='Naptár';
$sync_addressbook='Névjegyalbum';
$sync_server_is_master='A Group-Office adatai fontosabbak, mint a másik eszközön tároltak';
$sync_sync_private='A magánjellegű találkozókat is szinkronizálja';
$sync_devices='Eszközök';
$sync_last_calendar_sync='Utolsó naptár szinkronizálás';
$sync_last_addressbook_sync='Utolsó névjegyalbum szinkronizálás';
$sync_never='Soha';
$sync_last_todos_sync='Utolsó feladat szinkronizálás';
$sync_log='Szinkronizálási napló';
$sync_max_days_old='Csak olyan események szinkronizálása, amik nem régebbiek, mint';
$sync_days='nap';
$sync_delete_old_events='A megadott dátumnál korábbi események törlése a kliensről';
?>