<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Sincronizza con:';
$sync_calendar='Calendario';
$sync_addressbook='Rubrica';
$sync_server_is_master='Dati di Group-Office sono più importanti rispetto ai dati dei dispositivi esterni';
$sync_sync_private='Sincronizza anche gli appuntamenti privati';
$sync_devices='Dispositivi';
$sync_last_calendar_sync='Ultima sincronizzazione calendiario';
$sync_last_addressbook_sync='Ultima sincronizzazione rubrica';
$sync_never='Mai';
$sync_last_todos_sync='Ultime sincronizzazioni da fare';
$sync_log='Registro sincronizzazione';
$sync_max_days_old='Sincronizza eventi non pi&ugrave; vecchi di';
$sync_days='giorni';
$sync_delete_old_events='Cancella gli eventi che sono pi&ugrave; vecchi dell\'orario riportato sopra';
?>