<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = '同期:';
$sync_calendar = 'カレンダー';
$sync_addressbook = 'アドレス帳';
$sync_server_is_master = 'Group-Officeからのデータはゲストデバイスのデータより重要です';
$sync_sync_private = '個人的なアポイントメントも同期する';
$sync_devices = 'デバイス';

$sync_last_calendar_sync = 'カレンダ同期の最終更新';
$sync_last_addressbook_sync = 'アドレス帳同期の最終更新';

$sync_never = 'しない';
