<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Synchroniseer met:';
$sync_calendar='Agenda';
$sync_addressbook='Adresboek';
$sync_server_is_master='Gegevens van Group-Office gaan voor die van de client';
$sync_sync_private='Synchroniseer ook privé afspraken';
$sync_devices='Apparaten';
$sync_last_calendar_sync='Laatste synchronisatie met agenda';
$sync_last_addressbook_sync='Laatste synchronisatie met adresboek';
$sync_never='Nooit';
$sync_last_todos_sync='Laatste synchronisatie met taken';
$sync_log='Sync log';
$sync_max_days_old='Sync afspraken niet ouder dan';
$sync_days='dagen';
$sync_delete_old_events='Verwijder afspraken op de client die ouder zijn dan de hierboven aangegeven tijd';
$sync_click_to_verify='Klik om te testen';