<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Sincronizar com:';
$sync_calendar = 'Calendário';
$sync_addressbook = 'Contatos';
$sync_server_is_master = 'Dados do Group-Office é mais importante que os dados do dispositivo do convidado';
$sync_sync_private = 'Sincronizar compromissos particulares também';
$sync_devices = 'Dispositivos';

$sync_last_calendar_sync = 'Ultima sincronização do calendário';
$sync_last_addressbook_sync = 'Ultima sincronização dos contatos';

$sync_never = 'Nunca';

//2.15
$sync_last_todos_sync = 'Ultima pendência sincronizada';
