<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Синхронизировать с:';
$sync_calendar = 'Календарь';
$sync_addressbook = 'Адресная книга';
$sync_server_is_master = 'Данные из Group-Office is more important then the data from the guest device';
$sync_sync_private = 'Synchronize private appointments too';
$sync_devices = 'Устройства';

$sync_last_calendar_sync = 'Последняя синхронизация календаря';
$sync_last_addressbook_sync = 'Последняя синхронизация адресной книги';

$sync_never = 'Новое';
