<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Sinhroniziraj z:';
$sync_calendar='Koledar';
$sync_addressbook='Adresar';
$sync_server_is_master='Podatki iz Group-Office so bolj pomembni kot podatki iz gostujoče naprave';
$sync_sync_private='Sinhroniziraj tudi zasebne sestanke';
$sync_devices='Naprave';
$sync_last_calendar_sync='Zadnja sinhronizacija koledarja';
$sync_last_addressbook_sync='Zadnje sinhronizacija adresarja';
$sync_never='Nikoli';
$sync_last_todos_sync='Zadnja sinhronizacija opravil';
$sync_log='Sinhroniziraj dnevnik';
$sync_max_days_old='Sinhroniziraj dogodke, ki niso starejši od';
$sync_days='Dni';
$sync_delete_old_events='Izbriši dogodke od stranke ki so starejši od zgornjega časa';
$sync_click_to_verify='Klikni za potrditev';
$sync_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=185';
?>