<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));

$sync_with = 'Synchronisera med:';
$sync_calendar = 'Kalender';
$sync_addressbook = 'Adressbok';
$sync_server_is_master = 'Data från Group-Office är viktigare än data från gästenheten';
$sync_sync_private = 'Synchronisera privata uppgifter också';
$sync_devices = 'Enheter';

$sync_last_calendar_sync = 'Senaste kalender synchronisering';
$sync_last_addressbook_sync = 'Senaste adressboks synchronisering';

$sync_never = 'Aldrig';
