<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('sync'));
$sync_with='Bununla eşleştir:';
$sync_calendar='Takvim';
$sync_addressbook='Adres Defteri';
$sync_server_is_master='Group-Office üzerindeki veri, misafir bir aygıttaki cihazdan daha önemlidir';
$sync_sync_private='Özel verileri de eşleştir';
$sync_devices='Cihazlar';
$sync_last_calendar_sync='Son takvim eşlemesi';
$sync_last_addressbook_sync='Son adres defteri eşlemesi';
$sync_never='Asla';
$sync_last_todos_sync='Son yapılacaklar eşlemesi';
$sync_log='Kayıtı eşleştir';
$sync_max_days_old='Bundan eski olmayan olayları eşleştir:';
$sync_days='gün';
$sync_delete_old_events='İstemci üzerinde yukarıda belirtilenden daha eski olan olayları sil';
?>