<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='اللغه';
$pref_theme='الموضوعات';
$pref_date_format='تاريخ الشكل';
$pref_thousands_seperator='فاصل الآلاف';
$pref_decimal_seperator='الفاصل العشرى';
$pref_mail_client='استخدام مجموعة مكتب البريد لارسال البريد الألكتروني';
$pref_look='الشكل العام للبرنامج';
$pref_notations='الاعدادات الاقليمية';
$pref_currency='العملة';
$pref_region_code='المنطقة';
$pref_max_rows_list='الحد الاقصى لعدد الصفوف في قوائم';
$pref_unlimited='غير محدود';
$pref_timezone='المنطقة الزمنية';
$pref_time_format='شكل الوقت';
$pref_startmodule='Start in module';
$pref_first_weekday='الاسبوع الاول';
$adjust_to_dst='Automatically adjust time to Daylight Savings Time';
$pref_name_order='الاسماء بواسطة';
$pref_use_checkbox_select='Multiselect rows without using the CTRL key';
$pref_date_seperator='Date separator';
?>