<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Език";
$pref_theme = "Тема";
$pref_date_format = "Дата формат";
$pref_thousands_seperator = "Хиляден разделител";
$pref_decimal_seperator = "Десетичен разделител";
$pref_mail_client = "Използвай Group-Office пощенски клиент за да изпратиш E-mail.";
$pref_look = "Погледни & почуствай";
$pref_notations = "Нотация";
$pref_currency = 'Валута';
$pref_region_code = 'Регион';

//translation required
$pref_max_rows_list = 'Максимум редове на страница';
$pref_unlimited = 'Неограничен';
