<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Jazyk";
$pref_theme = "Téma";
$pref_date_format = "Formát data";
$pref_thousands_seperator = "Tisícinný oddělovač";
$pref_decimal_seperator = "Desetinný oddělovač";
$pref_mail_client = "Používat Group-Office mail klienta pro odesíláná E-mailů.";
$pref_look = "Vzhled";
$pref_notations = "Nastavení";
$pref_currency = 'Měna';
$pref_region_code = 'Kód oblasti';
$pref_max_rows_list = 'Maximální počet řádků v seznamech';
$pref_unlimited = 'Neomezený';
$pref_timezone = 'Časová zóna';
$pref_time_format = "Formát času";
$pref_startmodule = 'Startovat v modulu';

//2.01
$pref_first_weekday = 'První pracovní den týdne';

//2.05
$adjust_to_dst = 'Automaticky upravovat hodiny podle letního času';

//2.08
$pref_name_order = 'Řadit jména podle';

//2.14
$pref_use_checkbox_select = 'Multvýběr řádků bez použití klávesy CTRL';

//2.15
$pref_date_seperator = 'Oddělovač datumu';
