<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Sprog";
$pref_theme = "Tema";
$pref_date_format = "Datoformat";
$pref_thousands_seperator = "Talseparator";
$pref_decimal_seperator = "Decimaltegn";
$pref_mail_client = "Brug Group-Office mailklienten til at sende e-mail.";
$pref_look = "Udséende";
$pref_notations = "Formater";
$pref_currency = 'Møntfod';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Vis antal rækker i lister';
$pref_unlimited = 'Ubegrænset';
$pref_timezone = 'Tidszone';
$pref_time_format = "Tidsformat";
$pref_startmodule = 'Start i modul';

//2.01
$pref_first_weekday = 'Første ugedag';

//2.05
$adjust_to_dst = 'Tag automatisk højde for sommertid';
