<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Language";
$pref_theme = "Theme";
$pref_date_format = "Date format";
$pref_thousands_seperator = "Thousands seperator";
$pref_decimal_seperator = "Decimal seperator";
$pref_mail_client = "Use Group-Office mail client to send E-mail.";
$pref_look = "Look & feel";
$pref_notations = "Regional settings";
$pref_currency = 'Currency';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Maximum number of rows in lists';
$pref_unlimited = 'Unlimited';
$pref_timezone = 'Timezone';
$pref_time_format = "Time format";
$pref_startmodule = 'Start in module';

//2.01
$pref_first_weekday = 'First weekday';

//2.05
$adjust_to_dst = 'Automatically adjust time to Daylight Savings Time';

//2.08
$pref_name_order = 'Sort names by';

//2.14
$pref_use_checkbox_select = 'Multiselect rows without using the CTRL key';

//2.15
$pref_date_seperator = 'Date seperator';
