<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Kieli";
$pref_theme = "Ulkoasu";
$pref_date_format = "Päiväys muoto";
$pref_thousands_seperator = "Tuhat erotin";
$pref_decimal_seperator = "Desimaali erotin";
$pref_mail_client = "Käytä Group-Office sähköposti-klienttiä sähköpostin lähetykseen.";
$pref_look = "Ulkoasu";
$pref_notations = "Paikalliset asetukset";
$pref_currency = 'Valuutta';
$pref_region_code = 'Alue';
$pref_max_rows_list = 'Listan suurin rivimäärä';
$pref_unlimited = 'Rajoittamaton';
$pref_timezone = 'Aikavyöhyke';
$pref_time_format = "Aika muoto";
$pref_startmodule = 'Käynnistys moduuliin';

//2.01
$pref_first_weekday = 'Ensimmäinen viikkopäivä';

//2.05
$adjust_to_dst = 'Ota kesäaika käyttöön automaatisesti';

//2.08
$pref_name_order = 'Nimien mukaan lajittelu';

//2.14
$pref_use_checkbox_select = 'Rivien monivalinta käyttämättä CTRL näppäintä';

//2.15
$pref_date_seperator = 'Päiväys erotin';
