<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

//co-Author (only corrections of orthography): j.s Hubert jsh@interlug.net
//13 aout 2007

require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Langue";
$pref_theme = "Thème";
$pref_date_format = "Format de la date";
$pref_thousands_seperator = "Séparateur des milliers";
$pref_decimal_seperator = "Séparateur décimal";
$pref_mail_client = "Utiliser le client email de Group-Office pour envoyer le courrier.";
$pref_look = "Apparence";
$pref_notations = "Notations";
$pref_currency = 'Monétaire';
$pref_region_code = 'Région';
$pref_max_rows_list = 'Nombre maximum de lignes dans les listes';
$pref_unlimited = 'Illimité';
$pref_timezone = 'Fuseau horaire';
$pref_time_format = "Format horaire";
$pref_startmodule = 'Commencer avec le module'; //Start in module

//2.01
$pref_first_weekday = 'Premier jour de la semaine';

//2.05
$adjust_to_dst = 'Ajuster automatiquement l\'observation de l\'heure d\'été'; //Daylight Savings Time';

//2.08
$pref_name_order = 'Trier les noms par';

//2.14
$pref_use_checkbox_select = 'Sélection multiple de lignes sans utiliser la touche CTRL';

//2.15
$pref_date_seperator = 'Séparateur de date';
?>
