<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$htmldirection='rtl';
$charset='UTF-8';

$pref_language = "שפה";
$pref_theme = "ערכה";
$pref_date_format = "תבנית תאריך";
$pref_thousands_seperator = "מפריד אלפים";
$pref_decimal_seperator = "מפריד עשרות";
$pref_mail_client = "השתמש בלקוח הדואר של Group-Office לשליחת E-mail.";
$pref_look = "מראה ותחושה";
$pref_notations = "סימנים";
$pref_currency = 'מטבע';
$pref_region_code = 'אזור';
$pref_max_rows_list = 'מספר שורות מקסימלי ברשימות';
$pref_unlimited = 'לא מוגבל';
$pref_timezone = 'אזור זמן';
$pref_time_format = "תבנית זמן";
$pref_startmodule = 'התחל במודול';

//2.01
$pref_first_weekday = 'יום ראשון בשבוע';

//2.05
$adjust_to_dst = 'כוון את השעון באופן אוטומטי לשעון קיץ';
