<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='Nyelv';
$pref_theme='Téma';
$pref_date_format='Dátum formátum';
$pref_thousands_seperator='Ezres elválasztó';
$pref_decimal_seperator='Tizedesjel';
$pref_mail_client='A Group-Office levelezőkliens használata E-mailek küldéséhez.';
$pref_look='Megjelenés';
$pref_notations='Területi beállítások';
$pref_currency='Pénznem';
$pref_region_code='Régió';
$pref_max_rows_list='Listasorok maximális száma';
$pref_unlimited='Korlátlan';
$pref_timezone='Időzóna';
$pref_time_format='Időformátum';
$pref_startmodule='Kezdőlap';
$pref_first_weekday='Első munkanap';
$adjust_to_dst='Automatikus átállás nyári időszámításra';
$pref_name_order='Rendezés ez alapján';
$pref_use_checkbox_select='Több sor kijelölése a CTRL gomb használata nélkül';
$pref_date_seperator='Dátumelválasztó';
?>