<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='Lingua';
$pref_theme='Tema';
$pref_date_format='Formato data';
$pref_thousands_seperator='Separatore migliaia';
$pref_decimal_seperator='Separatore decimali';
$pref_mail_client='Usa Group-Office per spedire le E-mail.';
$pref_look='Aspetto';
$pref_notations='Notazione';
$pref_currency='Valuta';
$pref_region_code='Regione';
$pref_max_rows_list='Massimo numero di righe nelle liste';
$pref_unlimited='Nessun limite';
$pref_timezone='Fuso orario';
$pref_time_format='Formato ora';
$pref_startmodule='Modulo iniziale';
$pref_first_weekday='Inizio settimana';
$adjust_to_dst='Adatta automaticamente all\'ora legale';
$pref_name_order='Ordina i nomi per';
$pref_use_checkbox_select='Selezione multipla delle righe senza l\'uso del tasto CTRL';
$pref_date_seperator='Separatore di data';
?>