<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "言語";
$pref_theme = "テーマ";
$pref_date_format = "日付設定";
$pref_thousands_seperator = "千桁区切り";
$pref_decimal_seperator = "桁区切り";
$pref_mail_client = "メールを送るためにGroupOfficeメールクライアントを使用する";
$pref_look = "操作画面";
$pref_notations = "表記";
$pref_currency = '通貨';
$pref_region_code = 'リージョン';
$pref_max_rows_list = 'リストの最大数';
$pref_unlimited = '無制限';
$pref_timezone = 'タイムゾーン';
$pref_time_format = "時刻フォーマット";
$pref_startmodule = '初期モジュール';

//2.01
$pref_first_weekday = 'ウィークディの開始';

//2.05
$adjust_to_dst = '夏時間を自動的に調整';

//2.08
$pref_name_order = '名前で並び替え';

//2.14
$pref_use_checkbox_select = 'コントロールキーを使わずに列を複数選択';

//2.15
$pref_date_seperator = '日付の分け方';
