<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='Taal';
$pref_theme='Thema';
$pref_date_format='Datumformaat';
$pref_thousands_seperator='Scheidingsteken duizendgetallen';
$pref_decimal_seperator='Decimaal scheidingsteken';
$pref_mail_client='Gebruik standaard de Group-Office E-mail applicatie om E-mail te verzenden.';
$pref_look='Uiterlijk & Gebruiksgemak';
$pref_notations='Regionale instellingen';
$pref_currency='Valuta';
$pref_region_code='Regio';
$pref_max_rows_list='Maximaal aantal rijen in lijsten';
$pref_unlimited='Ongelimiteerd';
$pref_timezone='Tijdzone';
$pref_time_format='Tijd formaat';
$pref_startmodule='Start in module';
$pref_first_weekday='Eerste weekdag';
$adjust_to_dst='Tijd automatisch aan zomertijd aanpassen';
$pref_name_order='Sorteer namen op';
$pref_use_checkbox_select='Selecteer meervoudig zonder de CTRL toets te gebruiken';
$pref_date_seperator='Schedingsteken datum';
