<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Språk";
$pref_theme = "Tema";
$pref_date_format = "Datoformat";
$pref_thousands_seperator = "Tallseparator";
$pref_decimal_seperator = "Desimaltegn";
$pref_mail_client = "Bruk Group-Office e-postprogrammet for å sende mail.";
$pref_look = "Utseende";
$pref_notations = "Formater";
$pref_currency = 'Myntenhet';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Maks antall linjer tillatt i listene';
$pref_unlimited = 'Ingen grense';
