<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "L&iacute;ngua";
$pref_theme = "Tema";
$pref_date_format = "Formato da data";
$pref_thousands_seperator = "Separador dos milhares";
$pref_decimal_seperator = "Separador decimal";
$pref_mail_client = "Usar o m&oacute;dulo de correio para enviar email.";
$pref_look = "Aspecto";
$pref_notations = "Config. Regionais";
$pref_currency = 'Moeda';
$pref_region_code = 'Regi&atilde;o';
$pref_max_rows_list = 'Listas - M&aacute;ximo n&uacute;mero de linhas';
$pref_unlimited = 'Ilimitado';
$pref_timezone = 'Zona Hor&aacute:ria';
$pref_time_format = "Formato da Hora";
$pref_startmodule = 'Iniciar no m&oacute;dulo';

//2.01
$pref_first_weekday = 'Primeiro dia da semana';

//2.05
$adjust_to_dst = 'Ajustar automaticamente a mudan&ccedil;a da hora';

//2.08
$pref_name_order = 'Ordenar nomes por';

//2.14
$pref_use_checkbox_select = 'Seleccionar diversas linhas sem usar a tecla CTRL';

//2.15
$pref_date_seperator = 'Separador de data';
