<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Язык";
$pref_theme = "Тема";
$pref_date_format = "Формат даты";
$pref_thousands_seperator = "Разделитель тысячей";
$pref_decimal_seperator = "Десятичный разделитель";
$pref_mail_client = "Используйте Group-Office почтового клиента для отправки E-mail.";
$pref_look = "Отображение";
$pref_notations = "Региональные настройки";
$pref_currency = 'Валюта';
$pref_region_code = 'Регион';
$pref_max_rows_list = 'Максимальное число строк на странице';
$pref_unlimited = 'Неограниченно';
$pref_timezone = 'Временная зона';
$pref_time_format = "Вормат времени";
$pref_startmodule = 'Стартовый модуль';

//2.01
$pref_first_weekday = 'Первый день недели';

//2.05
$adjust_to_dst = 'Automatically adjust time to Daylight Savings Time';

//2.08
$pref_name_order = 'Сортировать имена по';
