<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='Jezik';
$pref_theme='Tema';
$pref_date_format='Prikaz datuma';
$pref_thousands_seperator='Ločilo tisočic';
$pref_decimal_seperator='Decimalno ločilo';
$pref_mail_client='Za pošiljanje E-pošte uporabi Group-Office poštni odjemalec.';
$pref_look='Izgled in funkcionalnost';
$pref_notations='Regionalne nastavitve';
$pref_currency='Denarna enota';
$pref_region_code='Regija';
$pref_max_rows_list='Maksimalno število vrstic na strani';
$pref_unlimited='Neomejeno';
$pref_timezone='Časovni pas';
$pref_time_format='Prikaz datuma';
$pref_startmodule='Začni v modulu';
$pref_first_weekday='Prvi dan tedna';
$adjust_to_dst='Samodejno nastavi čas na poletni čas';
$pref_name_order='Razvrsti imena po';
$pref_use_checkbox_select='Izbiranje večih vrstic brez uporabe tipke CTRL';
$pref_date_seperator='Datumsko ločilo';
?>