<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Jezik";
$pref_theme = "Tema";
$pref_date_format = "Oblika datuma";
$pref_thousands_seperator = "Loèilo tisoèin";
$pref_decimal_seperator = "Loèilo decimalnih mest";
$pref_mail_client = "Za po¹iljanje e-po¹te uporabi Group-Office.";
$pref_look = "Izgled in obèutek";
$pref_notations = "Zapisi";
$pref_currency = 'Valuta';
$pref_region_code = 'Podroèje';
$pref_max_rows_list = 'Najveèje ¹tevilo vrstic v seznamu';
$pref_unlimited = 'Neomejeno';
$pref_timezone = 'Èasovni pas';
$pref_time_format = "Oblika èasa";
$pref_startmodule = 'Zaèni v modulu';

//2.01
$pref_first_weekday = 'Prvi dan v tednu';

//2.05
$adjust_to_dst = 'Samodejno prilagodi èas v Daylight Savings Time';
