<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "Språk";
$pref_theme = "Tema";
$pref_date_format = "Datumformat";
$pref_thousands_seperator = "Tusentalsseparator";
$pref_decimal_seperator = "Decimalseperator";
$pref_mail_client = "Använd Group-Office e-postklient för att skicka e-post.";
$pref_look = "Känsla & utseende";
$pref_notations = "Notations";
$pref_currency = 'Valuta';
$pref_region_code = 'Region';
$pref_max_rows_list = 'Maximalt antal rader i listor';
$pref_unlimited = 'Obegränsat';
$pref_timezone = 'Tidszon';
$pref_time_format = "Tids format";
$pref_startmodule = 'Börja i modul';

//2.01
$pref_first_weekday = 'Första veckodag';

//2.05
$adjust_to_dst = 'Automatsikt justera tiden för sommartid';

//2.08
$pref_name_order = 'Sortera namn efter';
