<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "ภาษา";
$pref_theme = "ธีม";
$pref_date_format = "การแสดงผลเวลา";
$pref_thousands_seperator = "ขั้นเลขหนึ่งพันด้วย";
$pref_decimal_seperator = "ขันเลขทศนิยมด้วย";
$pref_mail_client = "ใช้กรุ๊ปออฟฟิสเมล์ไคลเอนท์เป็นตัวส่งเมล์";
$pref_look = "คุณลักษณะ";
$pref_notations = "สัญลักษณ์";
$pref_currency = 'อัตตราเงิน';
$pref_region_code = 'ภูมิภาค';
$pref_max_rows_list = 'ค่าสูงที่สุดที่ต้องการแสดงผลแถว';
$pref_unlimited = 'ไม่จำกัด';
$pref_timezone = 'ไทม์โซน';
$pref_time_format = "การแสดงผลเวลา";
$pref_startmodule = 'เริ่มในโมดูล';

//2.01
$pref_first_weekday = 'วันแรกของสัปดาห์';

//2.05
$adjust_to_dst = 'ปรับเวลาอัตโนมัติ';
//2.08
$pref_name_order = 'เรียงชื่อตามลำดับ';
