<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));
$pref_language='Dil';
$pref_theme='Tema';
$pref_date_format='Tarih biçimi';
$pref_thousands_seperator='Binlik ayracı';
$pref_decimal_seperator='Ondalık ayracı';
$pref_mail_client='Eposta göndermek için Group-Office eposta istemcisini kullan.';
$pref_look='Görünüş';
$pref_notations='Bölgesel ayarlar';
$pref_currency='Para birimi';
$pref_region_code='Bölge';
$pref_max_rows_list='Listedeki en fazla satır sayısı';
$pref_unlimited='Sınırsız';
$pref_timezone='Zaman bölgesi';
$pref_time_format='Zaman biçimi';
$pref_startmodule='Başlama modülü';
$pref_first_weekday='Haftanın ilk günü';
$adjust_to_dst='Kış/Yaz saati uygulamalarını otomatik ayarla';
$pref_name_order='Sıralama ölçütü';
$pref_use_checkbox_select='CTRL tuşu ile birden fazla satır seçilebilsin';
$pref_date_seperator='Tarih ayracı';
?>