<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('preferences'));

$pref_language = "語言";
$pref_theme = "佈景主題";
$pref_date_format = "日期格式";
$pref_thousands_seperator = "千位分隔符號";		
$pref_decimal_seperator = "小數位分隔符號";
$pref_mail_client = "使用Group-Office電郵客戶端寄出電子郵件";
$pref_look = "風格";
$pref_notations = "符號";
$pref_currency = '貨幣';
$pref_region_code = '區域';
$pref_max_rows_list = "每頁最多顯示列的數量";
$pref_unlimited = '沒有限制';
$pref_timezone = '時區';
$pref_time_format = "時間格式";
$pref_startmodule = '開始在模組';

//2.01
$pref_first_weekday = '一個星期的第一天';

//2.05
$adjust_to_dst = '自動調整日光節約時間';
