<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = 'Neznámý typ souboru';
$filetypes['txt'] = 'Textový soubor';
$filetypes['sxw'] = 'OpenOffice.Org Writer dokument';
$filetypes['doc'] = 'Microsoft Word dokument';
$filetypes['xls'] = 'Microsoft Excel tabulka';
$filetypes['mdb'] = 'Microsoft Access database';
$filetypes['ppt'] = $filetypes['pps'] = 'Microsoft Powerpoint presentace';
$filetypes['sxc'] = 'OpenOffice.Org Calc tabulka';
$filetypes['tar'] = 'Tar archiv';
$filetypes['zip'] = 'ZIP compressed archiv';
$filetypes['rar'] = 'RAR compressed archiv';
$filetypes['gz'] = $filetypes['tgz'] = 'GZIP compressed archiv';
$filetypes['bz2'] = 'BZIP2 compressed archiv';
$filetypes['pdf'] = 'PDF dokument';
$filetypes['exe'] = 'Windows spustitelný soubor';
$filetypes['ttf'] = 'True type font';
$filetypes['html'] = $filetypes['htm'] = 'HTML dokument';
$filetypes['jpg'] = $filetypes['jpeg'] = 'Obrázek';
$filetypes['gif'] = 'Obrázek';
$filetypes['bmp'] = 'Obrázek';
$filetypes['tif'] = 'Obrázek';
$filetypes['png'] = 'Obrázek';
$filetypes['php'] = 'PHP Script';
$filetypes['ics'] = 'Calendar informace';
$filetypes['vcf'] = 'Contact informace';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'Zvukový soubor';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'Video klip';
