<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = 'Tuntematon tiedosto tyyppi';
$filetypes['txt'] = 'Tekstitiedosto';
$filetypes['sxw'] = 'OpenOffice.Org Writer tiedosto';
$filetypes['doc'] = 'Microsoft Word tiedosto';
$filetypes['xls'] = 'Microsoft Excel tiedosto';
$filetypes['mdb'] = 'Microsoft Access tietokanta';
$filetypes['ppt'] = $filetypes['pps'] = 'Microsoft Powerpoint tiedosto';
$filetypes['sxc'] = 'OpenOffice.Org Calc tiedosto';
$filetypes['tar'] = 'Tar tiedosto';
$filetypes['zip'] = 'ZIP pakattu tiedosto';
$filetypes['rar'] = 'RAR pakattu tiedosto';
$filetypes['gz'] = $filetypes['tgz'] = 'GZIP pakattu tiedosto';
$filetypes['bz2'] = 'BZIP2 pakattu tiedosto'; 
$filetypes['pdf'] = 'PDF tiedosto';
$filetypes['exe'] = 'Windows exe tiedosto';
$filetypes['ttf'] = 'True type fontti tiedosto';
$filetypes['html'] = $filetypes['htm'] = 'HTML tiedosto';
$filetypes['jpg'] = $filetypes['jpeg'] = 'Kuva tiedosto';
$filetypes['gif'] = 'Kuva tiedosto';
$filetypes['bmp'] = 'Kuva tiedosto';
$filetypes['tif'] = 'Kuva tiedosto';
$filetypes['png'] = 'Kuva tiedosto';
$filetypes['php'] = 'PHP tiedosto';
$filetypes['ics'] = 'Kalenteri tiedosto';
$filetypes['vcf'] = 'Kontakti tiedosto';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'Ääni tiedosto';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'Video tiedosto';
$filetypes['pdf'] = 'Adobe Acrobat PDF tiedosto';
$filetypes['doc'] = $filetypes['dot'] = 'Microsoft Word tiedosto';
$filetypes['psd'] = 'Adobe Photoshop tiedosto';
$filetypes['rtf'] = 'Rich Text Format tiedosto';
$filetypes['swf'] = 'Macromedia Flash Movie tiedosto';
$filetypes['fla'] = 'Macromedia Flash Document (Source) tiedosto';
$filetypes['xls'] = $filetypes['xlt'] = 'Microsoft Excel tiedosto';
$filetypes['ai'] = 'Adobe Illustrator tiedosto';
