<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = '不明なファイル形式';
$filetypes['txt'] = 'テキスト';
$filetypes['sxw'] = 'OpenOffice.Org Writer document';
$filetypes['doc'] = 'Microsoft Word ドキュメント';
$filetypes['xls'] = 'Microsoft Excel スプレッドシート';
$filetypes['mdb'] = 'Microsoft Access データベース';
$filetypes['ppt'] = $filetypes['pps'] = 'Microsoft Powerpoint プレゼンテーション';
$filetypes['sxc'] = 'OpenOffice.Org Calc スプレッドシート';
$filetypes['tar'] = 'Tarアーカイブ';
$filetypes['zip'] = 'ZIPアーカイブ';
$filetypes['rar'] = 'RARアーカイブ';
$filetypes['gz'] = $filetypes['tgz'] = 'GZIPアーカイブ';
$filetypes['bz2'] = 'BZIP2アーカイブ'; 
$filetypes['pdf'] = 'PDFドキュメント';
$filetypes['exe'] = 'Windows実行ファイル';
$filetypes['ttf'] = 'True type フォント';
$filetypes['html'] = $filetypes['htm'] = 'HTMLドキュメント';
$filetypes['jpg'] = $filetypes['jpeg'] = 'イメージ';
$filetypes['gif'] = 'GIFイメージ';
$filetypes['bmp'] = 'ビットマップイメージ';
$filetypes['tif'] = 'tifイメージ';
$filetypes['png'] = 'PNGイメージ';
$filetypes['php'] = 'PHPスクリプト';
$filetypes['ics'] = 'カレンダー情報';
$filetypes['vcf'] = 'Contact information';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'サウンドファイル';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'ビデオファイル';
$filetypes['pdf'] = 'Adobe Acrobat PDF';
$filetypes['doc'] = $filetypes['dot'] = 'Microsoft Word ドキュメント';
$filetypes['psd'] = 'Adobe Photoshop ファイル';
$filetypes['rtf'] = 'リッチテキスト形式';
$filetypes['swf'] = 'Macromedia Flash ムービー';
$filetypes['fla'] = 'Macromedia Flash ドキュメント (ソース)';
$filetypes['xls'] = $filetypes['xlt'] = 'Microsoft Excel 形式';
$filetypes['ai'] = 'Adobe Illustrator ファイル';
