<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('filetypes'));

$filetypes['unknown'] = 'Okänd filtyp';
$filetypes['txt'] = 'Textfil';
$filetypes['sxw'] = 'OpenOffice.Org Writer dokument';
$filetypes['doc'] = 'Microsoft Word dokument';
$filetypes['xls'] = 'Microsoft Excel kalkylark';
$filetypes['mdb'] = 'Microsoft Access databas';
$filetypes['ppt'] = $filetypes['pps'] = 'Microsoft Powerpoint presentation';
$filetypes['sxc'] = 'OpenOffice.Org Calc kalkylark';
$filetypes['tar'] = 'Tar arkiv';
$filetypes['zip'] = 'ZIP komprimerat arkiv';
$filetypes['rar'] = 'RAR komprimerat arkiv';
$filetypes['gz'] = $filetypes['tgz'] = 'GZIP komprimerat arkiv';
$filetypes['bz2'] = 'BZIP2 komprimerat arkiv'; 
$filetypes['pdf'] = 'PDF dokument';
$filetypes['exe'] = 'Windows exekverbar fil';
$filetypes['ttf'] = 'True type font';
$filetypes['html'] = $filetypes['htm'] = 'HTML dokument';
$filetypes['jpg'] = $filetypes['jpeg'] = 'Bild';
$filetypes['gif'] = 'Bild';
$filetypes['bmp'] = 'Bild';
$filetypes['tif'] = 'Bild';
$filetypes['png'] = 'Bild';
$filetypes['php'] = 'PHP Skript';
$filetypes['ics'] = 'Kalender information';
$filetypes['vcf'] = 'Kontakt information';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = $filetypes['wma'] = 'Ljud fil';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'Video klipp';
