<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='تسجيل العلامه';
$bm_new_window='فتح العلامه فى نافذة جديدة';
$bm_current_page='الصفحه الحاليه';
$bm_no_bookmarks='انت لاتملك عناوين';
$bm_catagory_exists='الفئة بهذا الاسم بالفعل';
$bm_private='خاص';
$bm_catagory_other='الاخر';
$bm_add_bookmark='علامه جديدة';
$bm_add_catagory='فئة جديدة';
$bm_no_bookmarks_in_catagory='لايوجد علامات تم العثور عليها فى هذة الفئه';
$bm_catagory='الفئة';
$bm_no_select='انت لم تختر اى علامات';
$bm_bookmarks='علامات';
$bm_and_all_contents='جميع المحتويات';
$bm_copy_read_permissions='Copy read permissions to bookmarks';
$bm_copy_write_permissions='Copy write permissions to bookmarks';
$bm_move_to_catagory='تنتقل الاشارات المرجعيه الى الفئة المختاره';
?>