<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Desa l\'adreça d\'interès';
$bm_new_window='Obre l\'adreça d\'interès en una nova finestra.';
$bm_current_page='Pàgina actual';
$bm_no_bookmarks='No teniu cap adreça d\'interès.';
$bm_catagory_exists='Ja existeix una categoria amb aquest nom';
$bm_private='Privat';
$bm_catagory_other='Un altre';
$bm_add_bookmark='Nova adreça d\'interès';
$bm_add_catagory='Nova categoria';
$bm_no_bookmarks_in_catagory='No s\'ha trobat cap adreça d\'interès dins d\'aquesta categoria';
$bm_catagory='Categoria';
$bm_no_select='No heu seleccionat cap adreça d\'interès';
$bm_bookmarks='adreces d\'interès';
$bm_and_all_contents='i tot el contingut';
$bm_copy_read_permissions='Copia els permisos de lectura a les adreces d\'interès';
$bm_copy_write_permissions='Copia els permisos d\'escriptura a les adreces d\'interès';
$bm_move_to_catagory='Mou les adreces d\'interès seleccionades a la categoria...';
?>