<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Uložit odkaz";
$bm_new_window = "Otevřít odkaz v novém okně.";
$bm_current_page = "Tato stránka";
$bm_no_bookmarks = "Nemáte žádné odkazy.";

//2.03
$bm_catagory_exists = 'Kategorie tohoto jména už existuje';
$bm_private = 'Soukromé';
$bm_catagory_other = 'Ostatní';
$bm_add_bookmark = 'Nový odkaz';
$bm_add_catagory = 'Nová kategorie';
$bm_no_bookmarks_in_catagory = 'V této kategorii nejsou žádné odkazy';
$bm_catagory = 'Kategorie';
$bm_no_select = 'Nezvolil jste žádný odkaz';

$bm_bookmarks = 'odkazy';
$bm_and_all_contents = 'a všechen obsah';

$bm_copy_read_permissions = 'Kopírovat práva ke čtení do odkazů';
$bm_copy_write_permissions = 'Kopírovat práva k zápisu do odkazů';

$bm_move_to_catagory = 'Přesunout zvolené odkazy do kategorie...';
