<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Gem bogmærke";
$bm_new_window = "Åben i nyt vindue.";
$bm_current_page = "Aktuel side";
$bm_no_bookmarks = "Du har ingen bogmærker.";

//2.03
$bm_catagory_exists = 'En kategori ved det navn eksisterer allerede';
$bm_private = 'Privat';
$bm_catagory_other = 'Andre';
$bm_add_bookmark = 'Nyt bogmærke';
$bm_add_catagory = 'Ny kategori';
$bm_no_bookmarks_in_catagory = 'Ingen bogmærker fundet i denne kategori';
$bm_catagory = 'Kategori';
$bm_no_select = 'Du har ikke valgt nogen bogmærker';

$bm_bookmarks = 'bogmærker';
$bm_and_all_contents = 'og alt indhold';

$bm_copy_read_permissions = 'Kopier læserettigheder til bogmærker';
$bm_copy_write_permissions = 'Kopier skriverettigheder til bogmærker';

$bm_move_to_catagory = 'Flyt valgte bogmærker til kategori...';
