<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Lesezeichen speichern';
$bm_new_window='Lesezeichen in einem neuen Fenster öffnen.';
$bm_current_page='Aktuelle Seite';
$bm_no_bookmarks='Sie haben keine Lesezeichen';
$bm_catagory_exists='Eine Kategorie mit diesem Namen existiert bereits';
$bm_private='Privat';
$bm_catagory_other='Andere';
$bm_add_bookmark='Neues Lesezeichen';
$bm_add_catagory='Neue Kategorie';
$bm_no_bookmarks_in_catagory='In dieser Kategorie wurden keine Lesezeichen gefunden';
$bm_catagory='Kategorie';
$bm_no_select='Sie haben keine Lesezeichen ausgewählt';
$bm_bookmarks='Lesezeichen';
$bm_and_all_contents='und die gesamten Inhalte';
$bm_copy_read_permissions='Kopiere Leseberechtigungen zum Lesezeichen';
$bm_copy_write_permissions='Kopiere Schreibberechtigungen zum Lesezeichen';
$bm_move_to_catagory='Verschiebe ausgewählte Lesezeichen in Kategorie...';
?>