<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Save Bookmark";
$bm_new_window = "Open bookmark in a new window.";
$bm_current_page = "Current page";
$bm_no_bookmarks = "You don't have any bookmarks.";

//2.03
$bm_catagory_exists = 'A catagory with this name already exists';
$bm_private = 'Private';
$bm_catagory_other = 'Other';
$bm_add_bookmark = 'New bookmark';
$bm_add_catagory = 'New category';
$bm_no_bookmarks_in_catagory = 'No bookmarks were found in this category';
$bm_catagory = 'Category';
$bm_no_select = 'U didn\'t select any bookmarks';

$bm_bookmarks = 'bookmarks';
$bm_and_all_contents = 'and all contents';

$bm_copy_read_permissions = 'Copy read permissions to bookmarks';
$bm_copy_write_permissions = 'Copy write permissions to bookmarks';

$bm_move_to_catagory = 'Move selected bookmarks to category...';
