<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Guardar favorito';
$bm_new_window='Abrir el favorito en una nueva ventana.';
$bm_current_page='Página actual';
$bm_no_bookmarks='No tiene ningún favorito.';
$bm_catagory_exists='Ya existe una categoría con este nombre';
$bm_private='Privado';
$bm_catagory_other='Otro';
$bm_add_bookmark='Nuevo favorito';
$bm_add_catagory='Nueva categoría';
$bm_no_bookmarks_in_catagory='No se han encontrado favoritos dentro de esta categoría';
$bm_catagory='Categoría';
$bm_no_select='No ha seleccionado ningún favorito';
$bm_bookmarks='favoritos';
$bm_and_all_contents='y todo su contenido';
$bm_copy_read_permissions='Copiar los permisos de lectura a favoritos';
$bm_copy_write_permissions='Copiar los permisos de escritura a favoritos';
$bm_move_to_catagory='Mover los favoritos seleccionados a la categoría...';
?>