<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Talleta suosikki sivu";
$bm_new_window = "Avaa suosikki sicvu uuteen ikkunaan.";
$bm_current_page = "Nykyinen sivu";
$bm_no_bookmarks = "Sinulla ei ole suosikki sivuja.";

//2.03
$bm_catagory_exists = 'Tällä nimellä oleva kategoria on jo olemassa';
$bm_private = 'Yksityinen';
$bm_catagory_other = 'Muu';
$bm_add_bookmark = 'Uusi suosikki';
$bm_add_catagory = 'Uusi kategoria';
$bm_no_bookmarks_in_catagory = 'Suosikki sivuja ei löytynyt tästä kategoriasta';
$bm_catagory = 'Kategoria';
$bm_no_select = 'Et valinnnut suosikki sivua';

$bm_bookmarks = 'suosikit';
$bm_and_all_contents = 'ja kaikki sisältö';

$bm_copy_read_permissions = 'Kopioi lukuoikeus suosikkeihin';
$bm_copy_write_permissions = 'Kopioi kirjoitusoikeus suosikkeihin';

$bm_move_to_catagory = 'Siirrä valittu suosikki sivu kategoriaan...';
