<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Hozzáadás a kedvencekhez';
$bm_new_window='Hivatkozás megnyitása új ablakban';
$bm_current_page='Aktuális oldal';
$bm_no_bookmarks='Nincsenek kedvencek.';
$bm_catagory_exists='Ilyen néven már létezik kategória';
$bm_private='Magánjellegű';
$bm_catagory_other='Egyéb';
$bm_add_bookmark='Új kedvenc hozzáadása';
$bm_add_catagory='Új kategória';
$bm_no_bookmarks_in_catagory='Ebben a kategóriában nem találtam kedvenceket';
$bm_catagory='Kategória';
$bm_no_select='Nem választott ki egyetlen kedvencet sem';
$bm_bookmarks='kedvencek';
$bm_and_all_contents='és minden tartalom';
$bm_copy_read_permissions='Olvasási jogok másolása a kedvencekhez';
$bm_copy_write_permissions='Írási jogok másolása a kedvencekhez';
$bm_move_to_catagory='A kiválasztott kedvencek áthelyezése a megadott kategóriába...';
?>