<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Salva segnalibro';
$bm_new_window='Apri il segnalibro in una nuova finestra.';
$bm_current_page='pagina corrente';
$bm_no_bookmarks='Non hai nessun segnalibro.';
$bm_catagory_exists='Una categoria con questo nome esiste già';
$bm_private='Privato';
$bm_catagory_other='Altro';
$bm_add_bookmark='Nuovo segnalibro';
$bm_add_catagory='Nuova categoria';
$bm_no_bookmarks_in_catagory='Nessun segnalibro trovato per questa categoria';
$bm_catagory='Catagoria';
$bm_no_select='Non hai scelto nessun segnalibro';
$bm_bookmarks='segnalibri';
$bm_and_all_contents='e tutto il contenuto';
$bm_copy_read_permissions='Copia i permessi di lettura nei segnalibri';
$bm_copy_write_permissions='Copia i permessi di scrittura nei segnalibri';
$bm_move_to_catagory='Sposta i segnalibri selezionati nella categoria...';
?>