<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "ブックマークを保存";
$bm_new_window = "新しいウィンドウでブックマークを開く";
$bm_current_page = "現在のページ";
$bm_no_bookmarks = "ブックマークはありません。";

//2.03
$bm_catagory_exists = '同じ名前のカテゴリが存在します。';
$bm_private = 'プライベート';
$bm_catagory_other = 'そのほか';
$bm_add_bookmark = '新しいブックマーク';
$bm_add_catagory = '新しいカテゴリ';
$bm_no_bookmarks_in_catagory = 'このカテゴリにブックマークはありません。';
$bm_catagory = 'カテゴリ';
$bm_no_select = 'ブックマークが選択されていません。';

$bm_bookmarks = 'ブックマーク';
$bm_and_all_contents = 'とすべてのコンテンツ';

$bm_copy_read_permissions = 'ブックマークに読込権限をコピーする';
$bm_copy_write_permissions = 'ブックマークに書込権限をコピーする';

$bm_move_to_catagory = '選択されたカテゴリは移動しました・・・';
