<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Bladwijzer Opslaan';
$bm_new_window='Open bladwijzer in een nieuw venster';
$bm_current_page='Huidige pagina';
$bm_no_bookmarks='Geen bladwijzers gevonden';
$bm_catagory_exists='Er bestaat al een categorie met deze naam';
$bm_private='Privé';
$bm_catagory_other='Overige';
$bm_add_bookmark='Nieuwe bladwijzer';
$bm_add_catagory='Nieuwe categorie';
$bm_no_bookmarks_in_catagory='Geen bladwijzers gevonden in deze categorie';
$bm_catagory='Categorie';
$bm_no_select='U heeft geen bladwijzers geselecteerd';
$bm_bookmarks='favorieten';
$bm_and_all_contents='en alle inhoud';
$bm_copy_read_permissions='Kopiëer leesrechten naar bladwijzers';
$bm_copy_write_permissions='Kopiëer schrijfrechten naar bladwijzers';
$bm_move_to_catagory='Verplaats geselecteerde bladwijzers naar categorie...';
