<?php
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Salvar Favorito";
$bm_new_window = "Abrir Favoritos em uma nova janela.";
$bm_current_page = "Página atual";
$bm_no_bookmarks = "Você tem bookmarks.";

//2.03
$bm_catagory_exists = 'Já existe uma categoria com este nome';
$bm_private = 'Particular';
$bm_catagory_other = 'Outra';
$bm_add_bookmark = 'Novo favorito';
$bm_add_catagory = 'Nova categoria';
$bm_no_bookmarks_in_catagory = 'Não foram encontrados favoritos nesta categoria';
$bm_catagory = 'Categoria';
$bm_no_select = 'Você selecionou nenhum favorito';

$bm_bookmarks = 'favoritos';
$bm_and_all_contents = 'e todo o seu conteúdo';

$bm_copy_read_permissions = 'Permissão para ler';
$bm_copy_write_permissions = 'Permissão para alterar';

$bm_move_to_catagory = 'Mover favorito selecinado para a categoria...';
