<?php
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Guadar Favorito";
$bm_new_window = "Abrir favoritos numa nova janela";
$bm_current_page = "Página actual";
$bm_no_bookmarks = "Sem favoritos";

//2.03
$bm_catagory_exists = 'Já existe uma categoria com este nome';
$bm_private = 'Privado';
$bm_catagory_other = 'Outro';
$bm_add_bookmark = 'Novo Favorito';
$bm_add_catagory = 'Nova Categoria';
$bm_no_bookmarks_in_catagory = 'Não há favoritos nesta categoria';
$bm_catagory = 'Categoria';
$bm_no_select = 'Não seleccionou qualquer favorito';

$bm_bookmarks = 'favoritos';
$bm_and_all_contents = 'e todos os conteúdos';

$bm_copy_read_permissions = 'Copiar permissão de leitura para favoritos';
$bm_copy_write_permissions = 'Copiar permissão de escrita para favoritos';

$bm_move_to_catagory = 'Mover favoritos seleccionados para a categoria...';
