<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Сохранить ссылки";
$bm_new_window = "Открыть закладку в новом окне.";
$bm_current_page = "Текущая страница";
$bm_no_bookmarks = "Вы не имеете ни одной закладки.";

//2.03
$bm_catagory_exists = 'Категория с таким именем уже существует';
$bm_private = 'Частное';
$bm_catagory_other = 'Другое';
$bm_add_bookmark = 'Новая закладка';
$bm_add_catagory = 'Новая категория';
$bm_no_bookmarks_in_catagory = 'Нет закладок в данной категории';
$bm_catagory = 'Категория';
$bm_no_select = 'Вы не выбрали закладку';

$bm_bookmarks = 'закладки';
$bm_and_all_contents = 'и все входящие';

$bm_copy_read_permissions = 'Копировать права на чтение на закладки';
$bm_copy_write_permissions = 'Копировать права на запись на закладки';

$bm_move_to_catagory = 'Переместить выбранные закладки в категорию...';
