<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Shrani zaznamek';
$bm_new_window='Odpri zaznamek v novem oknu';
$bm_current_page='Trenutna stran';
$bm_no_bookmarks='Nimate zaznamkov';
$bm_catagory_exists='Kategorija s tem imenom že obstaja';
$bm_private='Zasebno';
$bm_catagory_other='Ostalo';
$bm_add_bookmark='Nov zaznamek';
$bm_add_catagory='Nova kategorija';
$bm_no_bookmarks_in_catagory='V tej kategoriji ni zaznamkov';
$bm_catagory='Kategorija';
$bm_no_select='Niste izbrali zaznamkov';
$bm_bookmarks='Zaznamki';
$bm_and_all_contents='In vsi stiki';
$bm_copy_read_permissions='Kopiraj dovoljenje za branje v zaznamke';
$bm_copy_write_permissions='Kopiraj dovoljenje za pisanje v zaznamke';
$bm_move_to_catagory='Premakni izbrane zaznamke v kategorijo...';
?>