<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "Spara bokmärke";
$bm_new_window = "Öppna bokmärke i ett nytt fönster.";
$bm_current_page = "aktuell sida";
$bm_no_bookmarks = "Du har inga bokmärken.";

//2.03
$bm_catagory_exists = 'En kategori med detta namn existerar redan';
$bm_private = 'Privat';
$bm_catagory_other = 'Annan';
$bm_add_bookmark = 'Nytt bokmärke';
$bm_add_catagory = 'Ny kategori';
$bm_no_bookmarks_in_catagory = 'Inga bokmärken hittades i denna kategori';
$bm_catagory = 'Kategori';
$bm_no_select = 'Du valde inga bokmärken';

$bm_bookmarks = 'bokmärken';
$bm_and_all_contents = 'och allt innehåll';

$bm_copy_read_permissions = 'Kopiera läsrättigheter till bokmärken';
$bm_copy_write_permissions = 'Kopiera skrivrättigheter till bokmärken';

$bm_move_to_catagory = 'Flytta valda bokmärken till kategori...';
