<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));

$bm_save_title = "บันทึกเว็บโปรด";
$bm_new_window = "เปิดเว็บโปรดหน้าใหม่";
$bm_current_page = "หนังปัจจุบัน";
$bm_no_bookmarks = "คุณยังไม่มีเว็บโปรด";

//2.03
$bm_catagory_exists = 'ชื่อหมวดหมู่ซ้ำกัน';
$bm_private = 'ส่วนตัว';
$bm_catagory_other = 'อื่นๆ';
$bm_add_bookmark = 'สร้างลิ้งค์ใหม่';
$bm_add_catagory = 'สร้างหมวดหมู่ใหม่';
$bm_no_bookmarks_in_catagory = 'ไม่พบเว็บโปรดในหมวดหมู่นี้';
$bm_catagory = 'หมวดหมู่';
$bm_no_select = 'คุณยังไม่ได้เลือกเว็บโปรด';

$bm_bookmarks = 'เว็บโปรด';
$bm_and_all_contents = 'และหัวข้อทั้งหมด';

$bm_copy_read_permissions = 'ก็อบปี้ เพอมิสชั่นของการอ่านไปยังเว็บโปรด';
$bm_copy_write_permissions = 'ก็อบปี้ เพอมิสชั่นของการเขียนไปยังเว็บโปรด';

$bm_move_to_catagory = 'ย้ายเว็บโปรดที่เลือกไปยังหมวดหมู่...';
