<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('bookmarks'));
$bm_save_title='Favorilere kaydet';
$bm_new_window='Sayfayı yeni pencerede aç.';
$bm_current_page='Şu anki sayfa';
$bm_no_bookmarks='Kayıtlı hiç favori yok.';
$bm_catagory_exists='Bu isimde bir kategori zaten mevcut';
$bm_private='Özel';
$bm_catagory_other='Diğer';
$bm_add_bookmark='Yeni favori';
$bm_add_catagory='Yeni kategori';
$bm_no_bookmarks_in_catagory='Bu kategoride hiç favori yok';
$bm_catagory='Kategori';
$bm_no_select='Hiçbir sık favori seçmediniz';
$bm_bookmarks='favoriler';
$bm_and_all_contents='ve tüm içerikler';
$bm_copy_read_permissions='Okuma haklarını favorilere kopyala';
$bm_copy_write_permissions='Yazma haklarını favorilere kopyala';
$bm_move_to_catagory='Seçilen favorileri kategoriye taşı...';
?>