<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Изберете потребителите и групите които искате да бъдат видими за.";

//security
$security_text = "Въведете вашата парола и полетата които искате да промените и след това натиснете 'Запис'.";
$security_current_password = "Текуща парола";
$security_new_password = "Нова парола";
$security_confirm_password = "Потвърди парола";
$security_new_authcode = "Нов код за авторизация";
$security_confirm_authcode = "Потвърдете кода за авторизация";
$security_question = "Секретен въпрос";
$security_answer = "Отговор";
$security_wrong_password = "Загубена парола.";
$security_tasks = "Задачите изпълнени";
$security_password_update = "Паролата е обновена.";
$security_authcode_update = "Кодовете за авторизация обновени.";
$security_question_update = "Въпрос и отговор обновени.";
$security_question_fail = "Не сте попълнили въпроса и отговора.";

$acProfile = "Профил";
$acSecurity = "Сигурност";
$acPrivacy = "Дискретност";
$acManager = "Вашата сметка";
$acStatistics = "Статистика";
$acProfileText = "Натиснете 'Запис' за да смените вашия профил.Полетата отбелязани със * са задължителни.";
$acTitle = "Вашата сметка";
$ac_login_info = "Информация за влизането";
$ac_registration_time = "Време на регистрацията";
$ac_lastlogin = "Последно влизане";
$ac_logins = "Общо влизания";
$ac_disk_usage = "Използваемост на диска";
$ac_max_diskspace = "Максимално дисково пространство";
$ac_available_diskspace = "Налично дисково пространство";
$ac_used_diskspace = "Използвано дисково пространство";
$ac_used = "използвано";

//translation required
$ac_add_user = 'Искане на авторизация';
$ac_auth_error = 'Настъпила е грешка по време на авторизация.Моля опитайте отново.';
$ac_auth_success = 'Вашата сметка е вече видима за този потребител и му е изпратено съобщение,че сте приели неговото искане.';
$ac_auth_decline = 'Изпратено е съобщение на този потребител,че сте отказали неговото искане.';
$ac_auth_accept_mail_title = 'Искането за авторизация на Група-Офис е прието';
$ac_auth_decline_mail_title = 'Искането за авторизация на Група-Офис не е прието';
$ac_salutation = 'Уважаеми Господине/Госпожо';
$ac_auth_accept_mail_body = 'прие вашето искане да направи неговата сметка видима за вас.';
$ac_auth_decline_mail_body = 'не прие вашето искане да направи неговата сметка видима за вас.';
$ac_request_auth = 'иска вашето разрешение да направите вашата сметка видима. Искате ли да направите вашата сметка видима за този потребител?';
$ac_request_auth_mail_title ='Искане за авторизация на Група-Офис';
$ac_invalid_email = 'E-mail адресъте който сте въвели не е регистриран в системата. Моля опитайте отново.';
$ac_request_mail_body_prefix = 'Изпратено е съобщение до ';
$ac_request_mail_body_suffix = 'иска се неговото разрешение да направи неговата сметка видима за вас.';
$ac_auth_text = 'Въведете e-mail адреса от потребителя чиято сметка искате да направите видима.';

$ac_accept = 'Приемам';
$ac_decline = 'Отказвам';
