<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Vyberte uživatele a skupiny, kterým se chcete zviditelnit."; 

//security
$security_text = "Zadejte vaše heslo a pole, které chcete změnit a klikněte na Ulož.";
$security_current_password = "Aktuální heslo";
$security_new_password = "Nové heslo";
$security_confirm_password = "Potvrdit heslo";
$security_new_authcode = "Nový přístupový kód";
$security_confirm_authcode = "Potvrdit přístupový kód";
$security_question = "Tajná otázka";
$security_answer = "Odpověď";
$security_wrong_password = "Špatné heslo.";
$security_tasks = "Úlohy byly ukončeny";
$security_password_update = "Heslo bylo aktualizováno.";
$security_authcode_update = "Přístupový kód byl aktualizován.";
$security_question_update = "Otázky a odpovědi byly aktualizovány.";
$security_question_fail = "Nevyplnil jste otázku a odpověď.";

$acProfile = "Profil";
$acSecurity = "Zabezpečení";
$acPrivacy = "Soukromí";
$acManager = "Váš účet";
$acStatistics = "Statistiky";
$acProfileText = "Klikněte na Ulož pro změnu vašeho profilu. Pole označená * jsou nezbytná.";
$acTitle = "Váš účet";
$ac_login_info = "Informace k přihlášení";
$ac_registration_time = "Čas registrace";
$ac_lastlogin = "Poslední přihlášení";
$ac_logins = "Celkový součet přihlášení";
$ac_disk_usage = "Využitelnost disku";
$ac_max_diskspace = "Maximum místa na Disku";
$ac_available_diskspace = "Volné místo na disku";
$ac_used_diskspace = "Použité místo na disku";
$ac_used = "použité";

//translation required
$ac_add_user = 'Požadavek k autorizaci';
$ac_auth_error = 'Během autorizace se stala chyba. Prosím zkuste to znovu.';
$ac_auth_success = 'Váš účet je zpřístupněn a zpráva byla zaslána tomu uživateli, u kterého jste akceptoval jeho požadavek.';
$ac_auth_decline = 'Zpráva byla zaslána tomu uživateli, který odepřel jeho požadavek.';
$ac_auth_accept_mail_title = 'Group-Office požadavek k autorizaci přijat';
$ac_auth_decline_mail_title = 'Group-Office pžadavek k autorizaci odepřen';

$ac_auth_accept_mail_body = 'akceptoval váš požadavek na zpřístupnění jeho účtu.';
$ac_auth_decline_mail_body = 'odepřel váš požadavek na zpřístupnění jeho účtu.';
$ac_request_auth = 'Chcete tomuto uživateli zpřístupnit váš účet?';
$ac_request_auth_mail_title ='Group-Office pžadavek na autorizaci';
$ac_invalid_email = 'Vámi zadaná e-mailová adresa není v systému. Prosím zkuste to znovu.';
$ac_request_mail_body_prefix = 'Zpráva byla poslána ';
$ac_request_mail_body_suffix = 'žádá práva pro pro přístup k informacím z Vašeho účtu.';
$ac_auth_text = 'Zadejte e-mailovou adresu uživatele, jehož účet chcete zpřístupnit.';

$ac_accept = 'přijmout';
$ac_decline = 'odepřít';
$ac_salutation = 'Vážení';
