<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Vælg de brugere og grupper din konto skal være synlig for.";

//security
$security_text = "Indtast din adgangskode og de felter du vil ændre og klik på 'Gem'.";
$security_current_password = "Nuværende adgangskode";
$security_new_password = "Ny adgangskode";
$security_confirm_password = "Bekræft adgangskode";
$security_new_authcode = "Ny autorisationskode";
$security_confirm_authcode = "Bekræft autorisationskode";
$security_question = "Hemmeligt spørgsmål";
$security_answer = "Svar";
$security_wrong_password = "Forkert adgangskode.";
$security_tasks = "Handling udført";
$security_password_update = "Adgangskode opdateret.";
$security_authcode_update = "Autorisationskoder opdateret.";
$security_question_update = "Spørgsmål og svar opdateret.";
$security_question_fail = "Du skal indtaste både spørgsmålet og svaret.";

$acProfile = "Profil";
$acSecurity = "Sikkerhed";
$acPrivacy = "Personoplysninger";
$acManager = "Din konto";
$acStatistics = "Statistik";
$acProfileText = "Klik på 'Gem' for at gemme din profil. Felterne markeret med * skal udfyldes.";
$acTitle = "Din konto";
$ac_login_info = "Login information";
$ac_registration_time = "Oprettet";
$ac_lastlogin = "Sidste login";
$ac_logins = "Totalt antal logins";
$ac_disk_usage = "Disk forbrug";
$ac_max_diskspace = "Maksimal diskplads";
$ac_available_diskspace = "Tilgængelig diskplads";
$ac_used_diskspace = "Forbrugt diskplads";
$ac_used = "brugt";

$ac_add_user = 'Anmod om autorisation';
$ac_auth_error = 'Der opstod en fejl under autorisationen. Prøv venligst igen.';
$ac_auth_success = 'Din konto er nu synlig for denne bruger og en besked om at du accepterede anmodningen er sendt til brugeren.';
$ac_auth_decline = 'En besked om at du har afslået anmodningen er sendt til denne bruger.';
$ac_auth_accept_mail_title = 'Group-Office autorisationsanmodning accepteret';
$ac_auth_decline_mail_title = 'Group-Office autorisationsanmodning afslået';

$ac_auth_accept_mail_body = 'har godkendt din anmodning om at gøre hans konto synlig for dig.';
$ac_auth_decline_mail_body = 'har afslået din anmodning om at gøre hans konto synlig for dig.';
$ac_request_auth = 'anmoder om din tilladelse til at gøre din konto synlig. Ønsker du at gøre din konto synlig for denne bruger?';
$ac_request_auth_mail_title ='Group-Office autorisationsanmodning';
$ac_invalid_email = 'Email addressen du indtastede er ikke registreret i systemet. Prøv venligst igen.';
$ac_request_mail_body_prefix = 'En besked blev sendt til ';
$ac_request_mail_body_suffix = 'anmoder om tilladelse til at gøre hans konto synlig for dig.';
$ac_auth_text = 'Indtast e-mail adressen for brugeren hvis konto du ønsker at gøre synlig.';

$ac_accept = 'Godkend';
$ac_decline = 'Afslå';
$ac_salutation = 'Kære';
