<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Select the users and groups that you want to be visible to.";

//security
$security_text = "Enter your password and the fields you want to change and click on 'Save'.";
$security_current_password = "Current password";
$security_new_password = "New password";
$security_confirm_password = "Confirm password";
$security_new_authcode = "New authorisation code";
$security_confirm_authcode = "Confirm authorisation code";
$security_question = "Secret question";
$security_answer = "Answer";
$security_wrong_password = "Wrong password.";
$security_tasks = "Tasks completed";
$security_password_update = "Password updated.";
$security_authcode_update = "Authorisation codes updated.";
$security_question_update = "Question and answer updated.";
$security_question_fail = "You didn't fill in both the question and the answer.";

$acProfile = "Profile";
$acSecurity = "Password";
$acPrivacy = "Privacy";
$acManager = "Your Account";
$acStatistics = "Statistics";
$acProfileText = "Click on 'Save' to change your profile. The fields marked with a * are required.";
$acTitle = "Your Account";
$ac_login_info = "Login information";
$ac_registration_time = "Registration time";
$ac_lastlogin = "Last login";
$ac_logins = "Total logins";
$ac_disk_usage = "Disk Usage";
$ac_max_diskspace = "Maximum Diskspace";
$ac_available_diskspace = "Available Diskspace";
$ac_used_diskspace = "Used Diskspace";
$ac_used = "used";

//translation required
$ac_add_user = 'Request Authorization';
$ac_auth_error = 'An error occured while authorizing. Please try again.';
$ac_auth_success = 'Your account is now visible to this user and a message has been sent to this user that you accepted his request.';
$ac_auth_decline = 'A message has been sent to this user that you have declined his request.';
$ac_auth_accept_mail_title = 'Group-Office authorization request accepted';
$ac_auth_decline_mail_title = 'Group-Office authorization request denied';

$ac_auth_accept_mail_body = 'has accepted your request to make his account visible to you.';
$ac_auth_decline_mail_body = 'has declined your request to make his account visible to you.';
$ac_request_auth = 'requests your permission to make your account visible. Do you want to make your account visible to this user?';
$ac_request_auth_mail_title ='Group-Office authorization request';
$ac_invalid_email = 'The e-mail address you entered is not registered in the system. Please try again.';
$ac_request_mail_body_prefix = 'A message was sent to ';
$ac_request_mail_body_suffix = 'requesting his permission to make his account visible to you.';
$ac_auth_text = 'Enter the e-mail address from the user who\'s account you want to make visible.';

$ac_accept = 'Accept';
$ac_decline = 'Decline';
$ac_salutation = 'Dear';

$groups_you_are_in = 'You are a member of the following user groups';
