<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Seleccione los usuarios y grupos para los que quiere ser visible.";

//security
$security_text = "Introduzca su clave y los campos que usted desea cambiar y haga click en 'Grabar'.";
$security_current_password = "Contraseña actual";
$security_new_password = "Nueva contraseña";
$security_confirm_password = "Confirme contraseña";
$security_new_authcode = "Nuevo código de autorización";
$security_confirm_authcode = "Confirme el código de autorización";
$security_question = "Pregunta secreta";
$security_answer = "Respuesta";
$security_wrong_password = "Contraseña incorrecta.";
$security_tasks = "Tareas completadas";
$security_password_update = "Contraseña actualizada.";
$security_authcode_update = "Códigos de autorización actualizados.";
$security_question_update = "Pregunta y respuesta actualizadas.";
$security_question_fail = "No ha introducido la pregunta y la respuesta.";

$acProfile = "Perfil";
$acSecurity = "Contraseña";
$acPrivacy = "Privacidad";
$acManager = "Su Cuenta";
$acStatistics = "Estadísticas";
$acProfileText = "Haga click en 'Grabar' para cambiar su perfil. Los campos marcados con '*' son obligatorios.";
$acTitle = "Su Cuenta";
$ac_login_info = "Información de entrada";
$ac_registration_time = "Hora de entrada";
$ac_lastlogin = "Última entrada";
$ac_logins = "Total de entradas";
$ac_disk_usage = "Uso del disco";
$ac_max_diskspace = "Espacio de disco máximo";
$ac_available_diskspace = "Espacio de disco disponible";
$ac_used_diskspace = "Espacio de disco usado";
$ac_used = "usado";

//translation required
$ac_add_user = 'Requiere Autorización';
$ac_auth_error = 'Ha ocurrido un error mientras se autorizaba. Por favor, inténtelo de nuevo.';
$ac_auth_success = 'Su cuenta es ahora visible para este usuario y se le enviará un mensaje acceptando su petición.';
$ac_auth_decline = 'Un mensaje ha sido enviado a este usuario declinando su petición.';
$ac_auth_accept_mail_title = 'Group-Office - aceptada la petición de autorización';
$ac_auth_decline_mail_title = 'Group-Office - rechazada la petición de autorización';

$ac_auth_accept_mail_body = 'se ha aceptado su petición para que la cuenta sea visible para usted.';
$ac_auth_decline_mail_body = 'se ha rechazado su petición para que la cuenta sea visible para usted.';
$ac_request_auth = 'se pide su permiso para hacer visible su cuenta. ¿Desea hacer visible su cuenta para este usuario?';
$ac_request_auth_mail_title ='Group-Office - petición de autorización';
$ac_invalid_email = 'La dirección de correo electrónico que ha introducido no esta registrada en este sistema. Por favor, inténtelo de nuevo.';
$ac_request_mail_body_prefix = 'Un mensaje ha sido enviado a ';
$ac_request_mail_body_suffix = 'requiriendo hacer visible la cuenta por usted.';
$ac_auth_text = 'Introduzca la dirección de correo electrónico del usuario que desea hacerse visible.';

$ac_accept = 'Aceptar';
$ac_decline = 'Rechazar';
$ac_salutation = 'Estimado/a';
