<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Valitse ne käyttäjät ja ryhmät joille sinä häluat näkyä.";

//security
$security_text = "Kirjoita salasanasi ja ne kentät joita haluat muuttaa, paina sen jälkeen 'Talleta'.";
$security_current_password = "Nykyinen salasana";
$security_new_password = "Uusi salasana";
$security_confirm_password = "Varmista salasana";
$security_new_authcode = "Uusi auktorisointikoodi";
$security_confirm_authcode = "Varmista auktorisointikoodi";
$security_question = "Sala kysymys";
$security_answer = "Vastaus";
$security_wrong_password = "Väärä salasana.";
$security_tasks = "Tehtävä loppuunviety";
$security_password_update = "Salasana päivitetty.";
$security_authcode_update = "Auktorisointikoodit päivitetty.";
$security_question_update = "Kysymys ja vastaus päivitetty.";
$security_question_fail = "Et täyttänyt kysymystä ja vastausta.";

$acProfile = "Oma profiili";
$acSecurity = "Salasana";
$acPrivacy = "Yksityisyys";
$acManager = "Tilitiedot";
$acStatistics = "Tilastot";
$acProfileText = "Paina 'Talleta'muuttaaksesi profiiliasi. *:lla merkityt kentät ovat pakolliset.";
$acTitle = "Tilitiedot";
$ac_login_info = "Tilitiedot";
$ac_registration_time = "Rekisteröinti aika";
$ac_lastlogin = "Edellinen kirjautuminen";
$ac_logins = "Kirjautumis kertoja";
$ac_disk_usage = "Talletus tilan käyttö";
$ac_max_diskspace = "Talletus tila raja";
$ac_available_diskspace = "Käytettävä talletus tila";
$ac_used_diskspace = "Käytetty talletus tila";
$ac_used = "käytetty";

//translation required
$ac_add_user = 'Vaadi auktorisointi';
$ac_auth_error = 'Auktorisoinnissa tapahtui virhe. Yritä uudelleen.';
$ac_auth_success = 'Sinun tilisi näkyy nytt tälle käyttäjälle ja sanoma että olet hyväksynyt hänen pyyntönsä on lähetetty.';
$ac_auth_decline = 'Sanama että olet hylännyt tämän käyttäjän pyynnön on lähetetty.';
$ac_auth_accept_mail_title = 'Group-Office auktorisointi hyväksyttiin';
$ac_auth_decline_mail_title = 'Group-Office auktorisointia ei hyväksytty';

$ac_auth_accept_mail_body = 'on hyväksynyt pyyntöäsi tehdä tilinsä näkyväksi sinulle.';
$ac_auth_decline_mail_body = 'ei ole hyväksynyt pyyntöäsi tehdä tilinsä näkyväksi sinulle.';
$ac_request_auth = 'pyytää lupaasi tehdä tilisi näkyväksi tälle käyttäjälle?';
$ac_request_auth_mail_title ='Group-Office auktorisointi kysely';
$ac_invalid_email = 'Sähköposti osoitetta jonka kirjoitit ei ole rekisteröity järjestelmään. Yritä uudelleen.';
$ac_request_mail_body_prefix = 'Viesti lähetettiin ';
$ac_request_mail_body_suffix = 'kyselyllä tehdä hänen tilinsä näkyväksi sinulle.';
$ac_auth_text = 'Kirjoita näkyväksi halumasi tilin käyttäjän sähköpostiosoite.';

$ac_accept = 'Hyväksy';
$ac_decline = 'Kieltäydy';
$ac_salutation = 'Hyvä';
