<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

//co-Author (only corrections of orthography): j.s Hubert jsh@interlug.net
//13 aout 2007

require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Choisissez les utilisateurs et les groupes pour lesquels vous souhaitez être visible.";

//security
$security_text = "Entrez votre mot de passe et les champs que vous voulez changer et cliquez sur 'Enregistrer'.";
$security_current_password = "Mot de passe courant";
$security_new_password = "Nouveau mot de passe";
$security_confirm_password = "Confirmer le mot de passe";
$security_new_authcode = "Nouveau code d'autorisation";
$security_confirm_authcode = "Confirmer le code d'autorisation";
$security_question = "Question secrète";
$security_answer = "Réponse";
$security_wrong_password = "Mauvais mot de passe.";
$security_tasks = "Tâche terminée.";
$security_password_update = "Mot de passe modifié.";
$security_authcode_update = "Code d'autorisation modifié";
$security_question_update = "Question et réponse modifiées.";
$security_question_fail = "Vous n'avez pas renseigné la question et la réponse.";
$acProfile = "Profil";
$acSecurity = "Sécurité";
$acPrivacy = "Intimité";
$acManager = "Votre compte";
$acStatistics = "Statistiques";
$acProfileText = "Cliquez sur 'Enregistrer' pour changer votre profil. Les champs marqués d'une * sont obligatoires.";
$acTitle = "Votre compte";
$ac_login_info = "Information de connexion";
$ac_registration_time = "Heure d'enregistrement";
$ac_lastlogin = "Dernière connexion";
$ac_logins = "Nombre total de connexions";
$ac_disk_usage = "Utilisation du disque";
$ac_max_diskspace = "Taille maximum de l'espace disque";
$ac_available_diskspace = "Taille disponible sur l'espace disque";
$ac_used_diskspace = "Espace disque utilisé";
$ac_used = "utilisé";
$ac_add_user = 'Demande d\'autorisation';
$ac_auth_error = 'Une erreur est apparue pendant la demande d\'autorisation. Merci de recommencer.';
$ac_auth_success = 'Votre compte est maintenant visible pour cet utilisateur et un message lui a été envoyé lui indiquant que vous avez accepté sa requête.';
$ac_auth_decline = 'Un message a été envoyé à l\'utilisateur pour lequel vous avez décliné la requête.';
$ac_auth_accept_mail_title = 'Demande d\'autorisation de Group-Office acceptée';
$ac_auth_decline_mail_title = 'Demande d\'autorisation de Group-Office refusée';
$ac_auth_accept_mail_body = 'a accepté votre requête de vous rendre visible pour ce compte.';
$ac_auth_decline_mail_body = 'a refusé votre requête de vous rendre visible pour ce compte.';
$ac_request_auth = 'demande votre permission pour rendre votre compte visible... Voulez-vous rendre votre compte visible pour cet utilisateur ?';
$ac_request_auth_mail_title ='Demande d\'autorisation de Group-Office';
$ac_invalid_email = 'L\'adresse email que vous avez entré n\'est pas enregistré dans le système. Merci de recommencer.';
$ac_request_mail_body_prefix = 'Un message a été envoyé à ';
$ac_request_mail_body_suffix = 'demander sa permission de rendre son compte visible pour vous.';
$ac_auth_text = 'Entrez l\'adresse email de l\'utilisateur dont vous souhaitez voir le compte.';
$ac_accept = 'Accepter';
$ac_decline = 'Refuser';
$ac_salutation = 'Chèr(e)';
?>
