<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));
$htmldirection='rtl';
$charset='UTF-8';

//privacy
$privacy_text = "בחר/י את המשתמשים והקבוצות שברצונך להיות זמין להם";

//security
$security_text = "נא להזין את הסיסמה שלך ואת השדות שברצונך לשנות ואז ללחוץ על 'שמור'";
$security_current_password = "סיסמה נוכחית";
$security_new_password = "סיסמה חדשה";
$security_confirm_password = "אימות סיסמה";
$security_new_authcode = "קוד אישור חדש";
$security_confirm_authcode = "אימות קוד אישור";
$security_question = "שאלה סודית";
$security_answer = "תשובה";
$security_wrong_password = "סיסמה שגויה.";
$security_tasks = "המשימות הושלמו";
$security_password_update = "הסיסמה עודכנה.";
$security_authcode_update = "קוד אישור עודכן.";
$security_question_update = "השאלה והתשובה עודכנו.";
$security_question_fail = "לא מילית את שדות השאלה והתשובה";

$acProfile = "פרופיל";
$acSecurity = "אבטחה";
$acPrivacy = "פרטיות";
$acManager = "החשבון שלך";
$acStatistics = "סטטיסטיקה";
$acProfileText = "לחץ/י על 'שמור' לשמירת הפרופיל שלך. השדות המסומנים ב- * הינם שדות חובה";
$acTitle = "החשבון שלך";
$ac_login_info = "פרטי התחברות";
$ac_registration_time = "זמן הרשמה";
$ac_lastlogin = "כניסה אחרונה";
$ac_logins = "סך הכל כניסות";
$ac_disk_usage = "שטח דיסק בשימוש";
$ac_max_diskspace = "שטח דיסק מירבי";
$ac_available_diskspace = "שטח דיסק זמין";
$ac_used_diskspace = "שטח דיסק בשימוש";
$ac_used = "תפוס";

//translation required
$ac_add_user = 'בקשת אישור';
$ac_auth_error = 'חלה טעות בזמן בקשת האישור. נא לנסות שנית.';
$ac_auth_success = 'החשבון שלך זמין עכשיו למשתמש הזה ונשלחה הודעה למשתמש להודיע על אישור הבקשה';
$ac_auth_decline = 'נשלחה הודעה למשתמש על דחיית הבקשה';
$ac_auth_accept_mail_title = 'בקשת האישור של Group-Office התקבלה';
$ac_auth_decline_mail_title = 'בקשת האישור של Group-Office נדחתה';
$ac_auth_accept_mail_body = 'קיבל/ה את בקשתך להפוך את חשבונו/ה זמין לך';
$ac_auth_decline_mail_body = 'בקשתך נדחתה להפוך את חשבונו/ה זמין לך';
$ac_request_auth = 'מבקש/ת את אישורך להפוך את חשבונך זמין. האם ברצונך להפוך את חשבונך זמין למשתמש זה?';
$ac_request_auth_mail_title ='בקשת אישור Group-Office.';
$ac_invalid_email = 'כתובת הדואל שהכנסת לא רשומה במערכת. נא לנסות שנית.';
$ac_request_mail_body_prefix = 'הודעה נשלחה אל ';
$ac_request_mail_body_suffix = 'מבקש את אישור המשתמש להפוך את חשבונו זמין בשבילך';
$ac_auth_text = 'נא להכניס כתובת דואל של המשתמש שברצונך להפוך את חשבונו לזמין.';

$ac_accept = 'מסכים';
$ac_decline = 'לא מסכים';
$ac_salutation = 'יקירי/תי';
