<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "閲覧可能なユーザグループを選択";

//security
$security_text = "変更したパスワードを有効にするには「保存」を押してください。";
$security_current_password = "現在のパスワード";
$security_new_password = "新しいパスワード";
$security_confirm_password = "パスワードの確認";
$security_new_authcode = "新しい認証コード";
$security_confirm_authcode = "認証コードの確認";
$security_question = "質問を選ぶ";
$security_answer = "回答";
$security_wrong_password = "パスワードが違います。";
$security_tasks = "タスクは完了しました。";
$security_password_update = "パスワードがアップデートされました。";
$security_authcode_update = "認証コードがアップデートされました。";
$security_question_update = "質問と回答がアップデートされました。";
$security_question_fail = "質問と回答を入力していません。";

$acProfile = "プロフィール";
$acSecurity = "セキュリティ";
$acPrivacy = "プライバシー";
$acManager = "あなたのアカウント";
$acStatistics = "統計";
$acProfileText = "プロフィールを変更するために「保存」を押してください。 *のところは必須です。";
$acTitle = "あなたのアカウント";
$ac_login_info = "ログイン情報";
$ac_registration_time = "登録時間";
$ac_lastlogin = "最終ログイン";
$ac_logins = "総合ログイン";
$ac_disk_usage = "ディスク使用量";
$ac_max_diskspace = "最大ディスク容量";
$ac_available_diskspace = "使用可能なディスク容量";
$ac_used_diskspace = "使用しているディスク容量";
$ac_used = "使用済";

//translation required
$ac_add_user = '権限要求';
$ac_auth_error = '権限処理中にエラーが発生しました。やり直してください。';
$ac_auth_success = 'このユーザにはあなたのアカウント情報を公開しています。このユーザに許可したメッセージが送信されました。';
$ac_auth_decline = '要求を辞退したユーザにメッセージが送信されました';
$ac_auth_accept_mail_title = 'Group-Office 権限要求が許可されました';
$ac_auth_decline_mail_title = 'Group-Office 権限要求が拒否されました';

$ac_auth_accept_mail_body = 'は、アカウント情報の閲覧を許可する要求を受け付けました。';
$ac_auth_decline_mail_body = 'は、アカウント情報の閲覧を許可する要求を辞退しました。';
$ac_request_auth = 'は、アカウント情報の公開を希望しています。 このユーザにアカウント情報の閲覧を許可しますか?';
$ac_request_auth_mail_title ='Group-Office 権限要求';
$ac_invalid_email = '入力したE-mailアドレスはシステムに登録されていません。やり直してください。';
$ac_request_mail_body_prefix = 'メッセージが送信済み： ';
$ac_request_mail_body_suffix = 'アカウント情報を閲覧する権限付与の処理中です';
$ac_auth_text = 'アカウント情報を閲覧したいユーザのE-mailアドレスを入力してください。';

$ac_accept = '受ける';
$ac_decline = '辞退する';
$ac_salutation = 'Dear';
