<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Velg de brukere og grupper din konto skal være synlig for.";

//security
$security_text = "Tast inn din adgangskode og de felter du vil endre og klikk på 'Lagre'.";
$security_current_password = "Nåværende adgangskode";
$security_new_password = "Ny adgangskode";
$security_confirm_password = "Bekreft adgangskode";
$security_new_authcode = "Ny autorisajonskode";
$security_confirm_authcode = "Bekreft autorisasjonskode";
$security_question = "Hemmeligt spørsmål";
$security_answer = "Svar";
$security_wrong_password = "Feil adgangskode.";
$security_tasks = "Handling utført";
$security_password_update = "Adgangskode oppdatert.";
$security_authcode_update = "Autorisasjonskode oppdatert.";
$security_question_update = "Spørgsmål og svar oppdatert.";
$security_question_fail = "Du må sette inn både spørsmål og svar.";

$acProfile = "Profil";
$acSecurity = "Sikkerhet";
$acPrivacy = "Personlig beskyttelse";
$acManager = "Din konto";
$acStatistics = "Statistikk";
$acProfileText = "Klikk på 'Skjul' for å skjule din profil. Feltene markert med * må fylles ut.";
$acTitle = "Din konto";
$ac_login_info = "Login informasjon";
$ac_registration_time = "Opprettelsestidspunkt";
$ac_lastlogin = "Siste login";
$ac_logins = "Totalt antall logins";
$ac_disk_usage = "Disk forbruk";
$ac_max_diskspace = "Total diskforbruk";
$ac_available_diskspace = "Tilgjengelig diskplass";
$ac_used_diskspace = "Forbrukt diskplass";
$ac_used = "brukt";

$ac_add_user = 'Be om Autentisering';
$ac_auth_error = 'Det oppstod en feil under autentisering. Vennligst prøv igjen.';
$ac_auth_success = 'Din Konto er nå synligtil denne brukeren og en melding er blitt sendt til denne brukeren som du har godkjent.';
$ac_auth_decline = 'En melding er sendt som forklarer at du ikke har akseptert dennes ønske.';
$ac_auth_accept_mail_title = 'Group-Office autentisering godkjent';
$ac_auth_decline_mail_title = 'Group-Office autentisering avslått';
$ac_salutation = 'Kjære Hr/Frue';
$ac_auth_accept_mail_body = 'har godkjent ditt ønske om å gjøre dennes konto synlig for deg.';
$ac_auth_decline_mail_body = 'har avslått ditt ønske om å gjøre dennes konto synlig for deg.';
$ac_request_auth = 'ber deg om å gjøre din konto synlig for søkeren. Ønsker du å gjøre din konto synlig for denne brukeren?';
$ac_request_auth_mail_title ='Group-Office autentisering søknad';
$ac_invalid_email = 'E-post adressen du har skrevet er ikke funnet i systemet. Vennligst prøv igjen.';
$ac_request_mail_body_prefix = 'En melding er sendt til ';
$ac_request_mail_body_suffix = 'med ønsket om tillatelse å synlig gjøre sin konto til deg.';
$ac_auth_text = 'Skriv e-post adressen til den brukers konto du ønsker å gjøre synlig.';

$ac_accept = 'Aksepter';
$ac_decline = 'Avslå';
