<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Selecione os usuários e os grupos a que você quer ser visível.";

//security
$security_text = "Introduza a sua senha e os campos que você quer mudar e clique 'Salvar'";
$security_current_password = "Senha atual";
$security_new_password = "Senha nova";
$security_confirm_password = "Confirme a senha";
$security_new_authcode = "Código novo de autorização";
$security_confirm_authcode = "Confirme o Código de autorização";
$security_question = "Pergunta secreta";
$security_answer = "Resposta";
$security_wrong_password = "Senha errada.";
$security_tasks = "Tarefas finalizadas.";
$security_password_update = "Senha atualizada.";
$security_authcode_update = "Os Códigos de autorização foram atualizados.";
$security_question_update = "Pergunta e resposta atualizada.";
$security_question_fail = "você não preencheu a pergunta e a resposta ..";

$acProfile = "Perfil";
$acSecurity = "Segurança";
$acPrivacy = "Privacidade";
$acManager = "Sua conta";
$acStatistics = "Estatisticas";
$acProfileText = "Clique sobre 'Salvar' para mudar seu perfil. Os campos marcados com o * s&atilde;o requeridos.";
$acTitle = "Sua conta";
$ac_login_info = "Informação sobre o inicio da sessão";
$ac_registration_time = "Tempo do registo";
$ac_lastlogin = "Último acesso ao Group-Office";
$ac_logins = "Todos os acessos ao Group-Office";
$ac_disk_usage = "Uso de disco";
$ac_max_diskspace = "Espaço em disco máximo ";
$ac_available_diskspace = "Espaço em disco disponível ";
$ac_used_diskspace = "Espaço em disco utilizado";
$ac_used = "Utilizado";

$ac_add_user = 'autorização Requerida';
$ac_auth_error = 'Algum erro ocorreu durante a autorização. Por favor tente novamente.';
$ac_auth_success = 'Sua conta está visível para este usuário. Uma mensagem foi encaminhada a este usuário avisando que você concordou com a requisição.';
$ac_auth_decline = 'Uma mensagem foi enviada a este usuário avisando que você negou sua requisição.';
$ac_auth_accept_mail_title = 'Group-Office - requisição de autorização Aceita';
$ac_auth_decline_mail_title = 'Group-Office - requisição de autorização Negada';
$ac_salutation = 'Caro Sr./Sra.';
$ac_auth_accept_mail_body = 'foi aceita sua requisição para tornar a conta visível a você.';
$ac_auth_decline_mail_body = 'não foi aceita sua requisição para tornar a conta visível a você.';
$ac_request_auth = 'Esta está uma requisição para que você permita que sua conta se torne visível a outro usuário. você quer tornar sua conta visível a este usuário?';
$ac_request_auth_mail_title ='Group-Office - requisição de autorização';
$ac_invalid_email = 'O endereço de correio que você inseriu não está registrado em nosso sistema. Por favor tente novamente.';
$ac_request_mail_body_prefix = 'Uma mensagem foi enviada para ';
$ac_request_mail_body_suffix = 'Requisitando a permissão do usuário para que torne visível sua conta à você.';
$ac_auth_text = 'Digite o endereço de correio eletrônico do usuário que você deseja que seja visível.';

$ac_accept = 'Concordo';
$ac_decline = 'não concordo';
$ac_salutation = 'Prezado(a)';
