<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Seleccione os utlizadores e os grupos que deseja quer tornar vis&iacute;veis.";

//security
$security_text = "Indroduza a password e os campos que deseja alterar e clique em 'Guardar'";
$security_current_password = "Password actual";
$security_new_password = "Nova password";
$security_confirm_password = "Confirme a password";
$security_new_authcode = "Novo c&oacute;digo de autoriza&ccedil;&atilde;o";
$security_confirm_authcode = "Confirme o c&oacute;digo de autoriza&ccedil;&atilde;o";
$security_question = "Pergunta secreta";
$security_answer = "Resposta";
$security_wrong_password = "Password errada.";
$security_tasks = "Tarefas concluidas.";
$security_password_update = "Password actualizada.";
$security_authcode_update = "C&oacute;digos de autoriza&ccedil;&atilde;o actualizados.";
$security_question_update = "Pergunta e resposta actualizadas.";
$security_question_fail = "N&atilde;o preencheu a pergunta e a resposta.";

$acProfile = "Perfil";
$acSecurity = "Password";
$acPrivacy = "Privacidade";
$acManager = "A sua conta";
$acStatistics = "Estat&iacute;sticas";
$acProfileText = "Clique em 'Guardar' para alterar o perfil. Os campos marcados com * s&atilde;o obrigat&oacute;rios.";
$acTitle = "A sua conta";
$ac_login_info = "Informa&ccedil;&atilde;o de entrada";
$ac_registration_time = "Hora do registo";
$ac_lastlogin = "Uacute;ltima entrada";
$ac_logins = "Total de entradas";
$ac_disk_usage = "Espaço usado em disco";
$ac_max_diskspace = "Disco - Espa&ccedil;o m&aacute;ximo a utilizar";
$ac_available_diskspace = "Disco - Espa&ccedil;o dispon&iacute;vel";
$ac_used_diskspace = "Disco - Espa&ccedil;o utilizado";
$ac_used = "utilizado";

//translation required
$ac_add_user = 'Pedido de Autorização';
$ac_auth_error = 'Ocorreu um erro ao autorizar. Por favor, tente de novo.';
$ac_auth_success = 'A sua conta está agora visível a este utilizador e foi enviada uma mensagem a aceitar o pedido.';
$ac_auth_decline = 'Foi enviada uma mensagem a este utilizador recusando o pedido.';
$ac_auth_accept_mail_title = 'Pedido de autorização Group-Office aceite';
$ac_auth_decline_mail_title = 'Pedido de autorização Group-Office recusado';

$ac_auth_accept_mail_body = 'aceitou o pedido para tornar a sua conta visível.';
$ac_auth_decline_mail_body = 'recusou o pedido para tornar a conta visível.';
$ac_request_auth = 'pede autorização para tornar a conta visível. Deseja tornar a sua conta visível a este utilizador?';
$ac_request_auth_mail_title ='Pedido de autorização Group-Office';
$ac_invalid_email = 'O endereço de email não está registado no sistema. Por favor, tente de novo.';
$ac_request_mail_body_prefix = 'Foi enviada uma mensagem para ';
$ac_request_mail_body_suffix = 'pedindo a sua permissão para tornar a conta visível.';
$ac_auth_text = 'Indique o email do utilizador cuja conta deseja tornar visível.';

$ac_accept = 'Aceite';
$ac_decline = 'Recusado';
$ac_salutation = 'Olá';

$groups_you_are_in = 'É membro dos seguintes grupos';