<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Izberi uporabnike in skupine, za katere ¾eli¹ biti viden.";

//security
$security_text = "Vnesi svoje geslo in polja katera ¾eli¹ spremeniti ter pritisni 'Shrani'.";
$security_current_password = "Trenutno geslo";
$security_new_password = "Novo geslo";
$security_confirm_password = "Potrdi geslo";
$security_new_authcode = "Nova pooblastitvena koda";
$security_confirm_authcode = "Potrdi pooblastitveno kodo";
$security_question = "Skrito vpra¹anje";
$security_answer = "Odgovor";
$security_wrong_password = "Napaèno geslo.";
$security_tasks = "Opravilo dokonèano";
$security_password_update = "Geslo posodobljeno.";
$security_authcode_update = "Pooblastitvena koda posodobljena.";
$security_question_update = "Vpra¹anje in odgovor posodobljena.";
$security_question_fail = "Nisi zapolnil obe polji; vpra¹anje in odgovor.";

$acProfile = "Profil";
$acSecurity = "Varnost";
$acPrivacy = "Zasebnost";
$acManager = "Tvoj raèun";
$acStatistics = "Statistika";
$acProfileText = "Klikni na 'Shrani', da spremeni¹ svoj profil. Polja oznaèena z * so obvezna.";
$acTitle = "Tvoj raèun";
$ac_login_info = "Prijavna informacija";
$ac_registration_time = "Èas registracije";
$ac_lastlogin = "Zadnja prijava";
$ac_logins = "Skupaj prijav";
$ac_logins = "Skupaj prijav";
$ac_disk_usage = "Poraba diska";
$ac_max_diskspace = "Dovoljen prostor na disku";
$ac_available_diskspace = "Prosti disk";
$ac_used_diskspace = "Uporabljen diskovni prostor";
$ac_used = "uporabljen";

//translation required
$ac_add_user = 'Zahtevaj pooblastitev';
$ac_auth_error = 'Pri pooblastitvi je pri¹lo do napake. Poskusite znova.';
$ac_auth_success = 'Sedaj bo ta uporabnik lahko videl va¹ raèun, poslano pa mu je bilo tudi sporoèilo, da ste sprejeli njegovo zahtevo.';
$ac_auth_decline = 'Uporabniku je bilo poslano sporoèilo, da ste zavrnili njegovo zahtevo.';
$ac_auth_accept_mail_title = 'Zahteva za pooblastitev v Group-Office je sprejeta';
$ac_auth_decline_mail_title = 'Zahteva za pooblastitev v Group-Office je zavrnjena';

$ac_auth_accept_mail_body = 'je sprejel tvojo zahtevo, da lahko vidi¹ njegov raèun.';
$ac_auth_decline_mail_body = 'je zavrnil zahtevo, da bi videl njegov raèun.';
$ac_request_auth = 'zahteva tvoje dovoljenje, da naredi tvoj raèun viden. Ali ¾elite narediti svoj raèun viden temu uporabniku?';
$ac_request_auth_mail_title ='Group-Office zahteva za pooblastitev';
$ac_invalid_email = 'E-po¹tni naslov, ki ste ga vpisali ni vpisan v sistem. Prosim, poizkusite znova.';
$ac_request_mail_body_prefix = 'Sporoèilo je bilo poslano';
$ac_request_mail_body_suffix = 'zahtevati dovoljenje, da postane njegov raèun vam dostopen.';
$ac_auth_text = 'Vnesite e-po¹tni naslov uporabnika, èigar raèun ¾elite videti.';

$ac_accept = 'Potrdi';
$ac_decline = 'Zavrni';
$ac_salutation = 'Dragi';
