<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "Välj de användare och grupper du vill vara synlig för.";

//security
$security_text = "Skriv in ditt lösenord och de fält du vill ändra på, tryck sedan 'Spara'.";
$security_current_password = "Nuvarande lösenord";
$security_new_password = "Nytt lösenord";
$security_confirm_password = "Bekräfta lösenord";
$security_new_authcode = "Ny authoriseringskod";
$security_confirm_authcode = "Bekräfta authoriseringskod";
$security_question = "Hemlig fråga";
$security_answer = "Svar";
$security_wrong_password = "Felaktigt lösenord.";
$security_tasks = "Uppgift slutförd";
$security_password_update = "Lösenord uppdaterat.";
$security_authcode_update = "Authoriseringskoder uppdaterade.";
$security_question_update = "Fråga och svar uppdaterat.";
$security_question_fail = "Du fyllde inte i både frågan och svaret.";

$acProfile = "Profil";
$acSecurity = "Säkerhet";
$acPrivacy = "Privat";
$acManager = "Ditt konto";
$acStatistics = "Statistik";
$acProfileText = "Tryck på 'Spara' för att ändra din profil. Fält markerade med * måste fyllas i.";
$acTitle = "Ditt konto";
$ac_login_info = "Kontoinformation";
$ac_registration_time = "Registreringstid";
$ac_lastlogin = "Senast inloggad";
$ac_logins = "Antal inloggningar";
$ac_disk_usage = "Använt utrymme";
$ac_max_diskspace = "Max utrymme";
$ac_available_diskspace = "Tillgängligt utrymme";
$ac_used_diskspace = "Använt utrymme";
$ac_used = "använt";

//translation required
$ac_add_user = 'Kräv auktorisering';
$ac_auth_error = 'Ett fel uppstod vid auktoriseringen. Var vänligt försök igen.';
$ac_auth_success = 'Ditt konto är nu synligt för denna användare och ett meddelande har skickats till använadaren om att du accepterade hans förfrågan.';
$ac_auth_decline = 'Ett meddelande har skickats till denna användare om att du nekade hans förfrågan.';
$ac_auth_accept_mail_title = 'Group-Office auktoriserings förfrågan accepterades';
$ac_auth_decline_mail_title = 'Group-Office auktoriserings förfrågan nekades';

$ac_auth_accept_mail_body = 'har accepterat din förfrågan om att göra hans konto synligt för dig.';
$ac_auth_decline_mail_body = 'har nekat din förfrågan om att göra hans konto synligt för dig.';
$ac_request_auth = 'frågar om din tillåtelse att göra ditt konto synligt. Vill du göra ditt konto synligt för denna användare?';
$ac_request_auth_mail_title ='Group-Office auktoriserings förfrågan';
$ac_invalid_email = 'E-post adressen du skrev är inte registrerad i systemet. Försök igen.';
$ac_request_mail_body_prefix = 'Ett meddelande skickades till ';
$ac_request_mail_body_suffix = 'med en förfrågan om att göra hans konto synligt för dig.';
$ac_auth_text = 'Skriv in e-post adressen till användaren vars konto du vill göra synligt.';

$ac_accept = 'Acceptera';
$ac_decline = 'Avböj';
$ac_salutation = 'Kära';
