<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "เลือกผู้ใช้และกลุ่มที่คุณต้องการแสดง";

//security
$security_text = "ใส่รหัสผ่านลงในช่องที่ต้องการเพื่อเปลี่ยนและคลิก 'บันทึก'";
$security_current_password = "รหัสผ่าน";
$security_new_password = "รหัสผ่านใหม่";
$security_confirm_password = "ยืนยันรหัสผ่าน";
$security_new_authcode = "รหัส";
$security_confirm_authcode = "ยืนยันรหัส";
$security_question = "คำถามลับ";
$security_answer = "คำตอบ";
$security_wrong_password = "รหัสผ่านไม่ถูกต้อง.";
$security_tasks = "งานสำเร็จ";
$security_password_update = "แก้ไขรหัสผ่าน";
$security_authcode_update = "แก้ไขรหัสเรียบร้อยแล้ว";
$security_question_update = "อัพเดตคำถามและคำตอบแล้ว";
$security_question_fail = "คุณไม่ได้ใส่คำถามและคำตอบลงในช่องว่าง";

$acProfile = "ข้อมูลโดยรวม";
$acSecurity = "ความปลอดภัย";
$acPrivacy = "ความเป็นส่วนตัว";
$acManager = "บัญชีของคุณ";
$acStatistics = "สถิติ";
$acProfileText = "คลิกที่ปุ่ม 'บันทึก' เพื่อเปลี่ยนข้อมูลของคุณ.ช่องที่มีเครื่องหมาย * คือช่องที่ต้องใส่";
$acTitle = "บัญชีของคุณ";
$ac_login_info = "ข้อมูลในการเข้าสู่ระบบ";
$ac_registration_time = "เวลาในการลงทะเบียน";
$ac_lastlogin = "นามสกุล";
$ac_logins = "ชื่อเต็มในการล็อกอิน";
$ac_disk_usage = "ขนาดพื้นที่ที่ใช้ไปแล้ว";
$ac_max_diskspace = "ขนาดพื้นที่สูงสุด";
$ac_available_diskspace = "พื้นที่ในขณะนี้";
$ac_used_diskspace = "พื้นที่ๆใช้ไปแล้ว";
$ac_used = "ใช้";

//translation required
$ac_add_user = 'เรียกร้อง';
$ac_auth_error = 'เกิดเหตุขัดข้องเกี่ยวกับการอนุญาติกรุณาลองอีกครั้ง.';
$ac_auth_success = 'Your account is now visible to this user and a message has been sent to this user that you accepted his request.';
$ac_auth_decline = 'A message has been sent to this user that you have declined his request.';
$ac_auth_accept_mail_title = 'Group-Office authorization request accepted';
$ac_auth_decline_mail_title = 'Group-Office authorization request denied';

$ac_auth_accept_mail_body = 'has accepted your request to make his account visible to you.';
$ac_auth_decline_mail_body = 'has declined your request to make his account visible to you.';
$ac_request_auth = 'requests your permission to make your account visible. Do you want to make your account visible to this user?';
$ac_request_auth_mail_title ='Group-Office authorization request';
$ac_invalid_email = 'The e-mail address you entered is not registered in the system. Please try again.';
$ac_request_mail_body_prefix = 'A message was sent to ';
$ac_request_mail_body_suffix = 'requesting his permission to make his account visible to you.';
$ac_auth_text = 'Enter the e-mail address from the user who\'s account you want to make visible.';

$ac_accept = 'ยอมรับ';
$ac_decline = 'ไม่ยอมรับ';
$ac_salutation = 'Dear';
