<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('account'));

//privacy
$privacy_text = "選擇可看見你/妳的使用者和群組";

//security
$security_text = "你/妳 必須先輸入現時的密碼才能變更其他的欄位，輸入後再按「儲存」。";
$security_current_password = "現時的密碼";
$security_new_password = "新的密碼";
$security_confirm_password = "確認密碼";
$security_new_authcode = "新的授權密碼";
$security_confirm_authcode = "確認授權密碼 ";
$security_question = "秘密問題";
$security_answer = "答案";
$security_wrong_password = "密碼錯誤";
$security_tasks = "作業完成";
$security_password_update = "密碼已更新";
$security_authcode_update = "授權密碼已更新";
$security_question_update = "問題和答案已更新";
$security_question_fail = "你/妳沒有填寫問題和答案";

$acProfile = "設定檔";
$acSecurity = "安全";
$acPrivacy = "私隱";
$acManager = "你/妳的賬戶";
$acStatistics = "狀態";
$acProfileText = "按「儲存」變更你/妳的設定檔。有 * 的欄位必須填寫。";
$acTitle = "你/妳的賬戶";
$ac_login_info = "登入資訊";
$ac_registration_time = "註冊時間";
$ac_lastlogin = "最後登入";
$ac_logins = "總共登入";
$ac_disk_usage = "磁碟使用量";
$ac_max_diskspace = "最大磁碟空間";
$ac_available_diskspace = "可用磁碟空間";
$ac_used_diskspace = "已使用磁碟空間";
$ac_used = "已使用";

//translation required
$ac_add_user = "要求授權";
$ac_auth_error = "當授權時發生錯誤，請重試。";
$ac_auth_success = "現在這個使用者可看見你/妳的賬號以及這個使用者將會收到一個你/妳已接受他的請求的信息。";
$ac_auth_decline = "這個使用者將會收到一個你/妳已拒絕他的請求的信息。";
$ac_auth_accept_mail_title = "Group-Office授權請求已接受";
$ac_auth_decline_mail_title = "Group-Office授權請求已拒絕";

$ac_auth_accept_mail_body = "已接受你/妳可看到他/她的賬號的請求。";
$ac_auth_decline_mail_body = "已拒絕你/妳可看到他/她的賬號的請求。";
$ac_request_auth = "請求授權可看到你/妳的賬號，你/妳是否想讓他/她看到你/妳的賬號?";
$ac_request_auth_mail_title ="Group-Office授權請求";
$ac_invalid_email = "你/妳所輸入的電子郵件地址沒有在系統登記，請重試。";
$ac_request_mail_body_prefix = "信息已寄給";
$ac_request_mail_body_suffix = "請求允許可看到他/她的賬號";
$ac_auth_text = "輸入電郵地址，這個電郵地址是你/妳想看到的使用者賬號的電郵地址";
$ac_accept = "接受";
$ac_decline = "拒絕";
$ac_salutation = "親愛的先生/小姐";
