<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='اهلا بكم فى';
$sum_you_have='لديك';
$sum_new_messages='<b>unread</b> e-mail messages';
$sum_new_message='<b>unread</b> e-mail message';
$sum_no_new_mail='لا ، لم يتم قراءتها البريد';
$sum_manage_announcements='ادارة الاعلانات';
$sum_announcements_count='الاعلانات';
$sum_announcements_count_single='اعلان';
$sum_no_announcements='لا ،يجد اعلانات';
$sum_due_time='تظهر حتى';
$sum_new_announcement='اعلان جديد';
$sum_private='خاص';
$sum_today='اليوم';
$sum_tommorow='غدا';
$sum_unfinished='لم تنته';
$sum_latest_files='آخر تحميل الملفات';
$sum_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=208';
?>