<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Benvingut a';
$sum_you_have='Teniu';
$sum_new_messages='missatges de correu electrònic <b>per llegir</b>';
$sum_new_message='missatge de correu electrònic <b>per llegir</b>';
$sum_no_new_mail='Cap missatge per llegir';
$sum_manage_announcements='Gestiona avisos';
$sum_announcements_count='avisos';
$sum_announcements_count_single='avís';
$sum_no_announcements='No s\'ha trobat cap avís';
$sum_due_time='Mostra fins';
$sum_new_announcement='Nou avís';
$sum_private='Privat';
$sum_today='Avui';
$sum_tommorow='Demà';
$sum_unfinished='Pendent d\'acabar';
?>