<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Vítejte na';
$sum_you_have = 'Máte';
$sum_new_messages = '<b>nepřečtených</b> e-mailových zpráv';
$sum_new_message = '<b>nepřečtenou</b> e-mailovou zprávu';
$sum_no_new_mail = 'Nemáte žádné nepřečtené e-mailové zprávy.';

$sum_manage_announcements = 'Editace poznámek';
$sum_announcements_count = 'poznámek';
$sum_announcements_count_single = 'poznámka';
$sum_no_announcements = 'Nejsou žádné poznámky';
$sum_due_time = 'Zobrazovat do';
$sum_new_announcement = 'Nová poznámka';
$sum_private = 'Soukromé';

//2.10
$sum_today = 'Dnes';
$sum_tommorow = 'Zítra';
$sum_unfinished = 'Nedokončené';

$sum_latest_files='Naposled nahrané soubory';

$sum_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=208';
