<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Velkommen til';
$sum_you_have = 'Du har';
$sum_new_messages = '<b>ulæste</b> e-mail beskeder';
$sum_new_message = '<b>ulæst</b> e-mail besked';
$sum_no_new_mail = 'Ingen ulæste beskeder';

$sum_manage_announcements = 'Administrer nyheder';
$sum_announcements_count = 'nyheder';
$sum_announcements_count_single = 'nyhed';
$sum_no_announcements = 'Ingen nyheder';
$sum_due_time = 'Vis nyhed indtil';
$sum_new_announcement = 'Opret nyhed';
$sum_private = 'Privat';
