<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='\'Willkommen in';
$sum_you_have='\'Sie haben';
$sum_new_messages='\'<b>ungelesene</b> E-Mail-Nachrichten';
$sum_new_message='\'<b>ungelesene</b> E-Mail-Nachricht';
$sum_no_new_mail='\'Keine ungelesenen E-Mails';
$sum_manage_announcements='\'Bekanntmachungen verwalten';
$sum_announcements_count='\'Bekanntmachungen';
$sum_announcements_count_single='\'Bekanntmachung';
$sum_no_announcements='\'Keine Bekanntmachungen vorhanden';
$sum_due_time='\'Anzeige bis';
$sum_new_announcement='\'Neue Bekanntmachung';
$sum_private='\'Privat';
$sum_today='\'Heute';
$sum_tommorow='\'Morgen';
$sum_unfinished='\'Unerledigt';
$sum_latest_files='Die letzten hochgeladenen Dateien';
?>