<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Welcome to';
$sum_you_have = 'You have';
$sum_new_messages = '<b>unread</b> e-mail messages';
$sum_new_message = '<b>unread</b> e-mail message';
$sum_no_new_mail = 'No unread mail';

$sum_manage_announcements = 'Manage announcements';
$sum_announcements_count = 'announcements';
$sum_announcements_count_single = 'announcement';
$sum_no_announcements = 'No announcements found';
$sum_due_time = 'Show until';
$sum_new_announcement = 'New announcement';
$sum_private = 'Private';

//2.10
$sum_today = 'Today';
$sum_tommorow = 'Tomorrow';
$sum_unfinished = 'Unfinished';

$sum_latest_files='Latest uploaded files';

$sum_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=208';
