<?php
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Bienvenido a';
$sum_you_have = 'Tiene';
$sum_new_messages = 'correos electrónicos <b>no leídos</b>';
$sum_new_message = 'correo electrónico <b>no leído</b>';
$sum_no_new_mail = 'Ningún mensaje no leído';

$sum_manage_announcements = 'Gestionar avisos';
$sum_announcements_count = 'avisos';
$sum_announcements_count_single = 'aviso';
$sum_no_announcements = 'No se ha encontrado ningún aviso';
$sum_due_time = 'Ver hasta';
$sum_new_announcement = 'Nuevo aviso';
$sum_private = 'Privado';

//2.10
$sum_today = 'Hoy';
$sum_tommorow = 'Mañana';
$sum_unfinished = 'Pendiente de finalizar';
