<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Tervetuloa ';
$sum_you_have = 'Sinulla on';
$sum_new_messages = '<b>lukematonta</b> sähköposti viestiä';
$sum_new_message = '<b>lukematon</b> sähköposti viesti';
$sum_no_new_mail = 'Ei ole lukemattomia viestejä';

$sum_manage_announcements = 'Hallinnoi ilmotuksia';
$sum_announcements_count = 'ilmoitukset';
$sum_announcements_count_single = 'ilmoitus';
$sum_no_announcements = 'Ilmoituksia ei löytynyt';
$sum_due_time = 'Näytä kunnes';
$sum_new_announcement = 'Uusi ilmoitus';
$sum_private = 'Yksityinen';

//2.10
$sum_today = 'Tänään';
$sum_tommorow = 'Huomenna';
$sum_unfinished = 'Kesken';
