<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Üdvözli Önt a';
$sum_you_have='Önnek van';
$sum_new_messages='<b>olvasatlan</b> e-mail üzenete';
$sum_new_message='<b>olvasatlan</b> e-mail üzenete';
$sum_no_new_mail='Nincs olvasatlan e-mail üzenete';
$sum_manage_announcements='Közlemények módosítása';
$sum_announcements_count='közlemény';
$sum_announcements_count_single='közlemény';
$sum_no_announcements='Nem találtam közleményeket';
$sum_due_time='Mutassa eddig:';
$sum_new_announcement='Új közlemény';
$sum_private='Magánjellegű';
$sum_today='Ma';
$sum_tommorow='Holnap';
$sum_unfinished='Befejezetlen';
?>