<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Benvenuto in';
$sum_you_have='Hai';
$sum_new_messages='messaggi <b>non letti</b>';
$sum_new_message='messaggio <b>non letto</b>';
$sum_no_new_mail='Nessun nuovo messaggio';
$sum_manage_announcements='Gestione annunci';
$sum_announcements_count='annunci';
$sum_announcements_count_single='annuncio';
$sum_no_announcements='Nessun annuncio trovato';
$sum_due_time='Mostra fino a';
$sum_new_announcement='Nuovo annuncio';
$sum_private='Privato';
$sum_today='Oggi';
$sum_tommorow='Domani';
$sum_unfinished='Non terminato';
?>