<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'ようこそ';
$sum_you_have = '';
$sum_new_messages = '<b>未読</b>メール';
$sum_new_message = '<b>未読</b>メール';
$sum_no_new_mail = '未読メールなし';

$sum_manage_announcements = 'アナウンス管理';
$sum_announcements_count = 'アナウンス';
$sum_announcements_count_single = 'アナウンス';
$sum_no_announcements = 'アナウンスが見つかりません';
$sum_due_time = '表示時間';
$sum_new_announcement = '新規アナウンス';
$sum_private = 'プライベート';

//2.10
$sum_today = '本日';
$sum_tommorow = '明日';
$sum_unfinished = '未終了';
