<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Welkom bij';
$sum_you_have='U heeft';
$sum_new_messages='<b>ongelezen</b> e-mail berichten';
$sum_new_message='<b>ongelezen</b> e-mail bericht';
$sum_no_new_mail='U heeft geen ongelezen e-mail berichten';
$sum_manage_announcements='Beheer aankondigingen';
$sum_announcements_count='aankondigingen';
$sum_announcements_count_single='aankondiging';
$sum_no_announcements='Geen aankondigingen gevonden';
$sum_due_time='Toon tot';
$sum_new_announcement='Nieuwe aankondiging';
$sum_private='Privé';
$sum_today='Vandaag';
$sum_tommorow='Morgen';
$sum_unfinished='Onvoltooid';
