<?php
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Bem-Vindo à;';
$sum_you_have = 'Você tem';
$sum_new_messages = 'mensagens de e-mail <b>não lidas</b>';
$sum_new_message = 'mensagem de e-mail <b>não lida</b>';
$sum_no_new_mail = 'Nenhuma mensagem não lida';

$sum_manage_announcements = 'Administre anúncios';
$sum_announcements_count = 'anúncios';
$sum_announcements_count_single = 'anúncio';
$sum_no_announcements = 'Nenhum anúncio encontrado';
$sum_due_time = 'Exibir até;';
$sum_new_announcement = 'Novo anúncio';
$sum_private = 'Particular';

//2.10
$sum_today = 'Hoje';
$sum_tommorow = 'Amanhã';
$sum_unfinished = 'Incompleta';
