<?php
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Bem-vindo a';
$sum_you_have = 'Tem';
$sum_new_messages = 'mensagens de email <b>não lidas</b>';
$sum_new_message = 'mensagem de e-mail <b>não lida</b>';
$sum_no_new_mail = 'Nenhuma mensagem por ler';

$sum_manage_announcements = 'O que há de importante - Inserir um Destaque';
$sum_announcements_count = 'destaques';
$sum_announcements_count_single = 'destaque';
$sum_no_announcements = 'Nenhum destaque encontrado';
$sum_due_time = 'Mostrar até';
$sum_new_announcement = 'Novo destaque';
$sum_private = 'Privado';

//2.10
$sum_today = 'Hoje';
$sum_tommorow = 'Amanhã';
$sum_unfinished = 'Por concluir';

$sum_latest_files='Últimos ficheiros enviados';

$sum_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=208';

