<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Добро пожаловать в';
$sum_you_have = 'Вы имеете:';
$sum_new_messages = '<b>непрочтенных</b> e-mail сообщений';
$sum_new_message = '<b>непрочтенное</b> e-mail сообщение';
$sum_no_new_mail = 'Нет новых сообщений';

$sum_manage_announcements = 'Управление анонсами';
$sum_announcements_count = 'Анонсы';
$sum_announcements_count_single = 'announcement';
$sum_no_announcements = 'Анонсы не найдены';
$sum_due_time = 'Show until';
$sum_new_announcement = 'Новый анонс';
$sum_private = 'Частное';

//2.10
$sum_today = 'Сегодня';
$sum_tommorow = 'Завтра';
