<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Pozdravljeni na';
$sum_you_have = 'Imate';
$sum_new_messages = '<b>neprebranih</b> e-sporoèil ';
$sum_new_message = '<b>neprebrano</b> e-sporoèilo ';
$sum_no_new_mail = 'Ni neprebrane po¹te';

$sum_manage_announcements = 'Upravljaj z naznanili';
$sum_announcements_count = 'naznanila';
$sum_announcements_count_single = 'naznanilo';
$sum_no_announcements = 'Ni najdenih naznanil';
$sum_due_time = 'Poka¾i dokler';
$sum_new_announcement = 'Novo naznanilo';
$sum_private = 'Zasebno';
