<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'Välkommen till';
$sum_you_have = 'Du har';
$sum_new_messages = '<b>olästa</b> e-post meddelanden';
$sum_new_message = '<b>oläst</b> e-post meddelande';
$sum_no_new_mail = 'Ingen oläst e-post';

$sum_manage_announcements = 'Hantera tillkännagivanden';
$sum_announcements_count = 'tillkännagivanden';
$sum_announcements_count_single = 'tillkännagivande';
$sum_no_announcements = 'Inga tillkännagivanden hittades';
$sum_due_time = 'Visa tills';
$sum_new_announcement = 'Nytt tillkännagivande';
$sum_private = 'Privat';

//2.10
$sum_today = 'I dag';
$sum_tommorow = 'I morgon';
$sum_unfinished = 'I dag';
