<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('summary'));

$sum_welcome_to = 'ยินดีต้อนรับเข้าสู่';
$sum_you_have = 'คุณมี';
$sum_new_messages = '<b>อีเมลล์</b> ที่ยังไม่ได้อ่าน';
$sum_new_message = '<b>อีเมลล์</b> ที่ยังไม่ได้อ่าน';
$sum_no_new_mail = 'ไม่มีจดหมายที่ยังไม่ได้อ่าน';

$sum_manage_announcements = 'จัดการเรื่องการประกาศ';
$sum_announcements_count = 'การประกาศ';
$sum_announcements_count_single = 'การประกาศ';
$sum_no_announcements = 'ไม่พบข้อความประกาศ';
$sum_due_time = 'แสดงจนถึง';
$sum_new_announcement = 'มีข้อความประกาศใหม่';
$sum_private = 'ส่วนตัว';

//2.10
$sum_today = 'วันนี้';
$sum_tommorow = 'พรุ่งนี้';
