<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('summary'));
$sum_welcome_to='Hoşgeldiniz:';
$sum_you_have='Sizin';
$sum_new_messages='<b>okunmamış</b> eposta mesajınız var';
$sum_new_message='<b>okunmamış</b> eposta mesajınız var';
$sum_no_new_mail='Okunmamış eposta yok';
$sum_manage_announcements='Duyuruları yönet';
$sum_announcements_count='duyuru';
$sum_announcements_count_single='duyuru';
$sum_no_announcements='Duyuru bulunamadı';
$sum_due_time='Gerçekleşinceye kadar göster:';
$sum_new_announcement='Yeni duyuru';
$sum_private='Özel';
$sum_today='Bugün';
$sum_tommorow='Yarın';
$sum_unfinished='Bitmemiş';
?>