<?php
$filetypes['unknown'] = 'filetypes/unknown.png';
$filetypes['txt'] = 'filetypes/txt.png';
$filetypes['pdf'] = 'filetypes/pdf.png';
$filetypes['doc'] = $filetypes['sxw'] = $filetypes['ott']=$filetypes['odt']= 'filetypes/doc.png';
$filetypes['xls'] = $filetypes['sxc'] = $filetypes['odc']= $filetypes['ods']= $filetypes['ots']='filetypes/spreadsheet.png';
$filetypes['tar'] = 'filetypes/tar.png';
$filetypes['gz'] = $filetypes['tgz'] = $filetypes['zip'] ='filetypes/tgz.png';

$filetypes['exe'] = 'filetypes/exec_wine.png';
$filetypes['ttf'] = 'filetypes/font_truetype.png';
$filetypes['html'] = $filetypes['htm'] = 'filetypes/html.png';
$filetypes['jpg'] = $filetypes['jpeg'] = $filetypes['tif'] = 'filetypes/images.png';
$filetypes['gif'] = 'filetypes/image2.png';
$filetypes['bmp'] = 'filetypes/images.png';
$filetypes['php'] = 'filetypes/php.png';
$filetypes['ics'] = 'filetypes/vcalendar.png';
$filetypes['vcf'] = 'filetypes/vcard.png';
$filetypes['wav'] = $filetypes['ogg'] = $filetypes['mp3'] = 'filetypes/sound.png';
$filetypes['mpg'] = $filetypes['mpeg'] = $filetypes['avi'] = $filetypes['wmv'] = $filetypes['wmf'] = 'filetypes/video.png';

$filetypes['eml'] = 'mail.png';
