<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('calendar'));

$sc_title = 'Nadpis';
$sc_description = 'Popis';
$sc_participants = 'Pozvaní';

$sc_location = 'Místo';

$month_times[0] = 'první';
$month_times[1] = 'druhý';
$month_times[2] = 'třetí';
$month_times[3] = 'čtvrtý';

$sc_new_app = 'Nová údálost';
$sc_calendars = 'Kalendáře';
$sc_invited = 'Jste pozváni na níže uvedenou údálost.';

$sc_types1[0] = 'bez opakování';
$sc_types1[1] = 'denně';
$sc_types1[2] = 'týdně';
$sc_types1[3] = 'měsíčně podle data';
$sc_types1[4] = 'mesíčně podle dne';
$sc_types1[5] = 'ročně';


$sc_types[0] = 'Jednou';
$sc_types[1] = 'Denně';
$sc_types[2] = 'Týdně';
$sc_types[3] = 'Měsíčně podle data';
$sc_types[4] = 'Měsíčně podle dne';
$sc_types[5] = 'Ročně';


$sc_start_at = 'Začátek';
$sc_end_at = 'Konec';
$sc_start_time = 'Začátek';
$sc_end_time = 'Konec';

$sc_at_days = 'Ve dnech';
$sc_of_month = 'měsíce.';

$sc_cycle_start = 'Období začíná v';
$sc_cycle_end = 'Opakovat do';
$sc_accept_question = 'Přejete si akceptovat a naplánovat tuto údálost?';

$sc_accept = 'přijmout';
$sc_decline = 'nepřijmout';

$sc_notime = 'celé dny';
$sc_noend = 'žádné konečné datum.';

$sc_never_happens = 'Špatné zadání! Tato událost se nikdy nestala.';
$sc_start_later = 'Špatné zadání! Začátek je zadán později než konec.';

$sc_add_self = 'Ruční zadání';

$sc_select_calendar = 'Vyberte kalendář a naplánujte událost';
$sc_accept_confirm = 'Událost je přijata a naplánována.';
$sc_no_calendars = 'Žádný platný kalendář nebyl nenalezen a událost nebyla nenaplánována.';
$sc_bad_event = 'Žádná platná událost nebyla nenalezena. Tato událost je pravděpodobně smazána.';
$sc_accept_title = 'Akceptovat událost';

$sc_decline_confirm = 'Událost nepřijata.';
$sc_decline_title = 'Nepřijmout událost';

$sc_status = 'Postavení';
$sc_not_responded = 'Nezodpovězeno';
$sc_accepted = 'Přijatá';
$sc_declined = 'Nepřijatá';
$sc_no_participants = 'Žádní účastníci';

$sc_person = 'Osoba';
$sc_owner = 'Vlastník';
$sc_type = 'Typ';
$sc_subscribed = 'Zapsáno';

$sc_subscribe = 'Zapsání se';
$sc_new_calendar = 'Nový kalendář';
$sc_no_calendar = 'Žádný kalendář nebyl nalezen. Prosím vytvořte jej nyní nebo jej Group-Office pro Vás automaticky vytvoří.';
$sc_day_view = 'Den';
$sc_week_view = 'Týden';
$sc_list_view = 'Seznam';
$sc_put_in = 'Uložit událost do';
$sc_inherit_permissions ='Zdědit práva po';
$sc_no_inherit = 'Nedědit';

$sc_select_calendar_please = 'Prosím, vyberte nejméně jeden kalendář.';
$sc_events = 'Události';

$sc_from_calendar = 'z kalendáře';
$sc_enitrely = 'Úplně';
$sc_delete_event = 'Odstranit událost';
$sc_delete_pre = 'Chcete událost odstranit';
$sc_delete_suf = 'úplně nebo jen z tohoto kalendáře?';

$sc_refresh = 'Obnovit';
$sc_reminder = 'Připomenout';
$sc_mins = 'minut';
$sc_hour = 'hodina';
$sc_hours = 'hodiny';
$sc_day = 'den';
$sc_days = 'dny/í';
$sc_week = 'týden';
$sc_weeks = 'týdny';
$sc_reminder_set_to_early = 'Připomínka se nemůže objevovat bez předchozího výskytu. Prosím zkraťte čas připomínky nebo prodlužte opakující se dobu.';
$sc_cycle_start_later = 'Začátek období je pozdější nebo roven datu konce.';


$cmdGenerate = 'Vytvořit';
$sc_preferences = 'Vlastnosti';
$sc_holidays = 'Svátky';

$strNoHolidays = 'Žádné svátky v databázi';
$strUnknown = 'Neznámý';
$strYear = 'Rok';
$strDeleteHolidaysPrefix = 'Jste si jistý, že chcete odstranit všechny prázdninové záznamy toho roku';
$strDeleteHolidaysSuffix = '?';
$strReplaceHolidays = 'Jste si jistý, že chcete přepsat všechny existující prázdninové záznamy?';
$sc_holidays_text1 = 'Prosím klikněte na \''.$cmdGenerate.'\' pro výpočet  svátků ve vybraném roce.';
$sc_holidays_text2 = 'Prosím klikněte na \''.$cmdApply.'\' pro uložení všech spočítaných svátků v databázi.';

//translation required below this
$sc_client = 'Klient';
$sc_no_contact = 'Žádný';

$sc_background = 'Barva pozadí';

$sc_colors['red'] = 'Červený';
$sc_colors['green'] = 'Zelený';
$sc_colors['blue'] = 'Modrý';
$sc_colors['pink'] = 'Růžový';
$sc_colors['orange'] = 'Oranžový';
$sc_colors['brown'] = 'Hnědý';
$sc_colors['yellow'] = 'Žlutý';
$sc_colors['grey'] = 'Šedý';
$sc_colors['purple'] = 'Nachový';
$sc_colors['white']= 'Bílý';
$sc_status = 'Stav';

$sc_show_hours = 'Zobrazovat hodiny od';
$sc_to = 'do';

$sc_today = 'Dnes';

$sc_recur_every = 'Opakování události';

$sc_private_event = 'Soukromá událost';
$sc_calendar_exists = 'Kalendář s tímto jménem již existuje';
//translate
$sc_month = 'měsíc';
$sc_view = 'Zobrazení';
$sc_calendar = 'Kalendář';
$sc_default = 'Výchozí';
$sc_month_view = 'Měsíc';

//text changed, needs new translation
$sc_holidays_no_file_prefix = 'Svátky nemohou být vytvořeny, protože soubor obsahující informace o svátcích pro jazyk ';
$sc_holidays_no_file_suffix = ' je prázdný nebo nebyl nalezen.';

$sc_no_events = 'Nenalezena žádná událost.';

//2.03
$cal_export = 'Export';
$cal_import = 'Import';
$cal_please_wait = 'Prosím čekejte...';
$cal_import_text = 'Vyber iCal ( *.ics ) soubor a klikni na "Ok"';
$cal_filename = 'Soubor';
$cal_import_success = 'Data importována';

//2.04
$cal_add_todo = 'Nový úkol';
$cal_todos = 'Úkol';

$cal_hide_completed = 'Schovat dokončené';
$cal_show_all = 'Zobrazit všechny úkoly';
$cal_show_own = 'Zobrazit vlastní úkoly';
$cal_show_responsible = 'Zobrazit přidělené úkoly';

$cal_priority = 'Priorita';
$cal_priority_values[0] = 'Malá';
$cal_priority_values[1] = 'Střední';
$cal_priority_values[2] = 'Velká';

$cal_status = 'Stav';
$cal_canceled = 'Zrušeno';
$cal_completed = 'Dokončeno na';
$cal_percent_completed = '% hotovo';

$cal_before_task_start = 'Dříve než se by se měl úkol spustit';
$cal_before_task_due = 'Dřívež by měl být úkol dokončen';
$cal_responsible = 'Přiděleno';
$cal_due_at = 'Termín';
$cal_no_todos= 'Žádné úkoly nenalezeny';
$cal_resend_invitation = 'Znovu zaslat pozvánku';

//2.05
$cal_everybody_write = 'Každý může měnit tuto událost';
$cal_everybody_read = 'Pouze já mohu měnit tuto událost';

$cal_view = 'Zobrazení';
$cal_views = 'Zobrazení';
$sc_view_exists = 'Zobrazení s tímto jménem už existuje.';
$cal_new_view = 'Nové zobrazení';
$cal_event_calendars = 'Kalendář(e)';

//2.06
$cal_view_merged = 'sloučeně';
$cal_view_emerged = 'odděleně';

//2.07
$cal_display = 'Zobrazit';
$sc_new_task = "Nový úkol";
$sc_all_day_events = 'události pro všechny dny';
$sc_all_day_event = 'událost pro všechny dny';
$sc_usual_events = 'události';
$sc_usual_event = 'událost';

//2.08
$sc_recur_section = 'Opakování';
$sc_options_section = 'Možnosti';
$sc_close = 'Zavřít';

$cal_count_single = 'událost';
$cal_count_multiple = 'události';

$cal_until = 'dokud';
$cal_forever = 'navždy';

//2.09
$cal_merged_overview = 'Sloučený přehled';
$cal_own_availability = 'Vlastní dostupnost';

//2.11
$cal_no_file = 'Nebyl přijat žádný soubor';
$cms_no_calendars_in_view = 'Nelze nic ukázat, protože ve zvoleném zobrazení není žádný kalendář. Klikněte na \'Zobrazení\' a nastavte jej.';
$cal_no_reminder = 'Bez budíku';

//2.13
$cal_refresh_rate = 'Frekvence obnovování';
$sc_seconds = 'sekund (Prázdná hodnota zakáže obnovování)';
$cal_default_reminder = 'Standardní budík';

// extra
$sc_months = 'měsíce';
$cal_open_calendar = 'Otevři další kalendář';
$cal_show_completed = 'Ukaž hotové úkoly';

//2.14
$cal_event = 'Událost';
$cal_todo = 'Úkol';
$cal_participants_write = 'Účastník může modifikovat událost';

$cal_everybody_write = 'Každý může modifikovat událost'; //modified string from 2.05 this became the
$cal_everybody_read = 'Jenom já mohu modifikovat událost';//modified string from 2.05 

$cal_default_permissions = 'Výchozí práva';
$cal_show_todos = 'Ukaž úkoly v kalendáři';

$cal_edit_series_or_single = 'Edituj pouze tento příklad nebo celou sérii?';
$cal_single = 'Příklad';
$cal_series = 'Celá série';

$cal_legend = 'Legenda';
$cal_multiple_calendars = 'Vícenásobný kalendář';

$cal_cumulative = 'Nesprávně vloženo! Událost musí být delší než opakovací interval.';

$cal_weekview = 'Náhled celého týdne';
$cal_mo_to_fr = 'Pondělí až pátek';
$cal_mo_to_su = 'Pondělí až neděle';

$cal_batchcalendars = 'Vytvořte kalendáře pro všechny uživatele';
$cal_create_all_calendars = 'Vytvořte kalendáře pro všechny uživatele nebo udělte práva uživatelským skupinám';

$cal_no_views = 'Nelze zobrazit';

$cal_my_cals = 'Moje kalendáře';

$cal_event_colors_override = 'Použijte manuální nastavení barev pro události';

//2.15
$cal_groups = 'Skupiny';
$cal_new_group = 'Nová skupina';
$cal_group_exists = 'Tato skupina již existuje. Prosím, vyberte si jiné jméno.';
$cal_no_calendars = 'Tato skupina neobsahuje žádné kaledáře';
$cal_group = 'Skupina';
$cal_resources = 'Zdroje';

$cal_event_mail_subject = 'Událost \'%s\' vytvořena ve Vašem kalendáři';//%s is event name
$cal_event_mail_body = '%s vytvořil schůzku \'%s\' ve Vašem kalendáři jménem \'%s\'.'; //irst %s is the name of the person who created the event. Second is the event name, third is the calendar name
$cal_event_mail_open = 'Otevři schůzku';
$cal_add_custom_field = 'Vyberte vlastní pole';

$cal_event_modified_mail_subject = 'Událost \'%s\' byla modifikována ve Vašem kalendáři';//%s is event name
$cal_event_modified_mail_body = '%s vytvořil schůzku \'%s\' ve Vašem kalendáři jménem \'%s\'.'; //First %s is the name of the person who created the event. Second is the event name, third is the calendar name

$cal_your_event_modified_mail_subject = 'Událost \'%s\' Vámi vytvořená byla modifikována';//%s is event name
$cal_your_event_modified_mail_body = '%s modifikoval schůzku \'%s\' která byla vytvořena Vámi.'; //First %s is the name of the person who created the event. Second is the event name.
$cal_no_custom_fields = 'Nebyla definována žádná vlastní pole';
$cal_add_field = 'Přidej pole';


$cal_resource_mail_subject = 'Zdroj \'%s\' zadán'; //%s is resource name
$cal_resource_mail_body = '%s udělal záznam pro tento zdroj \'%s\'. Jste správce tohoto zdroje. Prosím otevřete pro odmítnutí nebo potvrzení záznamu.'; //First %s is the name of the person who created the event. Second is the calendar name
$cal_open_resource = 'Otevři zadání';

$cal_resource_modified_mail_subject = 'Zdrojový \'%s\' záznam modifikován';//%s is resource name
$cal_resource_modified_mail_body = '%s modifikoval záznam zdroje \'%s\'. '; //First %s is the name of the person who created the event. Second is the calendar name

$cal_your_resource_modified_mail_subject = 'Váš záznam pro \'%s\' se statusem %s je modifikován';//%s is resource name, status
$cal_your_resource_modified_mail_body = '%s modifikoval záznam zdroje \'%s\'Jste správce tohoto zdroje. Prosím otevřete pro odmítnutí nebo potvrzení záznamu.'; //First %s is the name of the person who created the event. Second is the calendar name


$cal_accept_mail_subject = 'Pozvánka na \'%s\' akceptována';
$cal_accept_mail_body = '%s akceptoval Vaši pozvánku na \'%s\'';

$cal_decline_mail_subject = 'Pozvánka na \'%s\' zamítnuta';
$cal_decline_mail_body = '%s zamítl Vaši pozvánku na \'%s\'';

$cal_statuses['NEEDS-ACTION'] = 'Stále v řešení';
$cal_statuses['ACCEPTED'] = 'Přijatý';
$cal_statuses['DECLINED'] = 'Odmítnutý';
$cal_statuses['TENTATIVE'] = 'Nezávazný';
$cal_statuses['DELEGATED'] = 'Delegovaný';
$cal_statuses['COMPLETED'] = 'Hotový';
$cal_statuses['IN-PROCESS'] = 'Dělá se na tom';

$cal_booking = 'Záznam pro \'%s\'';//%s is resource name

$cal_group_admins = 'Admins';
$cal_no_admins = 'Zádný administrátor definován';
$cal_add_admin = 'Přidej administrátora';

$cal_scale='Míra';

$cal_show_completed = 'Ukaž hotové úkoly';

$cal_resource = 'Zdroj';
$cal_grid_view = 'Zobrazení jako síť';

$cal_field_types['checkbox'] = 'Checkbox';
$cal_field_types['text'] = 'Text';
$cal_field_types['textarea'] = 'Textarea';
$cal_field_types['date'] = 'Datum';

$cal_conflict = 'Tato událost je v konfliktu s jinou událostí nebo se zdrojovými záznamy. Klikněte na \'Ok\' nebo \'Apply\' znova pro ignorování nebo klikněte na \'Check availability\' pro nalezení vhodného času.';

$cal_select_calendar = 'Vyberte kalendář';
$cal_check_conflicts = 'Upozorni měna konflikty, kdyz vytvořím událost';
$cal_email_changes = 'Pošli e-mail když někdo udělá změny v mém kalendáři';
$cal_shared_calendars = 'Sdílené kalendáře';

$cal_admin = 'Administrace';
$cal_resource_groups = 'Zdrojové skupiny';
$cal_open_calendar = 'Otevři dalsí kalendář';

$cal_email_reminders='Pošli upozornění na událost emailem';

$cal_favourites = 'Oblíbené';

$cal_your_resource_accepted_mail_subject = 'Záznam pro \'%s\' je akceptován';//%s is resource name, status
$cal_your_resource_accepted_mail_body = '%s akceptoval záznam pro zdroj \'%s\'.'; //First %s is the name of the person who created the event. Second is the calendar name

$cal_your_resource_declined_mail_subject = 'Záznam pro \'%s\' je zamítnut';//%s is resource name
$cal_your_resource_declined_mail_body = '%s zamítl Váš záznam pro zdroj \'%s\'.'; //First %s is the name of the person who created the event. Second is the calendar name

$cal_resource_deleted_mail_subject = 'Záznam pro \'%s\' je smazán';//%s is resource name, status

$cal_repeats_at = 'Opakuj kazdé %s v %s';//eg. Repeats every month at the first monday
$cal_repeats_at_not_every = 'Opakuj každé %s %s v %s';//eg. Repeats every 2 weeks at monday 

$cal_repeats = 'Opakuj každé %s';

$cal_and='a';
$sc_months='měsíce';
$sc_month='měsíc';
$sc_year='rok';
$sc_years='roky';

$cal_another_resource = 'Zdroj byl změněn na %s';

$cal_background_colors = 'Barvy pozadí';

$cal_weekday = 'Pracovní den';
$cal_background_color='Barva pozadí';
$cal_background = 'Pozadí';

$cal_show_busy='Ukaž jako v činnosti';

$cal_subject='Předmět';
$cal_dismiss_all = 'Zruš vše';
$cal_schedule_group='Plánované události pro všechny uživatele jsou ve výchozím zobrazení. (Jinak je pouze vybrám výchozí kalendář)';

$cal_help_url='http://docs.group-office.com/index.php?folder_id=58&file_id=0';
$td_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=217';



