<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('calendar'));
$htmldirection='rtl';
#charset='UTF-8';

$sc_title = "כותרת";
$sc_description = "תיאור";
$sc_participants = "מוזמנים";

$sc_location = "מיקום";

$month_times[0] = "ראשון";
$month_times[1] = "שני";
$month_times[2] = "שלישי";
$month_times[3] = "רביעי";

$sc_new_app = "אירוע חדש";
$sc_calendars = "יומנים";
$sc_invited = 'הנך מוזמן להצתרף לאירוע הנ"\ל.';

$sc_types1[0] = 'ללא חזרה';
$sc_types1[1] = 'ימים';
$sc_types1[2] = 'שבועות';
$sc_types1[3] = 'חודשים לפי תאריך';
$sc_types1[4] = 'חודשים לפי יום';
$sc_types1[5] = 'שנים';


$sc_types[0] = 'חד פעמי';
$sc_types[1] = 'יומי';
$sc_types[2] = 'שבועי';
$sc_types[3] = 'חודשי לפי תאריך';
$sc_types[4] = 'חודשי לפי יום';
$sc_types[5] = 'שנתי';


$sc_start_at = 'מתחיל ב';
$sc_end_at = 'מסתיים ב';
$sc_start_time = 'זמן התחלה';
$sc_end_time = 'זמן סיום';

$sc_at_days = 'בימים';
$sc_of_month = 'של החודש.';

$sc_cycle_start = 'מחזור מתחיל ב';
$sc_cycle_end = 'חזור עד';
$sc_accept_question = 'האם הנך רוצה לקבל ולשבץ אירוע זה?';

$sc_accept = 'קבל';
$sc_decline = 'סרב';

$sc_notime = 'זמן אינו ישים';
$sc_noend = 'אין תאריך סיום.';

$sc_never_happens = 'קלט שגוי! אירוע זה לעולם לא קורא.';
$sc_start_later = 'קלט שגוי! זמן ההתחלה מאוחר יותר מזמן הסיום.';

$sc_add_self = 'קלט ידני';

$sc_select_calendar = 'בחר את היומן לשבץ אירוע זה';
$sc_accept_confirm = 'אירוע זה התקבל ושובץ.';
$sc_no_calendars = 'לא נמצא יומן תקין לשבץ אירוע זה.';
$sc_bad_event = 'לא נמצא אירוע תקין. כנראה שהאירוע נמחק.';
$sc_accept_title = 'קבל אירוע';

$sc_decline_confirm = '.האירוע סורב';
$sc_decline_title = 'סרב אירוע';

$sc_status = 'סטטוס';
$sc_not_responded = 'ללא תגובה';
$sc_accepted = 'התקבל';
$sc_declined = 'סורב';
$sc_no_participants = 'אין משתתפים';

$sc_person = 'בן אדם';
$sc_owner = 'בעלים';
$sc_type = 'סוג';
$sc_subscribed = 'מנוי';

$sc_subscribe = 'עשה מנוי';
$sc_new_calendar = 'יומן חדש';
$sc_no_calendar = 'לא נמצא יומן. אנא צור אחד חדש עכשיו או תן לגרופ-אופיס ליצור אחד בצורה אוטומטית עבורך.';
$sc_day_view = 'תצוגה יומית';
$sc_week_view = 'תצוגה שבועית';
$sc_list_view = 'תצוגת רשימה';
$sc_put_in = 'הכנס אירוע';
$sc_inherit_permissions ='רש זכויות מ';
$sc_no_inherit = 'אל תרש';

$sc_select_calendar_please = 'אנא בחר ביומן אחד לפחות.';
$sc_events = 'אירועים';

$sc_from_calendar = 'מיומן';
$sc_enitrely = 'לחלוטין';
$sc_delete_event = 'מחק אירוע';
$sc_delete_pre = 'האם ברצונך למחוק את האירוע';
$sc_delete_suf = 'לחלוטין או רק מיומן זה?';

$sc_refresh = 'רענן';
$sc_reminder = 'תזכורת';
$sc_mins = 'דקות';
$sc_hour = 'שעה';
$sc_hours = 'שעות';
$sc_day = 'יום';
$sc_days = 'ימים';
$sc_week = 'שבוע';
$sc_weeks = 'שבועות';
$sc_reminder_set_to_early = "אי אפשר לקבוע שהתזכורת תופיע לפני המאורע הקודם. אנא קצר את זמן התזכורת או הארך את תקופת החזרה.";
$sc_cycle_start_later = 'זמן ההתחלה של המחזור מאוחר או שווה לזמן הסיום.';


$cmdGenerate = 'חולל';
$sc_preferences = 'העדפות';
$sc_holidays = 'חגים';

$strNoHolidays = 'אין חגים במאגר הנתונים';
$strUnknown = 'לא ידוע';
$strYear = 'שנה';
$strDeleteHolidaysPrefix = 'האם הנך בטוח שברצונך למחוק את כל רשומות החגים של השנה  ';
$strDeleteHolidaysSuffix = '?';
$strReplaceHolidays = 'האם הנך בטוח שברצונך להחליף את כל רשומות החגים הקיימות?';
$sc_holidays_text1 = 'כדי לחשב את רשומות החגים לשנה שנבחרה. \''.$cmdGenerate.'\' אנא לחץ על';
$sc_holidays_text2 = 'כדי לשמור את כל רשומות החגים שחושבו במאגר הנתונים. \''.$cmdApply.'\' אנא לחץ על';

//translation required below this
$sc_client = 'לקוח';
$sc_no_contact = 'אין';

$sc_background = 'רקע';

$sc_colors['red'] = 'אדום';
$sc_colors['green'] = 'ירוק';
$sc_colors['blue'] = 'כחול';
$sc_colors['pink'] = 'ורוד';
$sc_colors['orange'] = 'כתום';
$sc_colors['brown'] = 'חום';
$sc_colors['yellow'] = 'צהוב';
$sc_colors['grey'] = 'אפור';
$sc_colors['purple'] = 'סגול';
$sc_colors['white']= 'לבן';
$sc_status = 'סטטוס';

$sc_show_hours = 'הצג שעות מ';
$sc_to = 'עד';

$sc_today = 'היום';

$sc_recur_every = 'חזור כל';
$sc_months = 'חודשים';

$sc_private_event = 'אירוע פרטי';
$sc_calendar_exists = 'יומן עם שם זה כבר קיים';
//translate
$sc_month = 'חודש';
$sc_view = 'תצוגה';
$sc_calendar = 'יומן';
$sc_default = 'ברירת מחדל';
$sc_month_view = 'תצוגה חודשית';

//text changed, needs new translation
$sc_holidays_no_file_prefix = ' החגים לא חוללו כיוון שהקובץ שמחיל את המידע על החגים ';
$sc_holidays_no_file_suffix = 'לשפה ריק או אינו קיים.';

$sc_no_events = 'לא נמצאו אירועים';

//2.03
$cal_export = 'יצא';
$cal_import = 'יבא';
$cal_please_wait = 'אנא המתן...';
$cal_import_text = 'בחר קובץ iCal (*.ics) ולחץ על \'Ok\'';
$cal_filename = 'קובץ';
$cal_import_success = 'מידע יובא';

//2.04
$cal_add_todo = 'משימה חדשה';
$cal_todos = 'משימות';

$cal_hide_completed = 'החבא משימות שהושלמו';
$cal_show_all = 'הצג את כל המשימות';
$cal_show_own = 'הצג משימות שלי';
$cal_show_responsible = 'הצג משימות שהני אחראי עליהם';

$cal_priority = 'עדיפות';
$cal_priority_values[0] = 'נמוכה';
$cal_priority_values[1] = 'רגילה';
$cal_priority_values[2] = 'גבוהה';

$cal_status = 'סטטוס';
$cal_canceled = 'בוטל';
$cal_completed = 'הושלם ב';
$cal_percent_completed = '% הושלם';

$cal_before_task_start = 'לפני שהמשימה מתחילה';
$cal_before_task_due = 'לפני שהמשימה אמורה להסתיים';
$cal_responsible = 'אחראי';
$cal_due_at = 'מועד סיום';
$cal_no_todos= 'לא נמצאו משימות';
$cal_resend_invitation = 'שלך הזמנה מחדש';

//2.05
$cal_everybody_write = 'כל אחד יכול לשנות אירוע זה';
$cal_everybody_read = 'רק אני יכול לשנות אירוע זה';

$cal_view = 'תצוגה';
$cal_views = 'תצוגות';
$sc_view_exists = 'תצוגה עם שם זה כבר קיימת';
$cal_new_view = 'תצוגה חדשה';
$cal_event_calendars = 'יומנים';

//2.06
$cal_view_merged = 'מוזג';
$cal_view_emerged = 'הופיע';
