<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('calendar'));

$sc_title = "Naslov";
$sc_description = "Opis";
$sc_participants = "Povabljenci";

$sc_location = "Mesto";

$month_times[0] = "Prvi";
$month_times[1] = "Drugi";
$month_times[2] = "Tretji";
$month_times[3] = "Èetrti";

$sc_new_app = "Nov dogodek";
$sc_calendars = "Koledarji";
$sc_invited = 'Povabljeni ste bili, da se pridru¾ite spodnjemu dogodku.';
$sc_invited = 'Povabljeni ste, da se pridru¾ite spodaj opisanemu dogodku.';

$sc_types1[0] = 'Brez ponovitev';
$sc_types1[1] = 'dni';
$sc_types1[2] = 'tedni';
$sc_types1[3] = 'meseci po datumu';
$sc_types1[4] = 'meseci po dnevih';
$sc_types1[5] = 'leta';


$sc_types[0] = 'Enkrat';
$sc_types[1] = 'Dnevno';
$sc_types[2] = 'Vsak teden';
$sc_types[3] = 'Vsak mesec na datum';
$sc_types[4] = 'Vsak mesec na dan';
$sc_types[5] = 'Vsako leto';

$sc_start_at = 'Zaèetek ob';
$sc_end_at = 'Konec ob';
$sc_start_time = 'Zaèetni èas';
$sc_end_time = 'Konèni èas';

$sc_at_days = 'Ob dnevih';
$sc_of_month = 'v mesecu.';
$sc_of_month = 'meseca.';

$sc_cycle_start = 'Cikel se zaène ob';
$sc_cycle_start = 'Ciklus se zaène ob';
$sc_cycle_end = 'Ponavljaj do';
$sc_cycle_end = 'Ciklus se konèa ob';
$sc_accept_question = 'Ali ¾elite sprejeti in shraniti ta dogodek?';
$sc_accept_question = 'Ali ¾elite sprejeti in èasovno razporediti ta dogodek?';

$sc_accept = 'potrdi';
$sc_accept = 'potrdi';
$sc_decline = 'zavrni';
$sc_decline = 'zavrni';

$sc_notime = 'Neveljaven èas';
$sc_notime = 'Èas ni veljaven';
$sc_noend = 'Ni konènega datuma.';
$sc_noend = 'Ni konènega datuma.';

$sc_never_happens = 'Napaèen vnos! Ta dogodek ni mogoè.';
$sc_never_happens = 'Napaèen vnos. Ta dogodek se nikoli ne dogodi.';
$sc_start_later = 'Napaèen vnos!! Zaèetni datum je kasnej¹i od konènega.';
$sc_start_later = 'Napaèen vnos! Zaèetni èas je kasnej¹i od konènega.';

$sc_add_self = 'Roèni vnos';
$sc_add_self = 'Roèni vnos';

$sc_select_calendar = 'Izberite koledar, v katerem boste nastavili dogodek';
$sc_accept_confirm = 'Dogodek je sprejet in shranjen.';
$sc_accept_confirm = 'Dogodek je bil sprejet in èasovno razporejen.';
$sc_no_calendars = 'Veljavnega koledarja ni bilo mogoèe najti, da bi ga dodali v razpored.';
$sc_bad_event = 'Dogodka ni bil najden. Dogodek je bil verjetno izbrisan.';
$sc_bad_event = 'Ni veljavnega dogodka. Dogodek je bil verjetno izbrisan.';
$sc_accept_title = 'Sprejmi dogodek';
$sc_accept_title = 'Sprejmi dogodek';

$sc_decline_confirm = 'Dogodek je zavrnjen.';
$sc_decline_title = 'Zavrni dogodek';

$sc_status = 'Stanje';
$sc_not_responded = 'Ni odziva';
$sc_accepted = 'Sprejet';
$sc_declined = 'Zavrnjen';
$sc_no_participants = 'Ni udele¾encev';

$sc_person = 'Oseba';
$sc_owner = 'Lastnik';
$sc_type = 'Vrsta';
$sc_subscribed = 'Naroèen';

$sc_subscribe = 'Naroèi';
$sc_new_calendar = 'Nov koledar';
$sc_no_calendar = 'Koledarja ni bilo mogoèe najti. Prosim, naredite novega ali pa pustite, da Group-Office samodejno naredi novega.';
$sc_day_view = 'Po&nbsp;dnevih';
$sc_day_view = 'Dnevni&nbsp;pogled';
$sc_week_view = 'Tedenski&nbsp;pogled';
$sc_week_view = 'Tedenski&nbsp;pogled';
$sc_list_view = 'Izpisni&nbsp;pogled';
$sc_list_view = 'Seznam';
$sc_put_in = 'Vstavi dogodek v';
$sc_put_in = 'Postavi dogodek v';
$sc_inherit_permissions ='Podeduj dovoljenja od';
$sc_no_inherit = 'Ne podeduj';
$sc_no_inherit = 'Ne podeduj';

$sc_select_calendar_please = 'Prosim, izberite vsaj en koledar.';
$sc_events = 'Dogodki';
$sc_events = 'Dogodki';

$sc_from_calendar = 'iz koledarja';
$sc_enitrely = 'V celoti';
$sc_enitrely = 'Celotno';
$sc_delete_event = 'Zbri¹i dogodek';
$sc_delete_event = 'Zbri¹i dogodek';
$sc_delete_pre = 'Ali ¾eli¹ zbrisati dogodek?';
$sc_delete_pre = 'Ali ste preprièani, da ¾elite zbrisat dogodek';
$sc_delete_suf = 'v celoti, ali samo iz tega koledarja?';
$sc_delete_suf = 'celotno ali samo iz tega urnika?';

$sc_refresh = 'Osve¾i';
$sc_reminder = 'Opomnik';
$sc_mins = 'minut';
$sc_hour = 'ura';
$sc_hours = 'ure';
$sc_day = 'dan';
$sc_days = 'dni';
$sc_week = 'teden';
$sc_weeks = 'tedni';
$sc_reminder_set_to_early = "Opomnik ne more biti nastavljen tako, da se pojavi pred prej¹njim dogodkom. Prosim, zmanj¹ajte èas opomnika ali podalj¹ajte obdobje ponovitve.";
$sc_reminder_set_to_early = "Opomnik se ne more pojaviti pred prej¹njim pojavom. Prosim zmanj¹ajte èas opomnika ali dol¾ino obdobja ponavljanja.";
$sc_cycle_start_later = 'Zaèetni datum je veèji ali enak konènemu datumu.';
$sc_cycle_start_later = 'Zaèetni datum ciklusa je poznej¹i ali enak konènem datumu.';


$cmdGenerate = 'Ustvari';
$sc_preferences = 'Nastavitve';
$sc_holidays = 'Prazniki';

$strNoHolidays = 'V zbirki podatkov ni praznikov';
$strUnknown = 'Neznano';
$strYear = 'Leto';
$strDeleteHolidaysPrefix = 'Ali ste preprièani, da ¾elite zbrisat vse zapise o praznikih izbranega leta';
$strDeleteHolidaysSuffix = '?';
$strReplaceHolidays = 'Ali ste preprièani da ¾elite prepisati vse obstojeèe zapise o praznikih?';
$sc_holidays_text1 = 'Prosim, kliknite na \''.$cmdGenerate.'\' za izraèun poèitni¹kih dni za izbrano leto.';
$sc_holidays_text2 = 'Prosim, kliknite na \''.$cmdApply.'\', da v zbirko podatkov shranite vse izraèunane zapise praznikov.';

//translation required below this
$sc_client = 'Odjemalec';
$sc_no_contact = 'Noben';

$sc_background = 'Ozadje';

$sc_colors['red'] = 'Rdeèe';
$sc_colors['green'] = 'Zeleno';
$sc_colors['blue'] = 'Modro';
$sc_colors['pink'] = 'Ro¾nato';
$sc_colors['orange'] = 'Oran¾no';
$sc_colors['brown'] = 'Rjavo';
$sc_colors['yellow'] = 'Rumeno';
$sc_colors['yellow'] = 'Rumeno';
$sc_colors['grey'] = 'Sivo';
$sc_colors['purple'] = 'Vijolièno';
$sc_colors['white']= 'Belo';
$sc_status = 'Stanje';

$sc_show_hours = 'Poka¾i ure iz';
$sc_to = 'do';

$sc_today = 'Danes';

$sc_recur_every = 'Vrni vse';
$sc_months = 'meseci';

$sc_private_event = 'Zasebni dogodek';
$sc_calendar_exists = 'Koledar s tem imenom ¾e obstaja';
//translate
$sc_month = 'Mesec';
$sc_view = 'Pogled';
$sc_calendar = 'Koledar';
$sc_default = 'Privzeto';
$sc_month_view = 'Meseèni&nbsp;pogled';

//text changed, needs new translation
$sc_holidays_no_file_prefix = 'Poèitnice ne morejo biti ustvarjene, ker je datoteka, ki vsebuje informacije o praznikih za va¹o regijo [\'';
$sc_holidays_no_file_suffix = '\'] prazna ali pa ne obstaja.';

$sc_no_events = 'Ni najdenega dogodka.';

//2.03
$cal_export = 'Izvozi';
$cal_import = 'Uvozi';
$cal_please_wait = 'Prosimo, poèakajte...';
$cal_import_text = 'Izberi iCal (*.ics) datoteko in klikni na \'V redu\'';
$cal_filename = 'Datoteka';
$cal_import_success = 'Podatki uvo¾eni';

//2.04
$cal_add_todo = 'Novo opravilo';
$cal_todos = 'Opravila';

$cal_hide_completed = 'Skrij dokonèane';
$cal_show_all = 'Poka¾i vsa opravila';
$cal_show_own = 'Poka¾i lastna opravila';
$cal_show_responsible = 'Poka¾i odgovorna opravila';

$cal_priority = 'Prednost';
$cal_priority_values[0] = 'Nizko';
$cal_priority_values[1] = 'Normalno';
$cal_priority_values[2] = 'Visoko';

$cal_status = 'Stanje';
$cal_canceled = 'Preklicano';
$cal_completed = 'Konèano ob';
$cal_percent_completed = '% dokonèano';

$cal_before_task_start = 'Preden se opravilo zaène';
$cal_before_task_due = 'Preden bi moralo biti opravilo dokonèano';
$cal_responsible = 'Odgovoren';
$cal_due_at = 'Zaradi';
$cal_no_todos= 'No tasks found';
$cal_resend_invitation = 'Ponovno po¹lji vabilo';

//2.05
$cal_everybody_write = 'Vsak lahko spremeni ta dogodek';
$cal_everybody_read = 'Samo jaz lahko spremenim ta dogodek';

$cal_view = 'Pogled';
$cal_views = 'Pogledi';
$sc_view_exists = 'Pogled s tem imenom ¾e obstaja';
$cal_new_view = 'Nov pogled';
$cal_event_calendars = 'Koledar(ji)';
