<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('calendar'));

$sc_title = "ชื่อเรื่อง";
$sc_description = "คำอธิบาย";
$sc_participants = "ชวนเพื่อน";

$sc_location = "ตำแหน่ง";

$month_times[0] = "หนึ่ง";
$month_times[1] = "สอง";
$month_times[2] = "สาม";
$month_times[3] = "สี่";

$sc_new_app = "เหตุการณ์ใหม่";
$sc_calendars = "ปฏิทิน";
$sc_invited = 'คุณได้ชวนเพื่อนด้วยเหตุการด้านล่างแล้ว';

$sc_types1[0] = 'ไม่มีการย้อนกลับมาใหม่';
$sc_types1[1] = 'วัน';
$sc_types1[2] = 'สัปดาห์';
$sc_types1[3] = 'เดือนของวันที่';
$sc_types1[4] = 'เดือนของวัน';
$sc_types1[5] = 'ปี';


$sc_types[0] = 'ครั้งเดียว';
$sc_types[1] = 'ทุกวัน';
$sc_types[2] = 'ทุกสัปดาห์';
$sc_types[3] = 'ทุกเดือนของวันที่';
$sc_types[4] = 'ทักเดือนของวัน';
$sc_types[5] = 'ทุกปี';


$sc_start_at = 'เริ่มที่';
$sc_end_at = 'สิ้นสุดที่';
$sc_start_time = 'เวลาเริ่ม';
$sc_end_time = 'เวลาสิ้นสุด';

$sc_at_days = 'สัปดาห์ที่';
$sc_of_month = 'ของเดือน';

$sc_cycle_start = 'เริ่มครบรอบที่';
$sc_cycle_end = 'เกิดขึ้นอีกจนกระทั้ง';
$sc_accept_question = 'คุณยอมรับเหตุการณ์ในตารางงานนั้นแล้ว?';

$sc_accept = 'ยอมรับ';
$sc_decline = 'ปฏิเสธ';

$sc_notime = 'ไม่แสดงเวลาสำหรับงานนี้';
$sc_noend = 'ไม่มีวันสิ้นสุด';

$sc_never_happens = 'ข้อมูลไม่ถูกต้อง! เหตุการณ์นี้ไม่ควรเกิดขึ้น.';
$sc_start_later ='ข้อมูลไม่ถูกต้อง!! เวลาเริ่ม เกิดทีหลัง เวลาสิ้นสุด';

$sc_add_self = 'ป้อนข้อมูลด้วยตนเอง';

$sc_select_calendar = 'เลือกจากปฏิทินเพื่อนำงานเข้าสู่ตารางงาน';
$sc_accept_confirm = 'เหตุการณ์นี้ได้ยอมรับแล้วและงานได้ผ่านไปแล้ว';
$sc_no_calendars = 'ไม่พบตารางเวลาในเหตุการณ์นี้.';
$sc_bad_event = 'ไม่พบเหตุการใดๆ หรือไม่อาจถูกลบไปแล้ว.';
$sc_accept_title = 'ยอมรับเหตุการณ์';

$sc_decline_confirm = 'เหตุการณ์ถูกปฏิเสฐ';
$sc_decline_title = 'ปฏิเสฐเหตุการนี้';

$sc_status = 'สถานะ';
$sc_not_responded = 'ไม่มีผลตอบสนอง';
$sc_accepted = 'ยอมรับ';
$sc_declined = 'ปฏิเสธ';
$sc_no_participants = 'ไม่มีผู้ส่วนร่วม';

$sc_person = 'บุคคล';
$sc_owner = 'เจ้าของ';
$sc_type = 'ชนิด';
$sc_subscribed = 'ลงชื่อ';

$sc_subscribe = 'ลงชื่อ';
$sc_new_calendar = 'สร้างปฏิทินใหม่';
$sc_no_calendar = 'ไม่พบปฏิทิน. กรุณาสร้างขึ้นมาใหม่หรือให้ Group-Office ทำการสร้างให้คุณโดยอัตโนมัติ.';
$sc_day_view = 'วัน';
$sc_week_view = 'สัปดาห์';
$sc_list_view = 'รายการ';
$sc_put_in = 'นำเหตุการไว้ใน';
$sc_inherit_permissions ='ถ่ายทอดการอนุญาติ';
$sc_no_inherit = 'ไม่ถ่ายทอด';

$sc_select_calendar_please = 'กรุณาเลือกปฏิทินมากกว่าหนึ่ง';
$sc_events = 'เหตุการณ์';

$sc_from_calendar = 'จากปฏิทิน';
$sc_enitrely = 'โดยสิ้นเชิง';
$sc_delete_event = 'ลบเหตุการณ์';
$sc_delete_pre = 'คุณต้องการลบเหตุการณ์นี้';
$sc_delete_suf = 'ทั้งหมดหรือเฉพาะปฏิทินนี้?';

$sc_refresh = 'รีเฟรช';
$sc_reminder = 'ช่วยจำ';
$sc_mins = 'นาที';
$sc_hour = 'ชั่วโมง';
$sc_hours ='ชั่วโมง';
$sc_day = 'วัน';
$sc_days = 'วัน';
$sc_week = 'สัปดาห์';
$sc_weeks = 'สัปดาห์';
$sc_reminder_set_to_early = "The reminder cannnot be set to appear before the previous occurence. Please shorten the reminder time or lengthen the recurring period.";
$sc_cycle_start_later = 'The cycle starting date is later or equal then the ending date.';


$cmdGenerate = 'ทั่วไป';
$sc_preferences = 'รายละเอียด';
$sc_holidays = 'วันหยุด';

$strNoHolidays = 'ไม่มีวันหยุดในฐานข้อมูล';
$strUnknown = 'ไม่รู้';
$strYear = 'ปี';
$strDeleteHolidaysPrefix = 'คุณต้องการที่จะลบวันหยุดในรอบปีจากฐานข้อมูล';
$strDeleteHolidaysSuffix = '?';
$strReplaceHolidays = 'คุณต้องการจะบันทึกวันหยุดใหม่ทับวันหยุดเดิมที่ยังคงอยู่?';
$sc_holidays_text1 = 'กรุณาคลิกที่ปุ่ม \''.$cmdGenerate.'\' เพื่อประมวลผลวันหยุดจากปีที่เลือก.';
$sc_holidays_text2 = 'กรุณาคลิกที่ปุ่ม \''.$cmdApply.'\'เพื่อดึงข้อมูลวันหยุดจากฐานข้อมูล';

//translation required below this
$sc_client = 'ไคลเอนท์';
$sc_no_contact = 'ไม่มี';

$sc_background = 'สีพื้น';

$sc_colors['red'] = 'แดง';
$sc_colors['green'] = 'เขียว';
$sc_colors['blue'] = 'น้ำเงิน';
$sc_colors['pink'] = 'ชมพู';
$sc_colors['orange'] = 'ส้ม';
$sc_colors['brown'] = 'น้ำตาล';
$sc_colors['yellow'] = 'เหลือง';
$sc_colors['grey'] = 'เทา';
$sc_colors['purple'] = 'ม่วง';
$sc_colors['white']= 'ขาว';
$sc_status = 'สถานะ';

$sc_show_hours = 'แสดงชั่วโมงจาก';
$sc_to = 'ถึง';

$sc_today = 'วันนี้';

$sc_recur_every = 'ทุกๆ';
$sc_months = 'เดือน';

$sc_private_event = 'เหตุการณ์ส่วนตัว';
$sc_calendar_exists = 'ชื่อปฏิทินนี้ยังคงมีตนใช้';
//translate
$sc_month = 'เดือน';
$sc_view = 'มุมมอง';
$sc_calendar = 'ปฏิทิน';
$sc_default = 'ค่าที่เลือก';
$sc_month_view = 'เดือน';

//text changed, needs new translation
$sc_holidays_no_file_prefix = 'ไม่สามารถสร้างวันหยุดได้ เนื่องจากไฟล์ที่บระจุข้อมูลของวันหยุดนั้น';
$sc_holidays_no_file_suffix = ' ว่างเปล่าหรือ ไม่มีภาษานี้อยู่เลย';

$sc_no_events = 'ไม่พบเหตุการณ์';

//2.03
$cal_export = 'ส่งออก';
$cal_import = 'นำเข้า';
$cal_please_wait = 'โปรดคอย';
$cal_import_text = 'เลือกไฟล์ (*.ics) แล้วคลิก \'ตกลง\'';
$cal_filename = 'File';
$cal_import_success = 'ข้อมูลนำเข้าแล้ว';

//2.04
$cal_add_todo = 'สร้างงานใหม่';
$cal_todos = 'งาน';

$cal_hide_completed = 'การซ่อนสำเร็จ';
$cal_show_all = 'แสดงงานทั้งหมด';
$cal_show_own = 'แสดงงานส่วนตัว';
$cal_show_responsible = 'แสดงผมตอบกลับของงาน';

$cal_priority = 'ความสำคัญ';
$cal_priority_values[0] = 'ต่ำ';
$cal_priority_values[1] = 'ปานกลาง';
$cal_priority_values[2] = 'สูง';

$cal_status = 'สถานะ';
$cal_canceled = 'ยเลิก';
$cal_completed = 'สำเร็จที่';
$cal_percent_completed = '% สำเร็จแล้ว';

$cal_before_task_start = 'ก่อนงานเริ่ม';
$cal_before_task_due = 'ก่อนงานควรจะจบ';
$cal_responsible = 'ผลตอบกลับ';
$cal_due_at = 'วันเก็บงิน';
$cal_no_todos= 'ไม่พบงาน';
$cal_resend_invitation = 'ชักชวนอีกครั้ง';

//2.05
$cal_everybody_write = 'ทุกคนสามารถแก้ไขเหตุการนี่';
$cal_everybody_read = 'ฉันเท่านั้นที่แก้ไขได้';

$cal_view = 'มุมมอง';
$cal_views = 'มุมมอง';
$sc_view_exists = 'ชื่อนี้ซ้ำ';
$cal_new_view = 'สร้างการดูขึ้นใหม่';
$cal_event_calendars = 'ปฏิทิน';

//2.06
$cal_view_merged = 'รวม';
$cal_view_emerged = 'แยก';


//2.08
$sc_recur_section = 'กระทำซ้ำ';
$sc_options_section = 'เพิ่มเติม';
$sc_close = 'ปิด';

$cal_count_single = 'เหตุการณ์';
$cal_count_multiple = 'เหตุการณ์';

$cal_until = 'จนถึง';
$cal_forever = 'ตลอดไป';

//2.09
$cal_merged_overview = 'รวมคำอธิบาย';
$cal_own_availability = 'เวลาที่ว่าง';
