<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='مرحباً فى';
$strUseMenu='إستخدم القائمة أو الوصلات السريعة';
$click_to_login='اضغط هنا للدخول';
$login_text='إكتب إسم المستخدم ثم كلمة المرور للدخول';
$login_username='اسم المستخدم';
$login_password='كلمه المرور';
$login_missing_field='انت لم تدخل اسم المستخدم او كلمه المرور';
$login_bad_login='اسم المستخدم  او كلمه المرور خطأ';
$login_remind='تذكرنى حتى أضغط على خروج';
$login_language='اللغة';
$login_here='هنا';
$login_lost_password='فقدت كلمه المرور';
$login_lost_password_title='استعادة كلمه المرور';
$login_lost_password_text='الرجاء ادخال عنوان البريد الالكتروني ادناه وكلمة سر جديدة سترسل الى عنوان بريدك الالكتروني';
$login_lost_password_mail_body='"استعلم على كلمه المرور الجديدة%s. سجيل الدخول الجديد بيانات لتسجيل الدخول في الدخول فى%s is:nnاسم المستخدم: %snكلمه المرور: %snnحظ سعيد';
$login_new_password='كلمه المرور الجديدة';
$login_lost_password_success='كلمه المرور الجديدة ارسلت الى';
$login_lost_password_failed='عفوا البريد الالكترونى غير مسجل هنا';
$login_fullscreen='تم فتح الشاشة كاملة بإمكانك إغلاق الشاشة و البدء مجدداً';
$login_start='البدء من جديد';
$login_to='دخولك هنا';
$login_no_account='لم تقوم بالتسجيل';
$login_register='اضغط هنا للتسجيل';
$login_no_account_text='تسجيل الدخول الى نظامنا عليك التسجيل مرة واحدة. عليك ان تشكل اسم المستخدم وكلمة السر التي يمكنك استخدامها لتسجيل الدخول في كل مرة';
?>