<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Добре дошли в ";
$strUseMenu = "Използвайте менюто или натиснете върху бързите линкове отдолу за да започнете ";
$click_to_login = "Натиснете бутона, за да продължите";
$login_text = "Въведете име и парола";
$login_username = "Име";
$login_password = "Парола";
$login_missing_field = "Не сте въвели вашето Потребителско име или Парола.";
$login_bad_login = "Грешно име или парола";
$login_remind = "Остави ме вързан в мрежата докато не натисна бутона за излизане.";
$login_language = 'Език';
