<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Benvinguts a ';
$strUseMenu='Utilitzeu el menú o feu clic a les dreceres de sota per començar ';
$click_to_login='Feu clic aquí per entrar.';
$login_text='Introduïu el vostre nom d\'usuari i la contrasenya per iniciar la sessió';
$login_username='Nom d\'usuari';
$login_password='Contrasenya';
$login_missing_field='No heu introduït el vostre nom d\'usuari o la contrasenya.';
$login_bad_login='Nom d\'usuari o contrasenya incorrectes';
$login_remind='Conserva la sessió fins que cliqui el botó de sortida.';
$login_language='Idioma';
$login_here='aquí';
$login_lost_password='contrasenya perduda?';
$login_lost_password_title='Recupera la contrasenya';
$login_lost_password_text='Si us plau, introduïu el vostre correu electrònic i se us enviarà una nova contrasenya a la vostra adreça.';
$login_lost_password_mail_body='Heu demanat una nova contrasenya per en %s. Les vostres dades per entrar com a %s són:nnNom d\'usuari: %snContrasenya: %snnBona sort!';
$login_new_password='Nova contrasenya';
$login_lost_password_success='Ha estat enviada una nova contrasenya a en %s';
$login_lost_password_failed='Ho sento, l\'adreça de correu electrònic \'%s\' no està registrada a aquest sistema.';
$login_fullscreen='Group-Office ha estat obert a pantalla sencera per a vostè automàticament. Podeu tancar la finestra o engegar Group-Office un altre cop.';
$login_start='Torna a començar';
$login_to='Entrada a %s';
$login_no_account='No esteu enregistrats encara?';
$login_register='o feu clic %s per signar';
$login_no_account_text='Per tal d\'entrar al nostre sistema us heu d\'enregistrar el primer cop. Necessiteu crear un nom d\'usuari i una contrasenya que pogueu fer servir per connectar-vos cada cop.';
?>