<?php
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Vítejte v"; 
$strUseMenu = "Využijte menu nebo klikněte na aktivní odkazy pro spuštění "; 
$click_to_login = "Zde klikněte pro přihlášení."; 
$login_text = "Uveďte Vaše uživatelské jméno a heslo pro přihlášení"; 
$login_username = "Uživatelské jméno"; 
$login_password = "Heslo"; 
$login_missing_field = "Neuvedl jste svoje uživatelské jméno nebo heslo."; 
$login_bad_login = "Nesprávné uživatelské jméno nebo heslo"; 
$login_remind = "Ponech mne přihlášeného dokud nestisknu odhlašovací tlačítko."; 
$login_language = 'Jazyk'; 

//2.12
$login_register = 'nebo klikněte %s pro přihlášení';
$login_here = "zde";
$login_lost_password = 'Zapoměli jste heslo?';
$login_lost_password_title = 'Obnova hesla';
$login_lost_password_text= 'Prosím zadejte svoji e-mailovou adresu a bude Vám na ni doručeno nové heslo.';
$login_lost_password_mail_body = "Požadujete nové heslo pro e-mail %s.\nVaše nové přihlašovací údaje pro %s jsou:\nJméno: %s\nHeslo: %s\n\nHodně štěstí!";
$login_new_password = 'Nové heslo';
$login_lost_password_success = 'Nové heslo bylo zaslána na %s';
$login_lost_password_failed = 'Litujeme, e-mailová adresa \'%s\' není v systému registrovaná.';

//2.14
$login_fullscreen = 'Group-Office byl zobrazen jako fullscreen automaticky. Můžete zavřít toto okno, nebo spustit Group-Office znova.';
$login_start = 'Spustit znova';

//2.16
$login_to = 'Přihlásit se k %s';
$login_no_account = 'Ještě neregistrován(a)?';
$login_register = 'Klikněte sem pro registraci %s';
$login_no_account_text = 'K přihlásění do systému potřebujete registraci.';
