<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Velkommen til ";

$strUseMenu = "Brug menuen eller klik på et link forneden for at starte med at bruge ";
$click_to_login = "Klik her for at logge ind.";
$login_text = "Indtast brugernavn og adgangskode";
$login_username = "Brugernavn";
$login_password = "Adgangskode";
$login_missing_field = "Du glemte at udfylde brugernavn eller adgangskode.";
$login_bad_login = "Forkert brugernavn eller adgangskode";
$login_remind = "Lad mig være logget ind indtil jeg klikker på 'Log ud'.";
$login_language = 'Sprog';
