<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Willkommen in';
$strUseMenu='Bitte das Menü oder die unteren Links verwenden für die Arbeit mit';
$click_to_login='Zum Anmelden hier klicken.';
$login_text='Zum Anmelden Benutzername und Passwort eingeben';
$login_username='Benutzername';
$login_password='Passwort';
$login_missing_field='Benutzername oder Passwort wurde nicht eingegeben.';
$login_bad_login='Benutzername oder Passwort falsch';
$login_remind='Ich möchte angemeldet bleiben bis ich mich mit Logout abmelde.';
$login_language='Sprache';
$login_here='hier';
$login_lost_password='Passwort vergessen?';
$login_lost_password_title='Passwort anfordern';
$login_lost_password_text='Bitte geben Sie Ihre E-Mail-Adresse ein, anschließend erhalten Sie Ihr neues Passwort per E-Mail gesandt.';
$login_lost_password_mail_body='Sie haben für %s ein neues Passwort angefordert. Die neuen Anmeldedaten für %s lauten:nnBenutzername: %snPasswort: %snnViel Glück!';
$login_new_password='Neues Passwort';
$login_lost_password_success='Ein neues Passwort ist an %s gesandt worden';
$login_lost_password_failed='Leider ist diese Email-Adresse \'%s\' hier nicht registriert.';
$login_fullscreen='Group-Office wurde automatisch im neuen Fenster im Vollbildmodus geöffnet. Sie können dieses Fenster schließen oder Group-Office neu starten.';
$login_start='Neu starten';
$login_to='einloggen als %s';
$login_no_account='Noch nicht registriert?';
$login_register='Klicken Sie hier, um sich bei %s zu registrieren.';
$login_no_account_text='Um sich in das System einloggen zu können, müssen Sie registriert. Sie müssen einen Benutzernamen und ein Passwort haben um sich einzuloggen.';
?>