<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Welcome to ";
$strUseMenu = "Use the menu or click on the fast links below to start using ";
$click_to_login = "Click here to login.";
$login_text = "Enter your username and password to login";
$login_username = "Username";
$login_password = "Password";
$login_missing_field = "You didn't fill out your username or password.";
$login_bad_login = "Wrong username or password";
$login_remind = "Keep me logged in till I press the logout button.";
$login_language = 'Language';

//2.12
$login_here = "here";
$login_lost_password = 'Lost password?';
$login_lost_password_title = 'Recover password';
$login_lost_password_text= 'Please enter your e-mail adress below and a new password will be sent to your e-mail address.';
$login_lost_password_mail_body = "You requested a new password for %s. Your new login data to login at login at %s is:\n\nUsername: %s\nPassword: %s\n\nGood luck!";
$login_new_password = 'New password';
$login_lost_password_success = 'A new password has been sent to %s';
$login_lost_password_failed = 'Sorry, the e-mail address \'%s\' is not registered here.';

//2.14
$login_fullscreen = 'Group-Office has been opened fullscreen for you automatically. You can close this window or start Group-Office again.';
$login_start = 'Start again';

//2.16
$login_to = 'Login to %s';
$login_no_account = 'Not registered yet?';
$login_register = 'Click here to register at %s';
$login_no_account_text = 'To login to our system you need to register once. You need to make up a username and password that you can use to login each time.';
