<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Bienvenido a ';
$strUseMenu='Use el menú o haga click en los accesos directos para iniciar cualquier aplicación de ';
$click_to_login='Haga click aquí para entrar.';
$login_text='Introduzca su nombre de usuario y contraseña para iniciar la sesión';
$login_username='Nombre de usuario';
$login_password='Contraseña';
$login_missing_field='No ha introducido el nombre de usuario o la contraseña.';
$login_bad_login='Nombre de usuario o contraseña incorrectos.';
$login_remind='Conservar la sesión hasta que pulse el botón de salir.';
$login_language='Idioma';
$login_here='aquí';
$login_lost_password='¿Contraseña perdida?';
$login_lost_password_title='Recuperar contraseña';
$login_lost_password_text='Por favor, introduzca su correo electrónico y se le enviará una nueva contraseña a su dirección.';
$login_lost_password_mail_body='ha pedido una nueva contraseña para %s. Sus datos para entrar como %s son:nnNombre de usuario: %snContraseña: %snn¡Buena suerte!';
$login_new_password='Nueva contraseña';
$login_lost_password_success='Ha sido enviada una nueva contraseña a %s';
$login_lost_password_failed='Lo siento, la dirección de correo electrónico \'%s\' no está registrada en este sistema.';
$login_fullscreen='Group-Office ha sido abierto en pantalla completa automáticamente. Puede cerrar esta ventana o iniciar Group-Office de nuevo.';
$login_start='Iniciar de nuevo';
$login_to='Conectarse a %s';
$login_no_account='¿No se ha registrado todavía?';
$login_register='o haga click en %s para registrarse';
$login_no_account_text='Para entrar en nuestro sistema necesita registrarse la primera vez. Necesitará crear un nombre de usuario y una contraseña que pueda usar para entrar cada vez.';
?>