<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Tervtuloa ";
$strUseMenu = "Aloita käyttö käytämällä valikkoa tai napsauta alapuolisia linkkejä ";
$click_to_login = "Paina tästä kirjautuaksesi sisään.";
$login_text = "Kirjoittaudu sisään syötämällä käyttäjätunnuksesi ja salasanasi";
$login_username = "Käyttäjätunnus";
$login_password = "Salasana";
$login_missing_field = "Et syöttänyt käyttäjätunnusta tai salasanaa.";
$login_bad_login = "Väärä käyttäjätunnus tai salasana";
$login_remind = "Pidä minut kirjautuneena kunnes kirjaudun ulos.";
$login_language = 'Kieli';

//2.12
$login_register = 'tai paina %s to sign up';
$login_here = "täällä";
$login_lost_password = 'Hukkunut salasana?';
$login_lost_password_title = 'Palauta salasana';
$login_lost_password_text= 'Syötä sähköpostiosoitteesi ja uusi salasana lähetetään sähköpostiosoitteeseesi.';
$login_lost_password_mail_body = "Käytttäjä %s pyysit uutta salasanaa. Uudet kirjautumistiedot %s ovat:\n\nKäyttäjätunnus: %s\nSalasana: %s\n\nOnnea!";
$login_new_password = 'Uusi salasana';
$login_lost_password_success = 'Uusi salasana on lähetetty käyttäjälle %s';
$login_lost_password_failed = 'Anteeksi, sähköpostiosoite \'%s\' ei ole rekisteröity täällä.';

//2.14
$login_fullscreen = $GO_CONFIG->title.' on avannut koko näytön sinulle automaattiseti. Voit sulkea ikkunan tai käynnistää Group-Office uudetaan.';
$login_start = 'Käynnistä uudelleen';
