<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$htmldirection='rtl';
$charset = 'UTF-8';

$strWelcomeTo = "ברוך/ה הבא/ה ";
$strUseMenu = "השתמש בתפריט או בקישורים תחת  שדה התחלה ";
$click_to_login = "לחץ כאן לכניסה";
$login_text = "הכנס שם משתמש וסיסמה";
$login_username = "שם משתמש";
$login_password = "סיסמה";
$login_missing_field = "לא מילית שם משתמש וסיסמה .";
$login_bad_login = "שם משתמש או סיסמה שגויים";
$login_remind = "השאר אותי בפנים עד שאני אבקש";
$login_language = 'שפה';
