<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Üdvözli Önt a ';
$strUseMenu='Használja ezt a menüt, vagy kattintson az alábbi linkek valamelyikére, hogy elkezdje használni a rendszert - ';
$click_to_login='A bejelentkezéshez kattintson ide.';
$login_text='A bejelentkezéshez adja meg a felhasználónevét és jelszavát';
$login_username='Felhasználónév';
$login_password='Jelszó';
$login_missing_field='Nem töltötte ki a felhasználónév vagy jelszó mezők valamelyikét.';
$login_bad_login='Érvénytelen felhasználónév vagy jelszó';
$login_remind='Addig maradjak bejelentkezve, amíg meg nem nyomom a kijelentkezés gombot.';
$login_language='Nyelv';
$login_fullscreen_link='Teljes képernyő';
$login_here='itt';
$login_lost_password='Elfelejtette a jelszavát?';
$login_lost_password_title='Jelszó visszaállítása';
$login_lost_password_text='Adja meg az e-mail címét, a rendszer ide fog küldeni Önnek egy új jelszót.';
$login_lost_password_mail_body='Új jelszót kért ehhez: %s. Az új bejelentkezési adatai a %s fiókhoz:nnFelhasználónév: %snnTovábbi jó munkát!';
$login_new_password='Új jelszó';
$login_lost_password_success='Az új jelszó el lett küldve neki: %s';
$login_lost_password_failed='Sajnálom, de \'%s\' e-mail címe nem szerepel az adatbázisban.';
$login_fullscreen='Group-Office automatikusan teljes képernyős üzemmódban nyílt meg. A rendszer újbóli indítását követően bezárhatja ezt az ablakot.';
$login_start='Újbóli indítás';
$login_to='Bejelentkezés ide: %s';
$login_no_account='Még nem rendelkezik felhasználói fiókkal?';
$login_register='A(z) %s rendszerébe történő regisztrációhoz kattintson ide';
$login_no_account_text='Csak regisztrált felhasználók jelentkezhetnek be ide. Ha be szeretne lépni, rendelkeznie kell egy felhasználónévvel és egy jelszóval.';
?>