<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Benvenuto in ';
$strUseMenu='Usa il menù o seleziona i collegamenti veloci sottostanti per iniziare ad usare ';
$click_to_login='Click qui per connettersi.';
$login_text='Inserire nome utente e password per connettersi';
$login_username='Nome utente';
$login_password='Password';
$login_missing_field='Non hai inserito il nomeutente o la password.';
$login_bad_login='Nome utente o password errate.';
$login_remind='Mantieni il collegamento finch&egrave; non seleziono \'disconnetti\'.';
$login_language='Lingua';
$login_here='qui';
$login_lost_password='Password dimenticata?';
$login_lost_password_title='Ripristino password';
$login_lost_password_text='Inserisci il tuo indirizzo e-mail e una nuova password ti sarà inviata alla casella e-mail specificata.';
$login_lost_password_mail_body='Hai richiesto una nuova password per %s. I tuoi nuovi dati per collegarti a %s sono:nnNome utente: %snPassword: %snnBuona fortuna!';
$login_new_password='Nuova password';
$login_lost_password_success='Una nuova password è stata inviata a %s';
$login_lost_password_failed='Siacenti, l\'indirizzo e-mail \'%s\' non è registrato qui.';
$login_fullscreen='GO_CONFIG->title.\' è stato aperto a schermo pieno automaticamente. Puoi chiudere questa finestra oppure avviare Group-Office nuovamente.';
$login_start='Avvia nuovamente';
$login_to='Effettua il login in %s';
$login_no_account='Non sei ancora registrato?';
$login_register='oppure seleziona %s per registrarti';
$login_no_account_text='Per l\'accesso al nostro sistema, devi registrarti una volta sola. Devi semplicemente specificare utente e password con cui accedere tutte le volte successive.';
?>