<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "ようこそ";
$strUseMenu = "お使いいただくためにメニューを使用するかショートカットをクリックしてください";
$click_to_login = "クリックしてログインしてください。";
$login_text = "ユーザ名とパスワードを入力してください。";
$login_username = "ユーザ名";
$login_password = "パスワード";
$login_missing_field = "ユーザ名とパスワードが入力されていません。";
$login_bad_login = "ユーザ名かパスワードが正しくありません。";
$login_remind = "ログインを記録";
$login_language = '言語';

//2.12
$login_register = 'もしくは、サインアップするために %s をクリックしてください。';
$login_here = "here";
$login_lost_password = 'パスワードを紛失しましたか?';
$login_lost_password_title = 'パスワードを回復';
$login_lost_password_text= 'E-mailアドレスを入力してください。新しいパスワードがE-mailアドレスに送られます。';
$login_lost_password_mail_body = "新規パスワードを要求しました。 %s. あなたの新しいログインデータは %s は:\n\nユーザ名: %s\nパスワード: %s\n\n";
$login_new_password = '新規パスワード';
$login_lost_password_success = '新しいパスワードは %s に送信されました。';
$login_lost_password_failed = ' \'%s\' のアドレスは登録されていません。';

//2.14
$login_fullscreen = $GO_CONFIG->title.' は自動的にフルスクリーン表示されました。このウィンドウを閉じるかGroup-Officeをもう一度開始してください。';
$login_start = '再スタート';
