<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Welkom bij ';
$strUseMenu='Gebruik het menu of klik op de snelkoppelingen hieronder om te starten met ';
$click_to_login='Klik hier om in te loggen';
$login_text='Voer gebruikersnaam en wachtwoord in om in te loggen';
$login_username='Gebruikersnaam';
$login_password='Wachtwoord';
$login_missing_field='U heeft uw wachtwoord of gebruikersnaam niet ingevuld.';
$login_bad_login='Wachtwoord of gebruikersnaam onjuist';
$login_remind='Klik hier om ingelogd te blijven tot U op uitloggen klikt.';
$login_language='Taal';
$login_here='hier';
$login_lost_password='Wachtwoord vergeten?';
$login_lost_password_title='Nieuw wachtwoord aanvragen';
$login_lost_password_text='Vul uw e-mail adres in en er zal een nieuw wachtwoord naar uw e-mail address worden verzonden.';
$login_lost_password_mail_body="U heeft een nieuw wachtwoord aangevraagd voor %s. Uw nieuwe login gegevens om in te loggen op \n\n%s\n\n zijn:\n\nGebruikersnaam: %s\nWachtwoord: %s\n\nVeel succes!";
$login_new_password='Nieuw wachtwoord';
$login_lost_password_success='Een nieuw wachtwoord is verzonden naar %s';
$login_lost_password_failed='Sorry, het e-mail adres \'%s\' is hier niet bekend.';
$login_fullscreen='Group-Office is automatisch voor u in een groter venster geopend. U kunt dit venster sluiten of Group-Office opnieuw starten.';
$login_start='Opnieuw starten';
$login_to='Inloggen bij %s';
$login_no_account='Nog niet geregisteerd?';
$login_register='Klik hier om te registreren bij %s';
$login_no_account_text='Om in te loggen moet u zich eenmalig registreren. U moet een gebruikersnaam en wachtwoord bedenken waarmee u in kunt loggen op het systeem.';
