<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Velkommen til ";
$strUseMenu = "Bruk menyen eller klikk på en link nedenfor for å starte med å bruke ";
$click_to_login = "Klikk her for å innlogging.";
$login_text = "Skriv brukernavn og adgangskode";
$login_username = "Brukernavn";
$login_password = "Adgangskode";
$login_missing_field = "Du glemte å sette inn brukernavn eller adgangskode.";
$login_bad_login = "Feil brukernavn eller adgangskode";
$login_remind = "La meg være innlogget inntil jeg klikker på 'Logg ut'.";
$login_language = 'Velg språk';
