<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bem Vindo a ";
$strUseMenu = "Use o menu ou clique nos ícones para começar a usar";
$click_to_login = "Click here to login.";
$login_text = "Entre seu nome de usuário e senha para entrar";
$login_username = "Nome de usuário";
$login_password = "Senha";
$login_missing_field = "Você não digitou o nome de usuário ou senha.";
$login_bad_login = "Nome de usuário ou senha errado";
$login_remind = "Mantenha-me logado até eu sair da sessão.";
$login_language = 'Lingua';

//2.12
$login_register = 'ou clique %s para cadastrar-se';
$login_here = "aqui";
$login_lost_password = 'Perdeu a senha?';
$login_lost_password_title = 'Recupere a senha';
$login_lost_password_text= 'Favor, digite seu e-mail abaixo e enviaremos a nova senha para seu e-mail.';
$login_lost_password_mail_body = "Você pediu uma nova senha para %s. Seus novos dados para logar em %s é:\n\nUsername: %s\nPassword: %s\n\nBoa Sorte!";
$login_new_password = 'Nova Senha';
$login_lost_password_success = 'A nova senha foi enviada para %s';
$login_lost_password_failed = 'desculpe, o endereço de e-mail \'%s\' não está registrado aqui.';

//2.14
$login_fullscreen = $GO_CONFIG->title.' está sendo aberto tela cheia para você automaticamente. Você pode fechar esta janela ou começar o Group-Office de novo.';
$login_start = 'Começar de novo';
