<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Bem-vindo! ";
$strUseMenu = "Use o menu ou clique nas liga&ccedil;&otilde;es ";
$click_to_login = "Clique aqui para iniciar a sess&atilde;o.";
$login_text = "Introduza o nome de utilizador e password para in&iacute;ciar a sess&atilde;o";
$login_username = "Utilizador";
$login_password = "Password";
$login_missing_field = "N&atilde;o introduziu o nome de utilizador ou password.";
$login_bad_login = "Falha no Nome ou Password";
$login_remind = "Manter-me ligado at&eacute; pressionar o bot&atilde;o de sair.";
$login_language = 'Idioma';

//2.12
$login_here = "aqui";
$login_lost_password = 'Perdeu a password?';
$login_lost_password_title = 'Recuperar a password';
$login_lost_password_text= 'Indique o endere&ccedil;o de email para a&iacute; receber uma nova password.';
$login_lost_password_mail_body = "Solicitou uma nova password para %s. Os novos dados de acesso em %s s&atilde;o:\n\nNome: %s\nPassword: %s\n\nObrigado.";
$login_new_password = 'Nova password';
$login_lost_password_success = 'Foi enviada uma nova password para %s';
$login_lost_password_failed = 'Desculpe, o endere&ccedil;o de email \'%s\' n&atilde;o est&aacute; registado aqui.';

//2.14
$login_fullscreen = 'O ecr&atilde; foi totalmente aberto de forma autom&aacute;atica. Pode fechar esta janela ou voltar a iniciar o programa.';
$login_start = 'Iniciar novamente';

//2.16
$login_to = 'Entrar em %s';
$login_no_account = 'Ainda n&atilde;o est&aacute; registado?';
$login_register = 'Clique aqui para se registar em %s';
$login_no_account_text = 'Para entrar neste sistema precisa de estar registado. Basta indicar o nome de utilizador e uma password.';
