<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Добро пожаловать в ";
$strUseMenu = "Use the menu or click on the fast links below to start using ";
$click_to_login = "Нажмите здесь для входа.";
$login_text = "Введите ваши имя пользователя и пароль для входа";
$login_username = "Имя пользователя";
$login_password = "Пароль";
$login_missing_field = "You didn't fill out your username or password.";
$login_bad_login = "Неправильная пара: имя пользователя и пароль";
$login_remind = "Запомнить мой вход до принудительного нажатия кнопки выход.";
$login_language = 'Язык';

//2.12
$login_register = 'or click %s to sign up';
$login_here = "here";
$login_lost_password = 'Забыли пароль?';
$login_lost_password_title = 'Восстановление пароля';
$login_lost_password_text= 'Пожалуйста введите Ваш e-mail адрес, и новый пароль будет выслан по указанному Вами адресу.';
$login_lost_password_mail_body = "You requested a new password for %s. Your new login data to login at login at %s is:\n\nUsername: %s\nPassword: %s\n\nGood luck!";
$login_new_password = 'Новый пароль';
$login_lost_password_success = 'Новый пароль выслан на %s';
$login_lost_password_failed = 'Извините, этот e-mail адрес \'%s\' не зарегистрирован в системе.';
