<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Dobrodošel na';
$strUseMenu='Uporabi meni ali klikni na eno od hitrih povezav spodaj, da pričneš z uporabo';
$click_to_login='Za prijavo kliknite tukaj.';
$login_text='Vstavite vaše uporabniško ime in geslo';
$login_username='Uporabniško ime';
$login_password='Geslo';
$login_missing_field='Niste vstavili uporabniškega imena ali gesla';
$login_bad_login='Napačno uporabniško ime ali geslo';
$login_remind='Zapomni si me';
$login_language='Jezik';
$login_here='tukaj';
$login_lost_password='Izgubljeno geslo?';
$login_lost_password_title='Obnovi geslo';
$login_lost_password_text='Prosimo vstavite vaš e-mail naslov spodaj in novo geslo bo poslano na ta naslov.';
$login_lost_password_mail_body='Zahtevali ste novo geslo za račun %s. Novi prijavni podatki za prijavo na %s so:nnUpor. Ime: %snGeslo: %snnLep dan vam želim!';
$login_new_password='Novo geslo';
$login_lost_password_success='Novo geslo je bilo poslano na račun %s';
$login_lost_password_failed='Oprostite, račun \'%s\'  ni registriran.';
$login_fullscreen='Group-Office je bil avtomatično odprt v celozaslonskem načinu. Če želite lahko zaprete to okno ali zopet zaženete Group-Office.';
$login_start='Začni ponovno';
$login_to='Prijava na račun %s';
$login_no_account='Še niste registrirani?';
$login_register='Kliknite tukaj za registracijo na ime %s';
$login_no_account_text='Za prijavo v naš sistem se morate registrirati. Morate si izmisliti uporabniško ime in geslo, ki ju boste uporabljali vsakokrat, ko se boste prijavili.';
?>