<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Pozdravljeni na ";
$strUseMenu = "Za zaèetek uporabite meni ali kliknite na spodnje povezave.";
$click_to_login = "Za prijavo kliknite sem.";
$login_text = "Za prijavo vnesite va¹e uporabni¹ko ime in geslo";
$login_username = "Uporabni¹ko ime";
$login_password = "Geslo";
$login_missing_field = "Niste vnesli uporabni¹kega imena in gesla.";
$login_bad_login = "Napaèno uporabni¹ko ime ali geslo";
$login_remind = "Obdr¾i me prijavljenega, dokler ne kliknem na gumb odjava.";
$login_language = 'Jezik';
