<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "Välkommen till ";
$strUseMenu = "Använd menyn eller klicka på snabblänkarna nedan för att börja använda ";
$click_to_login = "Tryck här för att logga in.";
$login_text = "Ange ditt användarnamn och lösenord för att logga in";
$login_username = "Användarnamn";
$login_password = "Lösenord";
$login_missing_field = "Du angav inte ditt användarnamn eller lösenord.";
$login_bad_login = "Felaktigt användarnamn eller lösenord";
$login_remind = "Håll mig inloggad tills jag själv loggar ut.";
$login_language = 'Språk';

//2.12
$login_register = 'eller klicka %s för att registrera dig';
$login_here = "här";
$login_lost_password = 'Glömt lösenordet?';
$login_lost_password_title = 'Återfå lösenordet';
$login_lost_password_text= 'Var vänlig och skriv in din e-post adress nedan så skickas ett nytt lösenord till din e-post adress.';
$login_lost_password_mail_body = "Du har begärt ett nytt lösenord för %s. Dina nya inloggningsdata för att logga in på %s är:\n\nAnvändarnamn: %s\nLösenord: %s\n\nLycka till!";
$login_new_password = 'Nytt lösenord';
$login_lost_password_success = 'Ett nytt lösenord har skickats till %s';
$login_lost_password_failed = 'Ledsen, men e-post adressen \'%s\' finns inte registrerad här.';
