<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));

$strWelcomeTo = "ยินดีต้อนรับ ";
$strUseMenu = "ใช้เมนูหรือคลิกที่ลิ้งค์ด้านล่างเพื่อเริ่มใช้ ";
$click_to_login = "คลิกที่นี่เพื่อล็อกอิน";
$login_text = "ใส่ชื่อผู้ใช้และรหัสผ่านเพื่อทำการล็อกอิน";
$login_username = "ผู้ใช้";
$login_password = "รหัสผ่าน";
$login_missing_field = "คุณไม่ได้กรอกชื่อผู้ใช้หรือรหัสผ่าน";
$login_bad_login = "ผู้ใช้หรือรหัสผ่านไม่ถูกต้อง";
$login_remind = "เก็บการล็อกอินนี้ไว้จนกระทั่งมีการล็อกเอ้าท์";
$login_language = 'ภาษา';
