<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('login'));
$strWelcomeTo='Hoşgeldiniz:';
$strUseMenu='Başlamak için menüyü veya hızlı başlatma kısayollarını kullanabilirsiniz.';
$click_to_login='Oturum açmak için buraya tıklayın.';
$login_text='Oturum açmak için kullanıcı adınız ve parolanızı girin';
$login_username='Kullanıcı adı';
$login_password='Parola';
$login_missing_field='Kullanıcı adınızı ve parolanızı doldurun.';
$login_bad_login='Hatalı kullanıcı adı veya parola';
$login_remind='"Oturumu kapat" düğmesine basıncaya kadar bağlı kalayım.';
$login_language='Dil';
$login_here='buradan';
$login_lost_password='Parolanızı mı kaybettiniz?';
$login_lost_password_title='Parolayı kurtarma';
$login_lost_password_text='E-posta adresinizi aşağıya yazın ve yeni parolanızı adresinize gönderelim.';
$login_lost_password_mail_body='%s icin yeni parola istediniz. Oturum acmak için yeni bilgileriniz; %s Kullanici adi:%s Parola:%s';
$login_new_password='Yeni parola';
$login_lost_password_success='Yeni parola %s adresine gönderildi';
$login_lost_password_failed='Üzgünüm, \'%s\' eposta adresi burada kayıtlı değil.';
$login_fullscreen='Group-Office otomatik olarak tam ekranda başladı. Bu pencereyi kapatabilir veya Group-Office\'i yeniden başlatabilirsiniz.';
$login_start='Yeniden başlat';
$login_to='Oturum aç: %s';
$login_no_account='Hala kayıt olmadınız mı?';
$login_register='%s üzerinde kayıt olmak için buraya tıklayın';
$login_no_account_text='Sisteme oturum açmak için önce kayıt olmalısınız. Her seferinde oturum açabilmek için bir kullanıcı adı ve parola oluşturmalısınız.';
?>