<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Office is created by Intermesh For more information visit <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a> - Translated into Arabic by Gega Solution for more information kindly visit <a class="normal" href="http://www.gegasolution.com/group-office/">http://www.gegasolution.com</a>';
$about_support='لديك الخيارات التالية للحصول على دعم';
$about_pro_support='الدعم الفنى';
$about_com_support='دعم المجتمع المحلي';
$about_help_files='الملفات المساعدة';
?>