<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Office ha estat creat per Intermesh. Per obtindre més informació visiteu <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support='Per tal d\'obtindre suport, teniu les opcions següents';
$about_pro_support='Suport professional';
$about_com_support='Suport de la Comunitat';
$about_help_files='Arxius d\'ajuda';
?>