<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Office je vyvíjen společností Intermesh.\n<br>Pro více informací jděte na <a target="_blank" href="http://www.group-office.com/" class="normal">http://www.group-office.com</a>.';
$about_support = 'Máte následující možnosti pro získání podpory';

$about_pro_support = 'Profesionální podpora Intermesh';
$about_com_support = 'Podpora pro komunitní verzi';
$about_help_files = 'Nápověda';
