<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Offce is created by Intermesh. For more information visit <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support = 'You have the following options to obtain support';

$about_pro_support = 'Professional support';
$about_com_support = 'Community support';
$about_help_files = 'Help files';
