<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Office ha sido creado por Intermesh. Para más información visite <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support='Dispone de las siguientes opciones para obtener soporte';
$about_pro_support='Soporte Profesional';
$about_com_support='Soporte de la Comunidad';
$about_help_files='Ficheros de ayuda';
?>