<?php
//Uncomment this line in new translations! LI 21.01.2006
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Office on Intermeshin luoma. Lisätietoja saat <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support = 'Sinulla on seuraavat mahdollisuudet saada tukea';

$about_pro_support = 'Professional tuki';
$about_com_support = 'Community tuki';
$about_help_files = 'Ohje tiedostot';
