<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Offce a été créé par <a class="normal" href="http://www.intermesh.nl">Intermesh</a>. Pour plus d\' information allez visiter <a target="_blank" href="http://www.group-office.com/" class="normal">http://www.group-office.com</a>.';
$about_support = 'Afin d\'obtenir du support, différentes options sont disponibles';
$about_pro_support = 'Support professionnel';
$about_com_support = 'Support communautaire';
$about_help_files = 'Fichiers d\'aide';
?>
