<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='A Group-Offce-t az Intermesh készítette. További részletekért látogassa meg a következő oldalt: <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support='Terméktámogatás tekintetében a következő lehetőségek adottak';
$about_pro_support='A Professional verzió terméktámogatása';
$about_com_support='A közösségi verzió terméktámogatása';
$about_help_files='Súgó fájlok';
?>