<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='GroupOffice è creato by Intermesh. Per maggiori informazioni visitare <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support='Hai le seguenbi possibilità per ottenere supporto';
$about_pro_support='Supporto Professional';
$about_com_support='Supporto Community';
$about_help_files='File di Aiuto';
?>