<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Offce は Intermesh により制作されました。さらに詳しい情報については <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>を参照してください。';
$about_support = '下記サイトにアクセスして追加情報を得ることが出来ます。';

$about_pro_support = 'プロフェッショナルサポート';
$about_com_support = 'コミュニティーサポート';
$about_help_files = 'ヘルプファイル';
