<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Office is ontwikkeld door Intermesh. Voor meer informatie bezoek de website van <a target="_blank" href="http://www.intermesh.nl/" class="normal">Intermesh</a>.';
$about_support='U heeft de volgende opties om ondersteuning te krijgen';
$about_pro_support='Professionele ondersteuning';
$about_com_support='Community ondersteuning';
$about_help_files='Help documenten';
