<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'As últimas atualizações deste software podem ser encontradas em <a target="_blank" href="http://group-office.sourceforge.net/" class="normal">Sourceforge</a>.'; 
$about_support = 'Você tem as seguintes opções para obter suporte';

$about_pro_support = 'Suporte Profissional';
$about_com_support = 'Suporte da Comunidade';
$about_help_files = 'Arquivos de ajuda';
