<?php
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Offce é criado por Intermesh. Para mais informação visite <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support = 'Pode obter o seguinte tipo de suporte';

$about_pro_support = 'Suporte profissional';
$about_com_support = 'Suporte comunitário';
$about_help_files = 'Ficheiros de ajuda';
