<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Offce создан компанией <a class="normal" href="http://www.intermesh.nl">Intermesh</a>. Больше информации Вы узнаете посетив <a target="_blank" href="http://www.group-office.com/" class="normal">http://www.group-office.com</a>.';
// version. 2.13
$about_support = 'You have the following options to obtain support';
$about_pro_support = 'Профессиональная поддержка';
$about_com_support = 'Поддержка сообщества';
$about_help_files = 'Файлы помощи';
