<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Office je razvilo podjetje Intermesh. Za več informacij obišči <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support='Za pomoč lahko zaprosiš na naslednje načine';
$about_pro_support='Strokovna podpora';
$about_com_support='Podpora skupnosti';
$about_help_files='Datoteke s pomočjo';
?>