<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));

$about_text = 'Group-Office skapas av Intermesh. För mer information gå till <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a>.';
$about_support = 'Du har följande möjligheter att få support';

$about_pro_support = 'Professionell support';
$about_com_support = 'Community support';
$about_help_files = 'Hjälp filer';
