<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_base_language_file('about'));
$about_text='Group-Offce, Intermesh tarafından yazılmıştır. Daha fazla bilgi için <a class="normal" href="http://www.intermesh.nl">http://www.intermesh.nl</a> adresini ziyaret edebilirsiniz.';
$about_support='Destek alabilmek için aşağıdaki seçenekler mevcut';
$about_pro_support='Profesyonel destek';
$about_com_support='İletişim desteği';
$about_help_files='Yardım dosyaları';
?>