<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='ممتلكات';
$admin_modules='وحدات';
$strPath='مسار';
$admin_invalid_path='ادخال غير صحيح المسار';
$admin_overview='مقدمة';
$admin_module='وحدة';
$admin_modules_text='اضغط على تثبيت او الغاء تثبيت. الاهتمام ازالة تثبيت وحدة سيزيل جميع البيانات وحدة';
$admin_bookmarks_text='Add bookmarks here that automatically will be created when you register a new user.';
$admin_bookmark_new_window='Open bookmark in a new window';
$admin_menus_text='مراجعة للقائمة التي تريد استخدامها واضغط على حفظ';
$admin_start_module='تبدأ المجموعة في المكتب';
$admin_menus='القائمة';
$admin_formats='صيغة التاريخ';
$admin_date_formats_text='Add date formats in <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> with a description and click on Ok.';
$strAuthors='Author(s)';
$strVersion='الاصدار';
$strReleaseDate='تاريخ الاصدار';
$strDescription='الوصف';
$strStatus='مركز';
$strNoModuleInfo='No module information available';
$cmdInstall='تثبيت';
$cmdUninstall='أزالة';
$strConfirmUninstallPrefix='هل أنت متأكد من انك تريد الغاء التثبيت';
$strConfirmUninstallSuffix='؟';
$mod_available='وحدات متاحة';
$mod_installed='تثبيت وحدات';
$mod_sort_order='نوع النظام';
$lang_modules['modules']='وحدات';
?>