<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='Propietats';
$admin_modules='Mòduls';
$strPath='Camí';
$admin_invalid_path='Heu introduït un camí incorrecte';
$admin_overview='Resum';
$admin_module='Mòdul';
$admin_modules_text='Feu clic a Instal·la o a Desinstal·la. Atenció, si desinstal·leu un mòdul es perdran totes les seves dades associades!';
$admin_bookmarks_text='Afegiu aquí les adreces d\'interès que voleu que siguin creades automàticament quan registreu un usuari nou.';
$admin_bookmark_new_window='Obre l\'adreça d\'interès en una nova finestra';
$admin_menus_text='Comproveu els menús que voleu fer servir i feu clic a \'Desa\'';
$admin_start_module='Inicia Group-Office en el';
$admin_menus='de Menú';
$admin_formats='Formats de data';
$admin_date_formats_text='Afegiu formats de data en <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">format PHP</a> amb una descripció i feu clic a D\'acord.';
$strAuthors='Autor(s)';
$strVersion='Versió';
$strReleaseDate='Data de llançament';
$strDescription='Descripció';
$strStatus='Estat';
$strNoModuleInfo='No hi ha informació disponible del mòdul';
$cmdInstall='Instal·la';
$cmdUninstall='Desinstal·la';
$strConfirmUninstallPrefix='Esteu segurs que voleu desinstal·lar';
$strConfirmUninstallSuffix='?';
$mod_available='Mòduls disponibles';
$mod_installed='Mòduls instal·lats';
$mod_sort_order='Ordre';
$lang_modules['modules']='Mòduls';
?>