<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Vlastnosti';
$admin_modules = 'Moduly';
$strPath = 'Cesta';
$admin_invalid_path = 'Zadal jste špatnou cestu';
$admin_overview = 'Přehled';
$admin_module = 'Modul';
$admin_modules_text = 'Klikněte na instaluj nebo odinstaluj. Pozor, odinstalování smaže všechna data modulu!';
$admin_bookmarks_text = 'Zadejete odkazy, které budou automaticky vytvořeny při zadání nového uživatele.';
$admin_bookmark_new_window = 'Otevřít odkaz v novém okně';
$admin_menus_text = "Označte položky menu, které chcete používat a klikněte na ulož'";
$admin_start_module = 'Spustit Group-Office v';
$admin_menus = "Menu";
$admin_formats = "Formát data";
$admin_date_formats_text = 'Zadejte formát data podle <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> s popisem a klikněte na OK.';

//2.05
$strAuthors = 'Autor(-ři)';
$strVersion = 'Verze';
$strReleaseDate = 'Vydáno dne';
$strDescription = 'Popis';
$strStatus = 'Stav';
$strNoModuleInfo = 'O modulu nejsou žádné informace';

$cmdInstall = 'Instalovat';
$cmdUninstall = 'Odinstalovat';
$strConfirmUninstallPrefix = 'Jste si jistí, že chcete odinstalovat';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Dostupné moduly';
$mod_installed = 'Nainstalované moduly';
$mod_sort_order = 'Pořadí řazení';

//2.13
$lang_modules['modules'] = 'Moduly';
