<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Egenskaber';
$admin_modules = 'Moduler';
$strPath = 'Sti';
$admin_invalid_path = 'Du har indtastet en ugyldig sti';
$admin_overview = 'Oversigt';
$admin_module = 'Modul';
$admin_modules_text = 'Klik Installer eller Afinstaller ved moduler. Bemærk: afinstallation af et modul sletter alle modulets data!';
$admin_bookmarks_text = 'Opret bogmærker her, som automatisk tilføjes når du opretter en ny bruger.';
$admin_bookmark_new_window = 'Åben bogmærke i nyt vindue';
$admin_menus_text = "Marker de menuer du ønsker at bruge og klik på 'Gem'";
$admin_start_module = 'Start Group-Office i';
$admin_menus = "Menuer";
$admin_formats = "Datoformater";
$admin_date_formats_text = 'Tilføj datoformater i <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> med en beskrivelse og klik på Ok.';

//2.05
$strAuthors = 'Udvikler(e)';
$strVersion = 'Version';
$strReleaseDate = 'Frigivelsesdato';
$strDescription = 'Beskrivelse';
$strStatus = 'Status';
$strNoModuleInfo = 'Ingen information tilgængelig om modul';

$cmdInstall = 'Installer';
$cmdUninstall = 'Afinstaller';
$strConfirmUninstallPrefix = 'Ønsker du at afinstallere';
$strConfirmUninstallSuffix = '?';
