<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='\'Eigenschaften';
$admin_modules='\'Module';
$strPath='\'Pfad';
$admin_invalid_path='\'Der eingegebene Pfad ist ungültig';
$admin_overview='\'Übersicht';
$admin_module='\'Modul';
$admin_modules_text='\'Bitte die zu aktivierenden Module wählen und auf \'Installieren\' klicken.<br />In einem installierten Modul auf \'Berechtigungen\' klicken, um die Berechtigungen zu ändern.';
$admin_bookmarks_text='\'Bitte hier Lesezeichen anlegen, die allen neu angelegten Benutzern zur Verfügung gestellt werden sollen.';
$admin_bookmark_new_window='\'Öffne Lesezeichen in einem neuen Fenster';
$admin_menus_text='"Bitte die zu aktivierenden Menü-Einträge auswählen und auf \'Speichern\' klicken';
$admin_start_module='\'Starte Group-Office mit';
$admin_menus='"Menüs';
$admin_formats='"Datumsformate';
$admin_date_formats_text='\'Bitte ein Datumsformat im <a class="normal" target="_blank" href="http://www.php.net/manual/de/function.date.php">PHP-Format</a> definieren und mit ok bestätigen.';
$strAuthors='\'Autor(en)';
$strVersion='\'Version';
$strReleaseDate='\'Veröffentlichungsdatum';
$strDescription='\'Beschreibung';
$strStatus='\'Status';
$strNoModuleInfo='\'Keine Modulinformation verfügbar';
$cmdInstall='\'Installieren';
$cmdUninstall='\'Deinstallieren';
$strConfirmUninstallPrefix='\'Sind Sie sicher, dass Sie das Modul';
$strConfirmUninstallSuffix='\'deinstallieren möchten?';
$mod_available='\'Verfügbare Module';
$mod_installed='\'Installierte Module';
$mod_sort_order='\'Sortierung';
$lang_modules['modules']='\'Module';
?>