<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Properties';
$admin_modules = 'Modules';
$strPath = 'Path';
$admin_invalid_path = 'You entered an invalid path';
$admin_overview = 'Overview';
$admin_module = 'Module';
$admin_modules_text = 'Click at Install or Uninstall. Attention, uninstalling a module will remove all module data!';
$admin_bookmarks_text = 'Add bookmarks here that automatically will be created when you register a new user.';
$admin_bookmark_new_window = 'Open bookmark in a new window';
$admin_menus_text = "Check the menu's that you wish to use and click on 'save'";
$admin_start_module = 'Start Group-Office in';
$admin_menus = "Menu's";
$admin_formats = "Date formats";
$admin_date_formats_text = 'Add date formats in <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> with a description and click on Ok.';

//2.05
$strAuthors = 'Author(s)';
$strVersion = 'Version';
$strReleaseDate = 'Release date';
$strDescription = 'Description';
$strStatus = 'Status';
$strNoModuleInfo = 'No module information available';

$cmdInstall = 'Install';
$cmdUninstall = 'Uninstall';
$strConfirmUninstallPrefix = 'Are you sure you want to uninstall';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Available modules';
$mod_installed = 'Installed modules';
$mod_sort_order = 'Sort order';

//2.13
$lang_modules['modules'] = 'Modules';
