<?php
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Propiedades';
$admin_modules = 'Módulos';
$strPath = 'Ruta';
$admin_invalid_path = 'Ha introducido una ruta incorrecta';
$admin_overview = 'Resumen';
$admin_module = 'Módulo';
$admin_modules_text = 'haga click en Instalar o Desinstalar. ¡Atención, si desinstala un módulo se perderán todos sus datos asociados!';
$admin_bookmarks_text = 'Agregue aquí los favoritos que desea que sean creados automáticamente cuando se registre un nuevo usuario.';
$admin_bookmark_new_window = 'Abrir el favorito en una nueva ventana';
$admin_menus_text = "Verifique los menús que desea utilitzar y haga click en 'Guardar'";
$admin_start_module = 'Iniciar Group-Office en el';
$admin_menus = "de Menú";
$admin_formats = "Formatos de fecha";
$admin_date_formats_text = 'Agregar formatos de fecha en <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato PHP</a> con una descripción y haga click en Aceptar.';

//2.05
$strAuthors = 'Autor(es)';
$strVersion = 'Versión';
$strReleaseDate = 'Fecha de lanzamiento';
$strDescription = 'Descripción';
$strStatus = 'Estado';
$strNoModuleInfo = 'No hay información disponible del módulo';

$cmdInstall = 'Instalar';
$cmdUninstall = 'Desinstalar';
$strConfirmUninstallPrefix = '¿Está seguro que desea desinstalar';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Módulos disponibles';
$mod_installed = 'Módulos instalados';
$mod_sort_order = 'Orden';

//2.13
$lang_modules['modules'] = 'Módulos';
