<?php
//Uncomment this line in new translations! LI 08.02.2006
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Ominaisuudet';
$admin_modules = 'Modulit';
$strPath = 'Polku';
$admin_invalid_path = 'Annoit kelvottoman polun';
$admin_overview = 'Kokonaiskuva';
$admin_module = 'Moduli';
$admin_modules_text = 'Paina Asenna tai Poista. Huom, modulin poistaminen poistaa modulin kaikki tiedot!';
$admin_bookmarks_text = 'Lisää tähän suosikki sivut jotka automattiseti luodaan kun sinä rekisteröit uuden käyttäjän.';
$admin_bookmark_new_window = 'Avaa suosikki uuteen ikkunaan';
$admin_menus_text = "Merkitse valikot jotka haluat käyttää use ja paina 'talleta'";
$admin_start_module = 'Käynnistä Group-Office ';
$admin_menus = "Valikot";
$admin_formats = "Päiviäys muoto";
$admin_date_formats_text = 'Lisää päiväys muoto <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> kuvauksella ja paina Ok.';

//2.05
$strAuthors = 'Tekijä(t)';
$strVersion = 'Versio';
$strReleaseDate = 'Päivämäärä';
$strDescription = 'Kuvaus';
$strStatus = 'Tila';
$strNoModuleInfo = 'Moduuli tietoja ei ole';

$cmdInstall = 'Asenna';
$cmdUninstall = 'Poista';
$strConfirmUninstallPrefix = 'Oletko varma että haluat poistaa';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Käytettävissä olevat moduulit';
$mod_installed = 'Asennetut moduulit';
$mod_sort_order = 'Lajittelu järjestys';

//2.13
$lang_modules['modules'] = 'Moduulit';
