<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Propriétés';
$admin_modules = 'Modules';
$strPath = 'Chemin';
$admin_invalid_path = 'Vous avez entré un chemin invalide';
$admin_overview = 'Aperçu';
$admin_module = 'Module';
$admin_modules_text = 'Cliquez sur Installer ou Désintaller. Attention, déinstaller un module supprime vos données.';
$admin_bookmarks_text = 'Ajouter un signet içi qui sera automatiquement créé lorsque vous enregistrerez un nouvel utilisateur.';
$admin_bookmark_new_window = 'Ouvrir le signet dans une nouvelle fenêtre';
$admin_menus_text = "Vérifiez le menu que vous souhaitez utiliser et cliquez sur 'enregistrer'";
$admin_start_module = 'Démarrer Group-Office dans';
$admin_menus = "Menus";
$admin_formats = "formats des dates";
$admin_date_formats_text = 'Ajouter les formats des dates dans <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">les formats PHP</a> avec une description et cliquez sur Ok.';

//2.05
$strAuthors = 'Auteur(s)';
$strVersion = 'Version';
$strReleaseDate = 'Date de validation';
$strDescription = 'Description';
$strStatus = 'Statut';
$strNoModuleInfo = 'Pas de module d\'information disponible.';
$cmdInstall = 'Installer';
$cmdUninstall = 'Désinstaller';
$strConfirmUninstallPrefix = 'Etes-vous sûr de vouloir désinstaller ce module ?';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Modules disponibles';
$mod_installed = 'Modules installés';
$mod_sort_order = 'Trier';

//2.13
$lang_modules['modules'] = 'Modules';
?>
