<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$htmldirection='rtl';
$charset='UTF-8';

$admin_properties = 'מאפיינים';
$admin_modules = 'מודולים';
$strPath = 'נתיב';
$admin_invalid_path = 'הזנת נתיב לא תקין';
$admin_overview = 'מבט כולל';
$admin_module = 'מודול';
$admin_modules_text = 'הקש ב- התקן או הסר. שים לב הסרת מודול תסיר כל מידע לגבי המודול!';
$admin_bookmarks_text = 'הוסף כאן סימנניות אשר יווצרו באופן אוטומטי בעת רישום משתמש חדש.';
$admin_bookmark_new_window = 'פתח סימניה בחלון חדש';
$admin_menus_text = "סמן את התפריטים בהם ברצונך להשתמש והקש 'שמור'";
$admin_start_module = 'אתחל את Group-Office ב-';
$admin_menus = "תפריטים";
$admin_formats = "תבנית מידע";
$admin_date_formats_text = 'הוסף תבנית תאריך ב- <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> בתוספת תיאור והקש על אישור.';

//2.05
$strAuthors = 'מחבר/ים';
$strVersion = 'גרסה';
$strReleaseDate = 'תאריך שחרור';
$strDescription = 'תיאור';
$strStatus = 'מעמד';
$strNoModuleInfo = 'אין מידע זמין למודול';

$cmdInstall = 'התקן';
$cmdUninstall = 'הסר';
$strConfirmUninstallPrefix = 'האם אתה בטוח שאתה רוצה להסיר';
$strConfirmUninstallSuffix = '?';
