<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='Tulajdonságok';
$admin_modules='Modulok';
$strPath='Útvonal';
$admin_invalid_path='Érvénytelen útvonalat adott meg';
$admin_overview='Áttekintés';
$admin_module='Modul';
$admin_modules_text='Kattintson a Hozzáadás vagy Törlés gombokra. Figyelem, ha töröl egy modult, azzal annak az adatbázisnak a tartalmát is törölni fogja!';
$admin_bookmarks_text='Ha itt megad kedvenceket, akkor azok automatikusan létrejönnek az új felhasználók létrehozásakor is, azok számára.';
$admin_bookmark_new_window='Kedvenc megnyitása új ablakban';
$admin_menus_text='Jelölje ki a használni kívánt menüket, majd kattintson a \'Mentés\' gombra';
$admin_start_module='A Group-Office indítása ezzel:';
$admin_menus='Menük';
$admin_formats='Dátum formátumok';
$admin_date_formats_text='Adja meg a dátum formátumot <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP formátumban</a>, majd kattintson az Ok gombra.';
$strAuthors='Készítő(k)';
$strVersion='Verzió';
$strReleaseDate='Kibocsátás dátuma';
$strDescription='Leírás';
$strStatus='Állapot';
$strNoModuleInfo='Nem érhető el modulinformáció';
$cmdInstall='Hozzáadás';
$cmdUninstall='Törlés';
$strConfirmUninstallPrefix='Biztosan törölni szeretné ezt:';
$strConfirmUninstallSuffix='?';
$mod_available='Elérhető modulok';
$mod_installed='Telepített modulok';
$mod_sort_order='Rendezési sorszám';
$lang_modules['modules']='Modulok';
?>