<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'プロパティ';
$admin_modules = 'モジュール';
$strPath = 'パス';
$admin_invalid_path = '無効なパスを入力しました';
$admin_overview = '概要';
$admin_module = 'モジュール';
$admin_modules_text = 'インストールかアンインストールをクリックしてください。 注意：モジュールをアンインストールするとモジュールのデータが全て削除されます！';
$admin_bookmarks_text = '自動的にアドレス帳へ追加し、新規ユーザの登録をします';
$admin_bookmark_new_window = '新規ウィンドウでブックマークを開く';
$admin_menus_text = "使用するメニューをチェックして '保存'をクリックしてください";
$admin_start_module = 'Group-Office開始と同時に使用する';
$admin_menus = "メニュー";
$admin_formats = "データフォーマット";
$admin_date_formats_text = '<a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a>に日付フォーマットと説明を追加してOKをクリック';

//2.05
$strAuthors = '作者';
$strVersion = 'バージョン';
$strReleaseDate = 'リリース日';
$strDescription = '説明';
$strStatus = 'ステータス';
$strNoModuleInfo = 'モジュールの情報はありません';

$cmdInstall = 'インストール';
$cmdUninstall = 'アンインストール';
$strConfirmUninstallPrefix = '本当にアンインストールしてもよろしいですか';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = '有効なモジュール';
$mod_installed = 'インストール済モジュール';
$mod_sort_order = '並び替え';

//2.13
$lang_modules['modules'] = 'モジュール';
