<?php
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Propriedades';
$admin_modules = 'Módulos';
$strPath = 'Caminho';
$admin_invalid_path = 'Você digitou um caminho inválido';
$admin_overview = 'Visão geral';
$admin_module = 'Módulo';
$admin_modules_text = 'Selecione os módulos que você deseja usar e clique sobre \''.$cmdSave.'\'.<br />Clique sobre os módulos ativos para mudar suas permissões.';
$admin_bookmarks_text = 'Adicione os favoritos aqui que serão criados automaticamente quando você regista um usuário novo.';
$admin_bookmark_new_window = 'Abrir a página dentro de uma janela nova';
$admin_menus_text = "Selecione os menus que você deseja usar e clique 'salvar'";
$admin_start_module = 'Começar o Group-Office em';
$admin_menus = "Menus";
$admin_formats = "Formato de data";
$admin_date_formats_text = 'Adicione os formatos de data no <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato de PHP</a> com a descrição e clique sobre OK.';

//2.05
$strAuthors = 'Autor(es)';
$strVersion = 'Versão';
$strReleaseDate = 'Data de lançamento';
$strDescription = 'Descrição';
$strStatus = 'Situação';
$strNoModuleInfo = 'Nenhuma informação sobre o módulo disponível';

$cmdInstall = 'Instalar';
$cmdUninstall = 'Desinstalar';
$strConfirmUninstallPrefix = 'Você tem certeza que deseja desinstalar';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Módulos disponiveis';
$mod_installed = 'Módulos instalados';
$mod_sort_order = 'Ordem de exibição';

//2.13
$lang_modules['modules'] = 'Módulos';
