<?php
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Propriedades';
$admin_modules = 'M&oacute;dulos';
$strPath = 'Caminho';
$admin_invalid_path = 'Indicou um caminho inválido';
$admin_overview = 'Vista geral';
$admin_module = 'M&oacute;dulo';
$admin_modules_text = 'Clique em Instalar ou Desinstalar. Aten&ccedil;&atilde;o, desinstalar um m&oacute;dulo remove todos os dados desse m&oacute;dulo!';
$admin_bookmarks_text = 'Os favoritos adicionados aqui ser&atilde;o criados automaticamente quando for registado um novo utilizador.';
$admin_bookmark_new_window = 'Abrir favoritos numa nova janela';
$admin_menus_text = "Marque os menus que deseja utilizar e clique em 'Guardar'";
$admin_start_module = 'Iniciar Group-Office em';
$admin_menus = "Menus";
$admin_formats = "Formato da data";
$admin_date_formats_text = 'Adicionar formatos de data em <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">formato PHPt</a> com a descri&ccedil;&atilde;o e clique em Ok.';

//2.05
$strAuthors = 'Autor(es)';
$strVersion = 'Vers&atilde;o';
$strReleaseDate = 'Data';
$strDescription = 'Descri&ccedil;&atilde;o';
$strStatus = 'Estado';
$strNoModuleInfo = 'Sem informa&ccedil;&atilde;o dispon&iacute;vel';

$cmdInstall = 'Instalar';
$cmdUninstall = 'Desinstalar';
$strConfirmUninstallPrefix = 'Tem a certeza que deseja desinstalar';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'M&oacute;dulos dispon&iacute;veis';
$mod_installed = 'M&oacute;dulos instalados';
$mod_sort_order = 'Ordenar';

//2.13
$lang_modules['modules'] = 'M&oacute;dulos';