<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Настройки';
$admin_modules = 'Модули';
$strPath = 'Путь';
$admin_invalid_path = 'Вы ввели неправильный путь';
$admin_overview = 'Overview';
$admin_module = 'Модуль';
$admin_modules_text = 'Click at Install or Uninstall. Attention, uninstalling a module will remove all module data!';
$admin_bookmarks_text = 'Add bookmarks here that automatically will be created when you register a new user.';
$admin_bookmark_new_window = 'Open bookmark in a new window';
$admin_menus_text = "Check the menu's that you wish to use and click on 'save'";
$admin_start_module = 'Start Group-Office in';
$admin_menus = "Menu's";
$admin_formats = "Date formats";
$admin_date_formats_text = 'Add date formats in <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> with a description and click on Ok.';

//2.05
$strAuthors = 'Автор(ы)';
$strVersion = 'Версия';
$strReleaseDate = 'Дата выпуска (релиза)';
$strDescription = 'Описание';
$strStatus = 'Статус';
$strNoModuleInfo = 'Информация о модуле недоступна';

$cmdInstall = 'Установить';
$cmdUninstall = 'Деинсталировать';
$strConfirmUninstallPrefix = 'Вы действительно хотите деинсталировать этот модуль';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Доступные модули';
$mod_installed = 'Установленные модули';
$mod_sort_order = 'Сортировать заказы(?)';

//2.13
$lang_modules['modules'] = 'Модули';
