<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='Lastnosti';
$admin_modules='Moduli';
$strPath='Pot';
$admin_invalid_path='Niste vnesli veljavne poti';
$admin_overview='Predogled';
$admin_module='Modul';
$admin_modules_text='Klikni na Namesti ali Odstrani. Opozorilo! Odstranjevanje modula bo odstranilo vse podatke tega modula!';
$admin_bookmarks_text='Tukaj dodaj označbe, ki bodo bile ustvarjene samodejno med registracijo novega uporabnika.';
$admin_bookmark_new_window='Odpri označbo v novem oknu';
$admin_menus_text='Preglej  menuje, ki jih želiš uporabiti in klikni na \'shrani\'';
$admin_start_module='Začni Group-Office v';
$admin_menus='Menuji';
$admin_formats='Formati datumov';
$admin_date_formats_text='Dodaj formate datumov v <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> z opisom in klikni na Ok.';
$strAuthors='Avtor(ji)';
$strVersion='Verzija';
$strReleaseDate='Datum izida';
$strDescription='Opis';
$strStatus='Stanje';
$strNoModuleInfo='Ni informacij za ta modul';
$cmdInstall='Namesti';
$cmdUninstall='Odstrani';
$strConfirmUninstallPrefix='Ali ste prepričani da želite odstraniti';
$strConfirmUninstallSuffix='?';
$mod_available='Dostopni moduli';
$mod_installed='Nameščeni moduli';
$mod_sort_order='Vrstni red sortiranja';
$lang_modules['modules']='Moduli';
?>