<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'Egenskaper';
$admin_modules = 'Moduler';
$strPath = 'Sögväg';
$admin_invalid_path = 'Du angav en felaktig sökväg';
$admin_overview = 'Överblick';
$admin_module = 'Modul';
$admin_modules_text = 'Klicka på Installera eller Avinstallera. Notera att avinstallera en modul tar också bort alla data modulen innehåller!';
$admin_bookmarks_text = 'Lägg till bokmärken här som automatiskt skapas åt nya användarkonton.';
$admin_bookmark_new_window = 'Öppna bokmärke i ett nytt fönster.';
$admin_menus_text = "Markera menyerna du önskar använda och tryck på 'Spara'";
$admin_start_module = 'Starta Group-Office i';
$admin_menus = "Menyer";
$admin_formats = "Datumformat";
$admin_date_formats_text = 'Lägg till datumformat i <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP format</a> med en beskrivning och klicka på Ok.';

//2.05
$strAuthors = 'Författare';
$strVersion = 'Version';
$strReleaseDate = 'Release datum';
$strDescription = 'Beskrivning';
$strStatus = 'Status';
$strNoModuleInfo = 'Det finns ingen modul information tillgänglig';

$cmdInstall = 'Installera';
$cmdUninstall = 'Avinstallera';
$strConfirmUninstallPrefix = 'Är du säker på att du vill avinstallera';
$strConfirmUninstallSuffix = '?';

//2.08
$mod_available = 'Tillgängliga moduler';
$mod_installed = 'Installerade moduler';
$mod_sort_order = 'Sorterings ordning';
