<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = 'พร็อพเพอตี้';
$admin_modules = 'โมดูล';
$strPath = 'แพทช์';
$admin_invalid_path = 'คุณใส่พาธไม่ถูกต้อง';
$admin_overview = 'อธิบาย';
$admin_module = 'โมดูล';
$admin_modules_text = 'คลิกเพื่อคติดตั้งหรือลบการติดตั้ง  หากลบการติดตั้งข้อมูลในโมดูลจะสูญหาย!';
$admin_bookmarks_text = 'เพิ่มที่คั่นหนังสือที่นี่ จะทำการสร้างสมาชิกเพิ่ม โดยอัตโนมัติ';
$admin_bookmark_new_window = 'เปิดที่คั่นหน้าในหน้าใหม่';
$admin_menus_text = "เช็ค เมนูที่ต้องการแล้วคลิกปุ่ม 'บันทึก'";
$admin_start_module = 'เริ่มกรุ๊ปเมเนเจอร์ใน';
$admin_menus = "เมนู";
$admin_formats = "ชนิดของวัน";
$admin_date_formats_text = "เพิ่มฟอร์แมทของวันได้ที่  <a class='normal' target='_blank' href='http://www.php.net/manual/en/function.date.php'>PHP format</a> โดยพิมพ์บรรยายแล้วคลิก 'ตกลง'";

//2.05
$strAuthors = 'ผู้เขียน';
$strVersion = 'เวอร์ชัน';
$strReleaseDate = 'วันผลิต';
$strDescription = 'บรรยาย';
$strStatus = 'สถานะ';
$strNoModuleInfo = 'ไม่มีโมดูล';

$cmdInstall = 'ติดตั้ง';
$cmdUninstall = 'ลบการติดตั้ง';
$strConfirmUninstallPrefix = 'คุณแน่ใจที่จะลบการติดตัง';
$strConfirmUninstallSuffix = '?';
//2.08
$mod_available = 'โมดูลที่ใช้งานได้';
$mod_installed = 'ติดตั้งโมดูล';
$mod_sort_order = 'จัดเรียงตาม';
