<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));
$admin_properties='Özellikler';
$admin_modules='Modüller';
$strPath='Yol';
$admin_invalid_path='Geçersiz bir yol belirttiniz';
$admin_overview='Özet';
$admin_module='Modül';
$admin_modules_text='Kur veya Kaldır\'a basın. DİKKAT: Bir modülü silmek, onunla ilgili tüm veriyi de siler.';
$admin_bookmarks_text='Yeni bir kullanıcı kaydettiğinizde burada otomatik olarak bir favori eklenir';
$admin_bookmark_new_window='Favorileri yeni sayfada aç';
$admin_menus_text='Kullanmak istediğiniz menüleri seçin ve \'kaydet\'e tıklayın';
$admin_start_module='Group-Office başlangıç modülü:';
$admin_menus='Menüler';
$admin_formats='Zaman biçimi';
$admin_date_formats_text='Zaman biçimini <a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP biçiminde </a> ve bir açıklama ile ekle ve \'Tamam\'a bas.';
$strAuthors='Yazar(lar)';
$strVersion='Sürüm';
$strReleaseDate='Yayın tarihi';
$strDescription='Açıklama';
$strStatus='Durum';
$strNoModuleInfo='Modül bilgisi mevcut değil';
$cmdInstall='Kur';
$cmdUninstall='Kaldır';
$strConfirmUninstallPrefix='Kaldırmak istediğinizden emin misiniz?';
$strConfirmUninstallSuffix='?';
$mod_available='Kurulabilir modüller';
$mod_installed='Kurulu modüller';
$mod_sort_order='Sıralama ölçütü';
$lang_modules['modules']='Modüller';
?>