<?php
require_once($GO_LANGUAGE->get_fallback_language_file('modules'));

$admin_properties = '內容';
$admin_modules = '模組';
$strPath = '路徑';
$admin_invalid_path = '你/妳輸入的路徑錯誤';
$admin_overview = '總覽';
$admin_module = '模組';
$admin_modules_text = '選擇你/妳想使用的模組再按 \''.$cmdSave.'\'.<br />按下已啟用的模組變更它們的權限';
$admin_bookmarks_text = '在這裡新增的書籤將會自動建立到所有註冊的使用者內';
$admin_bookmark_new_window = '在新的視窗開啟書籤';
$admin_menus_text = "選擇你/妳想使用的選單再按「儲存」'";
$admin_start_module = '每次使用Group-Office都開始在';
$admin_menus = "選單";
$admin_formats = "日期格式";
$admin_date_formats_text = '使用<a class="normal" target="_blank" href="http://www.php.net/manual/en/function.date.php">PHP格式</a> 新增日期格式及描述再按確定.';

//2.05
$strAuthors = '作者';
$strVersion = '版本';
$strReleaseDate = '發表日期';
$strDescription = '描述';
$strStatus = '狀態';
$strNoModuleInfo = 'No module information available';

$cmdInstall = '安裝';
$cmdUninstall = '移除';
$strConfirmUninstallPrefix = '你確定要移除';
$strConfirmUninstallSuffix = '?';
