<?php
require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Адресник";
$contacts_no_contacts = "Не са намерени контакти.";
$contacts_members = "Членове";
$contacts_contacts = "Контакти";
$contacts_add = "Нови контакти";
$contacts_groups = "Групи";
$contacts_other = "Други контакти";
$contacts_move_to_group = "Премести избраните контакти към група...";
$groups_no_groups = "Нямате никакви групи";
$contacts_group = "Група";
$contacts_empty_group = "Използвайте падащата кутия за да преместите контактите в тази група.";
$contacts_this_group = 'тази група';

$add_contacts_text = "Попълнете E-mail адресите на членовете и кода за оторизация и след това натиснете 'Ok'";
$add_contacts_success = "Потребителя е добавен успешно";
$add_contacts_wrong = "Грешен E-mail или код за оторизация.";
$add_personal_text = "Натиснете 'Save' за да добавите контакт. Полетата отбелязани с * са задължителни.";
$contacts_select = "Изберете контакти които да добавите и натиснете 'Ok'.";
$contacts_select_title = "Контакти";
$contact_profile = "Профил на контакт";
$user_profile = "Профил на Потребител";
$contacts_authorise = "Оторизация";
$contacts_add_member = "Добавете този член към вашите контакти";
$strConfirmSynchronise = "Това ще обнови този контакт с данните които потребителя е въвел за себе си. Ръчните промени направени от вас ще бъдат изгубени. Сигурен ли сте че искате да продължите?";
$contacts_import = "Внос";
$contacts_export = "Износ";
$contacts_export_text = "Изберете вида CSV който искате да създадете.";
$contacts_delete = "Изтрийте";

$contacts_import_text = "Изберете CSV файл и натиснете 'Ok'";
$contacts_import_text_group = "Изберете група и CSV файл. Натиснете 'Ok'.";
$fbNoFile = "Никакви файлове не са получени";
$fbPleaseWait = "Моля изчакайте докато зарежда файла...";

$strNotIncluded = "Не въвеждайте";
$contacts_import_feedback = "Следните колони са открити във вашия CSV файл.<br />";
$contacts_import_feedback .= "Изберете групата която искате да въведете или автоматично създайте групи базирани на колоните на файла.<br />";
$contacts_import_feedback .= " Съчетайте кореспондентните Група-Офис колони с колоните от файла и бъдете сигурен че не сте избрали колоните два пъти.";
$contacts_separator = "Стойностите са разделени по";
$contacts_no_separator = "Не сте въвели отделящ символ.";
$fbFilename = "Наименование на файла";
$contacts_import_title = "Въведете адресник";
$contacts_import_success = "Успешно въведен файл";
$contacts_import_double = "Избрали сте една или повече колони два пъти. Коригирайте това и опитайте отново.";
$contacts_import_noname = 'ТРябва да изберете поле за името';
$contacts_import_incompatible = "Несъвместим файл формат.<br /><br />CSV файла е файл със стойности отделени с (точки)запетайки.";
$strMember = "Член";
$contact_exist_warning = "<b>Бележка:</b> Този потребител съществува във вашия контактен лист.";
$contacts_add_to_group = "Добавете избраните потребители към контактите в група...";
$contacts_add_to = "Добавете избраните потребители към контакти";
$contacts_add_user = "Добавете";
$contacts_edit = "изменение";
$contacts_no_select = "Не сте избрали нищо";
$contacts_this_contact = "този контакт";

$contacts_seperator_text = 'Стойности отделени с';
$contacts_quote = 'Стойности заградени с';
$contacts_clrf = 'Линии премахнати с';
$contacts_auto_group = 'Автоматично създай групи от файл';
$contacts_import_to_group = 'Въведи в група';

$contacts_search = 'Търси';
$cmdSearch = 'Търси';
$contacts_search_text = "Въведете фразата която търсите и натиснете 'търси'. Може да използвате * като допълнителен символ.";
$contacts_results = 'резултат(и)';


$contacts_color = 'Цвят';

$contacts_colors['black'] = 'Черен';
$contacts_colors['red'] = 'Червен';
$contacts_colors['green'] = 'Зелен';
$contacts_colors['blue'] = 'Син';
$contacts_colors['pink'] = 'Розов';
$contacts_colors['orange'] = 'Оранджев';
$contacts_colors['brown'] = 'Кафяв';

//translation required
$ab_addressbooks = 'Адресници';
$ab_owner = 'Собственик';
$ab_subscribed = 'Подписан';
$ab_new_ab = 'Нов адресник';
$ab_addressbook_exists = 'Адресник с това име вече съществува';
$ab_addressbook = 'Адресник';
$contacts_select_single = 'Натиснете на контакт за да изберете тази личност';

$ab_group_exists = 'Вече съществува адресник с това име';
