<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = 'Adresář';
$contacts_no_contacts = 'Nenalezeny žádné kontakty.';
$contacts_members = 'Členové';
$contacts_contacts = 'Kontakty';
$contacts_add = 'Nový kontakt';
$contacts_groups = 'Skupiny';
$contacts_other = 'Další kontakty';
$contacts_move_to_group = 'Přesuňte vybrané kontakty do skupiny...';
$groups_no_groups = 'Nemáte žádné skupiny';
$contacts_group = 'Skupina';
$contacts_empty_group = 'Použijte rozevírací tabulku pro přesunutí kontaktů do této skupiny.';
$contacts_this_group = 'tato skupina';

$add_contacts_text = 'Vyplňte E-mailové adresy členů, jejich autorizační kódy a klikněte na OK';
$add_contacts_success = 'Úspěšně přidán uživatel';
$add_contacts_wrong = 'Špatný e-mail nebo přístupový kód.';
$add_personal_text = 'Klikněte na  "Uložit" pro přidání kontaktu. Pole označená * jsou nezbytná.';
$contacts_select = 'Vyberte kontakty pro přidání a klikněte na  "Ok".';
$contacts_select_title = 'Kontakty';
$contact_profile = 'Profil';
$user_profile = 'Profil uživatele';
$contacts_authorise = 'Autorizace';
$contacts_add_member = 'Přidat tohoto člena do vašich kontaktů';
$strConfirmSynchronise = 'Toto zaktualizuje kontakt s daty, které vložil sám uživatel. Vámi provedené manuální změny se neuloží. Jste si jistý, že chcete pokračovat?';
$contacts_import = 'Importovat';
$contacts_export = 'Exportovat';
$contacts_export_text = 'Vyberte typ CSV, které by jste chtěli vytvořit.';
$contacts_delete = 'Smazat';

$contacts_import_text_group = 'Vyberte skupinu a CSV soubor. Klikněte "Ok".';
$fbNoFile = 'Žádný soubor nebyl přijat';
$fbPleaseWait = 'Prosím čekejte než se načte soubor...';

$strNotIncluded = 'Neimportováno';
$contacts_import_feedback = 'Tyto sloupce byly nalezeny ve vašem CSV souboru.<br />';
$contacts_import_feedback .= 'Vyberte skupinu, kterou chcete importovat nebo automaticky vytvořte skupiny na základě sloupce v souboru.<br />';
$contacts_import_feedback .= ' Porovnejte odpovídajíci Group-Office sloupce ze sloupci z toho souboru  a ujistěte se, že jste žádný sloupec nevybrali dvakrát.';
$contacts_separator = 'Hodnoty jsou rozděleny ';
$contacts_no_separator = 'Nevložili jste oddělovací znak.';
$fbFilename = 'Název souboru';
$contacts_import_title = 'Importovat Adresář';
$contacts_import_success = 'Úspěšně importované soubory';
$contacts_import_double = 'Vybrali jste jeden nebo více odstavců dvakrát. Opravit to a zkusit znova.';
//changed:
$contacts_import_noname = 'Musíte vybrat pole "Křestní jméno" a "Příjmení" ';
$contacts_import_incompatible = 'Nekompatibilní formát souboru.<br /><br />CSV je soubor s hodnotami rozdělenými středníkem.';
$strMember = 'Osoba';
$contact_exist_warning = '<b>Upozornění:</b> Tento uživatel je již uveden ve vašich kontaktech.';
$contacts_add_to_group = 'Přidejte vybrané uživatele ke kontaktům ve skupině...';
$contacts_add_to = 'Přidej vybrané uživatele do kontaktů';
$contacts_add_user = 'přidat';
$contacts_edit = 'Upravit';
$contacts_no_select = 'Nic jste nevybral';
$contacts_this_contact = 'tento kontakt';

$contacts_seperator_text = 'Oddělovač hodnot';
$contacts_quote = 'Ohraničení hodnot';
$contacts_clrf = 'Konce řádků';
$contacts_auto_group = 'Automaticky tvořit skupiny ze souborů';
$contacts_import_to_group = 'Importovat do skupiny';

$contacts_search = 'Hledání v kontaktech ';
$cmdSearch = 'Hledat';
$contacts_search_text = 'Klikněte na písmeno nebo vložte výraz pro hledání a klikněte na "Hledat". Můžete použít * jako zástupný znak.';
$contacts_results = 'Výsledky';
$contacts_result = 'Výsledek';


$contacts_color = 'Barva';

$contacts_colors['black'] = 'Černá';
$contacts_colors['red'] = 'Červená';
$contacts_colors['green'] = 'Zelená';
$contacts_colors['blue'] = 'Modrá';
$contacts_colors['pink'] = 'Růžová';
$contacts_colors['orange'] = 'Oranžová';
$contacts_colors['brown'] = 'Hnědá';

$ab_addressbooks = 'Adresáře';
$ab_owner = 'Vlastník';
$ab_subscribed = 'Přihlášen';
$ab_new_ab = 'Nový adresář';
$ab_addressbook_exists = 'Adresář s tímto jménem již existuje';
$ab_addressbook = 'Adresář';
$contacts_select_single = 'Klikněte na kontakt pro výběr této osoby';

$ab_group_exists = 'Adresář s tímto jménem již existuje';
$ab_group_on_file = 'Skupinové kontakty na základě souboru';
$ab_default = 'Default';

//translation required
$ab_edit_contact = 'Klikněte na "Ok" pro uložení změn. Pole označené * jsou nezbytné';
$ab_group_on_file = 'Skupinové kontakty na základě tohoto souboru';
$ab_default = 'Default';
$ab_browse = 'Prohlížet';
$ab_comment = 'Komentář';

$ab_contact = 'Kontakt';
$ab_send_message = 'E-mail';
$ab_new_event = 'Událost';

$ab_templates = 'Šablony';
$ab_your_templates = 'Vaše';
$ab_all_templates = 'Vše';

$template_type[0] = 'E-mail';
$template_type[1] = 'OpenOffice.Org';
$ab_type = 'Typ';
$ab_template_exists = 'Šablona s tímto jménem již existuje.';

$sir_madam['M'] = 'pán';
$sir_madam['F'] = 'paní';

$ab_upload_oo = 'Upload OpenOffice.org šablona';
$ab_upload_nofile = 'Chyba během odesílání souboru.';

$ab_oo_doc = 'Textový dokument';
$ab_select_template = 'Vyberte šablonu pro tento dokument:';
$ab_add_field_data = 'Ve vašem dokumentu můžete použít tyto následující hodnoty:';
$ab_datafield = 'Datové pole';

$ab_no_template = 'Bez šablony';
$ab_new_note = 'Upozornění';

$ab_events = 'Události';

$ab_new_contact = 'Nový kontakt';
$ab_new_company = 'Nová firma';
$ab_companies = 'Firmy';
$ab_company_properties = 'Profil firmy';
$ab_bank_no = 'Číslo účtu';
$ab_companies_count_single = 'firma';
$ab_companies_count = 'firem';
$ab_no_companies = 'Žádné firmy nenalezeny';
$ab_no_company = 'Žádná firma';

$ab_import_type = 'Import';
$ab_no_company_found = 'Žádné firmy nenalezeny';
$ab_search_company = 'Vyhledat firmy';
$ab_edit_company = 'Změnit profil firmy';
$ab_new_group = 'Nová skupina';
$ab_export_type = 'Export';

$ab_custom_fields = 'Extra&nbsp;datová pole';
$ab_field_size = 'Velikost';

$ab_new_field = 'Nové datové pole';
$ab_invalid_field_size = 'Nesprávná velikost. Vyberte hodnotu mezi 10 a 255.';
$ab_field_exists = 'Pole s tímto názvem již existuje.';

$ab_employees = 'Zaměstnanci';
$ab_no_employees = 'Žádní zaměstnanci nenalezeni';

$ab_employee_count_single = 'zaměstnanec';
$ab_employee_count_multiple = 'zaměstnanci';
$ab_vat_no = 'DIČ';

$ab_add_new = 'Přidat nové';
$ab_add_existing = 'Přidej existující';

$ab_access = 'Přístup';
//1.98
$ab_mailings = 'Rozesílání';
$ab_mailing_groups = 'Skupiny pro rozesílání';
$ab_no_mailing_groups = 'Nejsou skupiny pro rozesílání';
$ab_no_templates = 'Nenalezena žádná šablona';
$ab_mailing_group_exists = 'Skupina pro rozesílání tohoto jména už existuje.';
$ab_contacts_count_single = 'kontakt';
$ab_contacts_count_multiple = 'kontakty';
$ab_new_mailing = 'Nové rozesílání';
$ab_all_your_addressbooks = 'všechny vaše adresáře';

$ab_search_for = 'Hledat';
$ab_search_in = 'v';
$ab_search_on = 'na';
$ab_search_keyword = 'Hledat výraz';
$ab_wildcard = '(Použijte "%" jako zástupný znak)';

//2.03
$ab_copy_read_acl = 'Zkopírovat práva ke čtení ke kontaktu a firmám';
$ab_copy_write_acl = 'Zkopírovat práva k psaní ke kontaktu a firmám';

$ab_catagory_exists = 'Kategorie s tímto jménem již existuje.';
$ab_add_catagory = 'Přidat kategorii';
$ab_add_field = 'Přidat pole';
$ab_catagory = 'Kategorie';

//2.04
$ab_todos = 'Úkoly';


//2.05
$ab_download = 'Stažení';
$ab_download_template = 'Klikněte na tlačítko \'Stažení\' pro uložení šablony k editaci na PC.';
$ab_upload = 'Nahrát';
//modified string:
$ab_upload_oo_text = 'Po ukončení editace šablony v OpenOffice.org nahrajte ji spět na Group-Office. Zvolte soubor a klikněte na tlačítko \'Nahrát\' pro přenesení šablony zpět na server.';
$ab_file_type = 'Typ souboru';
$ab_import_vcf_file_ok = 'Nahraný soubor vypadá v pořádku. Prosím klikněte na \'Ok\' pro aktivaci šablony.';
$ab_import_failed = 'Import selhal.';
//modified string:
$contacts_import_text = "Zvolte soubor s daty pro import a klikněte na 'Ok'";

//2.06
$ab_select_mailing_groups = 'Zvolte e=mailovou skupinu, do které kontakt patří';

//2.11
$ab_move_to_ab = 'Přenos zvolených kontaktů do adresáře...';
$ab_move_com_to_ab = 'Přenos zvolených firem do adresáře...';

//2.12
$ab_search_sender = 'Hledat e-mail';

$ab_contact_exists = 'Kontakt už patrně existuje. Klikněte na %s pro přechod na existujícího kontaktu nebo klikněte \'Ok\' nebo \'Použít\' pro uložení nového kontaktu.';
$ab_company_exists = 'Firma už patrně existuje. Klikněte na %s pro přechod na existující firmu nebo klikněte \'Ok\' nebo \'Použít\' pro uložení nové firmy.';
$ab_here = 'zde';
$ab_move = 'Přesunout';

//2.13
$ab_search_for_keyword = 'na';

$ab_search_in = 'Hledejte v'; //changed
$ab_search_on_users = 'Hledejte na';

$ab_users_count_single='uživatel';
$ab_users_count_multiple='uživatelé';
$ab_no_users='Žádný uživatel nenalezen';

//2.15
$ab_select_addressbook = 'Vyber adresář';
$ab_move = 'Přesuň';
$ab_file='Soubor';

$ab_template_uploaded = 'Dokument je uložen';
$ab_select_mailing_group = 'Vyberte skupinu, které chcete poslat vaše maily';

//2.16
$ab_id = 'ne.';

$ab_contact ='Kontakt';
$ab_company ='Společnost';

$ab_edit_selected = 'Edituj vybrané';
$ab_edit_selected_warning = 'Varování! Editujete %s %s. Všechno bude aktualizováno s těmito modifikacemi. Prázdná pole budou ignorována.';
$ab_contacts='kontakty';
$ab_companies='společnosti';
$ab_users='uživatelé';
$ab_dontchange='Nezměněno';

$ab_select_unknown_recipient='Příjemce %s je neznámý. Emailová adresa možná patří ke kontaktu vylistovaném dole. Klikněte na jméno kontaktu a vložte to k němu, Vložte nový kontakt nebo ignorujte e-mail adresu.';
$ab_ignore='Ignorovat';
$ab_check_info='Email adresa, která byla zadána není v adresáři. Klikněte na \'Ok\' pro uložení.';
$ab_reset='Reset';
$ab_help_url='http://docs.group-office.com/index.php?folder_id=56&file_id=0';

//Gmork
$strNoItemSelected = 'Vyberte ze seznamu';