<?php
require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Addressebok";
$contacts_no_contacts = "Det er ingen kontaktpersoner.";
$contacts_members = "Medlemmer";
$contacts_contacts = "Kontaktpersoner";
$contacts_add = "Ny kontaktperson";
$contacts_groups = "Grupper";
$contacts_other = "Andre kontaktpersoner";
$contacts_move_to_group = "Flytt valgte kontaktpersoner til gruppen...";
$groups_no_groups = "Der er ingen grupper";
$contacts_group = "Gruppe";
$contacts_empty_group = "Bruk listen til å flytte kontaktpersoner til denne gruppen.";
$contacts_this_group = 'Denne gruppen';

$add_contacts_text = "Sett inn medlemmets e-postadresse og autorisasjonskode og klikk på 'OK'";
$add_contacts_success = "Bruker lagt til";
$add_contacts_wrong = "Feil i e-postadresse eller autorisasjonskode.";
$add_personal_text = "Klikk på 'OK' for å legge til en kontakt. Feltene markert med * må fylles ut.";
$contacts_select = "Velg de kontaktpersoner som skal legges til og klikk på 'OK'.";
$contacts_select_title = "Kontaktpersoner";
$contact_profile = "Kontaktperson profil";
$user_profile = "Bruker profil";
$contacts_authorise = "Autorisasjon";
$contacts_add_member = "Legg til medlem til dine kontakter";
$strConfirmSynchronise = "Dette vil oppdate kontaktpersonen med data brukeren selv har lagt inn. Endringer du selv har laget vil gå tapt. Er du sikker på du vil fortsette?";
$contacts_import = "Importer";
$contacts_export = "Eksporter";
$contacts_export_text = "Velg den type fil du vil opprette.";
$contacts_delete = "Slett";

$contacts_import_text = "Velg en fil og klikk deretter på 'Ok'";
$contacts_import_text_group = "Velg en gruppe og en fil. Klikk deretter på 'Ok'.";
$fbNoFile = "Filen ble desverre ikke overført";
$fbPleaseWait = "Vent mens filen overføres...";

$strNotIncluded = "Importer ikke";
$contacts_import_feedback = "Følgende kolonner ble funnet i filen.<br />";
$contacts_import_feedback .= "Velg den gruppe du vil importere til eller velg å få gruppene opprettet automatisk på bakgrunn av kolonnene i filen.<br />";
$contacts_import_feedback .= " Match sammenhængende Group-Office columns med kolonnene fra filen. Vær sikker på du ikke har valgt en kolonne flere ganger.";
$contacts_separator = "Verdier avskillt av";
$contacts_no_separator = "Du har ikke satt inn et separator tegn.";
$fbFilename = "Filnavn";
$contacts_import_title = "Importer adressebok";
$contacts_import_success = "Filen ble importert";
$contacts_import_double = "Du har valgt en eller flere kolonner flere ganger. Ret feilen og prøv igjen.";
$contacts_import_noname = 'Du må velge en navnefelt';
$contacts_import_incompatible = "Innkompatibelt filformat.<br /><br />Filen skal bestå av felter avskilt med komma.";
$strMember = "Medlem";
$contact_exist_warning = "<b>OBS!:</b> Denne bruker er allerede i kontaktpersons listen.";
$contacts_add_to_group = "Tilføy valgte brukere til kontaktpersonerne i gruppen...";
$contacts_add_to = "Tilføy valgte brukere til kontaktpersoner";
$contacts_add_user = "Tilføy";
$contacts_edit = "Rett";
$contacts_no_select = "Du har ikke valgt noe";
$contacts_this_contact = "Denne kontaktperson";

$contacts_seperator_text = 'Verdier avskilt av';
$contacts_quote = 'Verdier innsatt i';
$contacts_clrf = 'Linjer avsluttet med';
$contacts_auto_group = 'Opprett automatisk grupper fra fil';
$contacts_import_to_group = 'Importer til gruppe';


$contacts_search = 'søk kontakter';
$cmdSearch = 'søk';
$contacts_search_text = "Sett inn enn søke tekst og klikk på 'søk'. Du kan bruke % som et wild card alternativ.";
$contacts_results = 'resultat(er)';


$contacts_color = 'Farge';

$contacts_colors['black'] = 'Sort';
$contacts_colors['red'] = 'Rød';
$contacts_colors['green'] = 'Grønn';
$contacts_colors['blue'] = 'Blå';
$contacts_colors['pink'] = 'Rosa';
$contacts_colors['orange'] = 'Oransje';
$contacts_colors['brown'] = 'Brun';

$ab_addressbooks = 'Adressebok';
$ab_owner = 'Eier';
$ab_subscribed = 'Abbonert';
$ab_new_ab = 'Ny adressebok';
$ab_addressbook_exists = 'En adressebok med dette navnet eksisterer allerede';
$ab_addressbook = 'Adressebok';
$contacts_select_single = 'Klikk på en kontakt for velge denne personen';

$ab_group_exists = 'En adressebok med dette navnet eksisterer allerede';
