<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "Adresar";
$contacts_no_contacts = "Ni stikov.";
$contacts_members = "Èlani";
$contacts_contacts = "Stiki";
$contacts_add = "Nov stik";
$contacts_groups = "Skupine";
$contacts_other = "Ostali stiki";
$contacts_move_to_group = "Premakni izbrane stike v skupino...";
$groups_no_groups = "Nimate skupin";
$contacts_group = "Skupina";
$contacts_empty_group = "Uporabite spustni meni za premik stikov v to skupino.";
$contacts_this_group = 'ta skupina';

$add_contacts_text = "Zapolnite uporabni¹ki E-po¹tni naslov in pooblastitveno kodo ter kliknite na 'V redu'";
$add_contacts_success = "Uporabnik uspe¹no dodan";
$add_contacts_wrong = "Napaèna E-po¹ta ali pooblastitena koda.";
$add_personal_text = "Klikni na 'Shrani' da doda¹ stik. Polja oznaèena z * so potrebna.";
$contacts_select = "Izberite stike za dodajanje in kliknite 'V redu'.";
$contacts_select_title = "Stiki";
$contact_profile = "Profil";
$contact_profile = "Profil stika";
$user_profile = "Uporabnikov profil";
$user_profile = "Uporabni¹ki profil";
$contacts_authorise = "Pooblastitev";
$contacts_add_member = "Dodaj tega èlana k tvojim stikom";
$strConfirmSynchronise = "To bo posodobilo stik s podatki, ki jih je vnesel uporabnik sam. Va¹e roène spremembe bodo izgubljene. Ali res ¾elite nadaljevati?";
$contacts_import = "Uvozi";
$contacts_export = "Izvozi";
$contacts_export_text = "Izberi tip CSVja, ki ga ¾eli¹ ustvariti.";
$contacts_delete = "Zbri¹i";

$contacts_import_text_group = "Izberi skupino in CSV datoteko. Klikni na 'V redu'.";
$fbNoFile = "Datoteka, ki jo ¾elite nalo¾iti je prevelika.<br /> Najveèja mo¾na velikost nalaganja je:";
$fbNoFile = "Nobena datoteka ni bila sprejeta";
$fbNoFile = "Datoteka, ki ste jo posku¹ali nalo¾iti je prevelika. <br /> Najveèja premestljiva velikost je nastavljena na:";
$fbPleaseWait = "Prosim, poèakajte. Po¹iljanje podatkov...";
$fbPleaseWait = "Prosim poèakajte med nalaganjem datoteke...";
$fbPleaseWait = "Prosim, poèakajte. Po¹iljanje podatkov...";

$strNotIncluded = "Ne uvozi";
$contacts_import_feedback = "Naslednji stolpci so bili najdeni v va¹i CSV datoteki.<br />";
$contacts_import_feedback .= "Select the group you wish to import to or automatically create groups based on a column of the file.<br />";
$contacts_import_feedback .= " Match corrosponding Group-Office columns with the columns from the file and make sure that you don't select columns twice.";
$contacts_separator = "Vrednosti so loèene z";
$contacts_no_separator = "Niste vnesli loèilnega znaka.";
$fbFilename = "Ime datoteke";
$fbFilename = "Ime datoteke";
$fbFilename = "Ime datoteke";
$contacts_import_title = "Uvozi adresar";
$contacts_import_success = "Uspe¹no uvo¾ena datoteka";
$contacts_import_double = "Enega ali veè stolpcev ste izbrali dvakrat. Popravite to in poskusite znova.";
//changed:
$contacts_import_noname = 'Izbrati morate polja \'Ime\' in \'Priimek\'';
$contacts_import_incompatible = "Nezdru¾ljiva vrsta datoteke.<br /><br />CVS datoteka je datoteka z vrednostmi loèeni z vejico/podpièjem.";
$strMember = "èlan";
$contact_exist_warning = "<b>Opomba:</b> Ta uporabnik je ¾e v va¹em seznamu stikov.";
$contacts_add_to_group = "Dodaj izbrane uporabnike k stikom v skupini...";
$contacts_add_to = "Dodaj izbrane uporabnike v stike";
$contacts_add_user = "Dodaj";
$contacts_edit = "Uredi";
$contacts_no_select = "Nièesar niste izbrali";
$contacts_this_contact = "ta stik";

$contacts_seperator_text = 'Vrednosti loèene z';
$contacts_quote = 'Vrednosti obdane z';
$contacts_clrf = 'Vrstice zakljuèene z';
$contacts_auto_group = 'Samodejno iz datoteke ustvari skupine';
$contacts_import_to_group = 'Uvozi v skupino';

$contacts_search = 'Iskanje';
$cmdSearch = 'Iskanje';
$cmdSearch = 'Iskanje';
$cmdSearch = 'Iskanje';
$cmdSearch = 'Iskanje';
$cmdSearch = 'Iskanje';
$contacts_search_text = "Kliknite na èrko ali pa vnesite iskalno frazo ter kliknite na 'i¹èi'.";
$contacts_results = 'zadetkov';
$contacts_result = 'rezultat';


$contacts_color = 'Barva';

$contacts_colors['black'] = 'Èrna';
$contacts_colors['red'] = 'Rdeèe';
$contacts_colors['green'] = 'Zeleno';
$contacts_colors['blue'] = 'Modra';
$contacts_colors['pink'] = 'Ro¾nata';
$contacts_colors['orange'] = 'Oran¾no';
$contacts_colors['brown'] = 'Rjava';

$ab_addressbooks = 'Adresarji';
$ab_owner = 'Lastnik';
$ab_subscribed = 'Naroèen';
$ab_new_ab = 'Nov adresar';
$ab_addressbook_exists = 'Adresar s tem imenom ¾e obstaja';
$ab_addressbook = 'Adresar';
$contacts_select_single = 'Kliknite na stik za izbiro te osebe';

$ab_group_exists = 'Adresar s tem imenom ¾e obstaja';
$ab_group_on_file = 'Skupinski stiki osnovani na datoteki';
$ab_group_on_file = 'Skupinski stiki osnovani na datoteki';
$ab_default = 'Privzeto';
$ab_default = 'Privzeto';

//translation required
$ab_edit_contact = 'Kliknite na \'V redu\' za shranitev sprememb. Polja oznaèena z * so obvezna';
$ab_group_on_file = 'Skupinski stiki osnovani na datoteki';
$ab_group_on_file = 'Skupinski stiki osnovani na datoteki';
$ab_default = 'Privzeto';
$ab_default = 'Privzeto';
$ab_browse = 'Brskanje';
$ab_comment = 'Komentar';

$ab_contact = 'Stiki';
$ab_send_message = 'E-po¹ta';
$ab_new_event = 'Dogodek';

$ab_templates = 'Predloge';
$ab_your_templates = 'Va¹';
$ab_all_templates = 'Vse';

$template_type[0] = 'E-po¹ta';
$template_type[1] = 'OpenOffice.Org';
$ab_type = 'Tip';
$ab_template_exists = 'Predloga s tem imenom ¾e obstaja.';

$sir_madam['M'] = 'gospod';
$sir_madam['M'] = 'g.';
$sir_madam['F'] = 'gospa';
$sir_madam['F'] = 'ga.';

$ab_upload_oo = 'Nalo¾i OpenOffice.org predlogo';
$ab_upload_nofile = 'Napaka pri po¹iljanju datoteke.';

$ab_oo_doc = 'Besedilni dokument';
$ab_select_template = 'Izberite predlogo za ta dokument:';
$ab_add_field_data = 'V dokumentu lahko uporabite naslednje vrednosti:';
$ab_datafield = 'Podatkovno polje';

$ab_no_template = 'Ni predloge';
$ab_new_note = 'Opomba';

$ab_events = 'Sestanki';

$ab_new_contact = 'Nov&nbsp;stik';
$ab_new_company = 'Novo&nbsp;podjetje';
$ab_companies = 'Podjetja';
$ab_company_properties = 'Profil&nbsp;podjetja';
$ab_bank_no = 'Banèni&nbsp;raèun';
$ab_companies_count_single = 'Podjetje';
$ab_companies_count = 'Podjetja';
$ab_no_companies = 'Ni najdenih podjetij';
$ab_no_company = 'Ni podjetja';

$ab_import_type = 'Uvozi';
$ab_no_company_found = 'Ni najdenih podjetij';
$ab_search_company = 'Poglej podjetje';
$ab_edit_company = 'Spremeni profil podjetja';
$ab_new_group = 'Nova skupina';
$ab_export_type = 'Izvozi';

$ab_custom_fields = 'Dodatna&nbsp;podatkovna polja ';
$ab_field_size = 'Velikost';

$ab_new_field = 'Nova podatkovna polja';
$ab_invalid_field_size = 'Neveljavna velikost. Izberite vrednost med 10 in 255.';
$ab_field_exists = 'Polje s tem imenom ¾e obstaja.';

$ab_employees = 'Zaposleni';
$ab_no_employees = 'Ni najdenih zaposlenih';

$ab_employee_count_single = 'zaposleni';
$ab_employee_count_multiple = 'zaposleni';
$ab_vat_no = 'VAT ¹tevilka';

$ab_add_new = 'Dodaj novo';
$ab_add_existing = 'Dodaj obstojeèo';

$ab_access = 'Dostop';
//1.98
$ab_mailings = 'Dopisi';
$ab_mailing_groups = 'Po¹tne skupine';
$ab_no_mailing_groups = 'NI po¹tnih skupin';
$ab_no_templates = 'Ni najdenih predlog';
$ab_mailing_group_exists = 'Po¹tna skupina s tem imenom ¾e obstaja.';
$ab_contacts_count_single = 'Stiki';
$ab_contacts_count_multiple = 'stiki';
$ab_new_mailing = 'Nova po¹ta';
$ab_all_your_addressbooks = 'vsi va¹i adresarji';

$ab_search_for = 'Najdi';
$ab_search_in = 'v';
$ab_search_on = 'ob';
$ab_search_keyword = 'Iskalna fraza';
$ab_wildcard = '(Uporabi \'%\' kot nadomestni znak)';

//2.03
$ab_copy_read_acl = 'Pisalno bralna dovoljenja za stik in podjetja';
$ab_copy_write_acl = 'Kopirna, pisalna dovoljenja za stik in podjetja';

$ab_catagory_exists = 'Kategorija s tem imenom ¾e obstaja.';
$ab_add_catagory = 'Dodaj kategorijo';
$ab_add_field = 'Dodaj polje';
$ab_catagory = 'Kategorija';

//2.04
$ab_todos = 'Opravila';


//2.05
$ab_download = 'Prenesi';
$ab_download_template = 'Kliknite na gumb \'Prenesi\', za prenos predloge, ki jo nato lahko uredite.';
$ab_upload = 'Nalo¾i';
//modified string:
$ab_upload_oo_text = 'Izberite predlogo, ki ste jo uredili z OpenOffice.org in kliknite na \'V redu\'';
$ab_file_type = 'Tip datoteke';
$ab_import_vcf_file_ok = 'Nalo¾ena datoteka je v redu. Prosim, kliknite na \'V redu\' za to sprejetje datoteke v adresar.';
$ab_import_failed = 'Uvoz spodletel.';
//modified string:
$contacts_import_text = "Izberi CSV datoteko in klikni na 'V redu'";
