<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('addressbook'));

//contacts
$contacts_title = "สมุดจดที่อยู่";
$contacts_no_contacts = "ไม่พบผู้ติดต่อ";
$contacts_members = "สมาชิก";
$contacts_contacts = "ผู้ติดต่อ";
$contacts_add = "สร้างผู้ติดต่อ";
$contacts_groups = "กลุ่ม";
$contacts_other = "ผู้ติดต่ออื่นๆ";
$contacts_move_to_group = "ย้ายผู้ติดต่อไปยังกลุ่ม";
$groups_no_groups = "คุณยังไม่มีกลุ่ม";
$contacts_group = "กลุ่ม";
$contacts_empty_group = "ใช้ดรอปดาวน์เลือกเพื่อย้ายผู้ติดต่อของกลุ่ม.";
$contacts_this_group = 'กลุ่ม';

$add_contacts_text = "ใส่ข้อมูลในช่อง สมาชิก อีเมล์ และ รหัสผ่าน แล้วคลิก ตกลง";
$add_contacts_success = "เพิ่มผู้ใช้สำเร็จแล้ว";
$add_contacts_wrong = "อีเมล์หรือหรัสไม่ถูกตอง";
$add_personal_text = "คลิกที่ 'บันทึก' เพื่อเพิ่มผู้ติดต่อ. ช่องที่มีเครื่องหมาย * คือช่องที่ต้องการให้กรอก.";
$contacts_select = "เลือกผู้ติดต่อเพื่อทำการเพิ่มแล้วคลิก 'ตกลง'.";
$contacts_select_title = "ผู้ติดต่อ";
$contact_profile = "ข้อมูลโดยรวม";
$user_profile = "ข้อมูลผู้ใช้โดยรวม";
$contacts_authorise = "การอนุญาติ";
$contacts_add_member = "เพิ่มสมาชิกนี้เข้าสู่ผู้ติดต่อของคุณ";
$strConfirmSynchronise = "ข้อมูลนี้จะทำการอัพเดทผู้ติดต่อโดยอัตโนมัต ิหากคุณแก้ไขด้วยตัวเองข้อมูลอาจสูญหายได้! คุณต้องการที่จะแก้ใขหรือไม่?";
$contacts_import = "นำเข้า";
$contacts_export = "ส่งออก";
$contacts_export_text = "เลือกชนิดของไฟล์ CSV ที่คุณต้องการสร้าง";
$contacts_delete = "ลบ";

$contacts_import_text_group = "เลือกกลุ่มและไฟล์ CSV แล้วคลิก 'ตกลง'";
$fbNoFile = "ไม่มีไฟล์ที่ไม่ได้รับ";
$fbPleaseWait = "กรุณาคอยสักครู่ระบบกำลังอัพโหลดไฟล์";
$strNotIncluded = "ห้ามนำเข้า";
$contacts_import_feedback = "ค้นพบคอลัมน์ภายใน CSV file.<br />";
$contacts_import_feedback .= "เลือกกลุ่มเพื่อนำเข้าอัตโนมัติ สร้างกลุ่มและคอลัมน์ของไฟล์.<br />";
$contacts_import_feedback .= " จัดให้ตรงกับ คอลัมน์ของ Group-Office และควรเช็คว่าคอลัมน์ไม่ซ้ำกัน";
$contacts_separator = "ค่าที่ได้แยกคำจาก";
$contacts_no_separator = "คุณไม่ได้ทำการแยกคำ";
$fbFilename = "ชื่อไฟล์";
$contacts_import_title = "นำสมุดที่อยุ่เข้า";
$contacts_import_success = "การนำเข้าเสร็จสมบูรณ์";
$contacts_import_double = "คุณเลือกคอลัมน์มากกว่าหนึ่งกรุญาลองอีกครั้ง";
//changed:
$contacts_import_noname = 'คุณต้องเลือกช่อง \'ชื่อ\' และ \'นามสกุล\' ';
$contacts_import_incompatible = "ไม่รองรับกับชนิดของไฟล์นี้<br /><br />ไฟล์ CSVจะใช้เครื่องหมาย (DOT)คอมม่า";
$strMember = "สมาชิก";
$contact_exist_warning = "<b>บันทึก:</b>ผู้ใช้คุณนี้อยู่ในรายการผู้ติดต่อแล้ว";
$contacts_add_to_group = "เพิ่มผู้ใช้ที่เลือกเข้าในกลุ่ม";
$contacts_add_to = "เพิ่มผู้ใช้ที่เลือกเข้าในกลุ่ม";
$contacts_add_user = "เพิ่ม";
$contacts_edit = "แก้ไข";
$contacts_no_select = "คุณไม่ได้เลือกอะไรเลย";
$contacts_this_contact = "ผู้ติดต่อคุณนี้";

$contacts_seperator_text = 'ค่าของตัวขั้นคือ';
$contacts_quote = 'Values enclosed by';
$contacts_clrf = 'Lines terminated by';
$contacts_auto_group = 'สร้างกลุ่มอัตโนมัติจากไฟล์';
$contacts_import_to_group = 'นำเข้าไปยังกลุ่ม';

$contacts_search = 'ค้นหา';
$cmdSearch = 'ค้นหา';
$contacts_search_text = "คลิกที่จดหมายหรือค้นหาคำแล้วคลิก 'ค้นหา'. คุณสามารถใช้เครื่องหมาย * เป็นตัวช่วยค้นได้.";
$contacts_results = 'ผลลัพธ์';
$contacts_result = 'ผลลัพธ์';


$contacts_color = 'สี';

$contacts_colors['black'] = 'ดำ';
$contacts_colors['red'] = 'แดง';
$contacts_colors['green'] = 'เขียว';
$contacts_colors['blue'] = 'น้ำเงิน';
$contacts_colors['pink'] = 'ชมพู';
$contacts_colors['orange'] = 'ส้ม';
$contacts_colors['brown'] = 'น้ำตาล';

$ab_addressbooks = 'สมุดจดที่อยู่';
$ab_owner = 'กลุ่ม';
$ab_subscribed = 'ซับสคริป';
$ab_new_ab = 'สร้างสมุดผู้ใช้ใหม่';
$ab_addressbook_exists = 'สมุดจดที่อยู่นี้มีชื่อซ้ำแล้ว';
$ab_addressbook = 'สมุดจดที่อยู่';
$contacts_select_single = 'คลิกที่ผู้ติดต่อเพื่อเลือกคน';

$ab_group_exists = 'ชื่อนี้พร้อมในการบันทึกแล้ว';
$ab_group_on_file = 'กลุ่มผู้ใช้หลักที่มาจากไฟล์';
$ab_default = 'ค่าพื้นฐาน';

//translation required
$ab_edit_contact = 'คลิกปุ่ม  ตกลง  เพื่อบันทึกการเปลี่ยนแปลง. ช่องที่มีเครื่องหมาย * จำเป็นต้องกรอกให้หมด';
$ab_group_on_file = 'กลุ่มผู้ใช้มาจากไฟล์';
$ab_default = 'ค่าพื้นฐาน';
$ab_browse = 'ค้นหา';
$ab_comment = 'คำแนะนำ';

$ab_contact = 'ผู้ติดต่อ';
$ab_send_message = 'อีเมล์';
$ab_new_event = 'เหตุการณ์';

$ab_templates = 'แม่แบบ';
$ab_your_templates = 'คุณ';
$ab_all_templates = 'ทั้งหมด';

$template_type[0] = 'อีเมล์';
$template_type[1] = 'OpenOffice.Org';
$ab_type = 'Type';
$ab_template_exists = 'เทมเพลทนี้มีชื่อซ้ำอยู่แล้ว';

$sir_madam['M'] = 'คุณ';
$sir_madam['F'] = 'มาดาม';

$ab_upload_oo = 'อัพโหลด OpenOffice.org เทมเพลท';
$ab_upload_nofile = 'เกิดข้อผิดพลาดในการส่งไฟล์.';

$ab_oo_doc = 'เอกสารชนิดเท็กไฟล์';
$ab_select_template = 'เลือกเทมเพลทสำหรับเอกสาร:';
$ab_add_field_data = 'คุรสามารถใช้ค่าตามเอกสารได้:';
$ab_datafield = 'ข้อมูล';

$ab_no_template = 'ไม่มีเทมเพลท';
$ab_new_note = 'บันทึก';

$ab_events = 'แต่งตั้ง';

$ab_new_contact = 'สร้างผู้ติดต่อใหม่';
$ab_new_company = 'สร้างบริษัทใหม่';
$ab_companies = 'บริษัท';
$ab_company_properties = 'ข้อมุลบริษัท';
$ab_bank_no = 'หมายเลขธนาคาร';
$ab_companies_count_single = 'บริษัท';
$ab_companies_count = 'บริษัท';
$ab_no_companies = 'ไม่พบบริษัท';
$ab_no_company = 'ไม่มีบริษัทนี้';

$ab_import_type = 'นำเข้า';
$ab_no_company_found = 'ไม่พบบริษัทนี้';
$ab_search_company = 'ดูบริษัทนี้';
$ab_edit_company = 'เปลี่ยนข้อมูลบริษัท';
$ab_new_group = 'สร้างกลุ่มใหม่';
$ab_export_type = 'ส่งออก';

$ab_custom_fields = 'ฟิลข้อมูล&nbsp;ขั้นสูง';
$ab_field_size = 'ขนาด';

$ab_new_field = 'สร้างข้อมูลใหม่';
$ab_invalid_field_size = 'ขนาดไม่ถูกต้องเลือกให้อยู่ในระหว่าง 10 ถึง 255 เท่านั้น';
$ab_field_exists = '=ชื่อนี้ซ้ำแล้ว';

$ab_employees = 'พนักงาน';
$ab_no_employees = 'ไม่พบพนักงานที่หา';

$ab_employee_count_single = 'พนักงาน';
$ab_employee_count_multiple ='พนักงาน';
$ab_vat_no = 'หมายเลข VAT';

$ab_add_new = 'เพิ่มใหม่';
$ab_add_existing = 'เพิ่มที่มีอยู่แล้ว';

$ab_access = 'ติดต่อ';
//1.98
$ab_mailings = 'จดหมาย';
$ab_mailing_groups = 'ส่งจดหมายแบบกลุ่ม';
$ab_no_mailing_groups = 'ไม่พบกลุ่มจดหมายที่ค้นหา';
$ab_no_templates = 'ไม่เจอเทมเพลท';
$ab_mailing_group_exists = 'ชื่อกลุ่มของกลุ่มจดหมายนี้ซ้ำ.';
$ab_contacts_count_single = 'ผู้ติดต่อ';
$ab_contacts_count_multiple = 'ผู้ติดต่อ';
$ab_new_mailing = 'สร้างจดหมายรายชื่อ';
$ab_all_your_addressbooks = 'สมุดจดที่อยู่ทั้งหมดของคุณ';

$ab_search_for = 'ค้นหาสำหรับคำว่า';
$ab_search_in = 'ใน';
$ab_search_on = 'บน';
$ab_search_keyword = 'ค้นหาแบบพาเซอร์';
$ab_wildcard = '(ใช้ % กำหนดค่า)';

//2.03
$ab_copy_read_acl = 'คัดลอกสิทธ์ในการอ่านไปยังผู้ติดต่อและบริษัทต่างๆ';
$ab_copy_write_acl = 'คัดลอกสิทธ์ในการเขียนไปยังผู้ติดต่อและบริษัทต่างๆ';

$ab_catagory_exists = 'แคตาล็อกนี้มีชื่อซ้ำ';
$ab_add_catagory = 'เพิ่มแคตาล็อก';
$ab_add_field = 'เพิ่มฟิลล์';
$ab_catagory = 'แคตาล็อก';

//2.04
$ab_todos = 'ทำอะไร';


//2.05
$ab_download = 'ดาวโหลด';
$ab_download_template = 'คลิกที่ปุ่ม  ดาวโหลด  เพื่อดาวโหลดเทมเพลท ไปยังเครื่อง PC  เพื่อแก้ไข.';
$ab_upload = 'อัพโหลด';
//modified string:
$ab_upload_oo_text = 'เมื่อคุณแก้ไขเทมเพลท OpenOffice.org ของคุณแล้วควรจะส่งกลับมายัง Group-Office. เลือกไฟล์แล้วคลิกเพื่อทำการอัพโหลดแลกเปลี่ยนเทมเพลท';
$ab_file_type = 'ชนิดของไฟล์';
$ab_import_vcf_file_ok = 'อัพโหลดไฟล์สำเร็จแล้วกรุณาคลิกตกลง';
$ab_import_failed = 'การนำเข้าล้มเหลว.';
//modified string:
$contacts_import_text = "เลือกไฟล์ที่ปรรจุข้อมูลที่ต้องการนำเข้าแล้วคลิก 'ตกลง'";

//2.06
$ab_select_mailing_groups = 'เลือกกลุ่มเมล์';
