<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='استخدم الاستديو';
$groups_tab='استديو';
$groups_saved='اماكن حفظها';
$groups_text='انقر على المجموعة لقراءة الممتلكات.';
$groups_users_in='المستخدمين في المجموعة';
$groups_no_contacts='انك لا تملك أي اتصالات لاختيار الأعضاء. <br/> لدى استخدام دفتر العناوين لاضافة اعضاء اتصالاتكم.';
$add_group_text='ادخل اسما وانقر على\' موافق \'لإضافة مجموعة جديدة.';
$add_group_fail='المحاوله';
$add_group_success='تم اضافة المجموعة بنجاح';
$add_group_exists='الاسم بالفعل. يرجى اختيار اسم آخر';
$add_group_no_name='أنت لم تحدد اسمها';
$groups_everyone='هذه المجموعة هى مجموعة خاصة وتحتوي على جميع المستخدمين. لا يمكنك تعديل هذه المجموعة.';
$groups_users_in1='المستخدم في المجموعة';
$groups_no_users='لا يوجد مستخدمين في هذه المجموعة.';
$groups_users_in_select='اختر المستخدمين التي تريد ان تضيف الى هذه المجموعة :';
$groups_new_group='مجموعة جديدة';
$groups_members='الاعضاء';
$lang_modules['groups']='المجموعة المستخدمة';
?>