<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Потребителски групи";
$groups_tab = "Групи";
$groups_saved = "Настройките са запазени.";
$groups_text = "Щракни върху групата за показване на найните свойствата.";
$groups_users_in = "Потребители в тази група";
$groups_no_contacts = "Нямате никакъв контакт на член на групата за избиране.<br /> Използвайте Адресната книга за добавяне на член към контактите.";

$add_group_text = "Въведи име и избери ОК за добавяне на нова група.";
$add_group_fail = "Грешка при добавяне на групата. Опитайте отново.";
$add_group_success = "Узпешно добавена група.";
$add_group_exists = "Името съществува. Изберете друго име.";
$add_group_no_name = "Не сте въвели име.";
$groups_everyone = "Тази група е специална и съдържа всички потребители. Не можете да променяте тази група.";
$groups_users_in1 = "Потребител(и) в групата";
$groups_no_users = "Няма потребители в тази група.";
$groups_users_in_select = "Изберете потребителите, които искате да добавите към тази група:";

//translation required
$groups_new_group = 'Нова група';
$groups_members = 'Членове';

//2.13
$lang_modules['groups'] = 'Потребителски групи';
