<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Grups d\'usuaris';
$groups_tab='Grups';
$groups_saved='Paràmetres desats.';
$groups_text='Feu clic a un grup per veure les seves propietats.';
$groups_users_in='Usuaris en el grup ';
$groups_no_contacts='No teniu cap membre per seleccionar a contactes.<br /> Feu servir la Llibreta d\'adreces per afegir membres als vostres contactes.';
$add_group_text='Introduïu un nom i feu clic a \'D\'acord\' per afegir un nou grup.';
$add_group_fail='No s\'ha pogut afegir el grup. Si us plau, torneu-ho a provar.';
$add_group_success='El grup ha estat afegit correctament.';
$add_group_exists='El nom ja existeix. Si us plau, trieu-ne un altre.';
$add_group_no_name='No heu especificat cap nom.';
$groups_everyone='Aquest grup és especial i conté tots els usuaris. No el podeu modificar.';
$groups_users_in1='usuari(s) en el grup';
$groups_no_users='No hi ha usuaris en aquest grup.';
$groups_users_in_select='Seleccioneu els usuaris que voleu afegir a aquest grup:';
$groups_new_group='Nou grup';
$groups_members='Membres';
$lang_modules['groups']='Grups d\'usuaris';
?>