<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Uživatelské skupiny";
$groups_tab = "Skupiny";
$groups_saved = "Nastavení uloženo.";
$groups_text = "Klikněte na skupinu pro zobrazení jejich vlastností.";
$groups_users_in = "Uživatelé ve skupině ";
$groups_no_contacts = "V kontaktech nemáte žádné členy na výběr.<br />Využije Adresáře pro přidání členů do vašich kontaktů.";

$add_group_text = "Vložte jméno a klikněte na OK pro přidání nové skupiny.";
$add_group_fail = "Neúspěšné přidání skupiny. Prosím zkuste to znovu.";
$add_group_success = "Skupina úspěšně přidána.";
$add_group_exists = "Jméno již existuje. Prosím vyberte si jméno jiné.";
$add_group_no_name = "Neupřesnil jste jméno.";
$groups_everyone = "Tato skupina je zvláštní skupina a obsahuje všechny uživatele. Tuto skupinu nemůžete změnit.";
$groups_users_in1 = "uživatelé ve skupině";
$groups_no_users = "V této skupině nejsou žádní uživatelé.";
$groups_users_in_select = "Vyberte ty uživatele, které chcete přidat do této skupiny:";

//translation required
$groups_new_group = 'Nová skupina';
$groups_members = 'Členové';

//2.13
$lang_modules['groups'] = 'Uživatelské skupiny';
