<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Brugergrupper";
$groups_tab = "Grupper";
$groups_saved = "Indstillinger gemt.";
$groups_text = "Klik på en gruppe for at se dets egenskaber.";
$groups_users_in = "Brugere i gruppen ";
$groups_no_contacts = "Du har ingen kontakter der kan vælges.<br /> Brug adressebogen til at tilføje kontakter.";

$add_group_text = "Indtast et navn og klik 'Ok' for at oprette en ny gruppe.";
$add_group_fail = "Kunne ikke tilføje gruppen. Prøv igen.";
$add_group_success = "Gruppen blev tilføjet.";
$add_group_exists = "Navnet findes allerede. Vælg venligst et andet navn.";
$add_group_no_name = "Du har ikke angivet et navn.";
$groups_everyone = "Denne gruppe er speciel og indeholder alle brugere. Den kan ikke ændres.";
$groups_users_in1 = "bruger(e) i gruppen";
$groups_no_users = "Der er ingen brugere i denne gruppe.";
$groups_users_in_select = "Vælg de brugere du vil tilføje til gruppen:";

//translation required
$groups_new_group = 'Ny gruppe';
$groups_members = 'Medlemmer';
