<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Grupos de usuarios';
$groups_tab='Grupos';
$groups_saved='Parámetros guardados.';
$groups_text='Haga click en el grupo para ver sus propiedades.';
$groups_users_in='Usuarios en grupo ';
$groups_no_contacts='No tiene ningún miembro seleccionado en contactos.<br /> Use la Libreta de direcciones para agregar miembros a sus contactos.';
$add_group_text='Introduzca un nombre y haga click en \'Aceptar\' para agregar un nuevo grupo.';
$add_group_fail='Ha habido un error al agregar el grupo. Por favor, inténtelo de nuevo.';
$add_group_success='El grupo ha sido agregado correctamente.';
$add_group_exists='El nombre ya existe. Por favor introduzca otro nombre.';
$add_group_no_name='No ha especificado ningún nombre.';
$groups_everyone='Este grupo es especial y contiene todos los usuarios. No puede modificar este grupo.';
$groups_users_in1='usuario(s) en el grupo';
$groups_no_users='No existen usuarios en este grupo.';
$groups_users_in_select='Seleccione los usuarios que desea agregar a este grupo:';
$groups_new_group='Nuevo grupo';
$groups_members='Miembros';
$lang_modules['groups']='Grupos de usuarios';
?>