<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Käyttäjä ryhmät";
$groups_tab = "Ryhmät";
$groups_saved = "Asetukset tallettu.";
$groups_text = "Paina ryhmää sen ominaisuuksien katsomiseksi.";
$groups_users_in = "Ryhmässä käyttäjiä ";
$groups_no_contacts = "Sinulla ei ole jäsen yhteyksiä valittavana.<br /> Käytä osoitekirjaa jäsenien lisämiseksi yhteyksiisi.";

$add_group_text = "Anna nimi ja paina 'Ok' uuden ryhmän lisäämiseksi.";
$add_group_fail = "Ryhmän lisääminen epäonnistui. Yritä uudelleen.";
$add_group_success = "Ryhmä onnistuneesti lisätty.";
$add_group_exists = "Nimi on jo olemassa. Valitse toinen nimi.";
$add_group_no_name = "Et antanut nimeä.";
$groups_everyone = "Tämä on erikois ryhmä joka sisltää kaikki käyttäjät. Et voi muokata tätä ryhmää.";
$groups_users_in1 = "käyttäjä(ä) ryhmässä";
$groups_no_users = "Tässä ryhmässä ei ole käyttäjiä.";
$groups_users_in_select = "Valitse ne käyttäjät jotka haluat lisätä tähän ryhmään:";

//translation required
$groups_new_group = 'Uusi ryhmä';
$groups_members = 'Jäsenet';

//2.13
$lang_modules['groups'] = 'Käyttäjä ryhmät';
