<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$htmldirection='rtl';
$charset='UTF-8';
$groups_title = "קבוצות המשתמש";
$groups_tab = "קבוצות";
$groups_saved = "ההגדרות נשמרו";
$groups_text = "לחץ/י על הקבוצה לראות את מאפייניה";
$groups_users_in = "משתמשים בקבוצה ";
$groups_no_contacts = "אין לך אנשי קשר לבחור.<br /> נא להשתמש ביומן הכתובות להוספת אנשי קשר לרשימה.";
$add_group_text = "הכנס שם ולחץ על 'אישור' להוספת קבוצה חדשה";
$add_group_fail = "הוספת קבוצה נכשלה. נא לנסות שנית";
$add_group_success = "הקבוצה נוספה בהצלחה";
$add_group_exists = "השם כבר קיים. נא לבחור שם אחר.";
$add_group_no_name = "לא ציינת שם";
$groups_everyone = "הקבוצה הזאת הינה מיוחדת ומכילה את כל המשתמשים. אין אפשרות לשנות אותה";
$groups_users_in1 = "משתמש/ים בקבוצה";
$groups_no_users = "אין משתמשים בקבוצה זו.";
$groups_users_in_select = "בחר את המשתמשים שברצונך להוסיף לקבוצה זו.";

//translation required
$groups_new_group = 'קבוצה חדשה';
$groups_members = 'חברים';
