<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Felhasználói csoportok';
$groups_tab='Csoportok';
$groups_saved='Beállítások elmentve';
$groups_text='Kattintson egy csoportra a tulajdonságai megjelenítéséhez.';
$groups_users_in='Felhasználók a csoportban';
$groups_no_contacts='Nincsenek kiválasztható felhasználói névjegyei.<br /> Használja a névjegyalbumot felhasználói névjegyek hozzáadásához.';
$add_group_text='Írjon be egy nevet, majd kattintson az \'Ok\' gombra az új csoport hozzáadásához.';
$add_group_fail='A csoport hozzáadása sikertelen volt. Kérem próbálja újra.';
$add_group_success='A csoport hozzáadása sikeresen végrehajtva.';
$add_group_exists='Ez a név már létezik. Kérem válasszon egy másikat.';
$add_group_no_name='Nem adott meg nevet.';
$groups_everyone='Ez egy speciális csoport, ami minden felhasználót magába foglal. Nem módosítható.';
$groups_users_in1='felhasználó ebben a csoportban:';
$groups_no_users='Nincsenek felhasználók ebben a csoportban.';
$groups_users_in_select='Válassza ki azokat a felhasználókat, akiket hozzá szeretne adni ehhez a csoporthoz:';
$groups_new_group='Új csoport';
$groups_members='Tagok';
$lang_modules['groups']='Felhasználói csoportok';
?>