<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "gruppi di utenti";
$groups_tab = "gruppi";
$groups_saved = "Impostazioni salvare.";
$groups_text = "Seleziona un gruppo per visualizzarne le proprietà.";
$groups_users_in = "Utenti del gruppo ";
$groups_no_contacts = "Non hai nessun elemento nei contatti da selezionare.<br /> Usa la Rubrica per aggiungere elementi nei contatti.";

$add_group_text = "Inserisci un nome e seleziona 'salva' per aggiungere un gruppo nuovo.";
$add_group_fail = "Inserimento del gruppo fallito. Riprovare nuovamente.";
$add_group_success = "Gruppo inserito con successo.";
$add_group_exists = "Il nome esiste già. Scegliere un altro nome.";
$add_group_no_name = "Non hai specificato nessun nome.";
$groups_everyone = "Questo gruppo è speciale perché contiene tutti gli utenti. Non è possibile modificarlo.";
$groups_users_in1 = "utenti nel gruppo";
$groups_no_users = "Non ci sono utenti nel gruppo.";
$groups_users_in_select = "Seleziona gli utenti che vuoi inserire in questo gruppo:";

$groups_new_group = 'Nuovo gruppo';
$groups_members = 'Membri';

//2.13
$lang_modules['groups'] = 'Gruppi di Utenti';
