<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "ユーザグループ";
$groups_tab = "グループ";
$groups_saved = "設定を保存";
$groups_text = "グループをクリックしてプロパティを見る";
$groups_users_in = "グループの所属ユーザ ";
$groups_no_contacts = "選択する連絡先にメンバーが存在しません。<br /> アドレス帳を使って連絡先にメンバーを追加してください。";

$add_group_text = "新規グループに追加するため、名前を入力して「OK」をクリックしてください。";
$add_group_fail = "グループの追加に失敗しました。やり直してください。";
$add_group_success = "グループの追加に成功しました。";
$add_group_exists = "名前がすでに存在しています。違う名前を選択してください。";
$add_group_no_name = "名前を指定していません";
$groups_everyone = "このグループは全てのユーザを含む特別なグループです。このグループを編集しないでください。";
$groups_users_in1 = "グループの所属ユーザ ";
$groups_no_users = "グループに所属しているユーザはいません";
$groups_users_in_select = "このグループに追加したいユーザを選択:";

//translation required
$groups_new_group = '新規グループ';
$groups_members = 'メンバー';

//2.13
$lang_modules['groups'] = 'ユーザグループ';
