<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Gebruikersgroepen';
$groups_tab='Groepen';
$groups_saved='Wijzigingen opgeslagen.';
$groups_text='Klik op een groep om de eigenschappen te bekijken.';
$groups_users_in='Gebruikers in groep ';
$groups_no_contacts='U heeft geen gebruikers in uw contactpersonenlijst om te selecteren.<br />Gebruik het adres boek om gebruikers toe te voegen aan je contactpersonen.';
$add_group_text='Voer een naam in en klik op \'Ok\' om de groep toe te voegen.';
$add_group_fail='Fout bij het toevoegen van de groep. Probeer het opnieuw.';
$add_group_success='Groep succesvol toegevoegd.';
$add_group_exists='De naam bestaat al. Kies een andere.';
$add_group_no_name='U heeft geen naam opgegeven.';
$groups_everyone='Dit is een speciale group en bevat alle gebruikers. U kunt deze groep niet wijzigen.';
$groups_users_in1='gebruiker(s) in groep';
$groups_no_users='Er zitten geen gebruikers in deze groep.';
$groups_users_in_select='Selecteer de gebruikers die u wilt toevoegen aan deze groep:';
$groups_new_group='Nieuwe groep';
$groups_members='Leden';
$lang_modules['groups']='Gebruikersgroepen';
