<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$charset='UTF-8';
$groups_title = "grupos de usuários";
$groups_tab = "grupos";
$groups_saved = "Os ajustes foram salvos.";
$groups_text = "Clique em um grupo para examinar as suas propriedades.";
$groups_users_in = "usuários no grupo ";
$groups_no_contacts = "Você não tem nenhum contato para selecionar.<br /> Use o módulo Contatos para adicionar membros à lista de contatos.";
$add_group_text = "Insira um nome e clique sobre 'OK' para adicionar um novo grupo.";
$add_group_fail = "A inclusão do grupo falhou. Por favor tente outra vez.";
$add_group_success = "O grupo foi adicionado com sucesso.";
$add_group_exists = "Esse nome já existe. Por favor escolha outro nome.";
$add_group_no_name = "Você não especificou um nome.";
$groups_everyone = "Este grupo é um grupo especial e contém todos os usuários. Você não pode modificar este grupo.";
$groups_users_in1 = "Usuário(s) no grupo";
$groups_no_users = "Não existem usuários neste grupo.";
$groups_users_in_select = "Selecione os usuários que quer adicionar a este grupo:";

//translation required
$groups_new_group = 'Novo grupo';
$groups_members = 'Membros';

//2.13
$lang_modules['groups'] = 'Grupos de usuários';
