<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Grupos de utilizadores";
$groups_tab = "Grupos";
$groups_saved = "Alterações guardadas";
$groups_text = "Clique num grupo para ver os detalhes";
$groups_users_in = "Utilizadores no grupo ";
$groups_no_contacts = "Não existem contactos a seleccionar.<br /> Use a Agenda para adicionar membros aos contactos.";

$add_group_text = "Escreva um nome e clique em 'OK' para adicionar um novo grupo.";
$add_group_fail = "Houve um problema. Por favor tente de novo.";
$add_group_success = "O grupo foi adicionado com sucesso.";
$add_group_exists = "Esse nome j&aacute; existe. Por favor escolha outro nome.";
$add_group_no_name = "Não foi indicado um nome.";
$groups_everyone = "Este é um grupo especial, porque contém todos os utilizadores. Não pode modificar este grupo.";
$groups_users_in1 = "utilizador(es) no grupo";
$groups_no_users = "N&atilde;o existem utilizadores neste grupo.";
$groups_users_in_select = "Seleccione os utilizadores que quer adicionar a este grupo:";

//translation required
$groups_new_group = 'Novo grupo';
$groups_members = 'Membros';

//2.13
$lang_modules['groups'] = 'Grupos de utilizadores';