<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "çÒÕÐÐÁ ÐÏÌØÚÏ×ÁÔÅÌÅÊ";
$groups_tab = "çÒÕÐÐÙ";
$groups_saved = "îÁÓÔÒÏÊËÉ ÓÏÈÒÁÎÅÎÙ.";
$groups_text = "îÁÖÍÉÔÅ ÎÁ ÉÎÔÅÒÅÓÕÀÝÅÊ ÇÒÕÐÐÅ ÄÌÑ ÐÒÏÓÍÏÔÒÁ ÎÁÓÔÒÏÅË ÜÔÏÊ ÇÒÕÐÐÙ.";
$groups_users_in = "ðÏÌØÚÏ×ÁÔÅÌÉ × ÇÒÕÐÐÅ ";
$groups_no_contacts = "You don't have any member contacts to select.<br /> Use the the Addressbook to add members to your contacts.";

$add_group_text = "÷×ÅÄÉÔÅ ÉÍÑ ÇÒÕÐÐÙ É ÎÁÖÍÉÔÅ 'Ok' ÄÌÑ ÓÏÚÄÁÎÉÑ ÎÏ×ÏÊ ÇÒÕÐÐÙ.";
$add_group_fail = "äÏÂÁ×ÌÅÎÉÅ ÚÁ×ÅÒÛÉÌÏÓØ ÎÅÕÄÁÞÅÊ. ðÏÖÁÌÕÊÓÔÁ, ÐÏÐÒÏÂÕÊÔÅ ÅÝÅ ÒÁÚ.";
$add_group_success = "çÒÕÐÐÁ ÕÓÐÅÛÎÏ ÄÏÂÁ×ÌÅÎÁ.";
$add_group_exists = "ôÁËÏÅ ÉÍÑ ÕÖÅ ÓÕÝÅÓÔ×ÕÅÔ. ÷×ÅÄÉÔÅ ÄÒÕÇÏÅ ÉÍÑ.";
$add_group_no_name = "÷Ù ÎÅ ××ÅÌÉ ÉÍÑ ÇÒÕÐÐÙ.";
$groups_everyone = "üÔÁ ÇÒÕÐÐÁ Ñ×ÌÑÅÔÓÑ ÓÐÅÃÉÁÌØÎÏÊ É ÓÏÄÅÒÖÉÔ ×ÓÅÈ ÐÏÌØÚÏ×ÁÔÅÌÅÊ. ÷Ù ÎÅ ÍÏÖÅÔÅ ÉÚÍÅÎÑÔØ ÜÔÕ ÇÒÕÐÐÕ.";
$groups_users_in1 = "ÐÏÌØÚÏ×ÁÔÅÌØ(ÅÊ) × ÇÒÕÐÐÅ";
$groups_no_users = "îÅÔ ÐÏÌØÚÏ×ÁÔÅÌÅÊ × ÜÔÏÊ ÇÒÕÐÐÅ.";
$groups_users_in_select = "÷ÙÂÅÒÅÔÅ ÐÏÌØÚÏ×ÁÔÅÌÅÊ ÄÌÑ ÄÏÂÁ×ÌÅÎÉÑ × ÇÒÕÐÐÕ:";

//translation required
$groups_new_group = 'îÏ×ÁÑ ÇÒÕÐÐÁ';
$groups_members = 'õÞÁÓÔÎÉËÏ×';

//2.13
$lang_modules['groups'] = 'çÒÕÐÐÙ ÐÏÌØÚÏ×ÁÔÅÌÅÊ';
