<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Uporabniške skupine';
$groups_tab='Skupine';
$groups_saved='Nastavitve shranjene.';
$groups_text='Klikni na skupino za ogled njenih lastnosti.';
$groups_users_in='Uporabniki v skupini';
$groups_no_contacts='Nimate nobenih stikov od članov, ki bi jih lahko izbrali..<br /> Uporabite Adresar da dodate člane med svoje stike.';
$add_group_text='Za dodajanje nove skupine vnesite ime in kliknite na \'Ok\' ';
$add_group_fail='Nisem uspel dodati skupine. Prosim poizkusite ponovno.';
$add_group_success='Uspešno dodal skupino.';
$add_group_exists='To ime že obstaja. Prosim izberite drugo ime.';
$add_group_no_name='Niste določili imena.';
$groups_everyone='Ta skupina je posebna in vsebuje vse uporabnike. Ne morate spreminjati te skupine.';
$groups_users_in1='uporabnik(i) v skupini';
$groups_no_users='V tej skupini ni uporabnikov.';
$groups_users_in_select='Izberi uporabnike, ki jih želite dodato v to skupino:';
$groups_new_group='Nova skupina';
$groups_members='Člani';
$lang_modules['groups']='Uporabniške skupine';
?>