<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "Användargrupper";
$groups_tab = "Grupper";
$groups_saved = "Inställningar sparade.";
$groups_text = "Klicka på en grupp för att se dess egenskaper.";
$groups_users_in = "Användare i grupp ";
$groups_no_contacts = "Du har inga medlemskontakter att välja.<br /> Använd Adressboken för att lägga till medlemmar till dina kontakter.";

$add_group_text = "Skriv in ett namn och tryck på 'Ok' för att lägga in en ny grupp.";
$add_group_fail = "Inläggningen av gruppen misslyckades. Var god försök igen.";
$add_group_success = "Inläggningen av gruppen lyckades.";
$add_group_exists = "Namnet existerar redan. Var god välj ett annant namn.";
$add_group_no_name = "Du angav inget namn.";
$groups_everyone = "Denna grupp är en speciell grupp och innehåller alla användare. Du kan inte modifiera denna grupp.";
$groups_users_in1 = "användare i grupp";
$groups_no_users = "Det finns inga användare i denna grupp.";
$groups_users_in_select = "Välj de användare du vill lägga in i denna grupp:";

//translation required
$groups_new_group = 'Ny grupp';
$groups_members = 'Medlemmar';
