<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "กลุ่มผู้ใช้";
$groups_tab = "กลุ่ม";
$groups_saved = "บันทึกการเซ็ตนี้.";
$groups_text = "คลิกบนปุ่มเพื่อดูเพร็อพเพอร์ตี้";
$groups_users_in = "ผู้ใช้ในกลุ่ม ";
$groups_no_contacts = "คุณไม่มีสมาชิกที่จะเลือกได้<br /> ใช้แอ็ดเดรสบุคเพื่อเพิ่มสมาชิกของคุณ";

$add_group_text = "กรอกชื่อและคลิก 'ตกลง' เพื่อทำการเพิ่มกลุ่ม";
$add_group_fail = "การเพิ่มกลุ่มไม่สำเร็จกรุณาลองใหม่อีกครั้ง";
$add_group_success = "การเพิ่มกลุ่มสำเร็จ";
$add_group_exists = "ชื่อที่คุณตั้งซ้ำกับชื่อที่มีอยู่แล้วกรุณาตั้งชื่ออื่น";
$add_group_no_name = "คุณไม่สามาถใช้ชื่อเฉพาะได้";
$groups_everyone = "กลุ่มนี้เป็นกลุ่มพิเศษและได้บรรจุรายชื่อผู้ใช้ทั้งหมด. คุณไม่สามารถแก้ไขกลุ่มนี้ได้";
$groups_users_in1 = "รายชื่อผู้ใช้ในกลุ่ม";
$groups_no_users = "ไม่มีรายชื่อผู้ใช้ในกลุ่มนี้";
$groups_users_in_select = "เลือกรายชื่อผู้ใช้ที่ต้องการเพื่อเพิ่มเข้ากลุ่มนี้:";

//translation required
$groups_new_group = 'กลุ่มใหม่';
$groups_members = 'สมาชิก';
