<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));
$groups_title='Kullanıcı grupları';
$groups_tab='Gruplar';
$groups_saved='Ayarlar kaydedildi.';
$groups_text='Bir grubun özelliklerini görüntülemek için üzerine tıklayın.';
$groups_users_in='Gruptaki kullanıcılar';
$groups_no_contacts='Seçebileceğiniz hiç üye kartı yok.<br /> Üyeleri kartlarınıza eklemek için Adres Defteri\'ni kullanın.';
$add_group_text='Yeni grubu eklemek için bir isim girin ve \'Tamam\'a basın.';
$add_group_fail='Grup eklenirken hata oluştu. Lütfen tekrar deneyin.';
$add_group_success='Grup ekleme tamamlandı.';
$add_group_exists='Bu isim zaten mevcut. Lütfen başka bir isim seçin.';
$add_group_no_name='Bir isim belirtmediniz.';
$groups_everyone='Bu grup özel bir grup ve tüm kullanıcıları içeriyor. Bu grupta değişiklik yapamazsınız.';
$groups_users_in1='kullanıcı var grupta';
$groups_no_users='Bu grupta hiç kullanıcı yok.';
$groups_users_in_select='Bu gruba eklemek istediğiniz kullanıcıları seçin:';
$groups_new_group='Yeni grup';
$groups_members='Üyeler';
$lang_modules['groups']='Kullanıcı grupları';
?>