<?php
require_once($GO_LANGUAGE->get_fallback_language_file('groups'));

$groups_title = "使用者群組";
$groups_tab = "群組";
$groups_saved = "設定值已儲存";
$groups_text = "按群組觀看內容";
$groups_users_in = "群組內的使用者";
$groups_no_contacts = "你/妳沒有任何聯絡人成員以供選擇<br /> 使用通訊錄新增成員到你/妳的聯絡人";
	
$add_group_text = "輸入名稱再按「確定」來新增群組";
$add_group_fail = "新增群組失敗，請重試。";
$add_group_success = "已成功新增群組";
$add_group_exists = "名稱已存在，請選用其他名稱。";
$add_group_no_name = "你/妳沒有指定名稱";
$groups_everyone = "這個群組是一個包含所有使用者的特別群組，你/妳不能修改它。";
$groups_users_in1 = "群組內的使用者";
$groups_no_users = "這個群組沒有使用者";
$groups_users_in_select = "選擇你/妳想新增到這群組的使用者：";

//translation required
$groups_new_group = '新增群組';
$groups_members = '成員';
