<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='استديو';
$ig_thumbwidth='عرض مصغر';
$ig_new_gallery='استديو جديد';
$ig_images='صور';
$ig_resizeto='تغيير حجم الصور';
$ig_maxcolumns='\'Maximum columns';
$ig_insert_gallery='تدريج الاستديو';
$ig_gallery='الاستديو';
$ig_no_file='\'لا يوجد ملف ورد. اما انك لم تختر الملف أو الملفات المختاره كبير جدا';
$ig_upload='اضف صورة';
$ig_select_gallery='اختر استديو';
$ig_maxrows='Maximum rows';
$ig_uploaded_by='المودع به';
?>