<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Galeria';
$ig_thumbwidth='Amplada de les miniatures';
$ig_new_gallery='Nova galeria';
$ig_images='Imatges';
$ig_resizeto='Redimensiona les imatges a';
$ig_maxcolumns='Màxim de columnes';
$ig_insert_gallery='Insereix galeria';
$ig_gallery='Galeria';
$ig_no_file='No s\'ha rebut cap fitxer. O bé no heu seleccionat un fitxer o els fitxers seleccionats eren massa grans.';
$ig_upload='Afegeix imatges';
$ig_select_gallery='Seleccioneu galeria';
$ig_maxrows='Màxim de files';
$ig_uploaded_by='Enviat per';
?>