<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));

$lang_modules['gallery'] = 'Galerie';

$ig_thumbwidth = 'Šířka miniatury';
$ig_new_gallery = 'nová galerie';
$ig_images = 'Obrázky';
$ig_resizeto = 'Změň velikost obrázků na';
$ig_maxcolumns = 'Maximum sloupců';

$ig_insert_gallery = 'Vlož galerii';
$ig_gallery = 'Galerie';
$ig_no_file = 'Žádný soubor nebyl obdržen. Buď jste nevybral(a) soubor nebo vybraný soubor byl moc velký.';

$ig_upload = 'Přidej obrázky';

$ig_select_gallery = 'Vyber galerii';

$ig_maxrows = 'Maximum řádků';

$ig_uploaded_by = 'Nahrál';
