<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Galerie';
$ig_thumbwidth='Breite des Vorschaubild';
$ig_new_gallery='Neue Galerie';
$ig_images='Bilder';
$ig_resizeto='Verkleinere Bilder zu';
$ig_maxcolumns='Maximale Spalten';
$ig_insert_gallery='Galerie einfügen';
$ig_gallery='Galerie';
$ig_no_file='Es wurde keine Datei empfangen. Sie haben entweder keine Datei ausgewählt, oder die gewählten Dateien sind zu groß.';
$ig_upload='Bilder hinzufügen';
$ig_select_gallery='Gallerie auswählen';
$ig_maxrows='Maximale Spaltenanzahl';
$ig_uploaded_by='Hochgeladen von';
?>