<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('billing'));

$lang_modules['gallery'] = 'Gallery';

$ig_thumbwidth = 'Thumbnail width';
$ig_new_gallery = 'New gallery';
$ig_images = 'Images';
$ig_resizeto = 'Resize images to';
$ig_maxcolumns = 'Maximum columns';

$ig_insert_gallery = 'Insert gallery';
$ig_gallery = 'Gallery';
$ig_no_file = 'No file was recieved. You either didn\'t select a file or the selected files were too large.';

$ig_upload = 'Add images';

$ig_select_gallery = 'Select gallery';

$ig_maxrows = 'Maximum rows';

$ig_uploaded_by = 'Uploaded by';
