<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Galería';
$ig_thumbwidth='Ancho de la miniatura';
$ig_new_gallery='Nueva galería';
$ig_images='Imágenes';
$ig_resizeto='Redimensionar las imágenes a';
$ig_maxcolumns='Máximo de columnas';
$ig_insert_gallery='Insertar galería';
$ig_gallery='Galería';
$ig_no_file='No se ha recibido ningún fichero. O no ha seleccionado ninguno, o los que ha seleccionado eran demasiado grandes.';
$ig_upload='Añadir imágenes';
$ig_select_gallery='Seleccione galería';
$ig_maxrows='Máximo de filas';
$ig_uploaded_by='Enviado por';
?>