<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));

$lang_modules['gallery'] = 'Galerie';
$ig_thumbwidth = 'Largeur des miniatures';
$ig_new_gallery = 'Nouvelle galerie';
$ig_images = 'Images';
$ig_resizeto = 'Redimensionner les images à';
$ig_maxcolumns = 'Nombre maximum de colonnes';
$ig_insert_gallery = 'Insérer une galerie';
$ig_gallery = 'Galerie';
$ig_no_file = 'Aucun fichier n\a été reçu. Soit vous n\'avez pas sélectionner un fichier, soit le fichier est trop gros.';
$ig_upload = 'Ajouter des images';
$ig_select_gallery = 'Sélectioner une galerie';
$ig_maxrows = 'Nombre maximun de lignes';
$ig_uploaded_by = 'Ajouter par';
?>
