<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Képtár';
$ig_thumbwidth='Előnézeti kép szélessége';
$ig_new_gallery='Új galéria';
$ig_images='Képek';
$ig_resizeto='Képek átméretezése erre';
$ig_maxcolumns='Oszlopok maximális száma';
$ig_insert_gallery='Képtár beillesztése';
$ig_gallery='Képtár';
$ig_no_file='Nem érkezett be fájl. Vagy nem választott ki egy fájlt sem, vagy pedig a méretük túl nagy volt.';
$ig_upload='Képek hozzáadása';
$ig_select_gallery='Képtár kiválasztása';
$ig_maxrows='Sorok maximális száma';
$ig_uploaded_by='Feltöltötte:';
?>