<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Foto albums';
$ig_thumbwidth='Breedte miniaturen';
$ig_new_gallery='Nieuw fotoalbum';
$ig_images='Afbeeldingen';
$ig_resizeto='Herschaal afbeeldingen naar';
$ig_maxcolumns='Maximaal aantal kolommen';
$ig_insert_gallery='Fotoalbum invoegen';
$ig_gallery='Fotoalbum';
$ig_no_file='Er was geen bestand ontvangen. Je had geen bestand geselecteerd of de bestanden waren te groot.';
$ig_upload='Foto\'s toevoegen';
$ig_select_gallery='Selecteer fotoalbum';
$ig_maxrows='Maximum aantal rijen';
$ig_uploaded_by='Geplaatst door';
