<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));

$lang_modules['gallery'] = 'Galeria';

$ig_thumbwidth = 'Largura da miniatura';
$ig_new_gallery = 'Nova galeria';
$ig_images = 'Imagens';
$ig_resizeto = 'Redimensionar imagens para';
$ig_maxcolumns = 'Máximo de colunas';

$ig_insert_gallery = 'Inserir galeria';
$ig_gallery = 'Galeria';
$ig_no_file = 'Nenhum arquivo recebido. Você não selecionou nenhum arquivo ou o arquivo selecionado era muito grande.';

$ig_upload = 'Adicionar imagens';
