<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));

$lang_modules['gallery'] = 'Galeria';

$ig_thumbwidth = 'Tamanho das Miniaturas';
$ig_new_gallery = 'Nova galeria';
$ig_images = 'Imagens';
$ig_resizeto = 'Alterar tamanho das imagens para';
$ig_maxcolumns = 'Máximo de colunas';

$ig_insert_gallery = 'Inserir galeria';
$ig_gallery = 'Galeria';
$ig_no_file = 'Nenhum ficheiro recebido. Ou não seleccionou um ficheiro ou o ficheiro era demasiado grande.';

$ig_upload = 'Adicionar imagens';

$ig_select_gallery = 'Seleccione galeria';

$ig_maxrows = 'Máximo de linhas';

$ig_uploaded_by = 'Enviado por';
