<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Galerija';
$ig_thumbwidth='Širina sličice';
$ig_new_gallery='Nova galerija';
$ig_images='Slike';
$ig_resizeto='Spremeni velikost podob na';
$ig_maxcolumns='Največje število stolpcev';
$ig_insert_gallery='Vstavi galerijo';
$ig_gallery='Galerija';
$ig_no_file='Ni bilo prejetih datotek. Ali niste izbrali datoteke, ali pa so bile izbrane datoteke prevelike.';
$ig_upload='Dodaj slike';
$ig_select_gallery='Izberi galerijo';
$ig_maxrows='Največje število vrstic';
$ig_uploaded_by='Slike je naložil';
?>