<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('gallery'));
$lang_modules['gallery']='Galeri';
$ig_thumbwidth='Küçük resim genişliği';
$ig_new_gallery='Yeni galeri';
$ig_images='Resimler';
$ig_resizeto='Resimleri buna boyutlandır:';
$ig_maxcolumns='En fazla sütun sayısı';
$ig_insert_gallery='Galeri ekle';
$ig_gallery='Galeri';
$ig_no_file='Dosya alınamadı. Ya dosya seçmediniz veya seçtiğiniz dosya çok büyük.';
$ig_upload='Resim ekle';
$ig_select_gallery='Galeri seç';
$ig_maxrows='En fazla satır';
$ig_uploaded_by='Gönderen:';
?>