<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('users'));

$strLogins = "Logins";
$strRegistrationDate = "Registration Date";
$strUsers = "user(s)";
$user_profile = "User Profile";
$ac_login_info = "Login information";
$ac_registration_time = "Registration time";
$ac_lastlogin = "Last login";
$ac_logins = "Total logins";
$strMaxOf = "registered from the maximum of";
$strUsername = "Username";
$delete_fail = "You can't delete yourself and the superuser.";
$admin_new_user = "New user";

$admin_modules = 'Modules';
$admin_module_access = 'This user has access to the following modules:';

$admin_password = 'Password';
$admin_confirm_password = 'Confirm password';
$admin_change_password = 'Change password';
$admin_pass_match = 'The passwords didn\'t match. Please try again.';

//registration
$registration_personal_info = "Personal information";
$registration_account_info = "Account information";
$registartion_username_text = "Enter a username and password for this user to login to the site.";


$registration_text='Fill out this form and click on \'Ok\' to register. The fields marked with a * are required.';

$registartion_authcode_text = "Enter an authorisation code. The authorisationcode is a code that other users will need to add this user to thier contactlist and view your details.";
$registartion_confirm_authcode = "Confirm authorisation code";
$registration_visibility = "Make this user visible to all users.";

$registration_failure = "An error occured while trying to register. Please try again.";

$registration_folder_error = "Failed creating the personal folder. Contact us to restore this!";


$registration_email = "Create an E-mail address for this user at Group-Office.";
$registration_samba = "File & Print server.";
$registration_email_error = "An error occured while creating your e-mail account. Contact us for support.";
$strPasswordConfirm = "Confirm password";
$strPassword = "Password";

$reg_company_info = "Company information";

$max_user_limit = "Maximum ammount of users reached.";
$max_users_text = "Sorry, you can't register more users. Contact us if you want to increase your number of users.";
$ml_sent_items = "Sent items";
$ml_spam = "Spam";
$ac_samba_user = "User has acces to the file and print server.";
$ml_email_only = "Only required when you don't create an E-mail address";
$register_new_user = 'New Group-Office subscriber';
$register_thanks = '<h2>Thank you</h2>Your subscription will be processed as soon as possible. You will recieve further notice.';
$register_accept = 'Add to users';
$register_addressbook = 'Add to addressbook';
$register_title = 'Subscribe';


//1.98
$reg_language = 'Language';
$reg_theme = 'Theme';

//2.05
$admin_use = 'Use';
$admin_module = 'Module';
$admin_manage = 'Manage';

$admin_groups = 'User groups';
$admin_groups_user = 'User is member of the following user groups';

//2.13
$registration_mail_subject = "Welcome to %groupoffice_title%"; //changed string
$registration_title = "Register at %groupoffice_title%"; //changed string

$lang_modules['users'] = 'Users';

//2.14
$users_enabled = 'Account enabled';

$admin_groups_visible = 'User is visible to the following user groups';
$admin_look_feel = 'Look & feel';

//2.16
$disabled_user_fields_text = 'Select the fields you wish to disable for editing by regular users at their profile page.';

$admin_disabled_user_fields = 'Disable user fields';
$admin_registration_unconfirmed = 'Unconfirmed registration e-mail';
$admin_registration_confirmation = 'Registration confirmation e-mail';

$admin_registration_confirmation_text = 'This is the e-mail users recieve when they get a new active account. Leave empty for no e-mail.';
$admin_registration_unconfirmed_text = 'This is the e-mail users recieve when they get a new inactive account. Leave empty for no e-mail.';

$admin_subject = 'Subject';

//string modified:
$registration_success = "<h1>Congratulations!</h1>The new user has been created successfully.";
$registration_success_activate = "<h1>Activation still required</h1>The new user has been created successfully but the administrator needs to activate your account.";


$admin_new_user_subject = 'New user registered';
$admin_new_user_body = 'A new user has registered. Click at the link below to open the account.';
$admin_new_user_subject_activate = 'New user registered. Activation required';


$admin_password_changed = 'Password changed succesfully';


$registration_self_success = 'Welcome to %s!';
$registration_self_success_text = 'Your account was successfully created. You can now login using your username and password.';
$us_reset='Reset';
$us_never='Never';

$us_help_url='http://docs.group-office.com/index.php?folder_id=53&file_id=0';