<?php
require_once($GO_LANGUAGE->get_fallback_language_file('users'));

$ac_lastlogin = "Última entrada";
$strLogins = "Entradas";
$strRegistrationDate = "Data do Registo";
$user_profile = "Perfil do utilizador";
$ac_login_info = "Informação de entrada";
$ac_registration_time = "Hora do registo";
$ac_lastlogin = "Última entrada";
$ac_logins = "Total de entradas";
$strMaxOf = "registos de um máximo de";
$strUsername = "Nome de Utilizador";
$delete_fail = "Não pode apagar o seu registo nem o do super-utilizador.";
$admin_new_user = "Novo utilizador";

$admin_modules = 'M&oacute;dulos';
$admin_module_access = 'Este utilizador tem acesso aos seguintes m&oacute;dulos:';

$admin_password = 'Password';
$admin_confirm_password = 'Confirmar a password';
$admin_change_password = 'Mudar a password';
$admin_pass_match = 'As passwords n&atilde;o coincidem. Por favor tente outra vez.';

//registration
$registration_personal_info = "Informa&ccedil;&atilde;o pessoal";
$registration_account_info = "Informa&ccedil;&atilde;o sobre a conta";
$registartion_username_text = "Introduza o nome e a password para este utilizador poder aceder a este site.";

$registration_text='Preencha o formulário e clique em \'Ok\' para se registar. Os campos marcados com * são obrigatórios.';

$registartion_authcode_text = "Escreva um c&oacute;digo de autoriza&ccedil;&atilde;o. O c&oacute;digo de autoriza&ccedil;&atilde;o &eacute; um c&oacute;digo que os outros utilizadores necessitam para adicionar este utilizador a listas de contacto e ver os seus detalhes";
$registartion_confirm_authcode = "Confirme o c&oacute;digo de autoriza&ccedil;&atilde;o ";
$registration_visibility = "Tornar este utilizador visível a todos os utilizadores.";
$registration_success = "Novo utilizador criado com sucesso";

$registration_failure = "Ocorreu um erro. Por favor tente outra vez.";
$registration_mail_subject = "Bem-vindo ao Group-Office.";

$registration_folder_error = "Ocorreu um erro ao criar a pasta pessoal. Contacte o serviço de apoio ao programa!";
$registration_title = "Registo em %groupoffice_title%";

$registration_email = "Criar um endereço de email para este utilizador no Group-Office.";
$registration_samba = "Servidor de Ficheiros e Impressão";
$registration_email_error = "Ocorreu um erro ao criar a sua conta de email. Contate o serviço de apoio ao programa!";
$strPasswordConfirm = "Confirmar a password";
$strPassword = "Password";

$reg_company_info = "Informação";

$max_user_limit = "Foi atingido o máximo de utilizadores.";
$max_users_text = "Não pode registar mais utilizadores. Contacte o serviço de apoio para aumentar o n&uacute;mero de utilizadores.";
$ml_sent_items = "Itens enviados";
$ml_spam = "Spam";
$ac_samba_user = "O utilizador tem acesso ao servidor de ficheiros e de impressão.";
$ml_email_only = "Só é necessário quando não é criado um endereço de email";

$register_new_user = 'Novo utilizador Group-Office';
$register_thanks = '<h2>Obrigado</h2>O registo será processado tão depressa quanto possível. Irá receber mais notícias.';
$register_accept = 'Adicionar aos utilizadores';
$register_addressbook = 'Adicionar à agenda';
$register_title = 'Subscrever';


//1.98
$reg_language = 'Língua';
$reg_theme = 'Tema';

//2.05
$admin_use = 'Use';
$admin_module = 'Módulo';
$admin_manage = 'Gerir';

$admin_groups = 'Grupos de utilizadores';
$admin_groups_user = 'O utilizador é membro dos seguintes grupos de utilizadores';

//2.13
$registration_mail_subject = "Bem-vindo a %groupoffice_title%"; //changed string
$registration_title = "Registar em %groupoffice_title%"; //changed string

$lang_modules['users'] = 'Utilizadores';

//2.14
$users_enabled = 'Conta activada';

$admin_groups_visible = 'O utilizador é visível para os seguintes grupos';
$admin_look_feel = 'Aspecto';

//2.16
$disabled_user_fields_text = 'Seleccione os campos que deseja impedir de alterações por parte dos utilizadores na sua página de perfil.';

$admin_disabled_user_fields = 'Desactivar campos dos utilizadores';
$admin_registration_unconfirmed = 'Email de registo não confirmado';
$admin_registration_confirmation = 'Email de registo confirmado';

$admin_registration_confirmation_text = 'Este é o email que os utilizadores recebem quando a conta é activada. Deixe em branco para não enviar email.';
$admin_registration_unconfirmed_text = 'Este é o email que os utilizadores recebem quando a conta está inactiva. Deixe em branco para não enviar email.';

$admin_subject = 'Assunto';

//string modified:
$registration_success = "<h1>Parabéns!</h1>Um novo utilizador foi criado com sucesso.";
$registration_success_activate = "<h1>Activação ainda necessária</h1>O novo utilizador foi criado com sucesso mas o administrador necessita de activar a conta.";


$admin_new_user_subject = 'Novo utilizador registado';
$admin_new_user_body = 'Foi registado um novo utilizador. Clique na ligação abixo para abrir a conta.';
$admin_new_user_subject_activate = 'Novo utilizador registado. Activação necessária.';


$admin_password_changed = 'Password alterada com sucesso';


$registration_self_success = 'Bem-vindo a %s!';
$registration_self_success_text = 'A conta foi criada com sucesso. Pode agora entrar com o nome de utilizador e password.';
$us_reset='Anular';
$us_never='Nunca';

$us_help_url='http://docs.group-office.com/index.php?folder_id=53&file_id=0';
