<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('users'));

$strLogins = "Prijave";
$strRegistrationDate = "Datum registracije";
$strUsers = "uporabnik(i)";
$user_profile = "Uporabnikov profil";
$user_profile = "Uporabni¹ki profil";
$ac_login_info = "Prijavna informacija";
$ac_login_info = "Prijavne informacije";
$ac_registration_time = "Èas registracije";
$ac_registration_time = "Èas registracije";
$ac_lastlogin = "Zadnja prijava";
$ac_lastlogin = "Zadnja prijava";
$ac_logins = "Skupaj prijav";
$ac_logins = "Skupaj prijav";
$strMaxOf = "registriran iz maksimuma od";
$strUsername = "Uporabni¹ko ime";
$strUsername = "Uporabni¹ko ime";
$delete_fail = "Sebe ali nadzornika ne more¹ zbrisat.";
$admin_new_user = "Nov uporabnik";

$admin_modules = 'Moduli';
$admin_modules = 'Moduli';
$admin_module_access = 'Ta uporabnik ima dovoljenja za dostop do modulov:';

$admin_password = 'Geslo';
$admin_confirm_password = 'Potrdi geslo';
$admin_change_password = 'Spremeni geslo';
$admin_pass_match = 'Gesli se ne ujemata. Prosim, poskusite znova.';

//registration
$registration_personal_info = "Osebne informacije";
$registration_account_info = "Informacije o raèunu";
$registartion_username_text = "Vnesite uporabni¹ko ime in geslo za tega uporabnika, za prijavo na stran.";

$registration_question_text=<<<registration_question_text
Vnesite skrivno vpra¹anje, za katerega uporabnik pozna odgovor. To vpra¹anje vam bomo zastavili v primeru, èe uporabnik pozabi svoje geslo.
Ko je podan pravilen odgovor, bo na registriran elekronski naslov poslana e-po¹ta z uporabni¹kim imenom in geslom.
registration_question_text;

$registration_text=<<<registration_text
Za registracijo zapolnite obrazec in kliknite na 'V redu'. Polja oznaèena z * so obvezna.<br />
Informacije, ki jih boste vnesli so samo za uporabo v Group-Office in je ne bomo posredovali nikomur drugemu.
registration_text;

$registartion_authcode_text = "Vnesite pooblastitevno kodo. Pooblastitvena koda je koda, ki jo bodo drugi uporabniki potrebovali, da bodo dodali uporabnika na njihov seznam stikov in videli va¹e podrobnosti.";
$registartion_confirm_authcode = "Potrdi kodo pooblastitve";
$registration_visibility = "Ta uporabnik naj bo viden vsem.";
$registration_success = "<h1>Èestitke!</h1>Uspe¹no ste bili registrirani, pozdravno sporoèilo pa je bilo poslano na:";
$registration_failure = "Med registracijo va¹ih informacij je pri¹lo do napake. Prosim, poskusite znova.";
$registration_mail_subject = "Pozdravljeni v Group-Office.";
$registration_folder_error = "Napaka pri ustvarjanju osebnega imenika. NaveŸite stik z nami za re¹itev!";
$registration_title = "Registriraj se na Group-Office";

$registration_email = "Na Group-Office ustvari e-po¹tni raèun za tega uporabnika.";
$registration_samba = "Datoteèni in tiskalni¹ki streŸnik.";
$registration_email_error = "Med ustvarjanjem va¹ega e-po¹tnega raèuna je pri¹lo do napake. Za podporo naveŸite stik z nami.";
$strPasswordConfirm = "Potrdi geslo";
$strPassword = "Geslo";
$strPassword = "Geslo";

$reg_company_info = "Informacije o podjetju";

$max_user_limit = "DoseŸeno je maksimalno ¹tevilo uporabnikov.";
$max_users_text = "?al ne morete registrirat veè uporabnikov. NaveŸite stik z nami, èe Ÿelite poveèat va¹e ¹tevilo uporabnikov.";
$ml_sent_items = "Poslano";
$ml_sent_items = "Poslano";
$ml_spam = "NeŸelena po¹ta";
$ml_spam = "NezaŸelena po¹ta";
$ac_samba_user = "Uporabnik ima dostop do datoteke in tiskalni¹kega streŸnika.";
$ml_email_only = "Zahtevano samo, ko ne ustvari¹ elektronskega naslova";
$register_new_user = 'Nov naroènik Group-Office-a';
$register_thanks = '<h2>Hvala</h2>Va¹a naroènina bo obdelana takoj ko bo moŸno. Prejeli boste nadaljno obvestilo.';
$register_accept = 'Dodaj k uporabnikom';
$register_addressbook = 'Dodaj k adresarju';
$register_title = 'Naroèi';
$registration_mail_body=<<<registration_mail_body
Dragi %sex% %last_name%,

Registrirani ste bili na Group-Office.
Upamo, da vam bo v¹eè na¹a storitev.

Prijavite se lahko z neslednjimi podatki:

Uporabni¹ko ime: %username%
Geslo: %password%

Za prijavo kliknite na spodnji gumb:

registration_mail_body;

//1.98
$reg_language = 'Jezik';
$reg_theme = 'Tema';

//2.05
$admin_use = 'Uporabi';
$admin_module = 'Modul';
$admin_manage = 'Upravljaj';

$admin_groups = 'Uporabni¹ke skupine';
$admin_groups_user = 'Uporabnik je èlan naslednjih skupin';
