<?php
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "От";
$ml_to = "За";
$ml_send = "Изпращам";
$ml_attach = "Закачва";
$ml_attachments = "Закачвам";
$ml_attachment = "Притурка";
$ml_high = "High";
$ml_normal = "Нормално";
$ml_low = "Ниско";
$ml_priority = "Приоритет";
$ml_subject = "Относно";
$ml_filename = "Име на файла";
$ml_total_size = "Общ размер";
$ml_size = "Размер";
$ml_to_empty = "Не сте отбелязали получател.";
$ml_print = "Печат";
$fbNoSelect = "Не сте избрали съобщение";

$ml_inbox = 'Входящи';
$ml_properties = 'Свойства';
$ml_add_account = "Добави адрес";
$em_new_folder = "Нова папка";
$ml_your_accounts = "Вашите E-mail акаунти";
$ml_no_accounts = "Нямате никакви конфигурирани E-mail акаунти.";
$ml_original_follows = "----- Оригинално Съобщение -----";
$ml_welcome = "Добре дошли в Група-Офис E-mail";
$ml_text = "Натиснете на акаунти за да добавите пощенски акаунт.";
$ml_accounts = "Регистрация";
$ml_compose = "Ново писмо";
$ml_delete = "Изтривам";
$ml_refresh = "Опресни";
$ml_reply = "Отговор";
$ml_forward = "Препращане";
$ml_reply_all = "Отговор на всички";
$ml_delete_message = "Сигурен ли сте че искате да изтриете това съобщение?";
$ml_no_subject = "Няма предмет";
$ml_no_reciepent = "Неоткрит получател";
$ml_online_files = "Файлове онлайн";
$ml_send_error = "Неуспешно изращане на пощата.";

$ml_attach_forget = "вие сте избрал файл но не сте го прикачили.";
$ml_messages = "Съобщения";
$ml_message = 'това съобщение';
$ml_messages2 = 'Съобщение';
$ml_new = "нов";
$ml_delete_mailbox = "Сигурен ли сте че искате да истриете това съобщение веднага?";

$contact_profile = "Контактен профил";
$ml_add_contact = "Добавете подателя към контакт листа";
$strHost = "Гост";
$strDefault = "Обичаен";
$ml_edit_account = "Добавете акаунт";
$ml_new_account = "Нов акаунт";
$ml_no_messages = "Няма съобщения в таи папка.";
$ml_file_too_big = "Файлът който се опитвате да прекачите и твърде голям, максимума е: ";
$fbNoRightToOverwrite = "Файлът вече съществува не ви е позволено да го презаписвате.";
$ml_save_attachment = "Запази прекачването в Group-Office.";
$ml_folders = "папки";

$ml_select_folder = "Изберете папка където Group-Office може да съхрани изпратени съобщения или въведете име отдолу за да създадете папка";
$ml_connect_failed = "Не може да се свържете с mail server:";
$ml_at_port = "at port";
$ml_solve_error = 'Натиснете върху \'Акаунти\' за да поправите настройките на вашия акаунт или натиснете върху \'Опресни\' за да отворите вашият обичаен акаунт.';
$ml_sent_items = "Изпратени икони";
$ml_spam = "Спам";
$ml_use = "използвам";
$ml_synchronise = "синхронизирам";
$ml_move_mail = "Премести маркираното съобщение в папка...";
$ml_filters = "филтри";
$ml_move_to = "после преместете съобщението към папка:";
$ml_email_is = "Ако e-mail адреса на получателя съдържа:";
$ml_to_is = "Ако полето на получателите съдържа:";
$ml_cc_is = "ако полето на cc съдържа:";

$ml_subject_is = "Ако темата съдържа:";
$ml_new_filter = "Нов филтър:";
$ml_field = "Поле";
$ml_contains = "Съдържание";
$ml_folder = "Папка";
$ml_no_folders = "Вие нямате никакви папки така че не можете да създадете филтри.";
$ml_unwanted = "Кликнете тук ако E-mail на подателя е нежелан";
$fbFolderSize = "Размер на папката";
$ml_move_up = "Увеличи приоритета";
$ml_delete_filter = "Сигурен ли сте че искате да изтриете тези филтри?";
$ml_high_priority = "Това съобщение има висок приоритет!";
$ml_low_priority = "Това съобщение има нисък приоритет.";
$ml_block = "блокирай изпращача";
$ml_sent_items_fail = "Съобщението беше изпратено но възникна грешка докато съобщението се записваше във вашата папка за изпратени съощения. Проверете вашият IMAP акаунт.";
$fbProperties = "Свойства";
$ml_notification = "Искане от получателя да изпрати прочетено известие";
$ml_ask_notify = "Подателя на това съобщение has requested a read notification from you. Do you wish to send a read report?";
$ml_displayed = "Този E-mail е показан като";
$ml_notify = "Read Notification";
$ml_delete_filter1 = "изтрий филтър";
$ml_html_message_attached = "Оригиналните HTML съобщения са прикачени";
$ml_add_recievers = "Прибави непознат получател към вашата адресна книга";
$ml_no_folders = 'Нямате никакви папки да филтрирате към';
$ml_no_filters = 'Нямате никакви филтри.';

$ml_host = 'Гост';
$ml_port = 'Порт';
$ml_type = 'Вид';
$ml_servertype = 'Вид сървър';
$ml_format = 'Формат';
$ml_loose_changes = 'Промените ще бъдат загубени Искате ли да продължите?';

$ml_markread = "Маркирайте&nbsp;as&nbsp;като прочетено";
$ml_markunread = "Маркирайте&nbsp;as&nbsp;като непрочетено";
$ml_root_mailbox = "the root mailbox";
$ml_inside = "в";

//translation required
$ml_no_mailbox = "Това не е пощенска кутия. Тази папка не може да съдържа съобщения.";
$ml_signature = 'Подпис';
$ml_root = 'Root mailbox';
$ml_disable_accounts = 'Забрани account management';
$ml_trash = 'Кош';
