<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

$ml_from = 'Od';
$ml_to = 'Komu';
$ml_send = 'Odeslat'; 
$ml_attach = 'Připojit'; 
$ml_attachments = 'Přílohy'; 
$ml_attachment = 'Příloha'; 
$ml_high = 'Velká'; 
$ml_normal = 'Střední'; 
$ml_low = 'Malá'; 
$ml_priority = 'Priorita'; 
$ml_subject = 'Předmět'; 
$ml_filename = 'Název souboru'; 
$ml_total_size = 'Celková velikost';
$ml_size = 'Velikost'; 
$ml_to_empty = 'Nespecifikovali jste příjemce';  
$ml_print = 'Tisk';
$fbNoSelect = 'Nevybrali jste žádnou zprávu'; 
$ml_inbox = 'Příchozí pošta';
$ml_properties = 'Vlastnosti'; 
$ml_add_account = 'Přidejte účet'; 
$em_new_folder = 'Nová složka'; 
$ml_your_accounts = 'Váš e-mailový účet'; 
$ml_no_accounts = 'Nenakonfiguroval jste žádný e-mailový účet'; 
$ml_original_follows = '----- Původní zpráva -----';
$ml_welcome = 'Vítejte v Group-Office E-mailu'; 
$ml_text = 'Klikněte na účty pro přidání mail účtu'; 
$ml_accounts = 'Účty'; 
$ml_compose = 'Napsat';
$ml_delete = 'Odstranit'; 
$ml_refresh = 'Aktualizovat';
$ml_reply = 'Odpovědět'; 
$ml_forward = 'Předat dál'; 
$ml_reply_all = 'Odpovědět všem'; 
$ml_delete_message = 'Jste si jistý, že chcete tuto zprávu odstranit na trvalo?'; 
$ml_no_subject = 'Žádný předmět'; 
$ml_no_reciepent = 'Nezobrazený příjemce';  
$ml_online_files = 'Online soubory'; 
$ml_send_error = 'Neúspěšné zaslání zprávy.'; 
$ml_attach_forget = 'Vybrali jste soubor, ale nepřipojili ho.';  
$ml_messages = 'zprávy'; 
$ml_message = 'zpráva';
$ml_messages2 = 'zprávy'; 
$ml_new = 'Nová'; 
$ml_delete_mailbox = 'Jste si jistý, že chcete smazat vybranou složku na trvalo?'; 
$contact_profile = 'Profil kontaktu'; 
$ml_add_contact = 'Přidat odesílatele do kontaktů'; 
$strHost = 'Host';
$strDefault = 'Výchozí';
$ml_edit_account = 'Nastavení'; 
$ml_new_account = 'Nový účet'; 
$ml_no_messages = 'V této složce nejsou žádné zprávy.'; 
$ml_file_too_big = 'Soubor, který jste zkoušel připojit, je příliš velký, maximální velikost přílohy je: '; 
$fbNoRightToOverwrite = ' Tento soubor již existuje a nemáte povolení jej přepsat.';
$ml_save_attachment = 'Uložte přílohu do Group-Office.'; 
$ml_folders = 'Složky'; 
$ml_select_folder = 'Vyberte složku, kde Group Office může ukládat/uchovávat poštu nebo zadejte jméno pro vytvoření složky'; 
$ml_connect_failed = 'Neúspěšné spojení k severu pošty'; 
$ml_at_port = 'Na portu';
$ml_solve_error = 'Klikněta na "Účty" pro opravu nastavení vašeho účtu nebo klikněte na "Obnovit" pro otevření nastaveného účtu.'; 
$ml_sent_items = 'Odeslané e-maily';
$ml_spam = 'Nevyžádané e-maily'; 
$ml_use = 'Použít';
$ml_synchronise = 'Synchronizovat';
$ml_move_mail = 'Přesuňte vybrané zprávy do složky...'; 
$ml_filters = 'Filtry';
$ml_move_to = 'Potom přesuňte  zprávu do složky:'; 
$ml_email_is = 'Jestliže odesílatelova adresa obsahuje:';
$ml_to_is = 'Jestliže příjemce obsahuje:'; 
$ml_cc_is = 'Jestliže cc položka obsahuje:';
$ml_subject_is = 'Jestliže předmět obsahuje:'; 
$ml_new_filter = 'Nový Filtr:';
$ml_field = 'Položka';
$ml_contains = 'Obsahuje';
$ml_folder = 'Složka'; 
$ml_no_folders = 'Nemáte žádné složky takže nemůžete vytvořit filtr';
$ml_unwanted = 'Klikněte zde, jestliže e-mail od tohoto odesílatele je nevyžádaný.';
$fbFolderSize = 'Velikost složky'; 
$ml_move_up = 'Vzestupná priorita'; 
$ml_delete_filter = 'Jste si jistý, že chcete smazat tento filtr'; 
$ml_high_priority = 'Tato zpráva má velkou důležitost!'; 
$ml_low_priority = 'Tato zpráva má malou důležitost';  
$ml_block = 'Blokovat odesílatele'; 
$ml_sent_items_fail = ' Tato zpráva byla odeslána, ale během přesunu zprávy do složky Pošta k odesílání nastala chyba. Prosím zkontrolujte svůj IMAP účet.'; 
$fbProperties = 'Vlastnosti';
$ml_notification = 'Požádat příjemce o zaslání potvrzení o přečtení'; 
$ml_ask_notify = 'Odesílatel této zprávy si od Vás vyžádal potvrzení o přečtení. Přejete si potvrzení odeslat?'; 
$ml_displayed = 'Tento následující e-mail je zobrazen... ';
$ml_notify = 'Potvrzení o přečtení';
$ml_delete_filter1 = 'Smazat filtr';
$ml_html_message_attached = 'Původní HTML zprávy jsou připojeny';
$ml_no_folders = 'Nemáte žádné složky k filtrování';
$ml_no_filters = 'Nemáte žádné filtry';
$ml_host = 'Host';
$ml_port = 'Port';
$ml_type = 'Typ';
$ml_servertype = 'Typ serveru';
$ml_format = 'Formát';
$ml_loose_changes = 'Změny nebudou uloženy. Jste si jistý?';
$ml_markread = 'Označit jako přečtené';
$ml_markunread = 'Označit jako nepřečtené';
$ml_root_mailbox = 'Kořenová schránka';
$ml_inside = 'v';
$ml_no_mailbox = 'Toto není schránka. Tato složka nemůže obsahovat zprávy.';
$ml_signature = 'Podpis';
$ml_root = 'Kořenová schránka';
$ml_disable_accounts = 'Zablokovat správu účtu';
$ml_trash = 'Koš';
$ml_disable = 'Zakázáno';
$ml_confirm_empty_mailbox = 'Jste si jistý, že chcete vyprázdnit tuto složku?';
$ml_empty_mailbox = 'Vyprázdnit&nbsp;složku';
$ml_you_have = 'Máte';
$ml_new_mail_single = 'novou e-mailovou zprávu';
$ml_new_mail_multiple = 'nové e-mailové zprávy.';
$ml_auto_check = 'Automaticky kontrolovat tento účet na nové zprávy.';
//1.98
$ml_no_contacts_in_mailing_group = 'V poštovní skupině, kterou jste vybrali nejsou žádné kontakty.  Prosím nejprve do této skupiny přidejte kontakty.';
$ml_attention= 'Upozornění';

//2.02
$ml_autocheck_disabled = ' není k dispozici. Automatická kontrola pro přijímání nových zpráv je pro tento účet vypnuta.';
$ml_mark = 'Označit zprávy...';
$ml_flag = 'Označit';
$ml_clearflag = 'Odznačit';
$ml_expand_all = 'Rozbalení všech složek';
$ml_collapse_all = 'Sbalení všech složek';

//2.05
$ml_search = 'Hledat';
$ml_answered = 'S odpovědi';
$ml_doesnt_matter = 'Není důležité';
$ml_body = 'Text zprávy';
$ml_before = 'Starší než';
$ml_since = 'Novější než';
$ml_select_one_criteria = 'Prosím zvolete nebo zadejte alespoň jedno kritétium pro hledání.';

//2.06
$ml_appointment = 'Zpráva obsahuje schůzku. Chcete ji zobrazit v kalendáři?';
$ml_mails_were_sent = 'e-mail byl odeslán';
$ml_novalidate_cert = 'Nekontrolovat certifikát';
$ml_appointment_vcf = 'Zpráva obsahuje kontaktní adresu. Chcete ji zobrazit v adresáři?';
$ml_add_recievers = 'Přidej neznámé příjemce do adresáře...';

//2.08 
$ml_add_senders = 'Ptát se na přidání neznámých odesílatelů do standardního adresáře';
$ml_text_format = 'Holý text';
$ml_html_format_is = 'HTML (když prohlížeč podporuje HTML editaci)';
$ml_html_format = 'HTML formatovaný';
$ml_always_ask_notification = 'Vždy se ptát příjemce na potvrzení o přečtení';
$ml_ask_add_sender = 'Adresa odesílatele %s patřící %s není ve Vašem adresáři. Chcete ji teď přidat?';

$ml_edit_filter = 'Změna filtru';
$ml_choose_action = 'Prosím zvolte akci:';
$ml_search_criteria = 'Kritéria pro hledání';
$ml_sender = 'Odesílatel';
$ml_reciever = 'Příjemce';
$ml_cc_reciever = 'Příjemce kopie';

//2.10
$ml_empty_trash = 'Vysypat&nbsp;koš';
//2.11
$ml_drafts = 'Koncept';
$ml_save_draft_error = 'Chyba při ukládání konceptu. Prosím zkontrolujte nastavení Vašeho účtu.';
$ml_search_sender = 'Hledat další e-maily pro tohoto odesílatele';

$ml_no_attachments = 'Nejsou připojeny žádné soubory';
$ml_search_active = 'Hledání je aktivní. Nejsou zobrazeny všechny zprávy ve složce. Klikněte zde pro ukončení hledání.';
$ml_local_files = 'Místní soubory';
$ml_please_close_attachments = 'Prosím uzavřete okno s prílohami a ujistěte se že jsou všechny přeneseny na server.';

$ml_please_wait = 'Prosím vyčkejte...';
$ml_max_attachment_size = 'Maximální velikost příloh';
$ml_select = 'Zvolte soubor';
$ml_multiple_files = 'Více souborů';

//2.12
$ml_reenter_password = 'Z bezpečnostních důvodů je třeba znovu zadat heslo pro Váš e-mailový účet.';
/////// extra string for my extension - used ?
$ml_sent_ok = 'Mail byl odeslan.';
$ml_sent_ok_not_stored = 'E-mail byl odeslan, ale neni definovana slozka pro odchozi maily.\nNastavte ji v dialogu slozky.';
$ml_attachments_added = 'připojené soubory';
$ml_attachment_added = 'připojený soubor';

//2.13
$ml_download_zipped_attachments = 'Zip archív všech přípon';
$ml_fullscreen = 'Otevři&nbsp;fullscreen';
$ml_nofullscreen = 'Zavři&nbsp;fullscreen';
$ml_confirm_empty_trash = 'Jste sijistí, ze chcete vyprázdnit koš?';
$ml_seen = 'Přečteno';
$ml_charset = 'Kódování';

//2.14
$ml_no_reciever_add = "Nepřidávej";
$ml_add_recievers = "Přidej neznámé příjemce do";//changed string from 2.06

$ml_automatic_reply = 'Aktivuj automatickou odpověď';

$ml_set_default = 'Nastav výchozí';

$ml_used_of = 'použito';

$ml_folder_not_available = 'Nemůžete vytvořit extra adresáře, pokud používáte POP-3 účty';

//2.15
$ml_mark_as_read='Označ filtrované zprávy jako přečtené';

$ml_get_message_error_title = 'Chyba při stahování zprávy';
$ml_get_message_error_text = 'Nemohu stáhnout zprávu ze serveru. Možná byla smazána jiným klientem. Prosím klikněte na \'Refresh\'.';
$ml_spamtag = 'Spam tag';
$ml_confirm_no_subject = 'Nenapsal jste předmět pro tento e-mail. Jste si jisti, že chcete poslat tento e-mail bez předmětu?';
$ml_show_preview = 'Ukaž náhled, když vyberu zprávu';

$ml_show_headers = 'Ukaž hlavičky zprávy';
$ml_confirm_empty_mailbox = 'Jste si jisti, že chcete vyprázdnit adresář \'%s\'?';

//2.16
$em_source = 'Zdrojový kód zprávy';
$ml_messages_linked = 'Vybrané zprávy jsou provázány';
$ml_handle_originals='Co chcete dělat s originálními zprávami?';
$ml_keep='Nechej';
$ml_examine_headers='Ukaž sponku, když má zpráva přílohu a když má vyšší prioritu ve vylistování zpráv. Varování! Toto zpomaluje prohlížení zpráv v seznamu.';
$ml_show_attachments='Ukaž přílohy a priority (pomalejší vylistování)';
$ml_unknown_reciepent='Příjemce je neznámý. Prosím vyplňte příjemcův profil.';

$ml_auto_check='Zkontroluj zda nejsou nějaké nové zprávy automaticky';
$ml_show_new_mail='Vždy ukazuj počet nových zpráv na vrchu ovládací lišty (vedle vyhledat)';
$ml_beep='Pípni na nový e-mail';

//2.17
$ml_mail_to='Editor zpráv by měl být pro Vás otevřen, jelikož jste klikli na e-mail adresu %s.';
$ml_windows_mail = 'Když chcete použít Group-Office jako Váš výchozí e-mailový klient v Microsoft Windows, tak potřebujete zapsat tento soubor do registru Windows. Po zapsání souboru do registrů si můžete vybrat Group-Office jako váš výchozí e-mail klient ve Windows v Ovládacích panelech -> Nastavení internetu -> Programy';
$ml_download_reg='Stáhni soubor registru';

$ml_help_url='http://docs.group-office.com/index.php?folder_id=57&file_id=0';

$ml_attachment_message = 'Zpráva';

$ml_open_popup='Příjde-li nový email, použij vyskakovací okno';

$ml_vacation='Automatická odpověď';

//2.18
$ml_forward_local_copy='Nech zprávu i na tomto účtě';

