<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('email'));

$ml_from = "From";
$ml_to = "To";
$ml_send = "Send";
$ml_attach = "Attach";
$ml_attachments = "Attachments";
$ml_attachment = "Attachment";
$ml_high = "High";
$ml_normal = "Normal";
$ml_low = "Low";
$ml_priority = "Priority";
$ml_subject = "Subject";
$ml_filename = "Filename";
$ml_total_size = "Total size";
$ml_size = "Size";
$ml_to_empty = "You didn't specify a recipient.";
$ml_print = "Print";
$fbNoSelect = "You didn't select a message";
$ml_inbox = 'Inbox';
$ml_properties = 'Properties';
$ml_add_account = "Add an account";
$em_new_folder = "New Folder";
$ml_your_accounts = "Your E-mail accounts";
$ml_no_accounts = "You don't have any E-mail accounts configured.";
$ml_original_follows = "----- Original Message -----";
$ml_welcome = "Welcome to Group-Office E-mail";
$ml_text = "Click on accounts to add a mail account.";
$ml_accounts = "Accounts";
$ml_compose = "Compose";
$ml_delete = "Delete";
$ml_refresh = "Refresh";
$ml_reply = "Reply";
$ml_forward = "Forward";
$ml_reply_all = "Reply all";
$ml_delete_message = "Are you sure you want to delete this message permanently?";
$ml_no_subject = "No subject";
$ml_no_reciepent = "Undisclosed recipient";
$ml_online_files = "Online files";
$ml_send_error = "Failed sending the mail.";
$ml_attach_forget = "You have selected a file but you didn't attach it.";
$ml_messages = "message(s)";
$ml_message = 'this message';
$ml_messages2 = 'messages';
$ml_new = "new";
$ml_delete_mailbox = "Are you sure you want to delete selected messages permanently?";
$contact_profile = "Contact profile";
$ml_add_contact = "Add sender to contacts";
$strHost = "Host";
$strDefault = "Default";
$ml_edit_account = "Edit account";
$ml_new_account = "New account";
$ml_no_messages = "There are no messages in this folder.";
$ml_file_too_big = "The file you tried to attach is too big, the maximum size for attachments is set to: ";
$fbNoRightToOverwrite = "The file already exists and you are not allowed to overwrite it.";
$ml_save_attachment = "Save attachment in Group-Office.";
$ml_folders = "Folders";
$ml_select_folder = "Select the folder where Group-Office can store sent mail or enter a name below to create a folder";
$ml_connect_failed = "Failed to connect to mail server:";
$ml_at_port = "at port";
$ml_solve_error = 'Click on \'Accounts\' to correct your account settings or click on \'Refresh\' to open your default account.';
$ml_sent_items = "Sent items";
$ml_spam = "Spam";
$ml_use = "Use";
$ml_synchronise = "synchronise";
$ml_move_mail = "Move selected messages to folder...";
$ml_filters = "Filters";
$ml_move_to = "then move the message to folder:";
$ml_email_is = "If the sender's E-mail adress contains:";
$ml_to_is = "If the recievers field contains:";
$ml_cc_is = "If the cc field contains:";
$ml_subject_is = "If the subject contains:";
$ml_new_filter = "New Filter:";
$ml_field = "Field";
$ml_contains = "Contains";
$ml_folder = "Folder";
$ml_no_folders = "You don't have any folders so you can't create filters.";
$ml_unwanted = "Click here if E-mail from this sender is unwanted";
$fbFolderSize = "Size of folder";
$ml_move_up = "Increase priority";
$ml_delete_filter = "Are you sure you want to delete this filter?";
$ml_high_priority = "This message has high priority!";
$ml_low_priority = "This message has low priority.";
$ml_block = "Block sender";
$ml_sent_items_fail = "The message was send but there was an error while creating this message in your sent items folder. Check your IMAP account.";
$fbProperties = "Properties";
$ml_notification = "Request the recipient to send a read notification";
$ml_ask_notify = "The sender of this message has requested a read notification from you. Do you wish to send a read report?";
$ml_displayed = "The following E-mail has been displayed to ";
$ml_notify = "Read Notification";
$ml_delete_filter1 = "Delete filter";
$ml_html_message_attached = "Original HTML messages are attached";
$ml_no_folders = 'You don\'t have any folders to filter to';
$ml_no_filters = 'You don\'t have any filters.';
$ml_host = 'Host';
$ml_port = 'Port';
$ml_type = 'Type';
$ml_servertype = 'Servertype';
$ml_format = 'Format';
$ml_loose_changes = 'Changes will be lost. Are you sure?';
$ml_markread = "Mark as read";
$ml_markunread = "Mark as unread";
$ml_root_mailbox = "the root mailbox";
$ml_inside = "in";
$ml_no_mailbox = "This is not a mailbox. This folder cannot contain messages.";
$ml_signature = 'Signature';
$ml_root = 'Root mailbox';
$ml_disable_accounts = 'Disable account management';
$ml_trash = 'Trash';
$ml_disable = 'Disable';

$ml_empty_mailbox = 'Empty folder';
$ml_you_have = 'You have';
$ml_new_mail_single = 'new e-mail message.';
$ml_new_mail_multiple = 'new e-mail messages.';
$ml_auto_check = 'Automatically check this account for new mail.';
//1.98
$ml_no_contacts_in_mailing_group = 'There are no contacts in the mailing group you selected. Please add contacts to the group first.';
$ml_attention= 'Attention';

//2.02
$ml_autocheck_disabled = ' could not be reached. The automatic check for new mail is disabled for this account.';
$ml_mark = 'Mark messages...';
$ml_flag = 'flagged';
$ml_clearflag = 'unflagged';
$ml_expand_all = 'Expand all folders';
$ml_collapse_all = 'Collapse all folders';

//2.05
$ml_search = 'Search';
$ml_answered = 'Answered';
$ml_doesnt_matter = 'Doesn\'t matter';
$ml_body = 'Body';
$ml_before = 'Older then';
$ml_since = 'Newer then';
$ml_select_one_criteria = 'Please select or enter at least one search criteria.';

//2.06
$ml_appointment = 'This message contains an appointment. Do you want to view this appointment in the calendar?';
$ml_mails_were_sent = 'mail messages sent';
$ml_novalidate_cert = 'Don\'t validate certificate';
$ml_appointment_vcf = 'This message contains a contact address. Do you want to view this address in the addressbook?';


//2.08 
$ml_add_senders = 'Ask if you want to add unknown senders to your default addressbook';
$ml_text_format = 'Plain text';
$ml_html_format_is = 'HTML (If browser supports HTML editing)';
$ml_html_format = 'HTML formatted';
$ml_always_ask_notification = 'Always ask reciever for a read notification by default';
$ml_ask_add_sender = 'The sender address %s belonging to %s is not in your addressbook. Would you like to add this person to your addressbook now?';

$ml_edit_filter = 'Edit filter';
$ml_choose_action = 'Please choose an action:';
$ml_search_criteria = 'Search criteria';
$ml_sender = 'Sender';
$ml_reciever = 'Reciever';
$ml_cc_reciever = 'CC-Reciever';

//2.10
$ml_empty_trash = 'Empty&nbsp;trashcan';
//2.11
$ml_drafts = 'Drafts';
$ml_save_draft_error = 'Failed saving the draft. Please check your account settings.';
$ml_search_sender = 'Search for other e-mails of this sender';

$ml_no_attachments = 'No files attached';
$ml_search_active = 'The search function is active. Not all messages of this folder are shown. Click here to end the search';
$ml_local_files = 'Local files';
$ml_please_close_attachments = 'Please close attachments window first and make sure the file transfers are complete';

$ml_please_wait = 'Please wait...';
$ml_max_attachment_size = 'Maximum size of attachment';
$ml_select = 'Select file';
$ml_multiple_files = 'Multiple files';

//2.12
$ml_reenter_password = 'For security reasons you will have to enter your password again for this e-mail account.';

$ml_attachments_added = 'files attached';
$ml_attachment_added = 'file attached';

//2.13
$ml_download_zipped_attachments = 'Zip archive of all attachments';
$ml_fullscreen = 'View&nbsp;fullscreen';
$ml_nofullscreen = 'Close&nbsp;fullscreen';
$ml_confirm_empty_trash = 'Are you sure you want to empty your trashcan?';
$ml_seen = 'Read';
$ml_charset = 'Character encoding';

//2.14
$ml_no_reciever_add = "Don' t add";
$ml_add_recievers = "Add unknown recievers to";//changed string from 2.06

$ml_automatic_reply = 'Activate automatic response';

$ml_set_default = 'Set default';

$ml_used_of = 'used of';

$ml_folder_not_available = 'you can\'t create extra folders with POP-3 accounts';

//2.15
$ml_mark_as_read='Mark filtered messages as read';

$ml_get_message_error_title = 'Error while fetching message';
$ml_get_message_error_text = 'Couldn\'t get the message from the server. Maybe it\'s deleted by another client. Please click at \'Refresh\'.';
$ml_spamtag = 'Spam tag';
$ml_confirm_no_subject = 'You didn\'t enter a subject for this e-mail. Are you sure you want to send this e-mail without a subject?';
$ml_show_preview = 'Show preview when I select a message';

$ml_show_headers = 'Show message headers';
$ml_confirm_empty_mailbox = 'Are you sure you want to empty the folder \'%s\'?';

//2.16
$em_source = 'Message source';
$ml_messages_linked = 'The selected messages are linked';
$ml_handle_originals='What do you want to do with the original messages?';
$ml_keep='Keep';
$ml_examine_headers='Show paperclip when a message has attachments and the message priority in messages listing. Warning! This slows down the viewing of the message list.';
$ml_show_attachments='Show attachments and priorities (slower)';
$ml_unknown_reciepent='The recipient is unknown. Please complete the recipient\'s profile.';

$ml_show_new_mail='Always show new messages in the top menubar';
$ml_beep='Beep on new e-mail';

//2.17
$ml_mail_to='A composer window should have been opened for you because you clicked on the e-mail address %s.';
$ml_windows_mail = 'If you want to use Group-Office as your default e-mail client in Microsoft Windows then you need to load a register file. After loading the register file you can select Group-Office as your default e-mail client in Windows at Control Panel -> Internet options -> Programs';
$ml_download_reg='Download register file';

$ml_help_url='http://docs.group-office.com/index.php?folder_id=57&file_id=0';

$ml_attachment_message = 'Message';
$ml_open_popup='Display popup on new e-mail';

$ml_vacation='Automatic reply';

//2.18
$ml_forward_local_copy='Keep the message in this account too';
