<?php 
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

$ml_from = "Lähettäjä";
$ml_to = "Vastaanottoaja";
$ml_send = "Lähetä";
$ml_attach = "Liitä";
$ml_attachments = "Liitteet";
$ml_attachment = "Liite";
$ml_high = "Korkea";
$ml_normal = "Normaali";
$ml_low = "Matala";
$ml_priority = "Prioritteeti";
$ml_subject = "Aihe";
$ml_filename = "Tiedostonimi";
$ml_total_size = "Koko yhteensä";
$ml_size = "Koko";
$ml_to_empty = "Et antanut vastaanottajaa.";
$ml_print = "Tulosta";
$fbNoSelect = "Et valinnut viestiä";
$ml_inbox = 'Sisään laatikko';
$ml_properties = 'Ominaisuudet';
$ml_add_account = "Lisää tili";
$em_new_folder = "Uusi kansio";
$ml_your_accounts = "Sinun sähköposti tilit";
$ml_no_accounts = "Sinulla ei ole sähköpostitilejä määriteltynä.";
$ml_original_follows = "----- Alkuperäinen viesti -----";
$ml_welcome = "Teretuloa Group-Office sähköpostiin";
$ml_text = "Paina Tilit sähköposti tilin lisäämiseksi.";
$ml_accounts = "Tilit";
$ml_compose = "Kirjoita";
$ml_delete = "Poista";
$ml_refresh = "Päivitä";
$ml_reply = "Vastaa";
$ml_forward = "Välitä";
$ml_reply_all = "Vastaa kaikille";
$ml_delete_message = "Oletko varma että haluat poistaa valittu viesti lopullisesti?";
$ml_no_subject = "Ei aihetta";
$ml_no_reciepent = "Vataanottaja tuntematon";
$ml_online_files = "Online tiedostot";
$ml_send_error = "Sähköpostin lähetys epäonnistui.";
$ml_attach_forget = "Valitsit tiedoston mutta et liittänyt sitä.";
$ml_messages = "viesti(t)";
$ml_message = 'tämä viesto';
$ml_messages2 = 'viestit';
$ml_new = "uusi";
$ml_delete_mailbox = "Oletko varma että haluat poistaa valitut viestit lopullisesti?";
$contact_profile = "Yhteystieto profiili";
$ml_add_contact = "Lisää lähettäjä yhteystietoihin";
$strHost = "Isäntä";
$strDefault = "Oletus";
$ml_edit_account = "Muokka tiliä";
$ml_new_account = "Uusi tili";
$ml_no_messages = "Tässä kansiossa ei ole viestejä.";
$ml_file_too_big = "Tiedosto jonka yritit liittää on liian suuri, liitetiedoston suurin koko on: ";
$fbNoRightToOverwrite = "Tiedosto on jo olemassa ja sinulla ei ole oikeutta kirjoittaa sen yli.";
$ml_save_attachment = "Talleta liite Group-Officeen.";
$ml_folders = "Kansiot";
$ml_select_folder = "Valitse kansio mihin Group-Office voi tallettaa lähetyt sähköpostit tai syötä nimi kansion luomiseksi";
$ml_connect_failed = "Yhteydenotto sähköpostipalvelimeen epäonnistui:";
$ml_at_port = "portissa";
$ml_solve_error = 'Paina \'Tilit\' korjataksesi tili asetuskset tai paina \'Päivitä\' oletus tilin avaamiseksi.';
$ml_sent_items = "Lähetetyt kohteet";
$ml_spam = "Roskaposti";
$ml_use = "Käytä";
$ml_synchronise = "synkronoi";
$ml_move_mail = "Siirrä valitut viestit kansioon...";
$ml_filters = "Suodattimet";
$ml_move_to = "siirrä sitten viesti kansioon:";
$ml_email_is = "Jos lähettäjän sähköpostiosoite sisältää:";
$ml_to_is = "Jos vastaanottaja kenttä sisältää:";
$ml_cc_is = "Jos kopio (cc) kenttä sisältää:";
$ml_subject_is = "Jos aihe sisältää:";
$ml_new_filter = "Uusi suodatin:";
$ml_field = "Kenttä";
$ml_contains = "Sisältää";
$ml_folder = "Kansio";
$ml_no_folders = "Sinulla ei ole kansioita joten sinä et voi luoda suodattimia.";
$ml_unwanted = "Paina tästä jos et toivo sähköpostia tältä lähettäjältä";
$fbFolderSize = "Kansion koko";
$ml_move_up = "Kasvata prioriteettia";
$ml_delete_filter = "Oletko varma että haluat poistaa tämän suodattimen?";
$ml_high_priority = "Tällä viestillä on korkea prioriteetti!";
$ml_low_priority = "Tällä viestillä on matala prioriteetti.";
$ml_block = "Estä lähetttäjä";
$ml_sent_items_fail = "Viesti lähetettiin mutta tapahtui virhe kun sitä luotiin lähetettyjen kansioon. Tarkista IMAP tilisi.";
$fbProperties = "Ominaisuudet";
$ml_notification = "Pyydä lähettäjää lähettämään lukukuittauksen";
$ml_ask_notify = "Viestin lähettäjä pyytää luku kuittausta. Haluatko lähettää lukukuittauksen?";
$ml_displayed = "seuraava sähköposti on näytetty ";
$ml_notify = "Luku kuittaus";
$ml_delete_filter1 = "Poista suodatin";
$ml_html_message_attached = "Alkuperäiset HTML viestit liitteenä";
$ml_no_folders = 'Sinulla ei ole suodatuksen kohde';
$ml_no_filters = 'Sinulla ei ole suoattimia.';
$ml_host = 'Isäntä';
$ml_port = 'Portti';
$ml_type = 'Typpi';
$ml_servertype = 'Palvelintyyppi';
$ml_format = 'Formaatti';
$ml_loose_changes = 'Muutoksia ei talleteta. Oletko varma?';
$ml_markread = "Merkitse&nbsp;as&nbsp;luetuksi";
$ml_markunread = "Meritse&nbsp;as&nbsp;lukemattoimaksi";
$ml_root_mailbox = "perussähköpostilaatikko";
$ml_inside = "on";
$ml_no_mailbox = "Tämä ei ole sähköpostilaatikko. Tämä kansio ei voi sisältää viestejä.";
$ml_signature = 'Allekirjoitus';
$ml_root = 'Perussähköpostilaatiiko';
$ml_disable_accounts = 'Poista tilin hallinta käytöstä';
$ml_trash = 'Roska';
$ml_disable = 'Poista käytöstä';
$ml_confirm_empty_mailbox = 'Haluatko varmasti tyhjentää tämän kansion?';
$ml_empty_mailbox = 'Tyhjennä&nbsp;kansio';
$ml_you_have = 'Sinulle on';
$ml_new_mail_single = 'uusi sähköposti.';
$ml_new_mail_multiple = 'uusia sähköposteja.';
$ml_auto_check = 'Tarkista automaattiset tämä tilin uudet sähköpostit.';
//1.98
$ml_no_contacts_in_mailing_group = 'Valitsemassasi sähköposti ryhmässä ei ole yhteystietoja. Lisää yhteystiedot ryhmään ensin.';
$ml_attention= 'Huomio';

//2.02
$ml_autocheck_disabled = ' ei ollut tavoitettavissa. Tämän tilin uusien sähköposti viestien haku on poistettu käytöstä.';
$ml_mark = 'Merkitse viestit...';
$ml_flag = 'merkitty';
$ml_clearflag = 'ei merkitty';
$ml_expand_all = 'Levitä kaikki kansiot';
$ml_collapse_all = 'supista kaikki kansiot';

//2.05
$ml_search = 'Etsi';
$ml_answered = 'Vastattu';
$ml_doesnt_matter = 'Ei ole mitää väliä';
$ml_body = 'Runko';
$ml_before = 'Vanhempi kuin';
$ml_since = 'Uudempi kuin';
$ml_select_one_criteria = 'Valitse tai syötä vähintää yksi haku ehto.';

//2.06
$ml_appointment = 'Tämä viesti sisältää kokouksen. Haluatko nähdä kokouksen kalenterissa?';
$ml_mails_were_sent = 'Sähköposti viestit lähetetty';
$ml_novalidate_cert = 'Älä hyväksy sertifikaattia';
$ml_appointment_vcf = 'Tämä viesti sisältää yhteytiedot. Haluatko nähdä yhteystiedot osoitekirjassa?';


//2.08 
$ml_add_senders = 'Kysy jos sinä haluat lisätä tuntemattomat lähettäjät oletus osoitekirjaan';
$ml_text_format = 'Teksit muodossa';
$ml_html_format_is = 'HTML (Jos selain tukee HTML muokkausta)';
$ml_html_format = 'HTML muodossa';
$ml_always_ask_notification = 'Pyydä oletuksena aina vastaanottajalta lukukuittausta';
$ml_ask_add_sender = 'Osoite %s joka kuuluu lähettäjälle %s ei ole osoitekirjassa. Haluatko lisätä tämän henkilön osoitekirjaan nytt?';

$ml_edit_filter = 'Muokka suodatinta';
$ml_choose_action = 'Valitse toimenpide:';
$ml_search_criteria = 'Haku ehto';
$ml_sender = 'Lähettäjä';
$ml_reciever = 'Vastaanottaja';
$ml_cc_reciever = 'CC-vastaanottaja';

//2.10
$ml_empty_trash = 'Tyhjennäy&nbsp;roskakori';
//2.11
$ml_drafts = 'Keskeneräiset';
$ml_save_draft_error = 'Keskeneräisen viestin tallennus epäonnistui. Tarkista tili asetukset.';
$ml_search_sender = 'Etsi muita tämän lähettäjän sähköposteja';

$ml_no_attachments = 'Liite tiedostoa ei ole';
$ml_search_active = 'Hakutoiminto aktiivinen. Tämän kansion kaikkia viestejä ei näytetä. Paina tästä hakun keskeyttämiseksi';
$ml_local_files = 'Paikalliset tiedostot';
$ml_please_close_attachments = 'Sulje liite ikkuna ensin ja varmista että tiedosto siirrot ovat valmiit';

$ml_please_wait = 'Odota...';
$ml_max_attachment_size = 'Liitteen suurin koko';
$ml_select = 'Valitse tiedosto';
$ml_multiple_files = 'Useampi tiedosto';

//2.12
$ml_reenter_password = 'Turvallisuus syistä sinun pitää syöttää salasanasi uudestaan tälle sähköposti tilille.';

$ml_attachments_added = 'tiedostoja liitetty';
$ml_attachment_added = 'tiedosto liitetty';

//2.13
$ml_download_zipped_attachments = 'Kaikkien liitteiden Zip arkisto';
$ml_fullscreen = 'Näytä&nbsp;koko näyttö';
$ml_nofullscreen = 'Sulje&nbsp;koko näyttö';

$ml_confirm_empty_trash = 'Haluatko varmasti tyhjentää roskakorin?';

$ml_seen = 'Lue';


$ml_charset = 'Merkki koodaus';

//2.14
$ml_no_reciever_add = "Älä lisää";
$ml_add_recievers = "Lisää tuntemattomat vastaanottajat";//changed string from 2.06

$ml_automatic_reply = 'Aktivoi automaattien vastaus';

$ml_set_default = 'Aseta oletukseksi';

$ml_used_of = 'käyttämä';

$ml_folder_not_available = 'et voi luoda ylimääräisiä kansioita POP-3 tileille';

//2.15
$ml_mark_as_read='Merkitse suodatetut tiedostot luetuiksi';
