<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('email'));

$ml_from = "送信元";
$ml_to = "送信先";
$ml_send = "送信";
$ml_attach = "添付する";
$ml_attachments = "添付";
$ml_attachment = "添付";
$ml_high = "高";
$ml_normal = "通常";
$ml_low = "低";
$ml_priority = "重要度";
$ml_subject = "件名";
$ml_filename = "ファイル名";
$ml_total_size = "合計サイズ";
$ml_size = "サイズ";
$ml_to_empty = "宛先が指定されていません。";
$ml_print = "印刷";
$fbNoSelect = "メッセージを選択していません。";
$ml_inbox = 'Inbox';
$ml_properties = 'プロパティ';
$ml_add_account = "アカウントを追加";
$em_new_folder = "新規フォルダ";
$ml_your_accounts = "あなたのE-mail アカウント";
$ml_no_accounts = "E-mail アカウントが設定されていません。";
$ml_original_follows = "----- Original Message -----";
$ml_welcome = "Group-Office E-mailへようこそ";
$ml_text = "メールアカウントを追加してください。";
$ml_accounts = "アカウント";
$ml_compose = "作成";
$ml_delete = "削除";
$ml_refresh = "更新";
$ml_reply = "返信";
$ml_forward = "転送";
$ml_reply_all = "全員へ返信";
$ml_delete_message = "完全にメッセージを削除してよろしいですか？";
$ml_no_subject = "件名なし";
$ml_no_reciepent = "宛先非公開";
$ml_online_files = "オンラインファイル";
$ml_send_error = "メールの送信に失敗しました。";
$ml_attach_forget = "選択したファイルが添付されていません。";
$ml_messages = "メッセージ";
$ml_message = 'このメッセージ';
$ml_messages2 = 'メッセージ';
$ml_new = "新規";
$ml_delete_mailbox = "選択したメッセージを完全に消去しますか？";
$contact_profile = "連絡先プロファイル";
$ml_add_contact = "送信者を連絡先に追加";
$strHost = "ホスト";
$strDefault = "デフォルト";
$ml_edit_account = "アカウント編集";
$ml_new_account = "新規アカウント";
$ml_no_messages = "このフォルダにメッセージはありません";
$ml_file_too_big = "添付しようとしたファイルは容量が大きすぎます。 添付ファイルの最大サイズ: ";
$fbNoRightToOverwrite = "ファイルは既に存在します。上書きは許可されていません。";
$ml_save_attachment = "Group-Officeに添付ファイルを保存";
$ml_folders = "フォルダ";
$ml_select_folder = "Group-Officeが送信済みメールを保存できるフォルダを選択するか、作成するフォルダ名を入力してください。";
$ml_connect_failed = "メールサーバ接続エラー:";
$ml_at_port = "ポート";
$ml_solve_error = 'アカウント設定を決定するのに「アカウント」をクリックするか、デフォルトアカウントを開くのに「更新」をクリックしてください';
$ml_sent_items = "送信アイテム";
$ml_spam = "スパム";
$ml_use = "使用";
$ml_synchronise = "同期";
$ml_move_mail = "選択したメッセージをフォルダに移動";
$ml_filters = "フィルタ";
$ml_move_to = "メッセージを移動するフォルダ:";
$ml_email_is = "送信者アドレスが次を含む:";
$ml_to_is = "受信者に次の文字列を含む:";
$ml_cc_is = "CCに次の文字列を含む:";
$ml_subject_is = "件名に次の文字列を含む:";
$ml_new_filter = "新規フィルタ:";
$ml_field = "フィールド";
$ml_contains = "Contains";
$ml_folder = "フォルダ";
$ml_no_folders = "フォルダがないためフィルタを作成できません";
$ml_unwanted = "この送信者からのメールを受け取りたくない場合はクリック";
$fbFolderSize = "フォルダサイズ";
$ml_move_up = "優先度を上げる";
$ml_delete_filter = "フィルタを削除してよろしいですか？";
$ml_high_priority = "このメッセージの優先度は高いです";
$ml_low_priority = "このメッセージの優先度は低いです";
$ml_block = "送信者ブロック";
$ml_sent_items_fail = "メッセージは送信されましたが、送信アイテムフォルダにメッセージを保存する際にエラーが発生しました。あなたのIMAPアカウントを確認してください。";
$fbProperties = "プロパティ";
$ml_notification = "受信者に受信確認を要求する";
$ml_ask_notify = "このメッセージの送信者が受信確認を要求しています。既読になったレポートを送信しますか？";
$ml_displayed = "以下のE-mailの表示先 ";
$ml_notify = "注意文をお読みください";
$ml_delete_filter1 = "フィルタ削除";
$ml_html_message_attached = "オリジナルHTMLメッセージは添付されています";
$ml_no_folders = 'フィルタするフォルダはありません';
$ml_no_filters = 'フィルタはありません';
$ml_host = 'ホスト';
$ml_port = 'ポート';
$ml_type = 'タイプ';
$ml_servertype = 'サーバタイプ';
$ml_format = 'フォーマット';
$ml_loose_changes = '変更は放棄されます。よろしいですか？';
$ml_markread = "既読にする";
$ml_markunread = "未読にする";
$ml_root_mailbox = "メールボックスのルート";
$ml_inside = "in";
$ml_no_mailbox = "メールボックスではありません。このフォルダにメッセージは含まれません";
$ml_signature = '署名';
$ml_root = 'メールボックスのルート';
$ml_disable_accounts = 'アカウント管理を無効にする';
$ml_trash = 'ゴミ箱';
$ml_disable = '無効';
$ml_confirm_empty_mailbox = 'このフォルダを空にしてよろしいですか？';
$ml_empty_mailbox = '空のフォルダ';
$ml_you_have = '';
$ml_new_mail_single = '新規メッセージ';
$ml_new_mail_multiple = '新規メッセージ';
$ml_auto_check = 'このアカウントの新規メールを自動的にチェックする';
//1.98
$ml_no_contacts_in_mailing_group = 'あなたの選択したメーリンググループに連絡先は存在しません。初めに連絡先をグループに追加してください。';
$ml_attention= '注意文';

//2.02
$ml_autocheck_disabled = 'このアカウントの新規メール自動チェックは無効です';
$ml_mark = 'マーク';
$ml_flag = 'フラグあり';
$ml_clearflag = 'フラグなし';
$ml_expand_all = 'すべてのフォルダを展開';
$ml_collapse_all = 'すべてのフォルダを閉じる';

//2.05
$ml_search = '検索';
$ml_answered = '回答';
$ml_doesnt_matter = '無視';
$ml_body = '本文';
$ml_before = '次より古い';
$ml_since = '次より新しい';
$ml_select_one_criteria = '検索基準を一つ選ぶか入力してください';

//2.06
$ml_appointment = 'このメッセージはアポイントメントを含んでいます。カレンダーのアポイントメントを表示しますか？';
$ml_mails_were_sent = '送信済みメッセージ';
$ml_novalidate_cert = '証明書を有効にしない';
$ml_appointment_vcf = 'このメッセージは連絡先アドレスに含まれています。アドレス帳内のこのアドレスを表示しますか？';


//2.08 
$ml_add_senders = '新しい送信者をデフォルトのアドレス帳に追加する場合確認する';
$ml_text_format = 'プレーンテキスト';
$ml_html_format_is = 'HTML (ブラウザがHTML編集をサポートしている場合)';
$ml_html_format = 'HTMLフォーマット';
$ml_always_ask_notification = '受信者に受信確認を常に確認する';
$ml_ask_add_sender = '送信アドレス %s （ %s ）はアドレス帳にありません。 アドレス帳に追加しますか？';

$ml_edit_filter = 'フィルタ編集';
$ml_choose_action = 'アクションを選択:';
$ml_search_criteria = '検索基準';
$ml_sender = '送信者';
$ml_reciever = '受信者';
$ml_cc_reciever = 'CCの受信者';

//2.10
$ml_empty_trash = 'ゴミ箱を空にする';
//2.11
$ml_drafts = '下書き';
$ml_save_draft_error = '下書きを保存できませんでした。アカウント設定を見直してください。';
$ml_search_sender = 'この送信者の違うメールを検索する';

$ml_no_attachments = '添付ファイルなし';
$ml_search_active = '検索機能は有効です。 メッセージのすべてが表示されてはいません。 ここをクリックして検索の終点を決定してください。';
$ml_local_files = 'ローカルファイル';
$ml_please_close_attachments = '添付ファイルウィンドウを閉じてください。ファイル転送が完了するのを確認してください。';

$ml_please_wait = 'しばらくお待ちください。...';
$ml_max_attachment_size = '添付最大サイズ';
$ml_select = 'ファイル選択';
$ml_multiple_files = '複数ファイル';

//2.12
$ml_reenter_password = 'セキュリティ上の理由のためこのE-mailアカウントのパスワードをもう一度入力してください。';

$ml_attachments_added = 'ファイル添付';
$ml_attachment_added = 'ファイル添付';

//2.13
$ml_download_zipped_attachments = '添付のZIP圧縮ファイル';
$ml_fullscreen = 'フルスクリーン表示';
$ml_nofullscreen = 'フルスクリーン解除';

$ml_confirm_empty_trash = '本当にゴミ箱を空にしますか?';

$ml_seen = '読む';


$ml_charset = '文字エンコード';

//2.14
$ml_no_reciever_add = "追加しない";
$ml_add_recievers = "新しい受信者をデフォルトのアドレス帳に追加する";//changed string from 2.06

$ml_automatic_reply = '自動応答を有効にする';

$ml_set_default = 'デフォルトにする';

$ml_used_of = 'used of';

$ml_folder_not_available = 'POP-3アカウントで追加フォルダを作成できません';

//2.15
$ml_mark_as_read='フィルタされたメッセージを既読にする';

$ml_get_message_error_title = 'メッセージ取得中にエラーが発生';
$ml_get_message_error_text = 'サーバからメッセージを取得できませんでした。他のアクセスで削除されたようです。更新ボタンを押してください。';
