<?php
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "Fra";
$ml_to = "Til";
$ml_send = "Send";
$ml_attach = "Vedlegg";
$ml_attachments = "Vedlagte filer";
$ml_attachment = "Vedlagt fil";
$ml_high = "Høy";
$ml_normal = "Normal";
$ml_low = "Lav";
$ml_priority = "Prioritet";
$ml_subject = "Emne";
$ml_filename = "Filnavn";
$ml_total_size = "Total størrelse";
$ml_size = "Størrelse";
$ml_to_empty = "Du må sette inn en mottaker.";
$ml_print = "Skriv ut";
$fbNoSelect = "Du må velge en beskjed";

$ml_inbox = 'innboks';
$ml_properties = 'egenskaper';
$ml_add_account = "Legg til en konto";
$em_new_folder = "Ny mappe";
$ml_your_accounts = "Dine e-post kontoer";
$ml_no_accounts = "Du har ikke konfigurert noen e-postkonto.";
$ml_original_follows = "----- Orginal beskjed -----";
$ml_welcome = "Velkommen til Group-Office mail";
$ml_text = "Klikk på konto for å legge til en e-postkonto.";
$ml_accounts = "Konto";
$ml_compose = "Skriv ny";
$ml_delete = "Slett";
$ml_refresh = "Oppdater";
$ml_reply = "Besvar";
$ml_forward = "Videresend";
$ml_reply_all = "Besvar alle";
$ml_delete_message = "Er du sikker på du vil slette beskjeden permanent?";
$ml_no_subject = "Intet emne";
$ml_no_reciepent = "Ukjent mottaker";
$ml_online_files = "Online filer";
$ml_send_error = "Kunne ikke sende besked.";

$ml_attach_forget = "Du har valgt en fil, men den er ikke lagt ved.";
$ml_messages = "beskjed(er)";
$ml_message = 'denne besked';
$ml_messages2 = 'beskjeder';
$ml_new = "nye";
$ml_delete_mailbox = "Er du sikker på du vil slette de markerte beskedene permanent?";

$contact_profile = "Kontakt profil";
$ml_add_contact = "Tilføy avsender til kontakter";
$strHost = "Server";
$strDefault = "Standard";
$ml_edit_account = "Endre konto";
$ml_new_account = "Ny konto";
$ml_no_messages = "Det er ingen beskjeder i denne mappen.";
$ml_file_too_big = "Filen du forsøkte å legge til er for stor, størrelsen for vedlagte filer er satt til: ";
$fbNoRightToOverwrite = "Filen eksisterer allerede, og du har ikke rettigheter til å overskrive den.";
$ml_save_attachment = "Gjem vedlagte fil i Group-Office.";
$ml_folders = "Mapper";

$ml_select_folder = "Velg den folder hvor Group-Office skal gjemme sendt post eller skriv et navn for at opprette en folder";
$ml_connect_failed = "Kunne ikke kontakte mailserveren:";
$ml_at_port = "på port";
$ml_solve_error = 'Klikk på  \'Konto\' for å endre din konto innstillinger eller klikk på \'Oppdater\' for å åpne din standard konto.';
$ml_sent_items = "Sendt post";
$ml_spam = "Spam";
$ml_use = "Bruk";
$ml_synchronise = "Synkroniser";
$ml_move_mail = "Flytt valgte beskeder til mappen...";
$ml_filters = "Filtrer";
$ml_move_to = "og flytt beskjeden til mappen:";
$ml_email_is = "Hvis avsenders e-postadresse inneholder:";
$ml_to_is = "Hvis mottakerfeltet inneholder:";
$ml_cc_is = "Hvis Cc: feltet inneholder:";

$ml_subject_is = "Hvis emnet inneholder:";
$ml_new_filter = "Nytt filter:";
$ml_field = "Felt";
$ml_contains = "Inneholder";
$ml_folder = "Mappe";
$ml_no_folders = "Du har ingen mapper, så du kan ikke opprette et filter.";
$ml_unwanted = "Klik her hvis beskjeden fra avsenderen er uønsket";
$fbFolderSize = "Størrelse på mappen";
$ml_move_up = "Høy prioritet";
$ml_delete_filter = "Er du sikker på du vil slette dette filter?";
$ml_high_priority = "Denne besked har høy prioritet!";
$ml_low_priority = "Denne besked har lav prioritet.";
$ml_block = "Blokker avsender";
$ml_sent_items_fail = "Beskjeden er sent, men det oppstod en feil da beskjeden skulle opprettes i Sendt Post mappen. Kontroller din IMAP konto.";
$fbProperties = "Egenskaper";
$ml_notification = "Anmod en bekreftelse når beskeden er lest";
$ml_ask_notify = "Afsender har anmodet om bekræftelse for lest e-post. Ønsker du å sende en bekreftelse?";
$ml_displayed = "Følgende besked er blitt vist hos ";
$ml_notify = "Beskjed ved lesning";
$ml_delete_filter1 = "Slett filter";
$ml_html_message_attached = "Orginal HTML beskjed er vedlagt";
$ml_add_recievers = "Tilføy ukjente mottagere til adresseboken";
$ml_no_folders = 'Du har ingen mapper å filtrere';
$ml_no_filters = 'Du har ingen filtre.';

$ml_host = 'Server';
$ml_port = 'Port';
$ml_type = 'Type';

$ml_loose_changes = 'Endringer vil gå tapt. Er du sikker?';
$ml_format = 'Format';

$ml_servertype = 'Servertype';
$ml_markread = "Marker som lest";
$ml_markunread = "Marker som ulest";
$ml_root_mailbox = "rot postkassen";
$ml_inside = "inne i";


$ml_no_mailbox = "Ikke en epost. Denne folderen er ikke istand til å holde noen meldinger.";

$ml_signature = 'Signatur';
$ml_root = 'Hoved e-postboks';
$ml_disable_accounts = 'Konto vedlikehold';
$ml_trash = 'Slett';
