<?php
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

//Email
$ml_from = "De";
$ml_to = "Para";
$ml_send = "Enviar";
$ml_attach = "Anexar";
$ml_attachments = "Anexos";
$ml_attachment = "Anexo";
$ml_high = "Alta";
$ml_normal = "Normal";
$ml_low = "Baixa";
$ml_priority = "Prioridade";
$ml_subject = "Assunto";
$ml_filename = "Nome do ficheiro";
$ml_total_size = "Tamanho total";
$ml_size = "Tamanho";
$ml_to_empty = "Destinat&aacute;rio n&atilde;o indicado";
$ml_print = "Imprimir";
$fbNoSelect = "N&atilde;o foi seleccionada uma mensagem";

$ml_inbox = 'Caixa de Entrada';
$ml_properties = 'Propriedades';
$ml_add_account = "Adicionar uma conta";
$em_new_folder = "Adicionar uma Pasta";
$ml_your_accounts = "As suas contas";
$ml_no_accounts = "N&atilde;o h&aacute; contas de email configuradas.";
$ml_original_follows = "----- Mensagem Original -----";
$ml_welcome = "Bem-vindo ao Email de Group-Office";
$ml_text = "Clique em contas para adicionar uma conta de email.";
$ml_accounts = "Contas";
$ml_compose = "Escrever uma mensagem";
$ml_delete = "Apagar";
$ml_refresh = "Refrescar";
$ml_reply = "Responder";
$ml_forward = "Reencaminhar";
$ml_reply_all = "Responder a todos";
$ml_delete_message = "Confirma apagar permanentemente a mensagem?";
$ml_no_subject = "N&atilde;o foi indicado o assunto";
$ml_no_reciepent = "Destinat&aacute;rios n&atilde;o divulgados";
$ml_online_files = "Ficheiros online";
$ml_send_error = "Falha ao enviar o correio.";

$ml_attach_forget = "O ficheiro seleccionado n&atilde;o foi anexado.";
$ml_messages = "mensagens";
$ml_message = 'esta mensagem';
$ml_messages2 = 'mensagens';
$ml_new = "nova";
$ml_delete_mailbox = "Confirma apagar permanentemente as mensagens seleccionadas?";

$contact_profile = "Perfil do contacto";
$ml_add_contact = "Adicionar o remetente aos contactos";
$strHost = "Servidor";
$strDefault = "Valor por defeito";
$ml_edit_account = "Editar conta";
$ml_new_account = "Nova conta";
$ml_no_messages = "N&atilde;o h&aacute; mensagens nesta pasta.";
$ml_file_too_big = "O ficheiro que deseja anexar &eacute; demasiado grande. O tamanho m&aacute;ximo &eacute;: ";
$fbNoRightToOverwrite = "O ficheiro j&aacute; existe e n&atilde;o pode substitu&iacute;-lo.";
$ml_save_attachment = "Guardar anexo em Group-Office.";
$ml_folders = "Pastas";

$ml_select_folder = "Seleccione a pasta onde Group-Office pode guardar o correio enviado ou crie uma pasta indicando um nome";
$ml_connect_failed = "Falhou a liga&ccedil;&atilde;o ao servidor de correio:";
$ml_at_port = "na porta";
$ml_solve_error = 'Clique em \'Contas\' para corrigir a configura&ccedil;&atilde;o da conta ou clique em \'Refrescar\' para abrir a conta por defeito.';
$ml_sent_items = "Itens enviados";
$ml_spam = "Spam";
$ml_use = "Usar";
$ml_synchronise = "sincronizar";
$ml_move_mail = "Mover as mensagens seleccionadas para a pasta...";
$ml_filters = "Filtros";
$ml_move_to = "depois mover a mensagem para a pasta:";
$ml_email_is = "Se o endere&ccedil;o de email do remetente cont&eacute;m:";
$ml_to_is = "Se o campo Para: cont&eacute;m:";
$ml_cc_is = "Se o campo CC: cont&eacute;m:";

$ml_subject_is = "Se o assunto cont&eacute;m:";
$ml_new_filter = "Novo Filtro:";
$ml_field = "Campo";
$ml_contains = "Cont&eacute;m";
$ml_folder = "Pasta";
$ml_no_folders = "Como n&atilde;o h&aacute; pastas, n&atilde;o pode criar filtros.";
$ml_unwanted = "Clique aqui se o email deste remetente for indesej&aacute;vel";
$fbFolderSize = "Tamanho da pasta";
$ml_move_up = "Aumentar a prioridade";
$ml_delete_filter = "Confirma apagar este filtro?";
$ml_high_priority = "Esta mensagem tem alta prioridade!";
$ml_low_priority = "Esta mensagem tem baixa prioridade.";
$ml_block = "Bloquear remetente";
$ml_sent_items_fail = "A mensagem foi enviada mas houve um erro ao criar esta mensagem na pasta de correio enviado.  Por favor, verifique a sua conta IMAP.";
$fbProperties = "Propriedades";
$ml_notification = "Pedir recibo de leitura";
$ml_ask_notify = "O remetente desta mensagem pediu um recibo de leitura. Deseja notificar o remetente?";
$ml_displayed = "O seguinte email foi visto por ";
$ml_notify = "Notifica&ccedil;&atilde;o de leitura";
$ml_delete_filter1 = "Apagar Filtro";
$ml_html_message_attached = "Est&atilde;o anexadas mensagens do tipo HTML";
$ml_add_recievers = "Adicionar destinat&aacute;rios desconhecidos a";
$ml_no_folders = 'Como n&atilde;o tem pastas, n&atilde;o pode usar filtros';
$ml_no_filters = 'N&atilde;o existem filtros.';

$ml_host = 'Servidor';
$ml_port = 'Porta';
$ml_type = 'Tipo';
$ml_servertype = 'Tipo de servidor';
$ml_format = 'Formato';
$ml_loose_changes = 'As altera&ccedil;ões ser&atilde;o perdidas. Tem a certeza?';

$ml_markread = "Marcar como lido";
$ml_markunread = "Marcar como não lido";
$ml_root_mailbox = "raiz da caixa de correio";
$ml_inside = "em";

//translation required
$ml_no_mailbox = "Isto n&atilde;o &eacute; uma caixa de correio. Esta pasta n&atilde;o pode ter mensagens.";
$ml_signature = 'Assinatura';
$ml_root = 'Raiz da caixa de correio';
$ml_disable_accounts = 'Desactivar a gest&atilde;o de contas';
$ml_trash = 'Lixo';
$ml_disable = 'Desactivar';

$ml_empty_mailbox = 'Pasta vazia';
$ml_you_have = 'Tem';
$ml_new_mail_single = 'nova mensagem de email.';
$ml_new_mail_multiple = 'novas mensagens de email.';
$ml_auto_check = 'Verificar automaticamente novas mensagens desta conta.';
//1.98
$ml_no_contacts_in_mailing_group = 'N&atilde;o h&aacute; contactos no grupo da lista de correio que foi seleccionado. Por favor, adicione primeiro contactos ao grupo.';
$ml_attention= 'Aten&ccedil;&atilde;o';

//2.02
$ml_autocheck_disabled = ' n&atilde;o foi encontrada. A verifica&ccedil;&atilde;o autom&aacute;tica de novo correio est&aacute; desactivada nesta conta.';
$ml_mark = 'Marcar mensagens...';
$ml_flag = 'marcadas';
$ml_clearflag = 'desmarcadas';
$ml_expand_all = 'Expandir todas as pastas';
$ml_collapse_all = 'Reduzir todas as pastas';

//2.05
$ml_search = 'Pesquisar';
$ml_answered = 'Respondido';
$ml_doesnt_matter = 'Sem interesse';
$ml_body = 'Corpo';
$ml_before = 'Mais antigo que';
$ml_since = 'Mais recente que';
$ml_select_one_criteria = 'Seleccione ou indique pelo menos um crit&eacute;rio de pesquisa.';

//2.06
$ml_appointment = 'Esta mensagem cont&eacute;m uma nota. Deseja ver esta nota no calend&aacute;rio?';
$ml_mails_were_sent = 'mensagens enviadas';
$ml_novalidate_cert = 'N&atilde;o validar certificado';
$ml_appointment_vcf = 'Esta mensagem cont&eacute;m um endere&ccedil;o de um contacto. Deseja ver este endere&ccedil;o na agenda?';


//2.08 
$ml_add_senders = 'Perguntar se deseja adicionar um remetente desconhecido à agenda';
$ml_text_format = 'Texto';
$ml_html_format_is = 'HTML (se o navegador suportar edi&ccedil;&atilde;o HTML)';
$ml_html_format = 'HTML formatado';
$ml_always_ask_notification = 'Pedir sempre um recibo de leitura por defeito';
$ml_ask_add_sender = 'O endere&ccedil;o do remetente %s pertencente a %s n&atilde;o est&aacute; na agenda. Deseja adicionar agora esta pessoa à agenda?';

$ml_edit_filter = 'Editar filtro';
$ml_choose_action = 'Escolha, por favor, uma ac&ccedil;&atilde;o:';
$ml_search_criteria = 'Crit&eacute;rios de pesquisa';
$ml_sender = 'Remetente';
$ml_reciever = 'Destinat&aacute;rio';
$ml_cc_reciever = 'CC-Destinat&aacute;rio';

//2.10
$ml_empty_trash = 'Esvaziar lixo';
//2.11
$ml_drafts = 'Rascunhos';
$ml_save_draft_error = 'Falha ao gravar o rascunho. Verifique as configura&ccedil;ões da conta.';
$ml_search_sender = 'Pesquisar outros emails deste remetente';

$ml_no_attachments = 'Sem ficheiros anexos';
$ml_search_active = 'A fun&ccedil;&atilde;o de pesquisa est&aacute; activa. Nem todas as mensagens desta pasta est&atilde;o vis&iacute;veis. Clique aqui para terminar a pesquisa';
$ml_local_files = 'Ficheiros locais';
$ml_please_close_attachments = 'Feche primeiro a janela dos anexos e verifique se a transfer&ecirc;ncia de ficheiros foi conclu&iacute;da';

$ml_please_wait = 'Por favor aguarde...';
$ml_max_attachment_size = 'Tamanho m&aacute;ximo do anexo';
$ml_select = 'Seleccione ficheiro';
$ml_multiple_files = 'Múltiplos ficheiros';

//2.12
$ml_reenter_password = 'Por razões de seguran&ccedil;a deve indicar novamente a password desta conta de email.';

$ml_attachments_added = 'ficheiros anexos';
$ml_attachment_added = 'ficheiro anexo';

//2.13
$ml_download_zipped_attachments = 'Criar ficheiros Zip de todos os anexos';
$ml_fullscreen = 'Ver em ecr&atilde; total';
$ml_nofullscreen = 'Fechar ecr&atilde; total';
$ml_confirm_empty_trash = 'Tem a certeza que deseja esvaziar o lixo?';
$ml_seen = 'Ler';
$ml_charset = 'Codifica&ccedil;&atilde;o de caracteres';

//2.14
$ml_no_reciever_add = "N&atilde;o adicionar";
$ml_add_recievers = "Adicionar remetentes desconhecidos a";//changed string from 2.06

$ml_automatic_reply = 'Activar resposta autom&aacute;tica';

$ml_set_default = 'Conta por defeito';

$ml_used_of = 'used of';

$ml_folder_not_available = 'N&atilde;o pode criar pastas extra em contas POP-3, apenas em contas IMAP';

//2.15
$ml_mark_as_read='Marcar mensagens filtradas como lidas';

$ml_get_message_error_title = 'Erro ao trazer a mensagem';
$ml_get_message_error_text = 'Imposs&iacute;vel obter a mensagem do servidor. Talvez a mensagem tenha sido apagada. Por favor, clique em \'Refrescar\'.';
$ml_spamtag = 'Marcar como SPAM';
$ml_confirm_no_subject = 'N&atilde;o indicou um assunto para este email. Deseja enviar sem assunto?';
$ml_show_preview = 'Mostrar pr&eacute;-visualiza&ccedil;&atilde;o ao seleccionar uma mensagem';

$ml_show_headers = 'Mostrar cabe&ccedil;alho da mensagem';
$ml_confirm_empty_mailbox = 'Tem a certeza que deseja esvaziar a pasta \'%s\'?';

//2.16
$em_source = 'C&oacute;digo da Mensagem';
$ml_messages_linked = 'As mensagens seleccionadas est&atilde;o ligadas';
$ml_handle_originals='O que deseja fazer com as mensagens originais?';
$ml_keep='Manter';
$ml_examine_headers='Listar mensagens com &iacute;cones que mostram a exist&ecirc;ncia de anexos ou prioridade. Aviso! Isto torna a listagem lenta.';
$ml_show_attachments='Mostrar anexos e prioridades (mais lento)';
$ml_unknown_reciepent='Destinatário desconhecido. Por favor, complete o perfil do destinatário.';

$ml_show_new_mail='Mostrar sempre novas mensagens na barra do menu';
$ml_beep='Aviso sonoro ao chegar um email';

//2.17
$ml_mail_to='Deve ter sido aberta uma janela para compor uma mensagem de email, porque deu um clique no endereço de email %s.';
$ml_windows_mail = 'Se deseja utilizar Group-Office como o programa de correio por defeito no Windows, precisa de carregar um ficheiro de registo. Depois de transferido o ficheiro pode seleccionar Group-Office no Painel de Controlo -> Opções da Internet -> Programas';
$ml_download_reg='Descarregar ficheiro de registo';

$ml_help_url='http://docs.group-office.com/index.php?folder_id=57&file_id=0';

$ml_attachment_message = 'Mensagem';
$ml_open_popup='Abrir janela ao chegar um novo email';

$ml_vacation='Resposta automática';

//2.18
$ml_forward_local_copy='Manter a mensagem também nesta conta';
