<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('email'));

$ml_from = "Från";
$ml_to = "Till";
$ml_send = "Skicka";
$ml_attach = "Bifoga";
$ml_attachments = "Bifogade filer";
$ml_attachment = "Bifogad fil";
$ml_high = "Hög";
$ml_normal = "Normal";
$ml_low = "Låg";
$ml_priority = "Prioritet";
$ml_subject = "Ämne";
$ml_filename = "Filnamn";
$ml_total_size = "Total storlek";
$ml_size = "Storlek";
$ml_to_empty = "Du angav ingen mottagare.";
$ml_print = "Skriv ut";
$fbNoSelect = "Du valde inget meddelande";
$ml_inbox = 'inkorg';
$ml_properties = 'Egenskaper';
$ml_add_account = "Lägg till e-postkonto";
$em_new_folder = "Ny mapp";
$ml_your_accounts = "Dina e-postkonton";
$ml_no_accounts = "Du har inga e-postkonton konfigurerade.";
$ml_original_follows = "----- Ursprungligt Meddelande -----";
$ml_welcome = "Välkommen till Group-Office E-post";
$ml_text = "Tryck på konton för att lägga till ett e-postkonto.";
$ml_accounts = "Konton";
$ml_compose = "Skriv";
$ml_delete = "Radera";
$ml_refresh = "Uppdatera";
$ml_reply = "Svara";
$ml_forward = "Skicka vidare";
$ml_reply_all = "Svara till alla";
$ml_delete_message = "Är du säker på att vill radera detta meddelande permanent?";
$ml_no_subject = "Inget ämne";
$ml_no_reciepent = "Undisclosed reciepent";
$ml_online_files = "Online filer";
$ml_send_error = "Misslyckades med att skicka brevet.";
$ml_attach_forget = "Du har valt en fil men inte bifogat den.";
$ml_messages = "meddelande(n)";
$ml_message = 'detta meddelande';
$ml_messages2 = 'meddelanden';
$ml_new = "ny";
$ml_delete_mailbox = "Är du säker på att vill radera markerade meddelanden permanent?";
$contact_profile = "Kontaktprofil";
$ml_add_contact = "Lägg till sändare till kontakter";
$strHost = "Värd";
$strDefault = "Default";
$ml_edit_account = "Ändra konto";
$ml_new_account = "Nytt konto";
$ml_no_messages = "Det är inga meddelande i denna mapp.";
$ml_file_too_big = "Filen du försökte bifoga är för stor. Maximala storleken för bifogade filer är inställt till: ";
$fbNoRightToOverwrite = "Filen existerar redan, och du har inte rättigheter att skriva över den.";
$ml_save_attachment = "Spara bifogningen i Group-Office.";
$ml_folders = "Mappar";
$ml_select_folder = "Välj den mapp där Group-Office kan lagra skickad post eller ange ett namn nedan för att skapa en ny mapp";
$ml_connect_failed = "Misslyckades att skapa en anslutning till e-postservern:";
$ml_at_port = "port";
$ml_solve_error = 'Tryck på \'Konton\' för att återgärda dina kontoinställningar eller tryck på \'Ladda om\' för att öppna upp standardkonton.';
$ml_sent_items = "Skickade brev";
$ml_spam = "Spam";
$ml_use = "Använd";
$ml_synchronise = "synkronisera";
$ml_move_mail = "Flytta valda meddelande till mapp...";
$ml_filters = "Filter";
$ml_move_to = "flytta sedan meddelandet till mapp: ";
$ml_email_is = "Ifall avsändarens e-postadress innehåller:";
$ml_to_is = "Ifall mottagarens fält innehåller:";
$ml_cc_is = "Ifall cc-fältet innehåller:";
$ml_subject_is = "Ifall subjektet innehåller:";
$ml_new_filter = "Nytt filter:";
$ml_field = "Fält";
$ml_contains = "Innehåller";
$ml_folder = "Mapp";
$ml_no_folders = "Du har inga mappar så du kan inte skapa några filter.";
$ml_unwanted = "Klicka här ifall e-post från denna avsändare är oönskad";
$fbFolderSize = "Storlek på mapp";
$ml_move_up = "Öka prioritet";
$ml_delete_filter = "Är du säker på att du vill radera detta filter?";
$ml_high_priority = "Detta meddelande har hög prioritet!";
$ml_low_priority = "Detta meddelande har låg prioritet.";
$ml_block = "Blocka avsändare";
$ml_sent_items_fail = "Meddelandet har skickats, men det uppstod fel när meddelandet skulle skapas i din utmapp. Kontrollera ditt IMAP-konto.";
$fbProperties = "Egenskaper";
$ml_notification = "Begär att mottagaren skickar en bekräftelse när brevet är läst";
$ml_ask_notify = "Avsändaren av detta meddelande har begärt en bekräftelse av dig när brevet är läst. Vill du skicka denna?";
$ml_displayed = "Följande e-post har visats för ";
$ml_notify = "Läsnotifikation";
$ml_delete_filter1 = "Radera filter";
$ml_html_message_attached = "Original HTML-meddelande finns bifogat";
$ml_no_folders = 'Du har inga mappar att filtrera till';
$ml_no_filters = 'Du har inga filter';
$ml_host = 'Värd';
$ml_port = 'Port';
$ml_type = 'Typ';
$ml_servertype = 'Servertyp';
$ml_format = 'Format';
$ml_loose_changes = 'Ändringar kommer att gå förlorade. Är du säker?';
$ml_markread = "markera&nbsp;som&nbsp;läst";
$ml_markunread = "markera&nbsp;som&nbsp;oläst";
$ml_root_mailbox = "huvudbrevlåda";
$ml_inside = "i";
$ml_no_mailbox = "Detta är ingen epostlåda. Denna mapp kan ej innehålla meddelanden.";
$ml_signature = 'Signatur';
$ml_root = 'Huvudbrevlåda';
$ml_disable_accounts = 'Avaktivera kontohantering';
$ml_trash = 'Papperskorgen';
$ml_disable = 'Disable';
$ml_confirm_empty_mailbox = 'Är du säker på att du vill tömma denna mapp?';
$ml_empty_mailbox = 'Töm&nbsp;mapp';
$ml_you_have = 'Du har';
$ml_new_mail_single = 'nytt e-post meddelande.';
$ml_new_mail_multiple = 'nya e-post meddelanden.';
$ml_auto_check = 'Sök automatiskt efter ny e-post med detta konto.';
//1.98
$ml_no_contacts_in_mailing_group = 'Det finns inga kontakter i mailing gruppen du har valt. Var vänlig lägg till kontakter till gruppen först.';
$ml_attention= 'Attention';

//2.02
$ml_autocheck_disabled = ' kunde inte nås. Den automatiska sökningen efter e-post är avaktiverad på detta konto.';
$ml_mark = 'Markera meddelanden...';
$ml_flag = 'flaggad';
$ml_clearflag = 'oflaggad';
$ml_expand_all = 'Expandera alla mappar';
$ml_collapse_all = 'Minimera alla mappar';

//2.05
$ml_search = 'Sök';
$ml_answered = 'Besvarat';
$ml_doesnt_matter = 'Spelar ingen roll';
$ml_body = 'Body';
$ml_before = 'Äldre än';
$ml_since = 'Nyare än';
$ml_select_one_criteria = 'Var vänlig och välj eller skriv in åtminstone ett sök kriterie.';

//2.06
$ml_appointment = 'Detta meddelande innehåller ett möte. Vill du visa detta möte i kalendern?';
$ml_mails_were_sent = 'e-post meddelandena skickades';
$ml_novalidate_cert = 'Validera inte certifikatet';
$ml_appointment_vcf = 'Detta meddelande innehåller en kontaktadress. Vill du visa denna adress i adressboken?';
$ml_add_recievers = "Lägg till okända mottagare till din adressbok";

//2.08 
$ml_add_senders = 'Fråga om du vill lägga till okända avsändare till din standard adressbok';
$ml_text_format = 'Oformaterad text';
$ml_html_format_is = 'HTML (Om browsern stödjer HTML editering)';
$ml_html_format = 'HTML formaterat';
$ml_always_ask_notification = 'Fråga alltid mottagaren efter en läsbekräftelse som standard';
$ml_ask_add_sender = 'Avsändar adressen %s som tillhör %s finns inte i din adressbok. Vill du lägga till denna person till din adressbok nu?';

$ml_edit_filter = 'Ändra filter';
$ml_choose_action = 'Välj en handling:';
$ml_search_criteria = 'Sök kriterium';
$ml_sender = 'Avsändare';
$ml_reciever = 'Mottagare';
$ml_cc_reciever = 'CC-Mottagare';

//2.10
$ml_empty_trash = 'Töm&nbsp;papperskorgen';
//2.11
$ml_drafts = 'Utkast';
$ml_save_draft_error = 'Misslyckades med att spara utkastet. Var vänlig undersök dina kontoinställningar.';
$ml_search_sender = 'Sök efter annan e-post från denna avsändare';

$ml_no_attachments = 'Inga bifogade filer';
$ml_search_active = 'Sökfunktionen är aktiverad. Alla meddelande i denna mapp visas inte. Klicka här för att avsluta sökningen';
$ml_local_files = 'Lokala filer';
$ml_please_close_attachments = 'Var vänlig och stäng bifogningsfönstret först och verifiera att filöverföringarna är färdiga';

$ml_please_wait = 'Var vänlig vänta...';
$ml_max_attachment_size = 'Största tillåtna storlek på bifogning';
$ml_select = 'Välj fil';
$ml_multiple_files = 'Multipla filer';

//2.12
$ml_reenter_password = 'Av säkerhetsskäl måste du ange lösenord igen för detta e-post konto.';

$ml_attachments_added = 'filerna är bifogade';
$ml_attachment_added = 'filen är bifogad';

//2.13
$ml_download_zipped_attachments = 'Zip arkiv av alla bifogade filer';
$ml_fullscreen = 'Visa&nbsp;fullskärm';
$ml_nofullscreen = 'Stäng&nbsp;fullskärm';

$ml_confirm_empty_trash = 'Är du säker på att du permanent vill rader alla filer i papperkorgen?';

$ml_seen = 'Läst';


$ml_charset = 'Teckenuppsättning';

//2.14
$ml_no_reciever_add = "Lägg inte till";
$ml_add_recievers = "Lägg till okända mottagare till";//changed string from 2.06

$ml_automatic_reply = 'Aktivera automatsvar';

$ml_set_default = 'Aktivera förval';

$ml_used_of = 'använt av';

$ml_folder_not_available = 'Du kan inte skapa extra mappar med POP3 konton'
;
