<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('common'));
$htmldirection='ltr';
$charset = 'UTF-8';
//main language menu file register login and other non logged in pages
//common
$cmdLogin = "Login";
$cmdSave = "Save";
$cmdBack = "Back";
$cmdCancel = "Cancel";
$cmdClose = "Close";
$cmdOk = "Ok";
$cmdDelete = "Delete";
$cmdNext = "Next";
$cmdPrevious = "Previous";
$cmdContinue = "Continue";
$cmdUpdate = "Synchronize";
$cmdApply = "Apply";
$cmdYes = "Yes";
$cmdNo = "No";
$cmdAdd = 'Add';
$cmdEdit = 'Edit';
$cmdInvertSelection = 'Invert selection';

$strEdit = "Edit";
$strThis = 'this';
$strItems = 'items';
$strDescription = 'Description';

$strName = "Name";
$strUser = "User";
$strUsername = "Username";
$strPassword = "Password";
$strAuthcode = "Authorization code";
$strCountry = "Country";
$strState = "State";
$strCity = "City";
$strZip = "ZIP/Postal code";
$strAddress = "Street address";
$strEmail = "E-mail";
$strPhone = "Phone";
$strWorkphone = "Phone work";
$strCellular = "Cellular";
$strCompany = "Company";
$strDepartment = "Department";
$strFunction = "Function";
$strQuestion = "Secret question";
$strAnswer = "Answer";
$strFax = "Fax";
$strWorkFax = "Fax work";
$strHomepage = "Homepage";
$strWorkAddress = "Address Work";
$strWorkZip = "Zipcode work";
$strWorkCountry = "Country work";
$strWorkState = "State work";
$strWorkCity = "City work";
$strPhoto = "Photo";
$strComments = "Comments";
$strProperties = 'Properties';
$strDeleteItem = "Delete";
$strDate = "Date";
$strSaveSuccess = "Data saved successfully";
$strSaveError = "An error occured while saving data.";
$strDataError = "An error occured while reading data.";
$strDeleteError = "Could not delete data.";
$strAclError = "Access Control error";
$strDateError = "You entered an invalid date";
$strAccessDenied = "Access denied";
$AccessDenied_text = "You are not allowed to view this section of the site or to perform this action.<br />Another user has restricted access to the information you requested.";
$invalid_chars = "The following characters are not allowed";
$strGroups = "Groups";
$strOwner = "Owner";
$strDeletePrefix = "Are you sure you want to delete ";
$strDeleteSuffix = "?";
//menu
$menu_logout = "Logout";
$menu_applications = "Applications";
$menu_help = "Help";
$menu_about = "About";
$menu_documentation = "Documentation";
$menu_configuration = "Configuration";
$menu_groups = "Manage user groups";
$menu_accounts = "Modify your account settings";
$menu_preferences = "Adjust personal preferences";
$menu_search_files = "Files&nbsp;and&nbsp;folders";
$menu_search_web = "The&nbsp;web";
$menu_filetypes = "Filetypes";
$menu_discussions = "Discussion&nbsp;board";

$menu_users = "Manage users";
$menu_new = "New";
$menu_message = "Message";
$menu_contact = "Contact";
$menu_event = "Event";
$menu_bookmark = "Bookmark";
$menu_topics = "Topics";
$menu_support = "Support";
$menu_projects = "Projects";
$menu_sysinfo = "View system information";
$menu_admin = 'Administrator menu';
$menu_modules = 'Add/remove modules';
$menu_manual = 'Manual';

//class validate
$error_required = "You didn't specify the required field below.";
$error_match_auth = "The authorisation codes didn't match.";
$error_match_pass = "The passwords didn't match.";
$error_min_length = "Minimum characters of the field below:";
$error_max_length = "Maximum characters of the field below:";
$error_email = "The E-mail address you specified was invalid.";
$error_email_exists = "The E-mail address you entered already exists.";
$error_username_exists = "Sorry, the username you entered already exists. Please choose another one.";
$errors_in_form = "There were errors in the form. Correct them and try again.";
$error_missing_field = "You didn't fill in all the required fields.";

//acl control
$acl_control_auth_groups = "Authorized groups";
$acl_control_auth_users = "Authorized users";
$acl_control_no_contacts = "You don't have any member contacts to select.<br /> Use the Addressbook to add members to your contacts.";

$strShowProfile = "View Profile";
$strShowGroup = "View group members";
$strProcessingTime = "The processing of this page took ";
$strLoggedInAs = "Logged in as ";
$strAt = " at ";
$strEmailTo = "Send an E-mail message to: ";
$strProtectedUser = "Protected User";

$http_not_found = "Document not found";
$http_not_found_text = "The requested document was not found. Maybe you mistyped the URL.";
$http_error = "Internal Server Error";
$http_bad_request = "Bad request";
$strAddContact = "Add to contacts";

$strReadRights = "Read permissions";
$strWriteRights = "Write permissions";
$strPermissions = 'Permissions';

$days[0]="Su";
$days[1]="Mo";
$days[2]="Tu";
$days[3]="We";
$days[4]="Th";
$days[5]="Fr";
$days[6]="Sa";

$months[0]="January";
$months[1]="February";
$months[2]="March";
$months[3]="April";
$months[4]="May";
$months[5]="June";
$months[6]="July";
$months[7]="August";
$months[8]="September";
$months[9]="October";
$months[10]="November";
$months[11]="December";

$full_days[0] = "Sunday";
$full_days[1] = "Monday";
$full_days[2] = "Tuesday";
$full_days[3] = "Wednesday";
$full_days[4] = "Thursday";
$full_days[5]= "Friday";
$full_days[6] = "Saturday";
$strLoadTime = 'Generated in';
$strDescription = 'Description';



$lang_modules['addressbook'] = "Addressbook";
$cmdShowAll = 'Show all';
$cmdSearch = 'Search';

//translation required
$cmdYesToAll = 'Yes to all';
$cmdNoToAll = 'No to all';

$short_months[0]="Jan";
$short_months[1]="Feb";
$short_months[2]="Mar";
$short_months[3]="Apr";
$short_months[4]="May";
$short_months[5]="Jun";
$short_months[6]="Jul";
$short_months[7]="Aug";
$short_months[8]="Sep";
$short_months[9]="Oct";
$short_months[10]="Nov";
$short_months[11]="Dec";

$strToday = 'Today';

$cmdPrint = 'Print';
$strFirstName = 'First name';
$strLastName = 'Last name';
$strInitials = 'Initials';
$strSex = 'Sex';
$strBirthday = 'Birthday';
$strSexes['M'] = 'Male';
$strSexes['F'] = 'Female';

$strTitle = 'Title';
$strBeginning = 'Beginning';
$strMiddleName = 'Middle name';
$sir_madam['M'] = 'Mr.';
$sir_madam['F'] = 'Ms.';
$strModifiedAt = 'Modified at';
$strCreatedAt = 'Created at';

$htmlarea_language_name = 'en';
$strLocalization = 'Localization';


//look up the language in controls/jscalendar/lang
$jscalendar_language_name = 'calendar-en.js';


//2.01 translations

//look up language in 'classes/phpmailer/language'
$php_mailer_lang = 'en';
$strEmailFail = 'Failed sending the e-mail.';

//for people that want to use ktmlarea
$ktml_language = 'english';

$ml_host_unreachable = ' is unreachable. Automatic checking of e-mail is disabled.';
$strRegion = 'Region';

//2.05
$cmdReset = 'Reset';
$strMyName = 'My name';

//2.06
$strDeleteRow = 'Are you sure you want to delete this row?';
$strAddressNo = 'number of house';
$strWorkAddressNo = 'Work number of house';

$strPostAddress = 'Post address';
$strPostAddressNo = 'Post number of house';
$strPostCity = 'Post city';
$strPostState = 'Post state';
$strPostCountry = 'Post country';
$strPostZip = 'Post zip';
$strVisitAddress = 'Visit address';
$strPostAddress = 'Post address';



//modules
$lang_modules['scheduler'] = 'Scheduler';
$lang_modules['calendar'] = "Calendar";
$lang_modules['filesystem'] = 'Files';
$lang_modules['email'] = 'E-mail';
$lang_modules['projects'] = 'Projects';
$lang_modules['search'] = 'Search';
$lang_modules['contacts'] = "Addressbook";
$lang_modules['cms'] = "Websites";
$lang_modules['notes'] = "Notes";
$lang_modules['bookmarks'] = "Bookmarks";
$lang_modules['summary'] = "Summary";
$lang_modules['todos'] = "Tasks";
$lang_modules['opentts'] = "Helpdesk";
$lang_modules['products'] = "Software shop";
$lang_modules['dupviewer'] = "Email Duplication Report";
$cmdVcard = 'vCard';

//2.07
$strNotEnoughLicenses = 'You don\'t have enough licenses to use this section of Group-Office. Contact sales@intermesh.nl if you want to purchase additional licenses.';

//2.08
$alphabet = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z';
									
$strContact = 'Contact';
$strRelatedTo = 'Related to';
$strProject = 'Project';

$strNewProject = 'New project';
$strNewEvent = 'New event';
$strNewTodo = 'New todo';
$strNewNote = 'New note';

$strActivities = 'Activities';
$strFile = 'File';

//2.10
$cmdCopy = 'Copy';
$strProjects = 'Projects';
$strFiles = 'Files';
$cmdSaveNew = 'Save & New';
$strAvailability = 'Availability';
$strCheckAvailabilityFor = 'Check availability for';
$cmdPleaseSelect = 'Please select...';

//2.11
$strNewEmail = 'New e-mail';
$strConsistencyCheck = "Consistency Check";
$strSearchAll = 'All fields';
$sync_download_clients = 'Download synchronization clients';

//2.12
$strNoData = 'No data found';
//2.13
$strSynchronization = 'Synchronization';
$strSnooze = 'Snooze';
$strDismiss = 'Dismiss';

//2.14
$strUpload = 'Upload file';
$cmdInsert = 'Insert';
$strText = 'Text';
$strType = 'Type';

$strNoItemSelected = 'You didn\'t select an item';
$strSelectedItem = 'the selected item';

$strKeyword = 'Keyword';

$strNoActivities = 'No activities for this item';

$strCopy = 'Copy'; //not a verb

//2.15
$strBank = 'Bank';
$strBankNo = 'Bank number';
$strSelectedItems = 'selected items';

$strMonth = 'Month';
$strYear = 'Year';
$strDay = 'Day';
$strHour = 'Hour';
$strMinute = 'Minute';

$strTwelveHourFormat = '12 hour format';
$strTwentyfourHourFormat = '24 hour format';

//2.16
$strCreateLink = 'Create link';
$strCancelLink = 'Cancel linking';
$strLinkText = 'Linking is active. Browse to a linkable item and click at the \'Create link\' button to link it to \'%s\'. If you create a new item that is linkable then it will be linked automatically.';
$strLinks = 'Links';
$strUnlinkPrefix = 'Are you sure you want to unlink ';
$strUnlinkSuffix = '?';
$cmdUnlink = 'Unlink';



$strAdministrate = 'Administration';
$strProOnly = 'This feature is only available in Group-Office Professional. <a href="http://www.group-office.com">Click here to learn more about Group-Office Professional</a>';

$strMoreColors='More colors';

$strNoItems = 'No items found';
$cmdExport = 'Export';

$error_username = 'Invalid username. Only these charachters are allowed: a-z, 0-9,- en _';

$cmdSettings = 'Settings';


$strTableConfig = 'Table configuration';

$strMonthText = 'Month text';

$cmdUpload='Upload';
$cmdAttachFile='Attach file';


$search_text = '<b>Tip:</b> Include the the type (contact, company, project etc.) of the item you are looking for in the search phrase if you get too many results';
$search_global='Search Group-Office';
$search_results='results';
$search_result='result';
$strTime='Time';
$table_config_text='Enter a number in front of the columns that you want to view. The columns will be sorted by the number you enter.';
$strMoveUp='Move up one row';

$strAddressAndNo='Address / No.';
$strWorkAddressAndNo='Workaddress / No.';

$config_help_url='http://docs.group-office.com/index.php?folder_id=49&file_id=202';

$jupload_text='Select the files from your computer and click at \'Upload\'.';

$jupload_max_size='Maximum size';
$jupload_width='width';
$jupload_height='height';

$strReminder = 'Reminder';

$strMin='Minute';
$strMins='Minutes';
$strHours='Hours';
$strHour='Hour';
$strDay='Day';
$strDays='Days';
$strWeek='Week';
$strWeeks='Weeks';

$strStartTime = 'Start time';
$strAddReminder = 'Add reminder';


