<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_base_language_file('common'));

$charset = 'ISO-8859-2';
//main language menu file register login and other non logged in pages
//common
$cmdLogin = "Prijava";
$cmdSave = "Shrani";
$cmdBack = "Nazaj";
$cmdCancel = "Preklièi";
$cmdClose = "Zapri";
$cmdOk = "V redu";
$cmdDelete = "Zbri¹i";
$cmdNext = "Naslednje";
$cmdPrevious = "Prej¹nje";
$cmdContinue = "Nadaljuj";
$cmdUpdate = "Èasovno uskladi";
$cmdApply = "Uporabi";
$cmdYes = "Da";
$cmdNo = "Ne";
$cmdAdd = 'Dodaj';
$cmdEdit = 'Uredi';
$cmdInvertSelection = 'Obrni izbiro';

$strEdit = "Uredi";
$strThis = 'ta';
$strItems = 'predmeti';
$strDescription = 'Opis';

$strName = "Ime";
$strUser = "Uporabnik";
$strUsername = "Uporabni¹ko ime";
$strPassword = "Geslo";
$strAuthcode = "Koda pooblastitve";
$strCountry = "Dr¾ava";
$strState = "Pokrajna";
$strCity = "Mesto";
$strZip = "Po¹tna ¹tevilka";
$strAddress = "Naslov ulice";
$strEmail = "E-po¹ta";
$strPhone = "Telefon";
$strWorkphone = "Telefon v slu¾bi";
$strCellular = "Mobilnik";
$strCompany = "Podjetje";
$strDepartment = "Oddelek";
$strFunction = "Funkcija";
$strQuestion = "Skrivno vpra¹anje";
$strAnswer = "Odgovor";
$strFax = "Faks";
$strWorkFax = "Faks (slu¾ba)";
$strHomepage = "Domaèa stran";
$strWorkAddress = "Naslov (slu¾ba)";
$strWorkZip = "Po¹tna ¹tevilka (slu¾ba)";
$strWorkCountry = "Dr¾ava (slu¾ba)";
$strWorkState = "Dr¾ava (slu¾ba)";
$strWorkCity = "Mesto slu¾be";
$strPhoto = "Fotografija";
$strComments = "Komentarji";
$strProperties = 'Lastnosti';
$strDeleteItem = "Zbri¹i";
$strDate = "Datum";
$strSaveSuccess = "Podatki uspe¹no shranjeni";
$strSaveError = "Med shranjevanjem podatkov se je pojavila napaka.";
$strDataError = "Med branjem podatkov se je pojavila napaka.";
$strDeleteError = "Podatki ne morejo biti izbrisani.";
$strAclError = "Napaka pri dostopu do stre¾nika";
$strDateError = "Vnesli ste neveljaven datum";
$strAccessDenied = "Dostop zavrnjen";
$AccessDenied_text = "Nimate dovoljenja za ogled razdelka te strani ali izvedbo tega dejanja. <br />Drug uporabnik vam je omejil dostop do informacij, ki ste jih zahtevali.";
$invalid_chars = "Sledeèi znaki niso dovoljeni";
$strGroups = "Skupine";
$strOwner = "Lastnik";
$strDeletePrefix = "Ali ste preprièani, da ¾elite izbrisati";
$strDeleteSuffix = "?";
//menu
$menu_logout = "Odjava";
$menu_applications = "Programi";
$menu_help = "Pomoè";
$menu_about = "O programu";
$menu_documentation = "Dokumentacija";
$menu_configuration = "Nastavitev";
$menu_groups = "Uporabni¹ke&nbsp;skupine";
$menu_accounts = "Va¹&nbsp;raèun";
$menu_preferences = "Nastavitve";
$menu_search_discussions = "Razprave";
$menu_search_files = "Datoteke&nbsp;in&nbsp;imeniki";
$menu_search_web = "Splet";
$menu_filetypes = "Tipi datotek";
$menu_discussions = "Forum";

$menu_users = "Uporabniki";
$menu_new = "Novo";
$menu_message = "Sporoèilo";
$menu_contact = "Stiki";
$menu_event = "Dogodek";
$menu_bookmark = "Zaznamek";
$menu_topics = "Teme";
$menu_support = "Podpora";
$menu_projects = "Projekti";
$menu_sysinfo = "Informacije o sistemu";
$menu_admin = 'Skrbnik';
$menu_modules = 'Moduli';
$menu_manual = 'Priroènik';

//class validate
$error_required = "Niste vnesli zahtevanih podatkov v spodnje polje";
$error_match_auth = "Pooblastitevne kode se ne ujemajo.";
$error_match_pass = "Gesli se ne ujemata.";
$error_min_length = "Najmanj¹e ¹t. znakov za spodnje polje:";
$error_max_length = "Najveèje ¹t. znakov za spodnje polje:";
$error_email = "Vneseni e-po¹tni naslov ni pravilen.";
$error_email_exists = "Vne¹eni e-po¹tni naslov ¾e obstaja.";
$error_username_exists = "Oprostite, uporabni¹ko ime, ki ste ga vnesli ¾e obstaja. Prosim, izberite novega.";
$errors_in_form = "V obrazcu so bile napake. Popravite jih in poskusite znova.";
$error_missing_field = "Niste vnesli vsa potrebna polja.";

//acl control
$acl_control_auth_groups = "Poobla¹èene skupine";
$acl_control_auth_users = "Poobla¹èeni uporabniki";
$acl_control_no_contacts = "Nimate nobenih èlanov na izbiro.<br /> Uporabi adresar za dodjanje èlanov k va¹im stikom.";

$strShowProfile = "Poglej profil";
$strShowGroup = "Poglej skupine uporabnikov";
$strProcessingTime = "Obdelovanje te strani je trajalo";
$strLoggedInAs = "Prijavljen kot";
$strAt = " ob ";
$strEmailTo = "Po¹lji E-po¹to za:";
$strProtectedUser = "Za¹èiten uporabnik";

$http_not_found = "Dokument ni najden";
$http_not_found_text = "Zahtevani dokument ni bil najden. Mogoèe ste se zmotili pri URL-ju.";
$http_error = "Notranja napaka stre¾nika";
$http_bad_request = "Slab zahtevek";
$strAddContact = "Dodaj k stikom";

$strReadRights = "Dovoljenja za branje";
$strWriteRights = "Dovoljenja za pisanje";
$strPermissions = 'dovoljenja';

$days[0]="Ne";
$days[1]="Po";
$days[2]="To";
$days[3]="Sr";
$days[4]="Èe";
$days[5]="Pe";
$days[6]="So";

$months[0]="Januar";
$months[1]="Februar";
$months[2]="Marec";
$months[3]="April";
$months[4]="Maj";
$months[5]="Junij";
$months[6]="Julij";
$months[7]="Avgust";
$months[8]="September";
$months[9]="Oktober";
$months[10]="November";
$months[11]="December";

$full_days[0] = "Nedelja";
$full_days[1] = "Ponedeljek";
$full_days[2] = "Torek";
$full_days[3] = "Sreda";
$full_days[4] = "Èetrtek";
$full_days[5]= "Petek";
$full_days[6] = "Sobota";
$strLoadTime = 'Ustvarjeno v';
$strDescription = 'Opis';


$lang_modules['addressbook'] = "Adresar";
$cmdShowAll = 'Prika¾i vse';
$cmdSearch = 'Iskanje';

//translation required
$cmdYesToAll = 'Da za vse';
$cmdNoToAll = 'Ne za vse';

$short_months[0]="Jan";
$short_months[1]="Feb";
$short_months[2]="Mar";
$short_months[3]="Apr";
$short_months[4]="Maj";
$short_months[5]="Jun";
$short_months[6]="Jul";
$short_months[7]="Avg";
$short_months[8]="Sep";
$short_months[9]="Okt";
$short_months[10]="Nov";
$short_months[11]="Dec";

$strToday = 'Danes';

$cmdPrint = 'Natisni';
$strFirstName = 'Ime';
$strLastName = 'Priimek';
$strInitials = 'Zaèetnice';
$strSex = 'Spol';
$strBirthday = 'Rojstni dan';
$strSexes['M'] = 'Mo¹ki';
$strSexes['F'] = '®enska';

$strTitle = 'Naslov';
$strBeginning = 'Zaèetek';
$strMiddleName = 'Srednje&nbsp;ime';
$sir_madam['M'] = 'gospod';
$sir_madam['F'] = 'gospa';
$strModifiedAt = 'Spremenjeno ob';
$strCreatedAt = 'Ustvarjen ob';

$htmlarea_language_name = 'sl';
$strLocalization = 'Lokalizacija';


//look up the language in controls/jscalendar/lang
$jscalendar_language_name = 'calendar-sl.js';


//2.01 translations

//look up language in 'classes/phpmailer/language'
$php_mailer_lang = 'sl';
$strEmailFail = 'Po¹iljanje e-po¹te ni uspelo.';

//for people that want to use ktmlarea
$ktml_language = 'slovensko';

$ml_host_unreachable = ' je nedosegljiv. Samodejno preverjanje e-po¹t je onemogoèeno.';
$strRegion = 'Regija';

//2.05
$cmdReset = 'Ponastavi';
$strMyName = 'Moje ime';

//modules
$lang_modules['scheduler'] = 'Urnik';
$lang_modules['calendar'] = "Koledar";
$lang_modules['filesystem'] = 'Datoteke';
$lang_modules['email'] = 'E-po¹ta';
$lang_modules['projects'] = 'Projekti';
$lang_modules['search'] = 'Iskanje';
$lang_modules['contacts'] = "Knjiga z naslovi";
$lang_modules['cms'] = "Spletne strani";
$lang_modules['notes'] = "Zapiski";
$lang_modules['bookmarks'] = "Zaznamki";
$lang_modules['summary'] = "Povzetek";
$lang_modules['todos'] = "Opravila";
