<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Místo";
$sc_description = "Popis";
$sc_client = 'Klient';
$sc_no_contact = 'žádný';
$sc_start_at = 'Začátek';
$sc_background = 'Barva pozadí';

$sc_mins = 'minut';
$sc_hour = 'hodina';
$sc_hours = 'hodin';
$sc_day = 'den';
$sc_days = 'dnů';
$sc_week = 'týden';
$sc_weeks = 'týdnů';

$sc_colors['red'] = 'Červená';
$sc_colors['green'] = 'Zelená';
$sc_colors['blue'] = 'Modrá';
$sc_colors['pink'] = 'Růžová';
$sc_colors['orange'] = 'Oranžová';
$sc_colors['brown'] = 'Hnědá';
$sc_colors['yellow'] = 'Žlutá';
$sc_colors['grey'] = 'Šedá';
$sc_colors['purple'] = 'Fialová';
$sc_colors['white']= 'Bílá';
$sc_status = 'stav';

$cal_add_todo = 'Nový úkol';
$cal_todos = 'Úkoly';
$sc_reminder = 'Budík';
$cal_hide_completed = 'Schovat hotové';
$cal_show_all = 'Zobrazit všechny úkoly';
$cal_show_own = 'Zobrazit vlastní úkoly';
$cal_show_responsible = 'Zobrazit přidělené úkoly';

$cal_priority = 'Důležitost';
$cal_priority_values[0] = 'Malá';
$cal_priority_values[1] = 'Normální';
$cal_priority_values[2] = 'Velká';

$cal_status = 'Stav';
$cal_canceled = 'Zrušeno';
$cal_completed = 'Hotovo';
$cal_percent_completed = '% hotovo';

$cal_before_task_start = 'Před začátkem úkolu';
$cal_before_task_due = 'Před koncem úkolu';
$cal_responsible = 'Zodpovídá';
$cal_due_at = 'Termín';
$cal_no_todos= 'Nejsou žádné úkoly';

$sc_start_later = 'Špatné zadání!! Konec je dříve než začátek.';

$td_count_single = 'úkol';
$td_count_multiple = 'úkoly';
