<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Location";
$sc_description = "Description";
$sc_client = 'Client';
$sc_no_contact = 'None';
$sc_start_at = 'Starting at';
$sc_background = 'Background';

$sc_mins = 'mins';
$sc_hour = 'hour';
$sc_hours = 'hours';
$sc_day = 'day';
$sc_days = 'days';
$sc_week = 'week';
$sc_weeks = 'weeks';

$sc_colors['red'] = 'Red';
$sc_colors['green'] = 'Green';
$sc_colors['blue'] = 'Blue';
$sc_colors['pink'] = 'Pink';
$sc_colors['orange'] = 'Orange';
$sc_colors['brown'] = 'Brown';
$sc_colors['yellow'] = 'Yellow';
$sc_colors['grey'] = 'Grey';
$sc_colors['purple'] = 'Purple';
$sc_colors['white']= 'White';
$sc_status = 'status';

$cal_add_todo = 'New task';
$cal_todos = 'Tasks';
$sc_reminder = 'Reminder';
$cal_hide_completed = 'Hide completed';
$cal_show_all = 'Show all tasks';
$cal_show_own = 'Show own tasks';
$cal_show_responsible = 'Show reponsible tasks';

$cal_priority = 'Priority';
$cal_priority_values[0] = 'Low';
$cal_priority_values[1] = 'Normal';
$cal_priority_values[2] = 'High';

$cal_status = 'Status';
$cal_canceled = 'Cancelled';
$cal_completed = 'Completed at';
$cal_percent_completed = '% completed';

$cal_before_task_start = 'Before the task starts';
$cal_before_task_due = 'Before the task should be finnished';
$cal_responsible = 'Responsible';
$cal_due_at = 'Due at';
$cal_no_todos= 'No tasks found';

$sc_start_later = 'Bad input!! The starting time is later then the ending time.';

$td_count_single = 'todo';
$td_count_multiple = 'todo\'s';


