<?php
require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Lugar";
$sc_description = "Descripción";
$sc_client = 'Cliente';
$sc_no_contact = 'Ningún';
$sc_start_at = 'Comienza el';
$sc_background = 'Color de fondo';

$sc_mins = 'minutos';
$sc_hour = 'hora';
$sc_hours = 'horas';
$sc_day = 'día';
$sc_days = 'días';
$sc_week = 'semana';
$sc_weeks = 'semanas';

$sc_colors['red'] = 'Rojo';
$sc_colors['green'] = 'Verde';
$sc_colors['blue'] = 'Azul';
$sc_colors['pink'] = 'Rosa';
$sc_colors['orange'] = 'Naranja';
$sc_colors['brown'] = 'Marrón';
$sc_colors['yellow'] = 'Amarillo';
$sc_colors['grey'] = 'Gris';
$sc_colors['purple'] = 'Púrpura';
$sc_colors['white']= 'Blanco';
$sc_status = 'estado';

$cal_add_todo = 'Nueva tarea';
$cal_todos = 'tareas';
$sc_reminder = 'Recordatorio';
$cal_hide_completed = 'Ocultar las completadas';
$cal_show_all = 'Ver todas las tareas';
$cal_show_own = 'Ver las tareas propias';
$cal_show_responsible = 'Ver tareas de responsabilidad';

$cal_priority = 'Prioridad';
$cal_priority_values[0] = 'Baja';
$cal_priority_values[1] = 'Normal';
$cal_priority_values[2] = 'Alta';

$cal_status = 'Estado';
$cal_canceled = 'Cancelado';
$cal_completed = 'Completado el';
$cal_percent_completed = '% completado';

$cal_before_task_start = 'Antes que la tarea empiece';
$cal_before_task_due = 'Antes que la tarea haya terminado';
$cal_responsible = 'Responsable';
$cal_due_at = 'Para el';
$cal_no_todos= 'No se ha encontrado ninguna tarea';

$sc_start_later = '¡¡Entrada incorrecta!! La hora de inicio es superior a la h
ora de finalización.';

$td_count_single = 'por-hacer';
$td_count_multiple = 'por-haceres';
