<?php
//Uncomment this line in new translations! LI 20.01.2006
require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Paikka";
$sc_description = "Kuvaus";
$sc_client = 'Asiakas';
$sc_no_contact = 'Tyhjä';
$sc_start_at = 'Alkaa';
$sc_background = 'Tausta';

$sc_mins = 'minuutit';
$sc_hour = 'tunti';
$sc_hours = 'tunnit';
$sc_day = 'päivä';
$sc_days = 'päivät';
$sc_week = 'viikko';
$sc_weeks = 'viikot';

$sc_colors['red'] = 'Punainen';
$sc_colors['green'] = 'Vihreä';
$sc_colors['blue'] = 'Sininen';
$sc_colors['pink'] = 'Pinkki';
$sc_colors['orange'] = 'Oransi';
$sc_colors['brown'] = 'Ruskea';
$sc_colors['yellow'] = 'Keltainen';
$sc_colors['grey'] = 'Harmaa';
$sc_colors['purple'] = 'Purppura';
$sc_colors['white']= 'Valkoinen';
$sc_status = 'tila';

$cal_add_todo = 'Uusi tehtävä';
$cal_todos = 'Tehtävät';
$sc_reminder = 'Muistutus';
$cal_hide_completed = 'Piilotus suoritettu';
$cal_show_all = 'Näytä kaikki tehtävät';
$cal_show_own = 'Näytä omat tehtävät';
$cal_show_responsible = 'Näytä vastuulliset tehtävät';

$cal_priority = 'Prioriteetti';
$cal_priority_values[0] = 'Matala';
$cal_priority_values[1] = 'Normaali';
$cal_priority_values[2] = 'Korkea';

$cal_status = 'Tila';
$cal_canceled = 'Peruttu';
$cal_completed = 'Valmistunut';
$cal_percent_completed = '% valmis';

$cal_before_task_start = 'Ennen tehtävän aloitusta';
$cal_before_task_due = 'Ennenkuin tehtävän pitäisi olla valmis';
$cal_responsible = 'Vastuullinen';
$cal_due_at = 'Tulossa';
$cal_no_todos= 'Tehtävä ei löytynyt';

$sc_start_later = 'Väärin syötetty!! Aloitus ajankohta on loppu ajankohdan jälkeen.';

$td_count_single = 'tehtävä';
$td_count_multiple = 'tehtävät';
