<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Emplacement";
$sc_description = "Description";
$sc_client = 'Client';
$sc_no_contact = 'Aucun';
$sc_start_at = 'Débutant à';
$sc_background = 'Arrière-plan';
$sc_mins = 'minutes';
$sc_hour = 'heure';
$sc_hours = 'heures';
$sc_day = 'jour';
$sc_days = 'jours';
$sc_week = 'semaine';
$sc_weeks = 'semaines';
$sc_colors['red'] = 'Rouge';
$sc_colors['green'] = 'Vert';
$sc_colors['blue'] = 'Bleu';
$sc_colors['pink'] = 'Rose';
$sc_colors['orange'] = 'Orange';
$sc_colors['brown'] = 'Brun';
$sc_colors['yellow'] = 'Jaune';
$sc_colors['grey'] = 'Gris';
$sc_colors['purple'] = 'Violet';
$sc_colors['white']= 'Blanc';
$sc_status = 'état';
$cal_add_todo = 'Nouvelle tâche';
$cal_todos = 'Tâches';
$sc_reminder = 'Rappel';
$cal_hide_completed = 'Cacher tâches terminées';
$cal_show_all = 'Montrer toutes les tâches';
$cal_show_own = 'Montrer mes tâches';
$cal_show_responsible = 'Montrer le responsable des tâches';
$cal_priority = 'Priorité';
$cal_priority_values[0] = 'Faible';
$cal_priority_values[1] = 'Normale';
$cal_priority_values[2] = 'Importante';
$cal_status = 'Etat';
$cal_canceled = 'Annulée';
$cal_completed = 'Terminé à ';
$cal_percent_completed = '% terminé(s)';
$cal_before_task_start = 'Avant que la tâche commence';
$cal_before_task_due = 'Avant que la tâche ne soit finie';
$cal_responsible = 'Responsable';
$cal_due_at = 'Se termine à';
$cal_no_todos= 'Aucune tâche trouvée';
$sc_start_later = 'Mauvaise entrée ! La date de fin précède la date de début.';
$td_count_single = 'tâche';
$td_count_multiple = 'tâches';
?>
