<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "ロケーション";
$sc_description = "説明";
$sc_client = 'クライアント';
$sc_no_contact = 'なし';
$sc_start_at = '開始';
$sc_background = '背景';

$sc_mins = '分';
$sc_hour = '時間';
$sc_hours = '時間';
$sc_day = '日';
$sc_days = '日';
$sc_week = '週';
$sc_weeks = '週';

$sc_colors['red'] = '赤';
$sc_colors['green'] = '緑';
$sc_colors['blue'] = '青';
$sc_colors['pink'] = 'ピンク';
$sc_colors['orange'] = 'オレンジ';
$sc_colors['brown'] = '茶色';
$sc_colors['yellow'] = '黄色';
$sc_colors['grey'] = '灰色';
$sc_colors['purple'] = '紫';
$sc_colors['white']= '白';
$sc_status = 'ステータス';

$cal_add_todo = '新規タスク';
$cal_todos = 'タスク';
$sc_reminder = '督促';
$cal_hide_completed = '不可視化完了';
$cal_show_all = '全てのタスクを表示';
$cal_show_own = '自分のタスクを表示';
$cal_show_responsible = '責任者のタスクを表示';

$cal_priority = '優先度';
$cal_priority_values[0] = '低';
$cal_priority_values[1] = '普通';
$cal_priority_values[2] = '高';

$cal_status = 'ステータス';
$cal_canceled = 'キャンセル';
$cal_completed = '完了';
$cal_percent_completed = '% 完了済み';

$cal_before_task_start = 'タスク開始前';
$cal_before_task_due = 'タスクが終了する前';
$cal_responsible = '責任者';
$cal_due_at = '締め切り';
$cal_no_todos= 'タスクなし';

$sc_start_later = '不正な入力です。開始時が終了時より後です。';

$td_count_single = 'タスク';
$td_count_multiple = 'タスク';
