<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Local";
$sc_description = "Descrição";
$sc_client = 'Cliente';
$sc_no_contact = 'Nenhum';
$sc_start_at = 'Começado em';
$sc_Fundo = 'Fundo';

$sc_mins = 'mins';
$sc_hour = 'hora';
$sc_hours = 'horas';
$sc_day = 'dia';
$sc_days = 'dias';
$sc_week = 'semana';
$sc_weeks = 'semanas';

$sc_colors['red'] = 'Vermelho';
$sc_colors['green'] = 'Verde';
$sc_colors['blue'] = 'Azul';
$sc_colors['pink'] = 'Rosa';
$sc_colors['orange'] = 'Laranja';
$sc_colors['brown'] = 'Marrom';
$sc_colors['yellow'] = 'Amarelo';
$sc_colors['grey'] = 'Cinza';
$sc_colors['purple'] = 'Lilás';
$sc_colors['white']= 'Branco';
$sc_status = 'status';

$cal_add_todo = 'Nova Tarefa';
$cal_todos = 'Tarefas';
$sc_reminder = 'Lembrar';
$cal_hide_completed = 'Escondido';
$cal_show_all = 'Mostrar todas as tarefas';
$cal_show_own = 'Mostrar donos das tarefas';
$cal_show_responsible = 'Mostrar responsabilidade pelas tarefas';

$cal_priority = 'Prioridade';
$cal_priority_values[0] = 'Baixa';
$cal_priority_values[1] = 'Normal';
$cal_priority_values[2] = 'Alta';

$cal_status = 'Status';
$cal_canceled = 'Cancelado';
$cal_completed = 'Completado em';
$cal_percent_completed = '% completado';

$cal_before_task_start = 'Antes de iniciar a tarefa';
$cal_before_task_due = 'Terminar antes da tarefa';
$cal_responsible = 'Responsável';
$cal_due_at = 'Feito em';
$cal_no_todos= 'Nenhuma tarefa encontrada';

$sc_start_later = 'Entrada errada!! A hora de inicio está maior do que a hora de término.';

$td_count_single = 'a fazer';
$td_count_multiple = 'a fazere\'s';
