<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "Plats";
$sc_description = "Beskrivning";
$sc_client = 'Klient';
$sc_no_contact = 'Ingen';
$sc_start_at = 'Börjar';
$sc_background = 'Bakgrund';

$sc_mins = 'mins';
$sc_hour = 'timme';
$sc_hours = 'timmar';
$sc_day = 'dag';
$sc_days = 'dagar';
$sc_week = 'vecka';
$sc_weeks = 'veckor';

$sc_colors['red'] = 'Röd';
$sc_colors['green'] = 'Grön';
$sc_colors['blue'] = 'Blå';
$sc_colors['pink'] = 'Rosa';
$sc_colors['orange'] = 'Orange';
$sc_colors['brown'] = 'Brun';
$sc_colors['yellow'] = 'Gul';
$sc_colors['grey'] = 'Grå';
$sc_colors['purple'] = 'Lila';
$sc_colors['white']= 'Vit';
$sc_status = 'status';

$cal_add_todo = 'Ny uppgift';
$cal_todos = 'Uppgifter';
$sc_reminder = 'Påminnelse';
$cal_hide_completed = 'Göm avklarade';
$cal_show_all = 'Visa alla uppgifter';
$cal_show_own = 'Visa egna uppgifter';
$cal_show_responsible = 'Visa ansvariga uppgifter';

$cal_priority = 'Prioritet';
$cal_priority_values[0] = 'Låg';
$cal_priority_values[1] = 'Normal';
$cal_priority_values[2] = 'Hög';

$cal_status = 'Status';
$cal_canceled = 'Avbruten';
$cal_completed = 'Avslutad';
$cal_percent_completed = '% avslutat';

$cal_before_task_start = 'Innan uppgiften börjar';
$cal_before_task_due = 'Innan uppgiften ska vara klar';
$cal_responsible = 'Ansvarig';
$cal_due_at = 'Avklarad';
$cal_no_todos= 'Inga uppgifter funna';

$sc_start_later = 'Felaktig uppgift!! Starttiden är senare än sluttiden.';

$td_count_single = 'uppgift';
$td_count_multiple = 'uppgifter';
