<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('todos'));

//translation required below this
$sc_location = "ตำแหน่ง";
$sc_description = "รายละเอียด";
$sc_client = 'เครื่องลูกข่าย';
$sc_no_contact = 'ไม่มี';
$sc_start_at = 'เริ่มต้นที่';
$sc_background = 'แบคกราวน์';

$sc_mins = 'นาที';
$sc_hour = 'ชั่วโมง';
$sc_hours = 'ชั่วโมง';
$sc_day = 'วัน';
$sc_days = 'วัน';
$sc_week = 'สัปดาห์';
$sc_weeks = 'สัปดาห์';

$sc_colors['red'] = 'Red';
$sc_colors['green'] = 'Green';
$sc_colors['blue'] = 'Blue';
$sc_colors['pink'] = 'Pink';
$sc_colors['orange'] = 'Orange';
$sc_colors['brown'] = 'Brown';
$sc_colors['yellow'] = 'Yellow';
$sc_colors['grey'] = 'Grey';
$sc_colors['purple'] = 'Purple';
$sc_colors['white']= 'White';
$sc_status = 'status';


$cal_add_todo = 'สร้างงานใหม่';
$cal_todos = 'งาน';
$sc_reminder = 'แจ้งเตือน';
$cal_hide_completed = 'ซ่อนงานที่สำเร็จ';
$cal_show_all = 'แสดงงานทั้งหมด';
$cal_show_own = 'แสดงเฉพาะงานส่วนตัว';
$cal_show_responsible = 'Show reponsible tasks';

$cal_priority = 'ความสำคัญ';
$cal_priority_values[0] = 'ต่ำ';
$cal_priority_values[1] = 'ปานกลาง';
$cal_priority_values[2] = 'สูง';

$cal_status = 'สถานะ';
$cal_canceled = 'ยกเลิก';
$cal_completed = 'สำเร็จที่';
$cal_percent_completed = '% สำเร็จ';


$cal_before_task_start = 'ก่อนงานจะเริ่มต้น';
$cal_before_task_due = 'หลังจกาวานเสร็จแล้ว';
$cal_responsible ='ตอบกลับ';
$cal_due_at = 'สิ้นสุดเมื่อ';
$cal_no_todos= 'ไม่พบงาน';
$sc_start_later = 'Bad input!! The starting time is later then the ending time.';

$td_count_single = 'งาน';
$td_count_multiple = 'งาน';
