<?php
// registration of all used image files

$images['apache_logo']		= 'apache_logo.gif';
$images['attach']		= 'attach.gif';
$images['colors']		= 'colors.gif';
$images['go_header']		= 'GO-header.png';
$images['google']		= 'google.gif';
$images['high_priority']	= 'high_priority.gif';
$images['info']			= 'info.png';
$images['low_priority']		= 'low_priority.gif';
$images['mail']			= 'mail.png';
$images['mail_forw']		= 'mail_forw.png';
$images['mail_repl']		= 'mail_repl.png';
$images['menu_arrow']		= 'menu_arrow.gif';
$images['menu_arrowdn']		= 'menu_arrowdn.gif';
$images['menubar']		= 'menubalk.gif';
$images['mysql_logo']		= 'mysql_logo.gif';
$images['newmail']		= 'newmail.png';
$images['php_logo']		= 'php_logo.gif';
$images['questionmark']		= 'questionmark.png';
$images['site']			= 'site.png';
$images['stop']			= 'stop.png';
$images['accounts']		= 'buttons/accounts.png';
$images['add_contact']		= 'buttons/add_contact.png';
$images['addressbook_small']		= 'buttons/addressbook.png';
$images['addressbook_big']	= 'buttons/addressbook_big.png';
$images['contacts']		= 'buttons/addressbook_big.png';
$images['addressbook']		= 'buttons/addressbook_big.png';
$images['arrow_down']		= 'buttons/arrow_down.gif';
$images['arrow_up']		= 'buttons/arrow_up.gif';
$images['authorise']		= 'buttons/authorise.png';
$images['bg_color']		= 'buttons/bg_color.gif';
$images['block']		= 'buttons/block.gif';
$images['bold']			= 'buttons/bold.gif';
$images['bullist']		= 'buttons/bullist.gif';
$images['center']		= 'buttons/center.gif';
$images['compose']		= 'buttons/compose.png';
$images['copy']			= 'buttons/copy.png';
$images['copy_small']		= 'buttons/copy_small.gif';
$images['cut']			= 'buttons/cut.png';
$images['paste']			= 'buttons/paste.png';
$images['delete']		= 'buttons/delete.png';
$images['delete_big']		= 'buttons/delete_big.png';
$images['dn']			= 'buttons/down_blue.png';
$images['drafts']		= 'buttons/drafts.gif';
$images['edit']			= 'buttons/properties.gif';
$images['em_refresh']		= 'buttons/em_refresh.png';
$images['email']		= 'buttons/email.png';
$images['email_small']		= 'buttons/email_small.png';
$images['export']		= 'buttons/export.png';
$images['files']		= 'buttons/files.png';
$images['filesystem']		= 'buttons/filesystem.png';
$images['filters']		= 'buttons/filters.png';
$images['folders']		= 'buttons/folders.png';
$images['forward']		= 'buttons/forward.png';
$images['fs_refresh']		= 'buttons/fs_refresh.png';
$images['groups']		= 'buttons/groups.png';
$images['import']		= 'buttons/import.png';
$images['inbox']		= 'buttons/inbox.png';
$images['listview']		= 'buttons/listview.png';
$images['mail_account']		= 'buttons/mail_account.gif';
$images['markread']		= 'buttons/markread.png';
$images['markunread']		= 'buttons/markunread.png';
$images['new_doc']		= 'buttons/newdoc.png';
$images['new_folder']		= 'buttons/new_folder.png';
$images['next']			= 'buttons/next.png';
$images['previous']		= 'buttons/previous.png';
$images['print']		= 'buttons/print.png';
$images['projects']		= 'buttons/projects.png';
$images['properties']		= 'buttons/properties.png';
$images['refresh']		= 'buttons/refresh.png';
$images['reply']		= 'buttons/reply.png';
$images['reply_all']		= 'buttons/reply_all.png';
$images['right_arrow']		= 'buttons/right_arrow.gif';
$images['save']			= 'buttons/save.png';
$images['calendar']		= 'buttons/calendar.png';
$images['search']		= 'buttons/search.png';
$images['sent']			= 'buttons/sent.gif';
$images['seperator']		= 'buttons/seperator.gif';
$images['sharing']		= 'buttons/sharing.png';
$images['spam']			= 'buttons/spam.gif';
$images['strikethrough']	= 'buttons/strikethrough.gif';
$images['up']			= 'buttons/up.png';
$images['upload']		= 'buttons/upload.png';
$images['uplvl_big']		= 'buttons/uplvl_big.png';
$images['users']		= 'buttons/users.png';
$images['week']			= 'buttons/week.png';
$images['blank']		= 'blank.gif';
$images['emptylastnode']	= 'treeview/emptylastnode.gif';
$images['emptynode']		= 'treeview/emptynode.gif';
$images['folder']		= 'treeview/folder.gif';
$images['folderclosed']		= 'treeview/folderclosed.gif';
$images['folderopen']		= 'treeview/folderopen.gif';
$images['home']			= 'treeview/home.png';
$images['lastnode']		= 'treeview/lastnode.gif';
$images['min_node']		= 'treeview/min_node.gif';
$images['min_node_white']	= 'treeview/min_node_white.gif';
$images['mlastnode']		= 'treeview/mlastnode.gif';
$images['mnode']		= 'treeview/mnode.gif';
$images['node']			= 'treeview/node.gif';
$images['plastnode']		= 'treeview/plastnode.gif';
$images['plus_node']		= 'treeview/plus_node.gif';
$images['plus_node_white']	= 'treeview/plus_node_white.gif';
$images['pnode']		= 'treeview/pnode.gif';
$images['vertline']		= 'treeview/vertline.gif';
$images['workgroup']		= 'treeview/workgroup.png';
$images['workstation']		= 'treeview/workstation.png';
$images['cms'] 			= 'buttons/cms.png';
$images['exit']	= 'buttons/exit.png';
$images['close']	= 'buttons/fileclose.png';
$images['save_big']	= 'buttons/filesave.png';
$images['magnifier']		= 'buttons/viewmag.png';
$images['magnifier_big']	= 'buttons/viewmag_big.png';
$images['shared']		= 'shared.png';
$images['shared_folder']		= 'treeview/shared_folder.gif';
$images['shared_folder_closed']		= 'treeview/shared_folder_closed.gif';
$images['shared_folder_open']		= 'treeview/shared_folder_open.gif';
$images['Intermesh'] = 'intermesh.gif';
$images['invisible_folder'] = 'treeview/folder_invisible.png';
$images['em_settings_admin'] = 'buttons/em_settings_admin.png';
$images['comics']               = 'buttons/garfield.gif';
$images['new_slide'] = 'buttons/window_new.png';
$images['compress'] = 'buttons/compress.png';
$images['decompress'] = 'buttons/decompress.png';

$images['new_letter'] = 'buttons/new_letter.png';
$images['alert'] = 'important.gif';
$images['ok'] = 'ok.png';
$images['ongoing'] = 'ongoing.png';
$images['offer'] = 'offer.png';
$images['clock'] = 'clock.gif';
$images['clockout'] = 'clockout.gif';

$images['calendar']		= 'buttons/calendar.png';
$images['cal_compose']		= 'buttons/cal_compose.png';
$images['cal_day']		= 'buttons/cal_day.png';
$images['cal_month']		= 'buttons/cal_month.png';
$images['cal_print']		= 'buttons/cal_print.png';
$images['cal_week']		= 'buttons/cal_week.png';
$images['cal_refresh']		= 'buttons/cal_refresh.png';
$images['cal_list']		= 'buttons/cal_list.png';
$images['cal_view']			= 'buttons/cal_group.png';

$images['enter_data']		= 'buttons/enter_data.png';

$images['notes']		= 'buttons/notes.png';
$images['empty_folder'] = 'buttons/empty_folder.png';

$images['configuration'] = 'buttons/configure.png';
$images['help'] = 'buttons/help.png';
$images['logout'] = 'buttons/exit_small.png';
$images['admin'] = 'buttons/admin.png';


$images['account'] = 'buttons/add_contact.png';
$images['preferences'] = 'buttons/preferences.png';
$images['filetypes'] = 'buttons/filetypes.png';
$images['modules'] = 'buttons/modules.png';
$images['phpsysinfo'] = 'buttons/sysinfo.png';

$images['ab_browse'] = 'buttons/ab_browse.png';
$images['ab_addressbooks'] = 'buttons/ab_addressbooks.png';
$images['ab_search'] = 'buttons/ab_search.png';
$images['fs_search'] = 'buttons/fs_search.png';
$images['fs_email'] = 'buttons/compose.png';
$images['ab_email'] = 'buttons/email.png';
$images['ml_inbox'] = 'buttons/email.png';
$images['bookmarks'] = 'buttons/bookmarks.png';
$images['ab_companies'] = 'buttons/ab_companies.png';
$images['ab_add_company'] = 'buttons/ab_add_company.png';
$images['cal_calendar']			= 'buttons/calendar.png';
$images['ab_notes'] = 'buttons/notes.png';

$images['ab_custom_fields'] = 'buttons/custom_fields.png';
$images['email_notify'] = 'buttons/email.png';
$images['mailings'] = 'buttons/mailings.png';

$images['alert_big'] = 'important_big.gif';
$images['flag'] = 'flag.png';
$images['expand_all'] = 'buttons/plus_node.gif';
$images['collapse_all'] = 'buttons/collapse_all.gif';
$images['bm_add_bookmark'] = 'buttons/bm_add_bookmark.gif';
$images['bm_add_bookmark_big'] = 'buttons/bm_add_bookmark_big.png';
$images['bm_catagories'] = 'buttons/bookmarks.png';
$images['cal_add_todo'] = 'buttons/todo.gif';
$images['todos'] = 'buttons/todos.png';
$images['summary'] = 'buttons/summary.png';
$images['unknown'] = 'buttons/unknown.png';

$images['ml_search'] = 'buttons/em_search.png';

//rittenregistratie
$images['up_green'] = 'buttons/up_green.png';
$images['down_blue'] = 'buttons/down_blue.png';

$images['opt_close'] = 'buttons/opt_close.png';
$images['opt_open'] = 'buttons/opt_open.png';

$images['pr_new_project'] = 'buttons/projects_new.png';
$images['pr_load'] = 'buttons/projects_load.png';
$images['pr_fees'] = 'buttons/projects_fees.png';

$images['todos_new'] = 'buttons/todos_new.png';

$images['cal_available'] = 'buttons/cal_available.png';
$images['calendar_small'] = 'buttons/calendar_small.png';
$images['user_small'] = 'buttons/user_small.png';

$images['back_small'] = 'buttons/back_small.png';
$images['forward_small'] = 'buttons/forward_small.png';
$images['users_small'] = 'buttons/users_small.png';

$images['close_small'] = 'buttons/close.gif';

$images['cms_settings'] = 'buttons/configuration_big.png';

//2.11
$images['ml_local_files'] = 'buttons/upload.png';
$images['products'] = 'buttons/products.png';
$images['rittenregistratie'] = 'buttons/rittenregistratie.png';

//2.12
$images['enter_data_big']		= 'buttons/enter_data_big.png';
//2.13
$images['fullscreen'] = 'buttons/window_fullscreen.png';
$images['nofullscreen'] = 'buttons/window_nofullscreen.png';
$images['blank'] = 'treeview/blank.gif';

//2.14
$images['user_add'] = 'buttons/user_add.png';
$images['add'] ='buttons/window_new.png';
$images['appearance'] = 'buttons/appearance.png';

//2.15
$images['resources'] = 'buttons/resources.png';

$images['plus'] = 'images/plus.png';
$images['min'] = 'images/min.png';
$images['link'] = 'buttons/connect_established.png';
$images['unlink'] = 'buttons/connect_no.png';
$images['billing'] = 'buttons/calc.png';
$images['recur'] = 'buttons/recur.png';
$images['links_small'] = 'buttons/attach.gif';
$images['custom_fields'] = 'buttons/custom_fields.png';

$images['apply'] = 'buttons/apply.png';
$images['parking'] = 'buttons/cal_list.png';
$images['cancel'] = 'buttons/cancel.png';

$images['gallery'] = 'buttons/gallery.png';
$images['translate'] = 'buttons/locale.png';
$images['timeregistration'] = 'buttons/xclock.png';
$images['properties_small']='buttons/edit.png';