<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='ملاحظة';
$no_notes_count='ملاحظات';
$no_catagory='الفئة';
$no_no_notes='لا توجد ملاحظات';
$no_new_note='ملاحظة جديدة';
$pm_note_exists='يوجد\'مذكرة بهذا الاسم بالفعل.';
$no_catagories='فئات';
$no_no_catagories='لم يتم تحديد فئات';
$no_new_catagory='فئة جديدة';
$pm_catagory_exists='هذة الفئة موجودة بالفعل';
$no_catagories_count='فئات';
$no_catagories_count_single='فئة';
$no_none='لاشئ';
$no_responsible='مسؤل';
$no_due_date='موعده';
$no_project='مشروع';
$no_contact='اتصال';
$no_file='ملف';
$no_show_all='اظهارالكل';
$no_show_own='اظهار الخاصة';
$no_show_responsible='اظهار مسؤوله';
$no_note='ملاحظة';
?>