<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='nota';
$no_notes_count='notes';
$no_catagory='Categoria';
$no_no_notes='No s\'ha trobat cap nota';
$no_new_note='Nova nota';
$pm_note_exists='Ja existeix una nota amb aquest nom.';
$no_catagories='Categories';
$no_no_catagories='No hi ha categories definides.';
$no_new_catagory='Nova categoria';
$pm_catagory_exists='Aquesta categoria ja existeix';
$no_catagories_count='Categories';
$no_catagories_count_single='Categoria';
$no_none='Cap';
$no_responsible='Responsable';
$no_due_date='per la data';
$no_project='Projecte';
$no_contact='Contacte';
$no_file='Fitxer';
$no_show_all='Mostra totes';
$no_show_own='Mostra les pròpies';
$no_show_responsible='Mostra responsables';
?>