<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'poznámka';
$no_notes_count = 'poznámky';
$no_catagory = 'Kategorie';
$no_no_notes = 'Nejsou žádné poznámky';
$no_new_note = 'Nová poznámka';
$pm_note_exists = 'Poznámka s tímto názvem už existuje.';
$no_catagories = 'Kategorie';
$no_no_catagories = 'Nejsou definovány žádné kategorie.';
$no_new_catagory= 'Nová kategorie';
$pm_catagory_exists = 'Tato kategorie už existuje';
$no_catagories_count = 'Kategorie';
$no_catagories_count_single = 'Kategorie';
$no_none = 'Žádná';
$no_responsible = 'Zodpovídá';
$no_due_date = 'Termín';

$no_project = 'Projekt';
$no_contact = 'Kontakt';
$no_file = 'Soubor';

$no_show_all = 'Zobrazit všechny';
$no_show_own = 'Zobrazit vlastní';
$no_show_responsible = 'Zobrazit přidělené';

$no_note='Poznámka';
