<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'note';
$no_notes_count = 'noter';
$no_catagory = 'Kategori';
$no_no_notes = 'Ingen noter fundet';
$no_new_note = 'Ny note';
$pm_note_exists = 'En note ved det navn eksisterer allerede.';
$no_catagories = 'Kategorier';
$no_no_catagories = 'Ingen kategorier er oprettede.';
$no_new_catagory= 'Ny kategori';
$pm_catagory_exists = 'Kategorien eksisterer allerede';
$no_catagories_count = 'Kategorier';
$no_catagories_count_single = 'Kategori';
$no_none = 'Ingen';
$no_responsible = 'Ansvarlig';
$no_due_date = 'Udføres den';

$no_project = 'Projekt';
$no_contact = 'Kontakt';
$no_file = 'Fil';

$no_show_all = 'Vis alle';
$no_show_own = 'Vis egne';
$no_show_responsible = 'Vis ansvarlige';
