<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='\'Notiz';
$no_notes_count='\'Notizen';
$no_catagory='\'Kategorie';
$no_no_notes='\'Keine Notizen gefunden';
$no_new_note='\'Neue Notiz';
$pm_note_exists='\'Eine Notiz mit diesem Namen ist bereits vorhanden.';
$no_catagories='\'Kategorien';
$no_no_catagories='\'Keine Kategorien vorhanden.';
$no_new_catagory='\'Neue Kategorie';
$pm_catagory_exists='\'Diese Kategorie ist bereits vorhanden';
$no_catagories_count='\'Kategorien';
$no_catagories_count_single='\'Kategorie';
$no_none='\'Keine';
$no_responsible='\'Verantwortliche(r)';
$no_due_date='\'Ablaufdatum';
$no_project='\'Projekt';
$no_contact='\'Kontakt';
$no_file='\'Datei';
$no_show_all='\'Alle Notizen';
$no_show_own='\'Eigene Notizen';
$no_show_responsible='\'Eigene Zuständigkeit';
$no_note='Notiz';
?>