<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'note';
$no_notes_count = 'notes';
$no_catagory = 'Category';
$no_no_notes = 'No notes found';
$no_new_note = 'New note';
$pm_note_exists = 'A note with this name already exists.';
$no_catagories = 'Categories';
$no_no_catagories = 'There are no categories definded.';
$no_new_catagory= 'New category';
$pm_catagory_exists = 'This catagory already exists';
$no_catagories_count = 'Categories';
$no_catagories_count_single = 'Category';
$no_none = 'None';
$no_responsible = 'Responsible';
$no_due_date = 'Due date';

$no_project = 'Project';
$no_contact = 'Contact';
$no_file = 'File';

$no_show_all = 'Show all';
$no_show_own = 'Show own';
$no_show_responsible = 'Show responsible';

$no_note='Note';
