<?php
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'nota';
$no_notes_count = 'notas';
$no_catagory = 'Categoría';
$no_no_notes = 'No se han encontrado notas';
$no_new_note = 'Nueva nota';
$pm_note_exists = 'Ya existe una nota con este nombre.';
$no_catagories = 'Categorías';
$no_no_catagories = 'No existen categorías definidas.';
$no_new_catagory= 'Nueva categoría';
$pm_catagory_exists = 'Esta categoría ya existe';
$no_catagories_count = 'Categorías';
$no_catagories_count_single = 'Categoría';
$no_none = 'Ninguna';
$no_responsible = 'Responsable';
$no_due_date = 'Para la fecha';

$no_project = 'Proyecto';
$no_contact = 'Contacto';
$no_file = 'Fichero';

$no_show_all = 'Ver todas';
$no_show_own = 'Ver las propias';
$no_show_responsible = 'Ver responsables';
