<?php
//Uncomment this line in new translations! LI 08.02.2006
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'muistiinpano';
$no_notes_count = 'muistiinpanot';
$no_catagory = 'Ryhmä';
$no_no_notes = 'Muistiinpanoja ei löytynyt';
$no_new_note = 'Uusi muistiinpano';
$pm_note_exists = 'Tämän niminen muistiinpano on jo olemassa.';
$no_catagories = 'Ryhmä';
$no_no_catagories = 'Ryhmiä ei ole määritelty.';
$no_new_catagory= 'Uusi ryhmä';
$pm_catagory_exists = 'Tämä ryhmä on jo olemassa';
$no_catagories_count = 'Ryhmät';
$no_catagories_count_single = 'Ryhmä';
$no_none = 'Ei kukaan';
$no_responsible = 'Vastuullinen';
$no_due_date = 'Loppu päivämäärä';

$no_project = 'Projekti';
$no_contact = 'Yhteys';
$no_file = 'Tiedosto';

$no_show_all = 'Näytä kaikki';
$no_show_own = 'Näytä omat';
$no_show_responsible = 'Näytä vastuullinen';
