<?php

// LANG: "fr", ENCODING: UTF-8
// Author: L. Jullien
// 15 Jan 2007

require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'note';
$no_notes_count = 'notes';
$no_catagory = 'Catégorie';
$no_no_notes = 'Aucune note trouvée';
$no_new_note = 'Nouvelle note';
$pm_note_exists = 'Une note avec ce nom existe déjà.';
$no_catagories = 'Catégories';
$no_no_catagories = 'Il n\'y a aucune catégorie définie.';
$no_new_catagory= 'Nouvelle catégorie';
$pm_catagory_exists = 'Cette catégorie existe déjà';
$no_catagories_count = 'Catégories';
$no_catagories_count_single = 'Catégorie';
$no_none = 'Aucun';
$no_responsible = 'Responsable';
$no_due_date = 'Date d\'expiration';
$no_project = 'Projet';
$no_contact = 'Contact';
$no_file = 'Fichier';
$no_show_all = 'Montrer toutes les notes';
$no_show_own = 'Montrer mes notes'; //show own
$no_show_responsible = 'Montrer par responsable';
?>