<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$htmldirection='rtl';
$charset='utf-8';
$no_notes_count_single = 'רשומה';
$no_notes_count = 'רשומות';
$no_catagory = 'קטגוריה';
$no_no_notes = 'לא נמצאו רשומות';
$no_new_note = 'רשומה חדשה';
$pm_note_exists = 'רשומה בעלת שם זה כבר קיימת';
$no_catagories = 'קטגוריות';
$no_no_catagories = 'אין קטגוריות מוגדרות';
$no_new_catagory= 'קטגוריה חדשה';
$pm_catagory_exists = 'קטגוריה זו כבר קיימת';
$no_catagories_count = 'קטגוריות';
$no_catagories_count_single = 'קטגוריה';
$no_none = 'אף אחת';
$no_responsible = 'אחראי';
$no_due_date = 'תאריך יעד';

$no_project = 'פרויקט';
$no_contact = 'איש קשר';
$no_file = 'קובץ';

$no_show_all = 'הראה הכל';
$no_show_own = 'הראה משלך';
$no_show_responsible = 'הראה אחראי';
