<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='feljegyzés';
$no_notes_count='feljegyzés';
$no_catagory='Kategória';
$no_no_notes='Nem találtam feljegyzéseket';
$no_new_note='Új feljegyzés';
$pm_note_exists='Már létezik ezen a néven feljegyzés.';
$no_catagories='Kategóriák';
$no_no_catagories='Nincsenek kategóriák létrehozva.';
$no_new_catagory='Új kategória';
$pm_catagory_exists='Ez a kategória már létezik';
$no_catagories_count='Kategória';
$no_catagories_count_single='Kategória';
$no_none='Semmi';
$no_responsible='Felelős';
$no_due_date='Határidő';
$no_project='Projekt';
$no_contact='Névjegy';
$no_file='Fájl';
$no_show_all='Mindet megjeleníti';
$no_show_own='Sajátokat megjeleníti';
$no_show_responsible='Felelőseket megjeleníti';
?>