<?php
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'nota';
$no_notes_count = 'note';
$no_catagory = 'Categoria';
$no_no_notes = 'Nessuna nota trovata.';
$no_new_note = 'Nuova nota';
$pm_note_exists = 'Una nota con questo nome esiste già.';
$no_catagories = 'Categorie';
$no_no_catagories = 'Non ci sono categoria definite.';
$no_new_catagory= 'Nuova categoria';
$pm_catagory_exists = 'Questa categoria esiste già';
$no_catagories_count = 'Categorie';
$no_catagories_count_single = 'Categoria';
$no_none = 'None';
$no_responsible = 'Responsabile';
$no_due_date = 'Scadenza';

$no_project = 'Progetto';
$no_contact = 'Contatto';
$no_file = 'File';

$no_show_all = 'Mostra tutte';
$no_show_own = 'Mostra proprie';
$no_show_responsible = 'Mostra responsabile';
