<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'メモ';
$no_notes_count = 'メモ';
$no_catagory = 'カテゴリ';
$no_no_notes = 'メモはありません';
$no_new_note = '新規メモ';
$pm_note_exists = '同じ名前のメモが存在します';
$no_catagories = 'カテゴリ';
$no_no_catagories = 'カテゴリがありません';
$no_new_catagory= '新規カテゴリ';
$pm_catagory_exists = '同じ名前のカテゴリが存在します';
$no_catagories_count = 'カテゴリ';
$no_catagories_count_single = 'カテゴリ';
$no_none = 'なし';
$no_responsible = '重要';
$no_due_date = '期限';

$no_project = 'プロジェクト';
$no_contact = '連絡';
$no_file = 'ファイル';

$no_show_all = 'すべて表示';
$no_show_own = '自分のを表示';
$no_show_responsible = '重要なものを表示';
