<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='notitie';
$no_notes_count='notities';
$no_catagory='Categorie';
$no_no_notes='Geen notities gevonden.';
$no_new_note='Nieuwe notitie';
$pm_note_exists='Er bestaat al een notitie met deze naam';
$no_catagories='Catagorieën';
$no_no_catagories='Er zijn geen categoriën gedefiniëerd.';
$no_new_catagory='Nieuwe categorie';
$pm_catagory_exists='Deze categorie bestaat al';
$no_catagories_count='Categorieën';
$no_catagories_count_single='Categorie';
$no_none='Geen';
$no_responsible='Verantwoordelijke';
$no_due_date='Uitvoerdatum';
$no_project='Project';
$no_contact='Contactpersoon';
$no_file='Bestand';
$no_show_all='Toon alles';
$no_show_own='Toon uw eigen';
$no_show_responsible='Toon uw verantwoordelijke';
