<?php
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'anotação';
$no_notes_count = 'anotações';
$no_catagory = 'Categoria';
$no_no_notes = 'Nenhuma anotação encontrada.';
$no_new_note = 'Nova anotação';
$pm_note_exists = 'Já existe uma anotação com este nome.';
$no_catagories = 'Categorias';
$no_no_catagories = 'Não existem categorias registadas.';
$no_new_catagory= 'Nova categoria';
$pm_catagory_exists = 'Esta categoria já existe';
$no_catagories_count = 'Categorias';
$no_catagories_count_single = 'categoria';
$no_none = 'Nenhuma';
$no_responsible = 'Responsável';
$no_due_date = 'Data';

$no_project = 'Processo';
$no_contact = 'Contacto';
$no_file = 'Arquivo';

$no_show_all = 'Mostrar todas';
$no_show_own = 'Mostrar apenas as minhas';
$no_show_responsible = 'Mostrar Responsável';

$no_note='Nota';

