<?php
//Uncomment this line in new translations!
require($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'запись';
$no_notes_count = 'записи';
$no_catagory = 'Категория';
$no_no_notes = 'Записи не найдены';
$no_new_note = 'Новая запись';
$pm_note_exists = 'Категория с таким именем уже существует.';
$no_catagories = 'Категории';
$no_no_catagories = 'Категория не определена.';
$no_new_catagory= 'Новая категория';
$pm_catagory_exists = 'Такая категория уже существует';
$no_catagories_count = 'Категории';
$no_catagories_count_single = 'Категория';
$no_none = 'нет';
$no_responsible = 'Responsible';
$no_due_date = 'Дата назначения';

$no_project = 'Проект';
$no_contact = 'Контакт';
$no_file = 'Файл';

$no_show_all = 'Показать все';
$no_show_own = 'Только свои';
$no_show_responsible = 'Show responsible';
