<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='zaznamek';
$no_notes_count='zaznamki';
$no_catagory='Kategorija';
$no_no_notes='Ni najdenih zaznamkov';
$no_new_note='Nov zaznamek';
$pm_note_exists='Zaznamek s tem imenom že obstaja.';
$no_catagories='Kategorije';
$no_no_catagories='Ni definiranih kategorij.';
$no_new_catagory='Nova kategorija';
$pm_catagory_exists='Ta kategorija že obstaja';
$no_catagories_count='Kategorije';
$no_catagories_count_single='Kategorija';
$no_none='Nobena';
$no_responsible='Odgovoren';
$no_due_date='Rok izvedbe';
$no_project='Projekt';
$no_contact='Stik';
$no_file='Datoteka';
$no_show_all='Prikaži vse';
$no_show_own='Prikaži lastne';
$no_show_responsible='Prikaži odgovorne';
$no_note='Zaznamek';
?>