<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'opomba';
$no_notes_count = 'opombe';
$no_catagory = 'Kategorija';
$no_no_notes = 'Ni zapiskov.';
$no_new_note = 'Nov zapisek';
$pm_note_exists = 'Zapisek s tem imenom ¾e obstaja.';
$no_catagories = 'Kategorije';
$no_no_catagories = 'Ni doloèenih kategorij.';
$no_new_catagory= 'New category';
$pm_catagory_exists = 'Ta kategorija ¾e obstaja';
$no_catagories_count = 'Kategorije';
$no_catagories_count_single = 'Kategorija';
$no_none = 'Noben';
$no_responsible = 'Odgovoren';
$no_due_date = 'Zapadel';

$no_project = 'Projekt';
$no_contact = 'Stik';
$no_file = 'Datoteka';

$no_show_all = 'Prika¾i vse';
$no_show_own = 'Poka¾i lastne';
$no_show_responsible = 'Poka¾i odgovornega';
