<?php
//Uncomment this line in new translations!
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'Anteckning';
$no_notes_count = 'Anteckningar';
$no_catagory = 'Kategori';
$no_no_notes = 'Inga anteckningar hittade';
$no_new_note = 'Ny Anteckning';
$pm_note_exists = 'En Anteckning med detta namn existerar redan.';
$no_catagories = 'Kategorier';
$no_no_catagories = 'Det finns inga kategorier definierade.';
$no_new_catagory= 'Ny kategori';
$pm_catagory_exists = 'Denna kategori existerar redan.';
$no_catagories_count = 'Kategorier';
$no_catagories_count_single = 'Kategori';
$no_none = 'Ingen';
$no_responsible = 'Ansvarig';
$no_due_date = 'Slut datum';

$no_project = 'Projekt';
$no_contact = 'Kontakt';
$no_file = 'File';

$no_show_all = 'Visa alla';
$no_show_own = 'Visa egna';
$no_show_responsible = 'Visa ansvariga';
