<?php
//Uncomment this line in new translations!
//require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = 'โน้ต';
$no_notes_count = 'โน้ต';
$no_catagory = 'หมวดหมู่';
$no_no_notes = 'ไม่พบโน้ต';
$no_new_note = 'เขียนโน้ตใหม่';
$pm_note_exists = 'ชื่อโน้ตนี้ซ้ำ';
$no_catagories = 'หมวดหมู่';
$no_no_catagories = 'ไม่มีหมวดหมู่นี้';
$no_new_catagory= 'สร้างหมวดหมู่ใหม่';
$pm_catagory_exists = 'ชื่อหมวดหมู่ซ้ำ';
$no_catagories_count = 'หมวดหมู่';
$no_catagories_count_single = 'หมวดหมู่';
$no_none = 'ไม่มี';
$no_responsible = 'ตอบ';
$no_due_date = 'วันสิ้นสุด';

$no_project = 'โปรเจ็ค';
$no_contact = 'การติดต่อ';
$no_file = 'ไฟลล์';

$no_show_all = 'แสดงทั้งหมด';
$no_show_own = 'แสดงส่วนตัว';
$no_show_responsible = 'แสดงผลที่มีการตอบ';
