<?php
//Translated with Group-Office translate module
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));
$no_notes_count_single='not';
$no_notes_count='not';
$no_catagory='Kategori';
$no_no_notes='Not bulunamadı';
$no_new_note='Yeni not';
$pm_note_exists='Bu isimde bir not zaten mevcut';
$no_catagories='Kategoriler';
$no_no_catagories='Hiçbir kategori tanımlanmamış.';
$no_new_catagory='Yeni kategori';
$pm_catagory_exists='Bu kategori zaten mevcut';
$no_catagories_count='Kategoriler';
$no_catagories_count_single='Kategori';
$no_none='Hiçbiri';
$no_responsible='Sorumlu';
$no_due_date='Gerçekleşme zamanı';
$no_project='Proje';
$no_contact='İletişim';
$no_file='Dosya';
$no_show_all='Tümünü göster';
$no_show_own='Kendininkileri göster';
$no_show_responsible='Sorumluları göster';
?>