<?php
require_once($GO_LANGUAGE->get_fallback_language_file('notes'));

$no_notes_count_single = '備忘錄';
$no_notes_count = '備忘';
$no_catagory = '分類';
$no_no_notes = '找不到備忘';
$no_new_note = '新增備忘';
$pm_note_exists = '這個名稱的備忘已經存在';
$no_catagories = '分類';
$no_no_catagories = '這裡沒有定義分類';
$no_new_catagory= '新增分類';
$pm_catagory_exists = '這個分類已經存在';
$no_catagories_count = '分類';
$no_catagories_count_single = '分類';
$no_none = '沒有';
$no_responsible = '負責人';
$no_due_date = '直至日期';
$no_project = '專案';
$no_contact = '聯絡人';
$no_file = '檔案';
$no_show_all = '顯示所有';
$no_show_own = '顯示自己的';
$no_show_responsible = '顯示負責人';
