<?php
$autodata_option['text'] = $strFirstName;
$autodata_option['value'] = '%first_name%';
$autodata[] = $autodata_option;

$autodata_option['text'] = $strMiddleName;
$autodata_option['value'] = '%middle_name%';
$autodata[] = $autodata_option;

$autodata_option['text'] = $strLastName;
$autodata_option['value'] = '%last_name%';
$autodata[] = $autodata_option;

$autodata_option['text'] = $strBeginning;
$autodata_option['value'] = '%beginning%';
$autodata[] = $autodata_option;

$autodata_option['text'] = $strUsername;
$autodata_option['value'] = '%username%';
$autodata[] = $autodata_option;

$autodata_option['text'] = $strPassword;
$autodata_option['value'] = '%password%';
$autodata[] = $autodata_option;


$autodata_option['text'] = 'Group-Office URL';
$autodata_option['value'] = '%full_url%';
$autodata[] = $autodata_option;
